{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.0-fix-versioning-with-github-action-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mhf6pbue2rcavclvj65ednvehq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "sdk-core-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 451637,
          "sha512": "e31d30875a1e4553f1faf839b90d4ccd440968a0c014d7015947fe884d135494f4fb1b4bfc566440d86efd12823a9c52237466e76d7a24cafe2a7b022ef90352",
          "sha256": "3c1710caf3ee634eb828b498b93f3f0629912e6ee75932d1a696b5ad46680eef",
          "sha1": "8c6cb7c5cb0f137d11c8e7aa52d48ea08867fe33",
          "md5": "ff84d845cb621be820acb2bb099c1930"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "hc-fhir-sdk-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "sdk-core-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 451637,
          "sha512": "e31d30875a1e4553f1faf839b90d4ccd440968a0c014d7015947fe884d135494f4fb1b4bfc566440d86efd12823a9c52237466e76d7a24cafe2a7b022ef90352",
          "sha256": "3c1710caf3ee634eb828b498b93f3f0629912e6ee75932d1a696b5ad46680eef",
          "sha1": "8c6cb7c5cb0f137d11c8e7aa52d48ea08867fe33",
          "md5": "ff84d845cb621be820acb2bb099c1930"
        }
      ]
    }
  ]
}
