{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xbilk6juhrfbdbz5fapthpzuhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "198b5417a9bff5f00187d31e1a5bf1ec3f5e4a3937947d18d27d592c67708f1ad5d6d252cd18358c69867f8c9778dee5ee59c4087f9a6ba41d9ce695aac679f6",
          "sha256": "c0f2b56147f19d197370fe59c0884595432b7a92a09926da5d2c28394024bef9",
          "sha1": "c347a86498ddfd9a8fafddcbac6f20ab9758a1d1",
          "md5": "7a3ffa9ed27d9dbdd6868e94aea44e14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "198b5417a9bff5f00187d31e1a5bf1ec3f5e4a3937947d18d27d592c67708f1ad5d6d252cd18358c69867f8c9778dee5ee59c4087f9a6ba41d9ce695aac679f6",
          "sha256": "c0f2b56147f19d197370fe59c0884595432b7a92a09926da5d2c28394024bef9",
          "sha1": "c347a86498ddfd9a8fafddcbac6f20ab9758a1d1",
          "md5": "7a3ffa9ed27d9dbdd6868e94aea44e14"
        }
      ]
    }
  ]
}
