{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "n22v6nixsvaphf4sksikff2phq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bd2132109258f674f49c56e0782c3fbd59cb8c1bee7962b0362303ddcfa46736ebc097e8a166574c4cf22fa8dde34662adcfcd421b9d46fc5ef56eec145b74d8",
          "sha256": "87e6882d2f3663997fd85f2bb10b53be09b645bd4f5db6de6f4ea5606911a370",
          "sha1": "a01cff354bc4b93457616dfc223970096ac1f251",
          "md5": "c59376ea8edba4b10a625221bec6efbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bd2132109258f674f49c56e0782c3fbd59cb8c1bee7962b0362303ddcfa46736ebc097e8a166574c4cf22fa8dde34662adcfcd421b9d46fc5ef56eec145b74d8",
          "sha256": "87e6882d2f3663997fd85f2bb10b53be09b645bd4f5db6de6f4ea5606911a370",
          "sha1": "a01cff354bc4b93457616dfc223970096ac1f251",
          "md5": "c59376ea8edba4b10a625221bec6efbc"
        }
      ]
    }
  ]
}
