{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dzv35tvuw5g75orrm34hqptk2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "be26f0d4b98d05ca8679e8491a4d85d1f4babdc21c18c51437d970fd47437e1ee7ac47423eeb0c766c4a275f993b2fe3ade242c6b8794daa2ea1f04b678dcd40",
          "sha256": "df0158a34e56ad7beff9f79fede90eb5c468808e6ad1bfd9e8857d60613cd608",
          "sha1": "27539bd4c853a32a0a8a9fd86f4ca27fea05f8ed",
          "md5": "f1cb211552aa2e40186530a14cfdfb77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "be26f0d4b98d05ca8679e8491a4d85d1f4babdc21c18c51437d970fd47437e1ee7ac47423eeb0c766c4a275f993b2fe3ade242c6b8794daa2ea1f04b678dcd40",
          "sha256": "df0158a34e56ad7beff9f79fede90eb5c468808e6ad1bfd9e8857d60613cd608",
          "sha1": "27539bd4c853a32a0a8a9fd86f4ca27fea05f8ed",
          "md5": "f1cb211552aa2e40186530a14cfdfb77"
        }
      ]
    }
  ]
}
