{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-add-generated-fhir-models-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "7jjjkpfv6bdjjcy3ahn6nnauw4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.0.1-add-generated-fhir-models-SNAPSHOT.jar",
          "url": "fhir-0.0.1-add-generated-fhir-models-SNAPSHOT.jar",
          "size": 518616,
          "sha512": "26e6ba6b7412b2f753144edac203ff2775b0a8b56751769a07687e6d8a13cd945671e83c9bae6576c7520cbd190087589a5c29f4e33ecd1b7266db37756eac54",
          "sha256": "3c88ac3beea8c8915becafba273708e5f82000280428b983f43e9548ad01154a",
          "sha1": "f7e74652fa208d596785eb0ca93d7d0a6f7a1c2f",
          "md5": "a3b00a77ad104b1f101e7a59cbe80372"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.0.1-add-generated-fhir-models-SNAPSHOT/fhir-android-0.0.1-add-generated-fhir-models-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.0.1-add-generated-fhir-models-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.0.1-add-generated-fhir-models-SNAPSHOT/fhir-android-0.0.1-add-generated-fhir-models-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.0.1-add-generated-fhir-models-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.0.1-add-generated-fhir-models-SNAPSHOT/fhir-iosarm64-0.0.1-add-generated-fhir-models-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.0.1-add-generated-fhir-models-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.0.1-add-generated-fhir-models-SNAPSHOT/fhir-iosx64-0.0.1-add-generated-fhir-models-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.0.1-add-generated-fhir-models-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.0.1-add-generated-fhir-models-SNAPSHOT/fhir-jvm-0.0.1-add-generated-fhir-models-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.0.1-add-generated-fhir-models-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.0.1-add-generated-fhir-models-SNAPSHOT/fhir-jvm-0.0.1-add-generated-fhir-models-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.0.1-add-generated-fhir-models-SNAPSHOT"
      }
    }
  ]
}
