{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.2-change-model-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5rlxeo2qu5e45pfhpw5vjyg3dq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "url": "securestore-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "size": 41913,
          "sha512": "18b2b7bc42cd75200e1dc3cf04417f929a23926b6c8aad590e0aa4c5eb9532bc0147be10f49af3e752293aabaa78809bc188a41cee21388638acadd2499ce2cc",
          "sha256": "ff8f5a4ca5e0762542dfa00c7b809cd36a4c3cc1300d7d9c40b8b207e7ad0a48",
          "sha1": "e4739d7bd59aea979959fef875e1a4548af5ce7b",
          "md5": "c520f12e4134ca5c629da56fc26300c4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "url": "securestore-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "size": 41913,
          "sha512": "18b2b7bc42cd75200e1dc3cf04417f929a23926b6c8aad590e0aa4c5eb9532bc0147be10f49af3e752293aabaa78809bc188a41cee21388638acadd2499ce2cc",
          "sha256": "ff8f5a4ca5e0762542dfa00c7b809cd36a4c3cc1300d7d9c40b8b207e7ad0a48",
          "sha1": "e4739d7bd59aea979959fef875e1a4548af5ce7b",
          "md5": "c520f12e4134ca5c629da56fc26300c4"
        }
      ]
    }
  ]
}
