{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xbilk6juhrfbdbz5fapthpzuhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "436c2a0dc1e24051a2a3e4a23d986f68372e3779c09ad84cbb0727ef5e46b6cd330714d8c3faee63f1e65cfe3f7b1720a20577c6d281c372866c981d32cffe08",
          "sha256": "a00dd5107cbd5d0db96f72c1c870acc9d0ea064056d2590aa4e649bf0dfe38f2",
          "sha1": "aa253a2db525cc96d8d7f5b9df61ea08c3b25b9f",
          "md5": "a18d0142c1546ce05e9e571c9f7d6a9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "436c2a0dc1e24051a2a3e4a23d986f68372e3779c09ad84cbb0727ef5e46b6cd330714d8c3faee63f1e65cfe3f7b1720a20577c6d281c372866c981d32cffe08",
          "sha256": "a00dd5107cbd5d0db96f72c1c870acc9d0ea064056d2590aa4e649bf0dfe38f2",
          "sha1": "aa253a2db525cc96d8d7f5b9df61ea08c3b25b9f",
          "md5": "a18d0142c1546ce05e9e571c9f7d6a9c"
        }
      ]
    }
  ]
}
