{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2onuqwkcdvbyriggqjczq32nry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "0588c0909cf67bb2b4a6750968ff526e97fed86d00428a9e7e0df25b624cc9cbe59548c465bbfa5309bdf8ea2a7444fd349e545fc9b89ba9ffd4b3aa1c9bb59a",
          "sha256": "39517b102b0ae26a1a3301e68613e1db2c11c233be3e826a08cb012f557a52e3",
          "sha1": "37038808b7a7ec83538de3a85473c31e81833323",
          "md5": "97d409bf31cb9e15a12bd2a9b81d4488"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "0588c0909cf67bb2b4a6750968ff526e97fed86d00428a9e7e0df25b624cc9cbe59548c465bbfa5309bdf8ea2a7444fd349e545fc9b89ba9ffd4b3aa1c9bb59a",
          "sha256": "39517b102b0ae26a1a3301e68613e1db2c11c233be3e826a08cb012f557a52e3",
          "sha1": "37038808b7a7ec83538de3a85473c31e81833323",
          "md5": "97d409bf31cb9e15a12bd2a9b81d4488"
        }
      ]
    }
  ]
}
