{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qcpriuiqafbnpdb6dk66lvkknm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "3a5aefc37aa6e6e8f8aa8f15d5c57523865cdb3ea963122111752a9a6ac8205052961440faf085642b773e7dda81028f721aaa93497e95f9136b2cda432b3852",
          "sha256": "f48c2a341a1dee3aa752b14e06d3467fd798d38cfc3c86a7fdfe6620ec2c5f36",
          "sha1": "526aa2c55aac466e06c5755747dff7d96bc1d10f",
          "md5": "b8c224e529b6f9ec8c7742a01badb570"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "3a5aefc37aa6e6e8f8aa8f15d5c57523865cdb3ea963122111752a9a6ac8205052961440faf085642b773e7dda81028f721aaa93497e95f9136b2cda432b3852",
          "sha256": "f48c2a341a1dee3aa752b14e06d3467fd798d38cfc3c86a7fdfe6620ec2c5f36",
          "sha1": "526aa2c55aac466e06c5755747dff7d96bc1d10f",
          "md5": "b8c224e529b6f9ec8c7742a01badb570"
        }
      ]
    }
  ]
}
