{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ipv65u7v3bbbrnjcja2ccy3xzm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "b5a0efc40ee22782841873eeea1c5c8051aef11671b699248252080cfd86932343a538085a24a9a63e0200240a1ebb3a6a489ea029b763c05f76cdd82a05e45b",
          "sha256": "6ac94532bf42bd43f329f6871a9d49c613dafbfe2b90104b970bfdf486454799",
          "sha1": "1e3ab568a43cbba394198f3742c8b02cd601c144",
          "md5": "3809bab4fc0e96fa6d8cc8dc05d5d7cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "b5a0efc40ee22782841873eeea1c5c8051aef11671b699248252080cfd86932343a538085a24a9a63e0200240a1ebb3a6a489ea029b763c05f76cdd82a05e45b",
          "sha256": "6ac94532bf42bd43f329f6871a9d49c613dafbfe2b90104b970bfdf486454799",
          "sha1": "1e3ab568a43cbba394198f3742c8b02cd601c144",
          "md5": "3809bab4fc0e96fa6d8cc8dc05d5d7cf"
        }
      ]
    }
  ]
}
