{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-change-recordservice-test-attachments-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6l76aactebef5mirvdcoqqgr6i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "dc7a0aebcaff9784d347ab7bc22f8e85594ba26b1f0847659a366a7b21d0e14977899fbd06c07ae106d6f7839f6b9f780871f9e59ab8fae16a64cdc482181460",
          "sha256": "f80a1b58b8cf9365e949ead565f7dbebd3d15f56448d8edc92f4f69c59b65ea2",
          "sha1": "0f5e17c2ef049b49203de04c80d2d62ab486e80f",
          "md5": "464ccede2fb5caab82d14c4be094c5b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "dc7a0aebcaff9784d347ab7bc22f8e85594ba26b1f0847659a366a7b21d0e14977899fbd06c07ae106d6f7839f6b9f780871f9e59ab8fae16a64cdc482181460",
          "sha256": "f80a1b58b8cf9365e949ead565f7dbebd3d15f56448d8edc92f4f69c59b65ea2",
          "sha1": "0f5e17c2ef049b49203de04c80d2d62ab486e80f",
          "md5": "464ccede2fb5caab82d14c4be094c5b4"
        }
      ]
    }
  ]
}
