{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-change-recordservice-test-attachments-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7kj5xfhcfvaknpbejkihbdn43a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "adf0a2af0d0bc859cdb93ad099e618ab6795a58c4d0fa8b92d351788785597b8440397c710aee9de61d62d7659cdee48b18a0bdf69814bf21197ff5d7ed65a07",
          "sha256": "5d30e5eba39c6c08c06b27bb349075cf68b055c049c036fd3aa427e8b0d764b4",
          "sha1": "03c2f755c1404a1d6acce7a4011e200e10105a84",
          "md5": "3e7b8efc3c7ecd254003b5a3333bbaed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "adf0a2af0d0bc859cdb93ad099e618ab6795a58c4d0fa8b92d351788785597b8440397c710aee9de61d62d7659cdee48b18a0bdf69814bf21197ff5d7ed65a07",
          "sha256": "5d30e5eba39c6c08c06b27bb349075cf68b055c049c036fd3aa427e8b0d764b4",
          "sha1": "03c2f755c1404a1d6acce7a4011e200e10105a84",
          "md5": "3e7b8efc3c7ecd254003b5a3333bbaed"
        }
      ]
    }
  ]
}
