{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uqyy5glaw5gpvjfyvnsd4h3a7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "712b5525fff20cd0701d1a71566c9a2442d6efccd557d020641981742bc92b89c74c8a915c46d0456ba9614298b8d069a80629c42ceaca4523a8dec39f4459a5",
          "sha256": "ead2bee802ca9e9bd7664e06badea7db620d9b9f5c4693134cb828e8219caf01",
          "sha1": "d3cb0ab61c7d09e2a8db84cc1e1a8cadcfcb6587",
          "md5": "375c2ab888ed4da6ddee14f7b3423118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "712b5525fff20cd0701d1a71566c9a2442d6efccd557d020641981742bc92b89c74c8a915c46d0456ba9614298b8d069a80629c42ceaca4523a8dec39f4459a5",
          "sha256": "ead2bee802ca9e9bd7664e06badea7db620d9b9f5c4693134cb828e8219caf01",
          "sha1": "d3cb0ab61c7d09e2a8db84cc1e1a8cadcfcb6587",
          "md5": "375c2ab888ed4da6ddee14f7b3423118"
        }
      ]
    }
  ]
}
