{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4r2mvycfuzfijcof52qoxdmbcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "66f882abd4ab321e9634ddd418c4c545ceefd6cc45ecf1494a5941234aa710f9faf6029da3b71b682ae8194995290d9871a4cfb016893b31d33d29d4c0913d03",
          "sha256": "1cbe750752212399734503660973fa4d54b8064e5ba9f81e90e63e37a29bd627",
          "sha1": "c4cddb86495034dbc7fba9c8cff59b084d3f3501",
          "md5": "428ef7379e985ae64f56c6cd093d5411"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "66f882abd4ab321e9634ddd418c4c545ceefd6cc45ecf1494a5941234aa710f9faf6029da3b71b682ae8194995290d9871a4cfb016893b31d33d29d4c0913d03",
          "sha256": "1cbe750752212399734503660973fa4d54b8064e5ba9f81e90e63e37a29bd627",
          "sha1": "c4cddb86495034dbc7fba9c8cff59b084d3f3501",
          "md5": "428ef7379e985ae64f56c6cd093d5411"
        }
      ]
    }
  ]
}
