{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.1-change-recordservice-test-attachments-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7kj5xfhcfvaknpbejkihbdn43a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "652c2b0de9c7882de1ea36ac663c5bb7e5d6fa4ea2423c328ad8b7722e0b152d8a6be1ed50cccda9d553e437606050bdeab2f9b2582c69f29f92a851dde0bef9",
          "sha256": "a29a01bad1848f2816d0372f27ec9ab0c7c5f5eb968bf4cc4f3b55b7d5cb272f",
          "sha1": "ca3492d9c0ee9aacf3c522ef10150123037ec5aa",
          "md5": "e9c4799db892def71c8389e19d0550fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "652c2b0de9c7882de1ea36ac663c5bb7e5d6fa4ea2423c328ad8b7722e0b152d8a6be1ed50cccda9d553e437606050bdeab2f9b2582c69f29f92a851dde0bef9",
          "sha256": "a29a01bad1848f2816d0372f27ec9ab0c7c5f5eb968bf4cc4f3b55b7d5cb272f",
          "sha1": "ca3492d9c0ee9aacf3c522ef10150123037ec5aa",
          "md5": "e9c4799db892def71c8389e19d0550fe"
        }
      ]
    }
  ]
}
