{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ogzlg5vlwjexre5xgpnsueyumu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a0949e57be8ad411e12282481fb30aec594bb65c122e064f0750d966e168c3928a89d0dd45ee8184bde0424cfe2aeb8236f18023b963bb70f8c169e1ef228a48",
          "sha256": "d672f2c6f372dfad612491108f8d3394440c85a15a9f1ca00ec7af3c377919ff",
          "sha1": "c33b6112794d4736a97caa75f9401832bf392af7",
          "md5": "e9efcad24a7045b3a15a044233f5692c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a0949e57be8ad411e12282481fb30aec594bb65c122e064f0750d966e168c3928a89d0dd45ee8184bde0424cfe2aeb8236f18023b963bb70f8c169e1ef228a48",
          "sha256": "d672f2c6f372dfad612491108f8d3394440c85a15a9f1ca00ec7af3c377919ff",
          "sha1": "c33b6112794d4736a97caa75f9401832bf392af7",
          "md5": "e9efcad24a7045b3a15a044233f5692c"
        }
      ]
    }
  ]
}
