{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2r7dgy54wvejhp6hlf6y46kg5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "4f47abd4f2fd0f59d90224a1ec99b23eef94e7e9321981fe00c101422fa1ac4c80f9e5609e88e6f5ef060af34ec87a444322e02176a430a87b2d00c268f01a99",
          "sha256": "b1fdfc7d6f9e35cd3051c127edf4a651bce0790ab94eea5f3accfed06d7c6deb",
          "sha1": "35c462463866ec58a0035091f1faf31910610403",
          "md5": "ba026c4c1dcc492026284bcc33ea9ab1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "4f47abd4f2fd0f59d90224a1ec99b23eef94e7e9321981fe00c101422fa1ac4c80f9e5609e88e6f5ef060af34ec87a444322e02176a430a87b2d00c268f01a99",
          "sha256": "b1fdfc7d6f9e35cd3051c127edf4a651bce0790ab94eea5f3accfed06d7c6deb",
          "sha1": "35c462463866ec58a0035091f1faf31910610403",
          "md5": "ba026c4c1dcc492026284bcc33ea9ab1"
        }
      ]
    }
  ]
}
