{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4q5aidtacncpffnbb72gqh2uuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1338ef233c6a3a20ba459e7c26277e343cf3786c60c4b50eca548d5ea8db68a1419bf248a59422ddca441e9c12d08970dac0d8ce9d262d3ac29dc1fa4d8f876c",
          "sha256": "3cde5d9fce614d2f4ba12769930abb529d8572db8a56faf3ab5e687952573bab",
          "sha1": "bc676b718e363e07ca7f600174c653da76a6efeb",
          "md5": "4fee7ddcd83b87498babe57e462466ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1338ef233c6a3a20ba459e7c26277e343cf3786c60c4b50eca548d5ea8db68a1419bf248a59422ddca441e9c12d08970dac0d8ce9d262d3ac29dc1fa4d8f876c",
          "sha256": "3cde5d9fce614d2f4ba12769930abb529d8572db8a56faf3ab5e687952573bab",
          "sha1": "bc676b718e363e07ca7f600174c653da76a6efeb",
          "md5": "4fee7ddcd83b87498babe57e462466ca"
        }
      ]
    }
  ]
}
