{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zkxoh34wznbunau4vjop3pk6dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e76b0190cf4a7d654de4bd8984581f6e22a47a661f97a044228f89a6738bfa4e2686e7171676548441cb35f37921ff3b24f26491cab5caaa9f4fb0fe1681bd7f",
          "sha256": "c58762d960db14b0a18ff1a541edf03710b25466baa70d93eac34694137f54bb",
          "sha1": "f325d47b3022469ded33cbf95676b93e045ede40",
          "md5": "92f256ae5cff58ea84afcc81a380c508"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e76b0190cf4a7d654de4bd8984581f6e22a47a661f97a044228f89a6738bfa4e2686e7171676548441cb35f37921ff3b24f26491cab5caaa9f4fb0fe1681bd7f",
          "sha256": "c58762d960db14b0a18ff1a541edf03710b25466baa70d93eac34694137f54bb",
          "sha1": "f325d47b3022469ded33cbf95676b93e045ede40",
          "md5": "92f256ae5cff58ea84afcc81a380c508"
        }
      ]
    }
  ]
}
