{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-change-versioning-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nlqi4dpq5baftgemygj3kxgg5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "ac812322e69dddda7979d8f5951ce43e4395f8ee9a1f0cdea04883cb6ec122f7f1fce6cbf0ca5a52a19644eca2b73ccf525621f7a0d7a555cb4503bddc7ff9e7",
          "sha256": "945a031eb9c0f6908b5a3b6537d646de1425d2789b9d7236880a46bd0abd8fbc",
          "sha1": "befd5d75282ba0df45a215703b65d2426c6f0d9e",
          "md5": "fa72b9947d8b2637182bbaf780e68ec5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-versioning-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "ac812322e69dddda7979d8f5951ce43e4395f8ee9a1f0cdea04883cb6ec122f7f1fce6cbf0ca5a52a19644eca2b73ccf525621f7a0d7a555cb4503bddc7ff9e7",
          "sha256": "945a031eb9c0f6908b5a3b6537d646de1425d2789b9d7236880a46bd0abd8fbc",
          "sha1": "befd5d75282ba0df45a215703b65d2426c6f0d9e",
          "md5": "fa72b9947d8b2637182bbaf780e68ec5"
        }
      ]
    }
  ]
}
