{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6oau6ptl7va6rdgaejx6j2j2um"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4a6b7866a4f996864e85bb3fccfaad7cec4ee25f4a35f6be69f8dbf068dbd6d5986d65b748dd0708031a4c449004eb805a63b7ef87d1b735fb77f6ccaa2ce57c",
          "sha256": "2e17e24bc5c838a000c084dd8141476b271994db079e1a07c622d889776aeb1a",
          "sha1": "0cad8e15f321b7ffe22adf7cd572aa0d31cffddb",
          "md5": "0ab70ddbdcd23886c6e5c307f65e27ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4a6b7866a4f996864e85bb3fccfaad7cec4ee25f4a35f6be69f8dbf068dbd6d5986d65b748dd0708031a4c449004eb805a63b7ef87d1b735fb77f6ccaa2ce57c",
          "sha256": "2e17e24bc5c838a000c084dd8141476b271994db079e1a07c622d889776aeb1a",
          "sha1": "0cad8e15f321b7ffe22adf7cd572aa0d31cffddb",
          "md5": "0ab70ddbdcd23886c6e5c307f65e27ed"
        }
      ]
    }
  ]
}
