{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-change-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5ra3tyqeafcl5cwiigzp2kmum4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "e1e277348f9acfc87b81e99c61e19a3d9245754c5ec569dee21fbe186d6c09a58f1455abc3302b98ebeafcbb1e52ada1725ea6e5060e14f526d7f34a2c6cc15b",
          "sha256": "682cbeaf109693d43e8f6bac2be56ecb02803cd401741d5e8a999655550ea3d4",
          "sha1": "07e645e546a8403fe022d5ae6e116a22931f962c",
          "md5": "05035b7c7d5e93c5ab3845dca69cc1fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "e1e277348f9acfc87b81e99c61e19a3d9245754c5ec569dee21fbe186d6c09a58f1455abc3302b98ebeafcbb1e52ada1725ea6e5060e14f526d7f34a2c6cc15b",
          "sha256": "682cbeaf109693d43e8f6bac2be56ecb02803cd401741d5e8a999655550ea3d4",
          "sha1": "07e645e546a8403fe022d5ae6e116a22931f962c",
          "md5": "05035b7c7d5e93c5ab3845dca69cc1fe"
        }
      ]
    }
  ]
}
