{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.0-fix-checkRestrictions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uakxpbldmjb6tazl5myxsuvqhi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.0-fix-checkRestrictions-SNAPSHOT.aar",
          "url": "securestore-android-1.9.0-fix-checkRestrictions-SNAPSHOT.aar",
          "size": 41916,
          "sha512": "537c123cdece2edb63b69602f3cc02d7433349fcef811e7b03db4b41be0dfa862c8392593156d31bd14d9a6779ad42afcc2bed4dd0d446ecdc51411dca091695",
          "sha256": "8ebf2ed62c8118dbbed2685645f05c2e7999a17a1e313bc479b25c8029591300",
          "sha1": "6f51c1778c6d8e3be8ed8d42c1bf6819ffc0e926",
          "md5": "e53be19923d6e13dfac6568bd0e08358"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.0-fix-checkRestrictions-SNAPSHOT.aar",
          "url": "securestore-android-1.9.0-fix-checkRestrictions-SNAPSHOT.aar",
          "size": 41916,
          "sha512": "537c123cdece2edb63b69602f3cc02d7433349fcef811e7b03db4b41be0dfa862c8392593156d31bd14d9a6779ad42afcc2bed4dd0d446ecdc51411dca091695",
          "sha256": "8ebf2ed62c8118dbbed2685645f05c2e7999a17a1e313bc479b25c8029591300",
          "sha1": "6f51c1778c6d8e3be8ed8d42c1bf6819ffc0e926",
          "md5": "e53be19923d6e13dfac6568bd0e08358"
        }
      ]
    }
  ]
}
