{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xhjn3mq3z5fb3ch22v4a32lkse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 453582,
          "sha512": "c51065a913092f68436e0433fd876f3debcdb079281b688eebd6082cdcbfa5ec03704771658e0b749b322fe9a772f96c4e2b14f1b89b738ff43b2fa523e4fd7c",
          "sha256": "cd40a9b57c68df355a5c10180165c4a8af8069f41b51c6b3152293452dc6a47c",
          "sha1": "e652a90df9caaa5d3dbdd8ceac3e41330bcb71f1",
          "md5": "a8730fa8b02c5e94f912cfd63da1a5f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 453582,
          "sha512": "c51065a913092f68436e0433fd876f3debcdb079281b688eebd6082cdcbfa5ec03704771658e0b749b322fe9a772f96c4e2b14f1b89b738ff43b2fa523e4fd7c",
          "sha256": "cd40a9b57c68df355a5c10180165c4a8af8069f41b51c6b3152293452dc6a47c",
          "sha1": "e652a90df9caaa5d3dbdd8ceac3e41330bcb71f1",
          "md5": "a8730fa8b02c5e94f912cfd63da1a5f1"
        }
      ]
    }
  ]
}
