{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-fix-document-upload-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5khqrztukbbz5mtsjprwk7j7wi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "46c2efb735e4c121b388a51041131023c95203626eef2eccf85e82e689581fc77a72d1342e5d947494f9aee7a15645a1195301db9ae372b438021be46942f006",
          "sha256": "500cedba5b1dba7b7e9f0d22090c38c18ffc11ec73bd0f130e5933692e354e44",
          "sha1": "49565a04ccbe57abfe321fb8163c47aba9498794",
          "md5": "0e2647b16946e51fdf7c6c37cbd89d6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "46c2efb735e4c121b388a51041131023c95203626eef2eccf85e82e689581fc77a72d1342e5d947494f9aee7a15645a1195301db9ae372b438021be46942f006",
          "sha256": "500cedba5b1dba7b7e9f0d22090c38c18ffc11ec73bd0f130e5933692e354e44",
          "sha1": "49565a04ccbe57abfe321fb8163c47aba9498794",
          "md5": "0e2647b16946e51fdf7c6c37cbd89d6e"
        }
      ]
    }
  ]
}
