{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-model-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tz5mqbfd7fh23bjnwme5ogmpru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "3486f1d034c5f29d9699d616c31a6f82c01564a1fa0a5563a2116ce850935f2860863adb002946cfeb7952697a40d12d10a3568fb322cd9ad1698edb5158ed98",
          "sha256": "d1681a7b903db71ae0224dcf46ec254874fdef567ee6d41f21dc3dfd88467dce",
          "sha1": "693511536683b02c6bd89f4c2ad828f6b40852f4",
          "md5": "59437256c81542f1470f493979d35778"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "3486f1d034c5f29d9699d616c31a6f82c01564a1fa0a5563a2116ce850935f2860863adb002946cfeb7952697a40d12d10a3568fb322cd9ad1698edb5158ed98",
          "sha256": "d1681a7b903db71ae0224dcf46ec254874fdef567ee6d41f21dc3dfd88467dce",
          "sha1": "693511536683b02c6bd89f4c2ad828f6b40852f4",
          "md5": "59437256c81542f1470f493979d35778"
        }
      ]
    }
  ]
}
