{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7wdmwkfllzfojdxiudlen4c3my"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "b8c9000f12bd57bd190bebe6092f57585c9ee3bb26bb31747774c127b278467369fae5c621d21db43db8e55299ffede4b43084abcfea76837f7af37008fe115a",
          "sha256": "dc5aea22995aeaebb38526b552d5734b0b1d81129e73aff15e8519b9835b96be",
          "sha1": "e82803a176718ef71881683be3effa8dd78a3661",
          "md5": "780a7a8219ef0b0233a12ebf9b5c8dc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "b8c9000f12bd57bd190bebe6092f57585c9ee3bb26bb31747774c127b278467369fae5c621d21db43db8e55299ffede4b43084abcfea76837f7af37008fe115a",
          "sha256": "dc5aea22995aeaebb38526b552d5734b0b1d81129e73aff15e8519b9835b96be",
          "sha1": "e82803a176718ef71881683be3effa8dd78a3661",
          "md5": "780a7a8219ef0b0233a12ebf9b5c8dc6"
        }
      ]
    }
  ]
}
