{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mznpa5qfq5a7hjujrnazuwiv3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "ec624ee3641c34690b90cd94fe5d3f1e4ecfca4f81b67e249d9b332c5fe8300e88b131b02001b90b0e0e0e164b621a034a675740ac5622ae02c2673dacba461f",
          "sha256": "47cd9719a22a5cc424054d3cc87d37a4cfa16f9d371ddab0c67b1e30f6089a63",
          "sha1": "e2aa75dbb3fae8329c0856eaec2a055c6cdc8d8d",
          "md5": "2ceb7d0ee2d2132222ba39093ee60ab1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "ec624ee3641c34690b90cd94fe5d3f1e4ecfca4f81b67e249d9b332c5fe8300e88b131b02001b90b0e0e0e164b621a034a675740ac5622ae02c2673dacba461f",
          "sha256": "47cd9719a22a5cc424054d3cc87d37a4cfa16f9d371ddab0c67b1e30f6089a63",
          "sha1": "e2aa75dbb3fae8329c0856eaec2a055c6cdc8d8d",
          "md5": "2ceb7d0ee2d2132222ba39093ee60ab1"
        }
      ]
    }
  ]
}
