{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "s2uv6hyio5a4zjpguswutgntie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "db9286ac0acc16e8f5f28f347a90aa229caea89c2df74f195929bd72d33a197485740b78f8056a276f67f54be6d63629cbd3c413d8a5471994312b2f2aae45e5",
          "sha256": "f7c2c62ec9791c384bc521c9ffb0a3013c0dbdeb269024d0973222b5a961b68b",
          "sha1": "a1fb309d839855a75dd8e88165829da0fd11e7e6",
          "md5": "4b299e6a86262c01df0737c2d6a4d5b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "db9286ac0acc16e8f5f28f347a90aa229caea89c2df74f195929bd72d33a197485740b78f8056a276f67f54be6d63629cbd3c413d8a5471994312b2f2aae45e5",
          "sha256": "f7c2c62ec9791c384bc521c9ffb0a3013c0dbdeb269024d0973222b5a961b68b",
          "sha1": "a1fb309d839855a75dd8e88165829da0fd11e7e6",
          "md5": "4b299e6a86262c01df0737c2d6a4d5b8"
        }
      ]
    }
  ]
}
