{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "b6u55qvqdbhk7k2ccz2mpkyc3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "7c60cc19873a2c9918f320eb85687ee8968b1a5a6f9ac57051c8c29ffbaf6b567c8e6a7d3263b4bf9af7673ebaa808414919e1e012199dd404a553247c3d3493",
          "sha256": "6dbecdb4a7519ae3fd1759fa6a9fc83dc617ff6a7e2832e4441c8f77c216879b",
          "sha1": "4ea7791cf098074724a2c21b81fbb10934058abb",
          "md5": "b41509f2a7f50483f2a2e161cbf9d519"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "7c60cc19873a2c9918f320eb85687ee8968b1a5a6f9ac57051c8c29ffbaf6b567c8e6a7d3263b4bf9af7673ebaa808414919e1e012199dd404a553247c3d3493",
          "sha256": "6dbecdb4a7519ae3fd1759fa6a9fc83dc617ff6a7e2832e4441c8f77c216879b",
          "sha1": "4ea7791cf098074724a2c21b81fbb10934058abb",
          "md5": "b41509f2a7f50483f2a2e161cbf9d519"
        }
      ]
    }
  ]
}
