{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nm7cvhxdf5d4hlkiajjryr4gtu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ca08e0fcf236a4db26aa6b12a810787f83517b9457e8df8a9bbb274d575542d3a53acfd703d980ced74b46f2d3374ace6fde7cab92e35ca2e18c5daedc747857",
          "sha256": "08fc11d602a91e28717fef11686901b302bca69bbc6b533199678646248da65c",
          "sha1": "d38017e88c8647411b9664ffe017139f1566e173",
          "md5": "99a3ae7777d7a367b80c89088aa1581b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ca08e0fcf236a4db26aa6b12a810787f83517b9457e8df8a9bbb274d575542d3a53acfd703d980ced74b46f2d3374ace6fde7cab92e35ca2e18c5daedc747857",
          "sha256": "08fc11d602a91e28717fef11686901b302bca69bbc6b533199678646248da65c",
          "sha1": "d38017e88c8647411b9664ffe017139f1566e173",
          "md5": "99a3ae7777d7a367b80c89088aa1581b"
        }
      ]
    }
  ]
}
