{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ogzlg5vlwjexre5xgpnsueyumu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d06dd2f4d8d5d06289c4aeb14638255343ed2fd7c0f5566ebe90efa60c73b244d2b2d5991499ae0d1d9ec8404ea6c813d7b2a899e593689f08da8e85c28bccc5",
          "sha256": "b4e670e3c8eb66eada1c7149918fc4017225ec5a69638ac03d2dd300de299b89",
          "sha1": "d829d818c52ef572e6c3f84adc0e5489c62ee6b0",
          "md5": "bcf9e0dda9ce0b01d26c78d84dee35ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d06dd2f4d8d5d06289c4aeb14638255343ed2fd7c0f5566ebe90efa60c73b244d2b2d5991499ae0d1d9ec8404ea6c813d7b2a899e593689f08da8e85c28bccc5",
          "sha256": "b4e670e3c8eb66eada1c7149918fc4017225ec5a69638ac03d2dd300de299b89",
          "sha1": "d829d818c52ef572e6c3f84adc0e5489c62ee6b0",
          "md5": "bcf9e0dda9ce0b01d26c78d84dee35ae"
        }
      ]
    }
  ]
}
