{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mqcpuq73arb4ppmqu2hzevedli"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a3051a50eee9db5f1223aa854b912f30379ac3e15499353d4c0f738c1e49c4972909937a6c58123ad4c83024c2972d7eea5cdf450e8f02765ed8ff9304113988",
          "sha256": "cfa066524749e0b4459af18aef13c2f38076ec6c7bea9841c24939a4051bfb4e",
          "sha1": "914380d6043216e04fc533c0ebae16439c4eff30",
          "md5": "539f9323bb1785f31553a5f8c512caee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a3051a50eee9db5f1223aa854b912f30379ac3e15499353d4c0f738c1e49c4972909937a6c58123ad4c83024c2972d7eea5cdf450e8f02765ed8ff9304113988",
          "sha256": "cfa066524749e0b4459af18aef13c2f38076ec6c7bea9841c24939a4051bfb4e",
          "sha1": "914380d6043216e04fc533c0ebae16439c4eff30",
          "md5": "539f9323bb1785f31553a5f8c512caee"
        }
      ]
    }
  ]
}
