{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "chojjztcwngxvnyz6vvkqrwrzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "9ccb6a36a7513d651147c506a21e6753be1f2d00f128c612e037e7b0f2546ce6d35f1490f006433d29cde3d0b9696774eb22c4aee25f947d51c65f25b3d842c7",
          "sha256": "500338b0af2cd163d285a7f6377c4c70a8a91d39f0ba7b4d5505cef399ac9968",
          "sha1": "b0af6133e1f0870b2c38ac3debfdde4603db858b",
          "md5": "faedc47d308d9098302c158d8d1e23f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "9ccb6a36a7513d651147c506a21e6753be1f2d00f128c612e037e7b0f2546ce6d35f1490f006433d29cde3d0b9696774eb22c4aee25f947d51c65f25b3d842c7",
          "sha256": "500338b0af2cd163d285a7f6377c4c70a8a91d39f0ba7b4d5505cef399ac9968",
          "sha1": "b0af6133e1f0870b2c38ac3debfdde4603db858b",
          "md5": "faedc47d308d9098302c158d8d1e23f8"
        }
      ]
    }
  ]
}
