{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2onuqwkcdvbyriggqjczq32nry"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7f89c174b1a134e9e15dc254e198e7f444f6e39b659abdf7114067cba219ec12a5eaa32c562bf530305dc96cc7ec81962cb5f7b43bc0c9b826f4b8e01b8463ea",
          "sha256": "c9c6333a76fa8a6c95a0a549e86a4c26072c86b5ba666d5f2fc83c61a2dcc050",
          "sha1": "c9a17c4be4c667cc9b1f06df141c19c18dda35e3",
          "md5": "fa82b1622ed98517a858ab31449383e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7f89c174b1a134e9e15dc254e198e7f444f6e39b659abdf7114067cba219ec12a5eaa32c562bf530305dc96cc7ec81962cb5f7b43bc0c9b826f4b8e01b8463ea",
          "sha256": "c9c6333a76fa8a6c95a0a549e86a4c26072c86b5ba666d5f2fc83c61a2dcc050",
          "sha1": "c9a17c4be4c667cc9b1f06df141c19c18dda35e3",
          "md5": "fa82b1622ed98517a858ab31449383e0"
        }
      ]
    }
  ]
}
