{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-add-git-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cikq23s6vfdxdjt4j2js6daa4i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-git-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-add-git-version-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-add-git-version-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "35545e3871ba82da247b611ba5e87ec04af09ae44a5f4eb787585ab2df9e1a3a8710ac26c43fc85a49ead08f3f25f378eaf274ecab4ffe14cc9b5ea7ab3291d3",
          "sha256": "b8ad4923ceec3cdc23d5017cc0dc9ceb5eaea2b23fc270786e7de941ed818230",
          "sha1": "23ee793ecd9011e2f1f4590130ddb03be745d3af",
          "md5": "3aa5c71750e889f21da2d16b08e4b11c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-git-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-add-git-version-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-add-git-version-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "35545e3871ba82da247b611ba5e87ec04af09ae44a5f4eb787585ab2df9e1a3a8710ac26c43fc85a49ead08f3f25f378eaf274ecab4ffe14cc9b5ea7ab3291d3",
          "sha256": "b8ad4923ceec3cdc23d5017cc0dc9ceb5eaea2b23fc270786e7de941ed818230",
          "sha1": "23ee793ecd9011e2f1f4590130ddb03be745d3af",
          "md5": "3aa5c71750e889f21da2d16b08e4b11c"
        }
      ]
    }
  ]
}
