{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "h7miabw7bffcvfavo3hkqxxsga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "be2349ae4e4b59f998ce7b8505a12c9a2edb8ea23dad16a2f7351883140afbc28ba60186aa8bc7cfe618ad480881e7a0afa1c9bf313caba54f8d887b173e68b3",
          "sha256": "9ce1d551e62a4bee6a3682e499dd1557a46b2bd6833e431748d370ee4efc6714",
          "sha1": "a593c86bd5c840ae2d73cec51f247fc8eda33e29",
          "md5": "dbfaae686baa08f56e67a5fefa5a4c6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "be2349ae4e4b59f998ce7b8505a12c9a2edb8ea23dad16a2f7351883140afbc28ba60186aa8bc7cfe618ad480881e7a0afa1c9bf313caba54f8d887b173e68b3",
          "sha256": "9ce1d551e62a4bee6a3682e499dd1557a46b2bd6833e431748d370ee4efc6714",
          "sha1": "a593c86bd5c840ae2d73cec51f247fc8eda33e29",
          "md5": "dbfaae686baa08f56e67a5fefa5a4c6c"
        }
      ]
    }
  ]
}
