{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ga3jzjkv2vetdk6r4y7hwzairi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "707956de123b62b639aca9539f99c1f578563ae3d4ed09e603812274f4cdba5ea521f2156499af909832e0942f7b394e3000cfbd1610dbdee8c92a7f96cfcb34",
          "sha256": "36850716a9f7191a9b7d179d84d35f43b006341cf369720cfe1ea40f277fcb84",
          "sha1": "0948a221cb1ec8e4426f00799a9be4757eb6ff7b",
          "md5": "f52185f8e0f53c8f66c8835a3337c4cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "707956de123b62b639aca9539f99c1f578563ae3d4ed09e603812274f4cdba5ea521f2156499af909832e0942f7b394e3000cfbd1610dbdee8c92a7f96cfcb34",
          "sha256": "36850716a9f7191a9b7d179d84d35f43b006341cf369720cfe1ea40f277fcb84",
          "sha1": "0948a221cb1ec8e4426f00799a9be4757eb6ff7b",
          "md5": "f52185f8e0f53c8f66c8835a3337c4cb"
        }
      ]
    }
  ]
}
