{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mo3uhzmzcvey3eimx3rsgwb3aa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "bb335c8557c12aa87ccd70a5c2632c15ea252987b91e7e287903b5c8700b24342ff75548295028276c85f130e2b382ae480788badbf678312102f4ff13b09eff",
          "sha256": "c6ee22404e9c800b51c08ee7321027ccbd64f54705d25e630dbe3ef0a45f10bc",
          "sha1": "7b164af1a2b02ec915d74fe4fadd3a51396b4253",
          "md5": "e6d4a1396cbd9a223ac5f9e4404fac68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "bb335c8557c12aa87ccd70a5c2632c15ea252987b91e7e287903b5c8700b24342ff75548295028276c85f130e2b382ae480788badbf678312102f4ff13b09eff",
          "sha256": "c6ee22404e9c800b51c08ee7321027ccbd64f54705d25e630dbe3ef0a45f10bc",
          "sha1": "7b164af1a2b02ec915d74fe4fadd3a51396b4253",
          "md5": "e6d4a1396cbd9a223ac5f9e4404fac68"
        }
      ]
    }
  ]
}
