{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nz6yfyustbadrjljfp7uu6fuje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "38a3577d67752d19c6493cb9f69dbe463dd4e0c19625e4ae1b421861b82366b2832dd7da6caa2a09f5d3bba9f0433bdd509f57cdb56e14c429ee9e6c43c65e46",
          "sha256": "7c4e5df6892ac9f73fe4f6189e37cf2f93ec63165eab547a5d6c651a180e7cf9",
          "sha1": "edd7e8fadd6a41941327065f034a27272157e13a",
          "md5": "803a8e665ceb123a3b4d81cb1f453f6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "38a3577d67752d19c6493cb9f69dbe463dd4e0c19625e4ae1b421861b82366b2832dd7da6caa2a09f5d3bba9f0433bdd509f57cdb56e14c429ee9e6c43c65e46",
          "sha256": "7c4e5df6892ac9f73fe4f6189e37cf2f93ec63165eab547a5d6c651a180e7cf9",
          "sha1": "edd7e8fadd6a41941327065f034a27272157e13a",
          "md5": "803a8e665ceb123a3b4d81cb1f453f6a"
        }
      ]
    }
  ]
}
