{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "l2ybysrhkzbpbl6dccawjm2vum"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "3f5cd256fdb4557d202a5cc07c068f9d74b713f6d8607660f2d24892c92803311b818667205acf4adf09c9ab5cb42d6266f5b9ee20ba42eac591559ec3b432fd",
          "sha256": "482a065e23395a446023523489c7e15f31f60978619d780e898d04ef24e8f298",
          "sha1": "dae7dbdd0cb58b4de0ddaa8924d8842c0f958e53",
          "md5": "a37f22fdce36d7a992303e63a6034eed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "3f5cd256fdb4557d202a5cc07c068f9d74b713f6d8607660f2d24892c92803311b818667205acf4adf09c9ab5cb42d6266f5b9ee20ba42eac591559ec3b432fd",
          "sha256": "482a065e23395a446023523489c7e15f31f60978619d780e898d04ef24e8f298",
          "sha1": "dae7dbdd0cb58b4de0ddaa8924d8842c0f958e53",
          "md5": "a37f22fdce36d7a992303e63a6034eed"
        }
      ]
    }
  ]
}
