{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgvack6m45gb5ff6rbnpy2t3ji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "4b7f75db5a01f66542182d0fe010617cdbd8e0a8947e506d7e92531aa9eae12c0d1903929fba10016eb4a80f956f74819e88581a6754c3813675552b40768e60",
          "sha256": "fc90a6a8d7425261cf8601daf14dcc3165c140cf3e8a941d7116c74a4be82c1e",
          "sha1": "b3ff97b2fb613aa59229883f16a48f33adb10b12",
          "md5": "223db8cda6d0fcdedd6971e14efcc287"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "4b7f75db5a01f66542182d0fe010617cdbd8e0a8947e506d7e92531aa9eae12c0d1903929fba10016eb4a80f956f74819e88581a6754c3813675552b40768e60",
          "sha256": "fc90a6a8d7425261cf8601daf14dcc3165c140cf3e8a941d7116c74a4be82c1e",
          "sha1": "b3ff97b2fb613aa59229883f16a48f33adb10b12",
          "md5": "223db8cda6d0fcdedd6971e14efcc287"
        }
      ]
    }
  ]
}
