{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2pcprbmndze7hp72ptcbanvfjy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "0bc07ff99488d77e8fba48e955699c1226efae48b3f66655424419db312df9d2a707312007da0d51c3b6867a686b65f1f4e33b1e7002a8955c92013de303d64b",
          "sha256": "2f32c38f8c825d81f0c2ce260eff4917e423e243187273f82b9a13f7fbe134e2",
          "sha1": "9e982e6fd23c6cbc6c9906eedeb85285c6bf66aa",
          "md5": "53d2364f2070f0c27f7b09515127c12c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "0bc07ff99488d77e8fba48e955699c1226efae48b3f66655424419db312df9d2a707312007da0d51c3b6867a686b65f1f4e33b1e7002a8955c92013de303d64b",
          "sha256": "2f32c38f8c825d81f0c2ce260eff4917e423e243187273f82b9a13f7fbe134e2",
          "sha1": "9e982e6fd23c6cbc6c9906eedeb85285c6bf66aa",
          "md5": "53d2364f2070f0c27f7b09515127c12c"
        }
      ]
    }
  ]
}
