{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hpmjtzkxqbcdllqwjveaz2c2te"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "7aa3543875d128ce53ea753984e87c6bfe963ec1674c452a248f5ba307fdc3a655a99ef57100d78ceec3c4923c9a97af5c86e00b4fe4c1dba8de08cfdd957bcf",
          "sha256": "e54e7171f73084bcf6e3304ae7185941f978fd2c18decf6b75f54c067eb68675",
          "sha1": "d4a047158ff6020c5c25a5e791344b989fc2cf82",
          "md5": "b1515cfc5e90cbc8bdb37deb6db76614"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "7aa3543875d128ce53ea753984e87c6bfe963ec1674c452a248f5ba307fdc3a655a99ef57100d78ceec3c4923c9a97af5c86e00b4fe4c1dba8de08cfdd957bcf",
          "sha256": "e54e7171f73084bcf6e3304ae7185941f978fd2c18decf6b75f54c067eb68675",
          "sha1": "d4a047158ff6020c5c25a5e791344b989fc2cf82",
          "md5": "b1515cfc5e90cbc8bdb37deb6db76614"
        }
      ]
    }
  ]
}
