{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "n62ezrvpj5bgfjhf5k5hxsucre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "dadf67830d53c30691e036753557e2dcffa91661d7cc0acfe58b8cfce19d52e2c1fee93d32c1710f4d4785279c4436acdc40ddbab438f695795a930c57e958bb",
          "sha256": "6bf0e5445e10b430a0c3bd171b459cd291fa30c9a70c36660e95fc9a9feb73d0",
          "sha1": "5299fb390d6501ebfabd20a7bd927d6a180b7d21",
          "md5": "c18033f72d42d82a9d95336a2d634b61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "dadf67830d53c30691e036753557e2dcffa91661d7cc0acfe58b8cfce19d52e2c1fee93d32c1710f4d4785279c4436acdc40ddbab438f695795a930c57e958bb",
          "sha256": "6bf0e5445e10b430a0c3bd171b459cd291fa30c9a70c36660e95fc9a9feb73d0",
          "sha1": "5299fb390d6501ebfabd20a7bd927d6a180b7d21",
          "md5": "c18033f72d42d82a9d95336a2d634b61"
        }
      ]
    }
  ]
}
