{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4ovpvallwnajbnnvoyewo5bhyq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "19ab47bf4aafc6a554d4820c690c9ba1e89d48980627d5647774de8265a09e2543b2364f1e33c99bc6b73d93581c300449264e30553762e82e074db512104d31",
          "sha256": "f60d0b24f2fed845cce63b1f24fe1cc8ed4b5f3c95de3bc3bd39238ac35480f8",
          "sha1": "5193647d637fe68c1bae648116db41194c258a36",
          "md5": "796938f482beb53696f015147c11d083"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "19ab47bf4aafc6a554d4820c690c9ba1e89d48980627d5647774de8265a09e2543b2364f1e33c99bc6b73d93581c300449264e30553762e82e074db512104d31",
          "sha256": "f60d0b24f2fed845cce63b1f24fe1cc8ed4b5f3c95de3bc3bd39238ac35480f8",
          "sha1": "5193647d637fe68c1bae648116db41194c258a36",
          "md5": "796938f482beb53696f015147c11d083"
        }
      ]
    }
  ]
}
