{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-ingestion",
    "version": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yl7niwsknrfxzkt2l6kfb3fq6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "size": 13405,
          "sha512": "b408ba2a6db80b45b362df55d7752f70f96ff34a9d8d5a3a686088f38a3dcb98397f51a285dcd90713c59ffd04a1d86f6c8d3a86aff4d56f093b65e979703a94",
          "sha256": "c274814a32b0299162914f0c3b626608a395e4d0f1d9abd07a8b2a45e7410f7e",
          "sha1": "62c2a4613ff2d8b5cd7a3de5f18decf14d84807a",
          "md5": "79b51475b8f4e0bd7c977deca90d0b73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "hc-fhir-sdk-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "size": 13405,
          "sha512": "b408ba2a6db80b45b362df55d7752f70f96ff34a9d8d5a3a686088f38a3dcb98397f51a285dcd90713c59ffd04a1d86f6c8d3a86aff4d56f093b65e979703a94",
          "sha256": "c274814a32b0299162914f0c3b626608a395e4d0f1d9abd07a8b2a45e7410f7e",
          "sha1": "62c2a4613ff2d8b5cd7a3de5f18decf14d84807a",
          "md5": "79b51475b8f4e0bd7c977deca90d0b73"
        }
      ]
    }
  ]
}
