{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uwmpo4yfrvdfpg35w7w5jzniaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "e74c9531cd170d19c2667c9ca551b4f276f464b06c7826561d657057f21d884427dc8100059275bc659e290dfa1ce656600f5bda922762389b9e2e4194ebb6ae",
          "sha256": "117787069c6d42f0997082925986949b3ba080eeee54fa7c1b9c2100bc250285",
          "sha1": "6a7dec3f853d3b5a767ee30bf1dae414af21f9c7",
          "md5": "2e2f77262aa6d4ae7b4344fddaa5b772"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "e74c9531cd170d19c2667c9ca551b4f276f464b06c7826561d657057f21d884427dc8100059275bc659e290dfa1ce656600f5bda922762389b9e2e4194ebb6ae",
          "sha256": "117787069c6d42f0997082925986949b3ba080eeee54fa7c1b9c2100bc250285",
          "sha1": "6a7dec3f853d3b5a767ee30bf1dae414af21f9c7",
          "md5": "2e2f77262aa6d4ae7b4344fddaa5b772"
        }
      ]
    }
  ]
}
