{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jaop2jc4tfej7kxvvv6ulzacdu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "50916bf45af567ca6d4bd1dafcb7ae0abfd464ed21da2c7e10037ef6694c61edb4f828087b812f705255c45543360f4ea8830364792526f13d3a9dccc4d5dd8b",
          "sha256": "4e72586cea1e09bc79e440f8aeb9a5557b371f7096c4ddfb1d0ffe9a8d616bc0",
          "sha1": "3cead000923cda3dbcaba4a1826507c0662ac125",
          "md5": "baa8816e3b2970ea6db5a1fad6a866fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "50916bf45af567ca6d4bd1dafcb7ae0abfd464ed21da2c7e10037ef6694c61edb4f828087b812f705255c45543360f4ea8830364792526f13d3a9dccc4d5dd8b",
          "sha256": "4e72586cea1e09bc79e440f8aeb9a5557b371f7096c4ddfb1d0ffe9a8d616bc0",
          "sha1": "3cead000923cda3dbcaba4a1826507c0662ac125",
          "md5": "baa8816e3b2970ea6db5a1fad6a866fd"
        }
      ]
    }
  ]
}
