{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bihq7l3hcfaudpwpbxompm2om4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "219e9ce175c5e061a4413e96f67cee69bdbaa172dc63d69fd3eff86937529e683de4cc3c1d8574b52e1d076c29822f8da6075f7dd7722f9d1dc33054fabad0f6",
          "sha256": "a59a538e5297c163afaa9eb1762e1bfb71e3186d1dbe17a3cad300c5417f9dfc",
          "sha1": "c0283318cc1140834033561fcdac957a2f2a46bb",
          "md5": "54dc227edb74c9976e02418941dac605"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "219e9ce175c5e061a4413e96f67cee69bdbaa172dc63d69fd3eff86937529e683de4cc3c1d8574b52e1d076c29822f8da6075f7dd7722f9d1dc33054fabad0f6",
          "sha256": "a59a538e5297c163afaa9eb1762e1bfb71e3186d1dbe17a3cad300c5417f9dfc",
          "sha1": "c0283318cc1140834033561fcdac957a2f2a46bb",
          "md5": "54dc227edb74c9976e02418941dac605"
        }
      ]
    }
  ]
}
