{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "q6l4to76bzgjpj727uaihl2dpq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "155d1084c97e77ce90dacf838cf17eeaaf1d080d818cb387d26043d28cde5a118e6729515045f907df6feb9802ac3d077460fe9b2fd9257efa88e9134bf3cae6",
          "sha256": "203e30687e6a7938cd5bd2a855d0d13829374f6a9c754fd815e5907dccdf34ca",
          "sha1": "119cc2dfbe2d74ec86e15de3b68f52c4b6c10e40",
          "md5": "dc4bb54b03007f28a2b6c727946068a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "155d1084c97e77ce90dacf838cf17eeaaf1d080d818cb387d26043d28cde5a118e6729515045f907df6feb9802ac3d077460fe9b2fd9257efa88e9134bf3cae6",
          "sha256": "203e30687e6a7938cd5bd2a855d0d13829374f6a9c754fd815e5907dccdf34ca",
          "sha1": "119cc2dfbe2d74ec86e15de3b68f52c4b6c10e40",
          "md5": "dc4bb54b03007f28a2b6c727946068a4"
        }
      ]
    }
  ]
}
