{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "q2d73emoy5ddnd7y7p43cgs3za"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f4d1c9df6f325e7adf9da28abad79477d6046c1b6232403daaeead79437d326d0b0b78f2d2cd20580488dbacf491014447f3355773502b9d3fcfacb4fbbc4ef2",
          "sha256": "a33f4db129113d07c2301f0a3a0c360575b82a5b8d5486663199e3b0e439992f",
          "sha1": "f68aa824f067b32a1c1a2db020f92b09a5355f8e",
          "md5": "cae70ff7a49f5894fb2abbcd0501c6af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f4d1c9df6f325e7adf9da28abad79477d6046c1b6232403daaeead79437d326d0b0b78f2d2cd20580488dbacf491014447f3355773502b9d3fcfacb4fbbc4ef2",
          "sha256": "a33f4db129113d07c2301f0a3a0c360575b82a5b8d5486663199e3b0e439992f",
          "sha1": "f68aa824f067b32a1c1a2db020f92b09a5355f8e",
          "md5": "cae70ff7a49f5894fb2abbcd0501c6af"
        }
      ]
    }
  ]
}
