{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-add-userservice-interface-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gq7rh7nl2ver7doxoqznlktzka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-userservice-interface-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "db59a53a62c1d858126efbcc0dcb1981fdaaa7b89a22d0d483dd84c672bc6d8eccd8592abfbfc60f5623e740199e2782b7f1f8e2a7bf1869fb94e623f0201db9",
          "sha256": "570aed6e65eace91e0fb0f5b22505c4c0e21fc95efe1e197f57565101a3f7ce8",
          "sha1": "509cd49b109f1b71e9bc5ca30e1766bd71c040dc",
          "md5": "d1037e7540a558f4cf4687c76487af06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-userservice-interface-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "db59a53a62c1d858126efbcc0dcb1981fdaaa7b89a22d0d483dd84c672bc6d8eccd8592abfbfc60f5623e740199e2782b7f1f8e2a7bf1869fb94e623f0201db9",
          "sha256": "570aed6e65eace91e0fb0f5b22505c4c0e21fc95efe1e197f57565101a3f7ce8",
          "sha1": "509cd49b109f1b71e9bc5ca30e1766bd71c040dc",
          "md5": "d1037e7540a558f4cf4687c76487af06"
        }
      ]
    }
  ]
}
