{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xhjn3mq3z5fb3ch22v4a32lkse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "451ee72c696ab92bdedc738ae6610ba0fe530041ba741a831070719e64b0802fc5ef56cdf2822cfb4e0225e404996c61b4d1126b629c8d3abbf6e740c1cbc5e5",
          "sha256": "255b003f287e1a61ae5afb7f16222af2c5c782c90ddd05f820a2043e9ae41422",
          "sha1": "d414281cd6e673f589fdcc666ca6317545697a9a",
          "md5": "fdf3b1f4555c0c4613069444e5ff8d76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "451ee72c696ab92bdedc738ae6610ba0fe530041ba741a831070719e64b0802fc5ef56cdf2822cfb4e0225e404996c61b4d1126b629c8d3abbf6e740c1cbc5e5",
          "sha256": "255b003f287e1a61ae5afb7f16222af2c5c782c90ddd05f820a2043e9ae41422",
          "sha1": "d414281cd6e673f589fdcc666ca6317545697a9a",
          "md5": "fdf3b1f4555c0c4613069444e5ff8d76"
        }
      ]
    }
  ]
}
