{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "chzn6qecbjbffgrbc333qtrp74"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "c8aadd2e7c0f883790339b1b61e60da4b27781119e87b0a43842a932e1aa22f35b190280eaaea9251b14b3fb16b65b2fc4a9b70c4a2d705604adc75e84db35c3",
          "sha256": "fab0dba4b22adeb55a14ef6da330709f62bdf9f9c655eea181c399dbeac2e7cb",
          "sha1": "f78e20cb551f954b8312f8b142e6e816b41417c0",
          "md5": "963561d7f27a650619b0bfee873b8ac4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "c8aadd2e7c0f883790339b1b61e60da4b27781119e87b0a43842a932e1aa22f35b190280eaaea9251b14b3fb16b65b2fc4a9b70c4a2d705604adc75e84db35c3",
          "sha256": "fab0dba4b22adeb55a14ef6da330709f62bdf9f9c655eea181c399dbeac2e7cb",
          "sha1": "f78e20cb551f954b8312f8b142e6e816b41417c0",
          "md5": "963561d7f27a650619b0bfee873b8ac4"
        }
      ]
    }
  ]
}
