{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.10.0-change-attachment-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "exelpoy45nfzfo62fxa23bssyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 478016,
          "sha512": "d9da295137b300e8e0fb16a9a1eeebc21b4007cac81590b63964ba19d088c89538aafb251cb37989e6db919d03d5249a8e5c3a5b76bd74ce3927d7c71788f916",
          "sha256": "4d9ea23c93d8b55001eb4e80ab7537c8ddc5bd34db3fd446050bb83854dea597",
          "sha1": "3c843cf222490b8ab77000fd8a1dc80778aa1b61",
          "md5": "f78fe11105390899baa2a1feea15c1fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 478016,
          "sha512": "d9da295137b300e8e0fb16a9a1eeebc21b4007cac81590b63964ba19d088c89538aafb251cb37989e6db919d03d5249a8e5c3a5b76bd74ce3927d7c71788f916",
          "sha256": "4d9ea23c93d8b55001eb4e80ab7537c8ddc5bd34db3fd446050bb83854dea597",
          "sha1": "3c843cf222490b8ab77000fd8a1dc80778aa1b61",
          "md5": "f78fe11105390899baa2a1feea15c1fe"
        }
      ]
    }
  ]
}
