{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bwy24dubdva5djrrcuvxm56d5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "25611a35eccbab43c52dc0767441733db8d040c4a5ed8f751d17711cc6fe81c59a54e990c0679d9c98235c32eb5ef892cea059ac67ef917d2bda9a21835d82f8",
          "sha256": "e5cafed1c6fbcd6920b1aaed124dbc4b7d36d8ccab9e1f8bec652d76059a13e7",
          "sha1": "830bd790482aef89029b2d2e8a9f831a03e88708",
          "md5": "ff7d20429325d0ec28d693f3dc865881"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "25611a35eccbab43c52dc0767441733db8d040c4a5ed8f751d17711cc6fe81c59a54e990c0679d9c98235c32eb5ef892cea059ac67ef917d2bda9a21835d82f8",
          "sha256": "e5cafed1c6fbcd6920b1aaed124dbc4b7d36d8ccab9e1f8bec652d76059a13e7",
          "sha1": "830bd790482aef89029b2d2e8a9f831a03e88708",
          "md5": "ff7d20429325d0ec28d693f3dc865881"
        }
      ]
    }
  ]
}
