{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ga3jzjkv2vetdk6r4y7hwzairi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "557e8e9794f526ca8869102807517e4e9d5a977e3dc50eff2e61cdee3663a9c93a96b5642b6f0fb3cfdc05219ee46df9bca871fc5bd09b439ce04633f72c608b",
          "sha256": "d625aac0c09b57645d8dc70de9ab3a71b4b12af6887d615502a7c534d4facca9",
          "sha1": "ed6b79e2c319aea11f9159d98517af997be4838e",
          "md5": "82a7cb9af6d41d224ccf25f8266ec027"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "557e8e9794f526ca8869102807517e4e9d5a977e3dc50eff2e61cdee3663a9c93a96b5642b6f0fb3cfdc05219ee46df9bca871fc5bd09b439ce04633f72c608b",
          "sha256": "d625aac0c09b57645d8dc70de9ab3a71b4b12af6887d615502a7c534d4facca9",
          "sha1": "ed6b79e2c319aea11f9159d98517af997be4838e",
          "md5": "82a7cb9af6d41d224ccf25f8266ec027"
        }
      ]
    }
  ]
}
