{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-attachment-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "exelpoy45nfzfo62fxa23bssyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "850c6dbb6488785a156a9dc812855d1df6057fc2265a1281580af23f1eff2cb786ce008d6ea7909b78341ed67395833a3831e63f2d8370ca363285d1b16fa26f",
          "sha256": "e84078ded8a8dd3f4e32db3623fa504c961429a7e209242c7bfc9ba5eec430b2",
          "sha1": "e4aeede487d70b339b332ba5d08c7f1ea7584c34",
          "md5": "b73a8f6ebd9d0801f4ecb909c7f06861"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "850c6dbb6488785a156a9dc812855d1df6057fc2265a1281580af23f1eff2cb786ce008d6ea7909b78341ed67395833a3831e63f2d8370ca363285d1b16fa26f",
          "sha256": "e84078ded8a8dd3f4e32db3623fa504c961429a7e209242c7bfc9ba5eec430b2",
          "sha1": "e4aeede487d70b339b332ba5d08c7f1ea7584c34",
          "md5": "b73a8f6ebd9d0801f4ecb909c7f06861"
        }
      ]
    }
  ]
}
