{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hqezsfxogzctdfzn6snxh6dfmq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.aar",
          "size": 51841,
          "sha512": "401c371e03c4fb8f9f023c8b215077ce356c054b3255479354017075d9a2807ed35de38dd20d45206066ff48515094a4e14a54a29b047b8f114653f2566d5b71",
          "sha256": "556a97babc5d14f265d3a3b04ad8e69a9e23bc7a3495e829a37fcb63bb2ddc93",
          "sha1": "f724c1eeea76f3ab97e75de99639528a49fe9f99",
          "md5": "a9cea2004a1566923622abf93ee804a1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.aar",
          "size": 51841,
          "sha512": "401c371e03c4fb8f9f023c8b215077ce356c054b3255479354017075d9a2807ed35de38dd20d45206066ff48515094a4e14a54a29b047b8f114653f2566d5b71",
          "sha256": "556a97babc5d14f265d3a3b04ad8e69a9e23bc7a3495e829a37fcb63bb2ddc93",
          "sha1": "f724c1eeea76f3ab97e75de99639528a49fe9f99",
          "md5": "a9cea2004a1566923622abf93ee804a1"
        }
      ]
    }
  ]
}
