{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.2-fix-search-count-api-call-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3zsqnthe7rerjmbd6qiqaozyxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 456030,
          "sha512": "a37ca90a85262f34adc60e4f74fce084525e7b76c7bbbe5f11ea225f49608b59373f4b3ca602ffbdde0ab61a2c5d3042edeeb460bb159028d03607f476bb7f55",
          "sha256": "5b2c8e41de9f5d5ef50c965a4831b973d587e6c0aec71b06d76117d4b3f0d5e8",
          "sha1": "e6d1e260bcde8db9f98ee479b61a2186845e2ab3",
          "md5": "24ff423a3d6d5fe0aacfd16d4e88f3ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-fix-search-count-api-call-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.2-fix-search-count-api-call-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.2-fix-search-count-api-call-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 456030,
          "sha512": "a37ca90a85262f34adc60e4f74fce084525e7b76c7bbbe5f11ea225f49608b59373f4b3ca602ffbdde0ab61a2c5d3042edeeb460bb159028d03607f476bb7f55",
          "sha256": "5b2c8e41de9f5d5ef50c965a4831b973d587e6c0aec71b06d76117d4b3f0d5e8",
          "sha1": "e6d1e260bcde8db9f98ee479b61a2186845e2ab3",
          "md5": "24ff423a3d6d5fe0aacfd16d4e88f3ff"
        }
      ]
    }
  ]
}
