{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-fix-document-upload-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7fswvv4qirhtrj77wv2b5d6kiu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 46152,
          "sha512": "cbc7d17459fcbc8ff7d54655f572759b42aa8c71d5b7998fea56897933e88d04f511d84b22c7b0b8270e571608a9bb6c93cf2e101dba08afe8d1b06d66d88efe",
          "sha256": "f2f6e5b3a024dc71e06690f3008729a61f29ad12f03068465fbadf73b41f6fcb",
          "sha1": "44fe99a83188a8c96890e7fd0156f307854705c1",
          "md5": "98883e919ffaac0c68560374c9a4fcd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 46152,
          "sha512": "cbc7d17459fcbc8ff7d54655f572759b42aa8c71d5b7998fea56897933e88d04f511d84b22c7b0b8270e571608a9bb6c93cf2e101dba08afe8d1b06d66d88efe",
          "sha256": "f2f6e5b3a024dc71e06690f3008729a61f29ad12f03068465fbadf73b41f6fcb",
          "sha1": "44fe99a83188a8c96890e7fd0156f307854705c1",
          "md5": "98883e919ffaac0c68560374c9a4fcd6"
        }
      ]
    }
  ]
}
