{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nz6yfyustbadrjljfp7uu6fuje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a43372faab3db3ad20f7727a17662866ea8e6c47d6387c89333b4f1117c7a4f51624e621b76b5cdefe495f76239914ac096bc8df30be71ae90464bc068765afd",
          "sha256": "c9d997110bf552c6e55e62cca04bbba51b03b26b7135cfd40a8779c08b864602",
          "sha1": "e96684759bc90d5e992927b7b50c1e9852208737",
          "md5": "55776710add9401edd534dd1c36c1410"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a43372faab3db3ad20f7727a17662866ea8e6c47d6387c89333b4f1117c7a4f51624e621b76b5cdefe495f76239914ac096bc8df30be71ae90464bc068765afd",
          "sha256": "c9d997110bf552c6e55e62cca04bbba51b03b26b7135cfd40a8779c08b864602",
          "sha1": "e96684759bc90d5e992927b7b50c1e9852208737",
          "md5": "55776710add9401edd534dd1c36c1410"
        }
      ]
    }
  ]
}
