{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-fix-versioning-with-github-action-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2bpvqtigovaijblxhc2k5zwyaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bb34fd2c44ddd5f69efc4db65e1f90356bd2d0a02fb247d7a356d9700599a7b8bf78059e5dd7ec576db58fe7e39b0b879ecc5617892a29abd0aa752dd43b83ab",
          "sha256": "82c42df9ae6af35178070cc882308435f3590e00c35f908afcd00119b0c8a4e6",
          "sha1": "99fd5fd98e5b6bf07d763ceed38652c5dc961ec5",
          "md5": "f080e670e3bf019021d27a54494107b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bb34fd2c44ddd5f69efc4db65e1f90356bd2d0a02fb247d7a356d9700599a7b8bf78059e5dd7ec576db58fe7e39b0b879ecc5617892a29abd0aa752dd43b83ab",
          "sha256": "82c42df9ae6af35178070cc882308435f3590e00c35f908afcd00119b0c8a4e6",
          "sha1": "99fd5fd98e5b6bf07d763ceed38652c5dc961ec5",
          "md5": "f080e670e3bf019021d27a54494107b3"
        }
      ]
    }
  ]
}
