{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6oau6ptl7va6rdgaejx6j2j2um"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.aar",
          "size": 41924,
          "sha512": "2a437625d9cb3c74c0189c3d8d3e31ef0462140bc6f276d65622a316085f57fa41429fe3d2ffbb4429dd5de408c713f86c719bf6245393f730e861e176d03c64",
          "sha256": "49587e7ff547b19072a2247decbcd258b7440206a74353408e106a4d1b6a99dc",
          "sha1": "9d249804f9518f04bb7a3b19c3a641e328e640cf",
          "md5": "e893e0b01114aea5fc48a92d735ee2a4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.aar",
          "size": 41924,
          "sha512": "2a437625d9cb3c74c0189c3d8d3e31ef0462140bc6f276d65622a316085f57fa41429fe3d2ffbb4429dd5de408c713f86c719bf6245393f730e861e176d03c64",
          "sha256": "49587e7ff547b19072a2247decbcd258b7440206a74353408e106a4d1b6a99dc",
          "sha1": "9d249804f9518f04bb7a3b19c3a641e328e640cf",
          "md5": "e893e0b01114aea5fc48a92d735ee2a4"
        }
      ]
    }
  ]
}
