{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-recordservice-crypto-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wbrwgj5hnfap3l6ykkhhzzxwge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1c539a12e87598386d68b683da353b7c3a4492d500bb4a6e9ba86e12b39bf4b602663c74dbb14af62201fe3c5dfcceb48e212260e0f9fcf6993604b1ffebc174",
          "sha256": "6b0f23c1c1ec96013f02acd209cff492015c98f91fe19a287833f15376c6bd5a",
          "sha1": "8e3e772af71ebd97cdf18f5c1c03600059ed4e65",
          "md5": "1985e1ed06dbb98f65f5b62ead3474de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1c539a12e87598386d68b683da353b7c3a4492d500bb4a6e9ba86e12b39bf4b602663c74dbb14af62201fe3c5dfcceb48e212260e0f9fcf6993604b1ffebc174",
          "sha256": "6b0f23c1c1ec96013f02acd209cff492015c98f91fe19a287833f15376c6bd5a",
          "sha1": "8e3e772af71ebd97cdf18f5c1c03600059ed4e65",
          "md5": "1985e1ed06dbb98f65f5b62ead3474de"
        }
      ]
    }
  ]
}
