{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-add-public-userid-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6rownicaifc75pidpscs3pwvki"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "88664d2ed8d8061a06bc0123c540b9b2e22f9f3fced3b22a041dd029c60068569280ef83415a8604277e259c5979a01e3f3ccc123b2a9294812fc4e4fac04691",
          "sha256": "59b47ba3fd72e9ac1e2026021f7ee735d183505fefa8be66e9fd6eeb79b6fc62",
          "sha1": "fa2e1eb2957fc83825e140f5fdebc70a3e074814",
          "md5": "b9a2c301a0a00a0b57c7250883c41e8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "88664d2ed8d8061a06bc0123c540b9b2e22f9f3fced3b22a041dd029c60068569280ef83415a8604277e259c5979a01e3f3ccc123b2a9294812fc4e4fac04691",
          "sha256": "59b47ba3fd72e9ac1e2026021f7ee735d183505fefa8be66e9fd6eeb79b6fc62",
          "sha1": "fa2e1eb2957fc83825e140f5fdebc70a3e074814",
          "md5": "b9a2c301a0a00a0b57c7250883c41e8b"
        }
      ]
    }
  ]
}
