{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pljt23c73fbfbcvqonbftgc4t4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "ada42d627316488d26dfb06228f0d6fd7826aacf731d82c81132a91ccfd15c99cf216f135dfa0ca11a71e99700aada73d4d197884bab38c8f9642d9e53b069b5",
          "sha256": "19d22ec6bfbe5a33e7f72ec4877f4d251005a7c8547f10cea4a41014fc60d4a9",
          "sha1": "3a8aa3aa7589bff340a38d20c42d1d10272b2f33",
          "md5": "b37267cdec2c0a8ae3f2a9bf51769ce0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "ada42d627316488d26dfb06228f0d6fd7826aacf731d82c81132a91ccfd15c99cf216f135dfa0ca11a71e99700aada73d4d197884bab38c8f9642d9e53b069b5",
          "sha256": "19d22ec6bfbe5a33e7f72ec4877f4d251005a7c8547f10cea4a41014fc60d4a9",
          "sha1": "3a8aa3aa7589bff340a38d20c42d1d10272b2f33",
          "md5": "b37267cdec2c0a8ae3f2a9bf51769ce0"
        }
      ]
    }
  ]
}
