{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hqezsfxogzctdfzn6snxh6dfmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "9cd275b279e06f553d1218b0288ba072511f28deb940dfdeca38a1c16a1081a6d1383355aeb0febb21fa86a4a24b8def6bb0cf9ed0317edaea8611dfb2bd6a9c",
          "sha256": "cde8cfc3ccacabe517afa367d31d4f4012d77d40a499344f81426ada111763b5",
          "sha1": "4c4557bba73caa407473e6bba01e28b5c0099b8a",
          "md5": "bf3a88615656879dc1a920a2110ea1f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "9cd275b279e06f553d1218b0288ba072511f28deb940dfdeca38a1c16a1081a6d1383355aeb0febb21fa86a4a24b8def6bb0cf9ed0317edaea8611dfb2bd6a9c",
          "sha256": "cde8cfc3ccacabe517afa367d31d4f4012d77d40a499344f81426ada111763b5",
          "sha1": "4c4557bba73caa407473e6bba01e28b5c0099b8a",
          "md5": "bf3a88615656879dc1a920a2110ea1f9"
        }
      ]
    }
  ]
}
