{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "s2uv6hyio5a4zjpguswutgntie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "1f4b1c384f2ef1a01de7160232eeef136f490c6b06d0156ba4a015e3488068c72eff40dc0e27a1634c4689e2a89b6d77899e29663ac92983c57b9eb4ad039469",
          "sha256": "1fe733f401960b6a25a8665e43caa4593ab9fad0700e257f3dd9352c8c0b21db",
          "sha1": "fe77a6c5569094efa993580c9b0e458637ff7043",
          "md5": "94006d3b1163c24187281117b22765c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "1f4b1c384f2ef1a01de7160232eeef136f490c6b06d0156ba4a015e3488068c72eff40dc0e27a1634c4689e2a89b6d77899e29663ac92983c57b9eb4ad039469",
          "sha256": "1fe733f401960b6a25a8665e43caa4593ab9fad0700e257f3dd9352c8c0b21db",
          "sha1": "fe77a6c5569094efa993580c9b0e458637ff7043",
          "md5": "94006d3b1163c24187281117b22765c2"
        }
      ]
    }
  ]
}
