{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bb2lswjribhfnprrhaf5juron4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "c6e70f9da22bb0bb24c742e0e8f2d3e3e16efe510311a8fad8481b60f83bc2b880c3056c93ef7dd5d983142238de6ae14c486705edd44c8fa3de4b18767a34fa",
          "sha256": "865ca1516aac75080e526591d2671f35e5f96e695fe30b2c4b4a62b1953b6ab9",
          "sha1": "35e44031ca92f821f13013c4abf4f899bcd71b18",
          "md5": "68ae38c3bd412f06407e6ed489879ce4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "c6e70f9da22bb0bb24c742e0e8f2d3e3e16efe510311a8fad8481b60f83bc2b880c3056c93ef7dd5d983142238de6ae14c486705edd44c8fa3de4b18767a34fa",
          "sha256": "865ca1516aac75080e526591d2671f35e5f96e695fe30b2c4b4a62b1953b6ab9",
          "sha1": "35e44031ca92f821f13013c4abf4f899bcd71b18",
          "md5": "68ae38c3bd412f06407e6ed489879ce4"
        }
      ]
    }
  ]
}
