{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-recordservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "q2bungffdbe6lkj2c7hhl3izcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "94d0ee1b9fcd7ca05870dbb6d2eefda323d532ba862bd2ac1ab91807b83fd4aefb15c0e393f2b54632ff16f533981811b98c37a1396a540e9324bb06f01f72ce",
          "sha256": "325244b8ec74f0877a750f813d0ffd05e2ca096df93b222c40c4d4494f88acca",
          "sha1": "9645106532c2c524ed7eaf462c119ad5c73bcaac",
          "md5": "c3fe6e3d70390b29c5bb3d95444e0b38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "94d0ee1b9fcd7ca05870dbb6d2eefda323d532ba862bd2ac1ab91807b83fd4aefb15c0e393f2b54632ff16f533981811b98c37a1396a540e9324bb06f01f72ce",
          "sha256": "325244b8ec74f0877a750f813d0ffd05e2ca096df93b222c40c4d4494f88acca",
          "sha1": "9645106532c2c524ed7eaf462c119ad5c73bcaac",
          "md5": "c3fe6e3d70390b29c5bb3d95444e0b38"
        }
      ]
    }
  ]
}
