{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-recordservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lc4ekwaa25aupaccjktqbxouxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "3a52f239c47e4391e6c4a6206f71b35f4ad374c65e8bac86124bab58163e8560d2263c7a4c906caa469b054f50028662cbfbd9fecc92e716573ac27db8328e88",
          "sha256": "4eafc305157184ff9656d43e7bf7bce99ce52f50cf890d25134be754fe955e38",
          "sha1": "462bfe7a0e93c92bf92ae343560b33e3f0c048a6",
          "md5": "0e63f2ed00f9880db508c262819db2cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "3a52f239c47e4391e6c4a6206f71b35f4ad374c65e8bac86124bab58163e8560d2263c7a4c906caa469b054f50028662cbfbd9fecc92e716573ac27db8328e88",
          "sha256": "4eafc305157184ff9656d43e7bf7bce99ce52f50cf890d25134be754fe955e38",
          "sha1": "462bfe7a0e93c92bf92ae343560b33e3f0c048a6",
          "md5": "0e63f2ed00f9880db508c262819db2cc"
        }
      ]
    }
  ]
}
