{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-recordservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dsyetl2jarfqfakaqxyp3brncq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d5c8010cbd9e8f1fe90653c39e8d6b1eec5bedebabbbf117ba087c8f399186e7ea0782027cd9229a44886610b05e26952edce93bb88c8f95f8325914f406ba22",
          "sha256": "574011185b94377f250a45c0ee0f69cbe7fda7aa8282b93494e9b6e2f14daeb8",
          "sha1": "3c2507b609e054b81e5ad375eef7082d02a6afa3",
          "md5": "771f0467c9d13ca057d6249dd499bdc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d5c8010cbd9e8f1fe90653c39e8d6b1eec5bedebabbbf117ba087c8f399186e7ea0782027cd9229a44886610b05e26952edce93bb88c8f95f8325914f406ba22",
          "sha256": "574011185b94377f250a45c0ee0f69cbe7fda7aa8282b93494e9b6e2f14daeb8",
          "sha1": "3c2507b609e054b81e5ad375eef7082d02a6afa3",
          "md5": "771f0467c9d13ca057d6249dd499bdc4"
        }
      ]
    }
  ]
}
