{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wakwsun7erdyhdcvwter7j4g3q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0.aar",
          "url": "auth-android-1.11.0.aar",
          "size": 44919,
          "sha512": "4aff772336ebc3e9d7723565a4843923924859d4a8491f84f56a0509523833d4fd42d3137f26ea225f0540ae9f68a7d8f4622ca6fb05ea554df7425929956112",
          "sha256": "bebeb4d336e1416cca83fd630ef0ac21d4e1b79a73cb506ffe3461326e9c68f9",
          "sha1": "65d28273e55845cfdfc0e4e2ceb14e0b7588decc",
          "md5": "d3cb8429a06078510549ac9833ada005"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0.aar",
          "url": "auth-android-1.11.0.aar",
          "size": 44919,
          "sha512": "4aff772336ebc3e9d7723565a4843923924859d4a8491f84f56a0509523833d4fd42d3137f26ea225f0540ae9f68a7d8f4622ca6fb05ea554df7425929956112",
          "sha256": "bebeb4d336e1416cca83fd630ef0ac21d4e1b79a73cb506ffe3461326e9c68f9",
          "sha1": "65d28273e55845cfdfc0e4e2ceb14e0b7588decc",
          "md5": "d3cb8429a06078510549ac9833ada005"
        }
      ]
    }
  ]
}
