{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4r2mvycfuzfijcof52qoxdmbcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "e0a53527f9565f6734d1c087fea9792207525d6c8d883b9bc46ba6ad44a89e1f71207de2975582faaa2f8ad9c59d042b1e429acc42889f75d3ee4fc7a9130d38",
          "sha256": "b64484d11712fc90b8ed9edaf8b900cf66f26620707345b84f04a659a7ab4761",
          "sha1": "fbce66b4f9d1cd55a894f22fc7183ac151ace76a",
          "md5": "ec29d223604d04e211cc6e3eba459f9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "e0a53527f9565f6734d1c087fea9792207525d6c8d883b9bc46ba6ad44a89e1f71207de2975582faaa2f8ad9c59d042b1e429acc42889f75d3ee4fc7a9130d38",
          "sha256": "b64484d11712fc90b8ed9edaf8b900cf66f26620707345b84f04a659a7ab4761",
          "sha1": "fbce66b4f9d1cd55a894f22fc7183ac151ace76a",
          "md5": "ec29d223604d04e211cc6e3eba459f9e"
        }
      ]
    }
  ]
}
