{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uhc6akxktvhrvmzhgrg4srjpwq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "90ca164bc154e8397c0c1594bc65a64d215374e98560e0bba661b9e16b9000e7402bacf485865c631f23d87fbbbb123a0e03b669d4ba8b528459f046f27f67f3",
          "sha256": "c6c514f511d4720c5f5b6b505590f0903fd03a9fea2bc970b2e0f42388779b55",
          "sha1": "5e52edfcb9bb1bcad100dd4c5d3b6f5c5b17312f",
          "md5": "27284f0c3eb3ac34543af6040fa02745"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "90ca164bc154e8397c0c1594bc65a64d215374e98560e0bba661b9e16b9000e7402bacf485865c631f23d87fbbbb123a0e03b669d4ba8b528459f046f27f67f3",
          "sha256": "c6c514f511d4720c5f5b6b505590f0903fd03a9fea2bc970b2e0f42388779b55",
          "sha1": "5e52edfcb9bb1bcad100dd4c5d3b6f5c5b17312f",
          "md5": "27284f0c3eb3ac34543af6040fa02745"
        }
      ]
    }
  ]
}
