{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5szpxyiewvhale5jpuegcbu7ou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "ad951262482efa2558d8dd4df45b2e47eaf05b2916392d5ae865591faa14353e3c594578768a4bac4f9cfdaad98cb0b9cc984aad24907f61d128f8ddcda62fc5",
          "sha256": "6e49ee07abc3ba7c10726745432367c2ece095d5557c130400b5229269cbc019",
          "sha1": "2e08d1f5fb933ba89ac516568ed3f9a89b015602",
          "md5": "ed35e169a6bf2c9fbb5ae82ddb3ecb6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "ad951262482efa2558d8dd4df45b2e47eaf05b2916392d5ae865591faa14353e3c594578768a4bac4f9cfdaad98cb0b9cc984aad24907f61d128f8ddcda62fc5",
          "sha256": "6e49ee07abc3ba7c10726745432367c2ece095d5557c130400b5229269cbc019",
          "sha1": "2e08d1f5fb933ba89ac516568ed3f9a89b015602",
          "md5": "ed35e169a6bf2c9fbb5ae82ddb3ecb6d"
        }
      ]
    }
  ]
}
