{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ppijtr35czhnrfpayokisrwiji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "2abb528ac02d2718565bc7ee73fd8cbc170a8f87b8e4e64b7991e95be29c84629be262a81225368b9b3967705fc2ee0e3ef70d129f21b416941dfadcc5fd2cc8",
          "sha256": "1420f3161d3af343a972daa8e7a506b235920b42463c5e80e9d33f90c8cd85a2",
          "sha1": "f85d5d4f8a6f99766046c3d0bbaa3ee88afa438d",
          "md5": "f319ac5c6858e199a409af125f90687e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "2abb528ac02d2718565bc7ee73fd8cbc170a8f87b8e4e64b7991e95be29c84629be262a81225368b9b3967705fc2ee0e3ef70d129f21b416941dfadcc5fd2cc8",
          "sha256": "1420f3161d3af343a972daa8e7a506b235920b42463c5e80e9d33f90c8cd85a2",
          "sha1": "f85d5d4f8a6f99766046c3d0bbaa3ee88afa438d",
          "md5": "f319ac5c6858e199a409af125f90687e"
        }
      ]
    }
  ]
}
