{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zs5bqhfjbzdkljd5h6p63dloh4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "cdf5e9caea983490001e8a264579084b198b4239ed5407a089aaa82db629327d3cfca41bdfbd765e2f9f3d40ff725e4c12f048d29810b49b92aecaf26a895a67",
          "sha256": "0268add7cf6e0c3614be704feac8ae5286ed3e1803603203b378319b995f0890",
          "sha1": "fbbe6ccabfaee7917c38b0c60a56291a469ec5f1",
          "md5": "b73a3ba3472f57a66947c6debd54dad4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "cdf5e9caea983490001e8a264579084b198b4239ed5407a089aaa82db629327d3cfca41bdfbd765e2f9f3d40ff725e4c12f048d29810b49b92aecaf26a895a67",
          "sha256": "0268add7cf6e0c3614be704feac8ae5286ed3e1803603203b378319b995f0890",
          "sha1": "fbbe6ccabfaee7917c38b0c60a56291a469ec5f1",
          "md5": "b73a3ba3472f57a66947c6debd54dad4"
        }
      ]
    }
  ]
}
