{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-change-update-record-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "slieyfkueza7xlsgkkerzpcicu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-update-record-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "5842fa60b031bf68e7c836abf80a27bc1bfc5c9518584a9aefac8d1fb5621e56fb0a509b0e57868c5cb253dac36fc82f3c3e07f96d8592108ba0551ee42bb715",
          "sha256": "348b5d9ddc4b07ecb20775d18220c2d9aa9189a22dc925ca056e51189b39d337",
          "sha1": "7f7a69b2531fcdda5ff0e6bf9ce16cb1d36814bf",
          "md5": "46497fce377244d8de07d486906ecd63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-update-record-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "5842fa60b031bf68e7c836abf80a27bc1bfc5c9518584a9aefac8d1fb5621e56fb0a509b0e57868c5cb253dac36fc82f3c3e07f96d8592108ba0551ee42bb715",
          "sha256": "348b5d9ddc4b07ecb20775d18220c2d9aa9189a22dc925ca056e51189b39d337",
          "sha1": "7f7a69b2531fcdda5ff0e6bf9ce16cb1d36814bf",
          "md5": "46497fce377244d8de07d486906ecd63"
        }
      ]
    }
  ]
}
