{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-fix-release-ci-job-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pr6loosk2fa5jlcqcqncxhbwra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4690d8c97a63611a4fbbbca75a4523ca24b57805fed66a4af9bc0b3c1b2fbd98c3520012508572ce4b8058678c26b80be7ab341c4adc52d1310daef38cad6bdb",
          "sha256": "a2368cefb1652a847e71b10389c23397788e6626865beecb556c7ccd66b96e62",
          "sha1": "6a638203401df8aa432b75591e6762d554f2b5fb",
          "md5": "63fbc9d2d1357c8b65965dd97d2fd9f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4690d8c97a63611a4fbbbca75a4523ca24b57805fed66a4af9bc0b3c1b2fbd98c3520012508572ce4b8058678c26b80be7ab341c4adc52d1310daef38cad6bdb",
          "sha256": "a2368cefb1652a847e71b10389c23397788e6626865beecb556c7ccd66b96e62",
          "sha1": "6a638203401df8aa432b75591e6762d554f2b5fb",
          "md5": "63fbc9d2d1357c8b65965dd97d2fd9f9"
        }
      ]
    }
  ]
}
