{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ztcrv55rn5gjrdntn7yjwcrf3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "5a3c967bbfd638322b48dd342b9436cc11cf333874366992b4cdc7ea9f1366a2adf53e9b10dd5b50df6f7b7fc3e2c12b7e8ed9430c954740dcb113224bfc018c",
          "sha256": "7fcbf93ceef5115246b61006d556452c09b4a7b67b6c08da3d15cff07e7833d3",
          "sha1": "f2694f22d9f656a89cf293be935b69d0f29adcf0",
          "md5": "e54e37fe3bae2d6ae40a8b8540da8ba4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "5a3c967bbfd638322b48dd342b9436cc11cf333874366992b4cdc7ea9f1366a2adf53e9b10dd5b50df6f7b7fc3e2c12b7e8ed9430c954740dcb113224bfc018c",
          "sha256": "7fcbf93ceef5115246b61006d556452c09b4a7b67b6c08da3d15cff07e7833d3",
          "sha1": "f2694f22d9f656a89cf293be935b69d0f29adcf0",
          "md5": "e54e37fe3bae2d6ae40a8b8540da8ba4"
        }
      ]
    }
  ]
}
