{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zriivgusrng6bavxn7or772wey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "3feb9c54f00840473693ec982b0835421eb03a7fb0c4b0da0e25187797562a8a4b7caff99322ceed60a99c702c6e05c597c7b87122b576bf2248164508be65a5",
          "sha256": "1569bb5f680d6d4a8eb868dbddfc377ec10a34102ecc28e1f290d67aaa22c5be",
          "sha1": "dc113826f920dae7b6ad80c99c8571024d2dba31",
          "md5": "981f7ee3c30251b00ce8092d5518b892"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "3feb9c54f00840473693ec982b0835421eb03a7fb0c4b0da0e25187797562a8a4b7caff99322ceed60a99c702c6e05c597c7b87122b576bf2248164508be65a5",
          "sha256": "1569bb5f680d6d4a8eb868dbddfc377ec10a34102ecc28e1f290d67aaa22c5be",
          "sha1": "dc113826f920dae7b6ad80c99c8571024d2dba31",
          "md5": "981f7ee3c30251b00ce8092d5518b892"
        }
      ]
    }
  ]
}
