{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ph4iogeq5jbadpvnlkizdi2iye"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "49c11640ccb815416ab808e379dc1b22113b74c9914b50e6aae2ae6be6e4b48b2553284953abdeb13d6e41330b8cbe6e9e0001791a9930fe80702a1a89bef726",
          "sha256": "c81c3ec7d6bc4b6d4b1ab338331ee1bcb3511df60ef23aa92168953e8b09e323",
          "sha1": "650e41903fa9f6d84017f284d2ac3d1f17a22496",
          "md5": "72375eebcf85983ec0817fdc02a79c23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "49c11640ccb815416ab808e379dc1b22113b74c9914b50e6aae2ae6be6e4b48b2553284953abdeb13d6e41330b8cbe6e9e0001791a9930fe80702a1a89bef726",
          "sha256": "c81c3ec7d6bc4b6d4b1ab338331ee1bcb3511df60ef23aa92168953e8b09e323",
          "sha1": "650e41903fa9f6d84017f284d2ac3d1f17a22496",
          "md5": "72375eebcf85983ec0817fdc02a79c23"
        }
      ]
    }
  ]
}
