{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vfqva2c7evbi7isa5xterb7xia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "c668e19a0aa3f2076bdbb2740d616b755a8d1daa55d62c05c1b4ae2812151138ed34c5d4b3977aa9374308d3a0e3544d977e689532e0c9ae9a7329fdf0faa3aa",
          "sha256": "faeb23c7dd326fdc7d8d6e5801ae46641d2b59568e575f25b6d1abc4afe906e9",
          "sha1": "38c98326b9cb229ce704eb32e908d7b86c74d38b",
          "md5": "fb3edc532386ccb7571b033fb822f541"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "c668e19a0aa3f2076bdbb2740d616b755a8d1daa55d62c05c1b4ae2812151138ed34c5d4b3977aa9374308d3a0e3544d977e689532e0c9ae9a7329fdf0faa3aa",
          "sha256": "faeb23c7dd326fdc7d8d6e5801ae46641d2b59568e575f25b6d1abc4afe906e9",
          "sha1": "38c98326b9cb229ce704eb32e908d7b86c74d38b",
          "md5": "fb3edc532386ccb7571b033fb822f541"
        }
      ]
    }
  ]
}
