{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kbq63nxerffnrfw7qmmxelluri"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "url": "securestore-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "size": 42012,
          "sha512": "8e5443c8b479291f8241416641508fbe7f8fb4b56af08831d4df9fa24d06d54a9578866e704e162c0ee59e276d2af69c4da3cf8913fb1d4c97e925da6f6d2a7f",
          "sha256": "819c6704a4649f1f7cb76b00a02ff8c03cad38a98880cd76ecc2503fb75c2e4e",
          "sha1": "0cfdc2f6b8c1dd8f119401a1fd0e18566760cd21",
          "md5": "6727a5ca6b3bbf4079c4ef3386db006a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "url": "securestore-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "size": 42012,
          "sha512": "8e5443c8b479291f8241416641508fbe7f8fb4b56af08831d4df9fa24d06d54a9578866e704e162c0ee59e276d2af69c4da3cf8913fb1d4c97e925da6f6d2a7f",
          "sha256": "819c6704a4649f1f7cb76b00a02ff8c03cad38a98880cd76ecc2503fb75c2e4e",
          "sha1": "0cfdc2f6b8c1dd8f119401a1fd0e18566760cd21",
          "md5": "6727a5ca6b3bbf4079c4ef3386db006a"
        }
      ]
    }
  ]
}
