{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-add-fhir4-download-record-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yz3pmnwyq5etxpjz2z3357s7xu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-record-support-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "e7fb9395488ac596711e2d98cdb3a2804f0002ddd918bc3a82b7a68dd404ef10aa8b0db523122a55acb3bd89bd65e418d99cb85b91f97b85df571bf41c0e0da3",
          "sha256": "59bf34edd6d8a3818b0cccc6db23b99fedc0529dd6a35e453bf4eed932da215b",
          "sha1": "f2423a82bdee5ca9b19a1c23ccbe90570eeb8eaa",
          "md5": "1a8d06e99e29b451244ff0eb5492c39f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-record-support-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "e7fb9395488ac596711e2d98cdb3a2804f0002ddd918bc3a82b7a68dd404ef10aa8b0db523122a55acb3bd89bd65e418d99cb85b91f97b85df571bf41c0e0da3",
          "sha256": "59bf34edd6d8a3818b0cccc6db23b99fedc0529dd6a35e453bf4eed932da215b",
          "sha1": "f2423a82bdee5ca9b19a1c23ccbe90570eeb8eaa",
          "md5": "1a8d06e99e29b451244ff0eb5492c39f"
        }
      ]
    }
  ]
}
