{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "b645qhpounhvbn4genyfu62jb4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "f9a01d4dac2e5ed175c979175973b7894f757196ee2c2f8680d5abf12252d1852ebe600743b7c3fbdf03bcef9262d0482742fac91f134a18738b6cec86b94870",
          "sha256": "2d05f854f455a07dd6a9e8e49bf488a029a3b57adfe05fc0d840eaadcc9083c3",
          "sha1": "e90f541a9ceaf261f01d9fd6859bf30e07cf887b",
          "md5": "41ac318ed81659e5d41a72758a19982c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "f9a01d4dac2e5ed175c979175973b7894f757196ee2c2f8680d5abf12252d1852ebe600743b7c3fbdf03bcef9262d0482742fac91f134a18738b6cec86b94870",
          "sha256": "2d05f854f455a07dd6a9e8e49bf488a029a3b57adfe05fc0d840eaadcc9083c3",
          "sha1": "e90f541a9ceaf261f01d9fd6859bf30e07cf887b",
          "md5": "41ac318ed81659e5d41a72758a19982c"
        }
      ]
    }
  ]
}
