{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6u2uiei5vnd45k5lwuwzjxc3ay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "71224396163b22775abffcc0e84279f58a5bd98ad1e4c55d918f6b83826e379f5b0c021195bb437ff0a6cfca510855046df770c530295f7edf23ee6fa3974ff0",
          "sha256": "a7a1b7ffb2b31c58f9c15ce21549c375fdd57084969e7a258d46250774d0f6e7",
          "sha1": "8872971552d2274cd01703e0e2cae6523dd16e5c",
          "md5": "df5df155fc5c98e56fe41cca3afe4272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "71224396163b22775abffcc0e84279f58a5bd98ad1e4c55d918f6b83826e379f5b0c021195bb437ff0a6cfca510855046df770c530295f7edf23ee6fa3974ff0",
          "sha256": "a7a1b7ffb2b31c58f9c15ce21549c375fdd57084969e7a258d46250774d0f6e7",
          "sha1": "8872971552d2274cd01703e0e2cae6523dd16e5c",
          "md5": "df5df155fc5c98e56fe41cca3afe4272"
        }
      ]
    }
  ]
}
