{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3eif4yillff6njydnkmeiklnmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "f8446dd60a490d8b500d7803c1a64741305d667d558a762903b06e4976ff1f55faaf88065772cc4c5da74ab4223839de22d7f5611ee4bfcbefb8776f2e885dd3",
          "sha256": "81c58a64bedac8aad5f950e6c92c27203295e577e05c011191e2974e2bb91b4f",
          "sha1": "1c1be536a8e2f11864d42b9bee31231750c413ea",
          "md5": "e00458afed5013e5a39f27764c00cf7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "f8446dd60a490d8b500d7803c1a64741305d667d558a762903b06e4976ff1f55faaf88065772cc4c5da74ab4223839de22d7f5611ee4bfcbefb8776f2e885dd3",
          "sha256": "81c58a64bedac8aad5f950e6c92c27203295e577e05c011191e2974e2bb91b4f",
          "sha1": "1c1be536a8e2f11864d42b9bee31231750c413ea",
          "md5": "e00458afed5013e5a39f27764c00cf7b"
        }
      ]
    }
  ]
}
