{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mhtegx5hr5bvlnzldnfls4vgzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "5f7842c68bf0e22230b56a1cf31a1fd3393504107471d87b21234525f68906a2eae70de070945a5bf31c3f43ce22dce06460859a8ee0071108f64935b3790cd1",
          "sha256": "85a51a3708264afc3ee8098693785a671f48941edf151273ea9e839a4fd620da",
          "sha1": "0059b6a6d60ee0fe42b1f160ed092bd7f7f3321e",
          "md5": "6dd20a5d5a119afbcee420f7e5eba89e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "5f7842c68bf0e22230b56a1cf31a1fd3393504107471d87b21234525f68906a2eae70de070945a5bf31c3f43ce22dce06460859a8ee0071108f64935b3790cd1",
          "sha256": "85a51a3708264afc3ee8098693785a671f48941edf151273ea9e839a4fd620da",
          "sha1": "0059b6a6d60ee0fe42b1f160ed092bd7f7f3321e",
          "md5": "6dd20a5d5a119afbcee420f7e5eba89e"
        }
      ]
    }
  ]
}
