{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.7.0-SNAPSHOT/util-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mip6usmk3fajzmnx6dxbshmvla"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "bc1c058a728ee9c65862d8e9b4dd2e5aa1a9c9f1438f95d996f4e3b1b1d7abab57d6640e62b7b2a2f1976dc625c60bcab745646e139cab0a9aaaadecfda34f89",
          "sha256": "bbfb9ae1c40825cd48a5f54525f9c81e62108e3e9a529f510a19654f181c8a76",
          "sha1": "5081873a0886010acb888061dbbc8b0ac5f26deb",
          "md5": "18a7e611aabc6f3efaa486fd5fc62850"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.7.0-SNAPSHOT.jar",
          "url": "util-jvm-1.7.0-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "bc1c058a728ee9c65862d8e9b4dd2e5aa1a9c9f1438f95d996f4e3b1b1d7abab57d6640e62b7b2a2f1976dc625c60bcab745646e139cab0a9aaaadecfda34f89",
          "sha256": "bbfb9ae1c40825cd48a5f54525f9c81e62108e3e9a529f510a19654f181c8a76",
          "sha1": "5081873a0886010acb888061dbbc8b0ac5f26deb",
          "md5": "18a7e611aabc6f3efaa486fd5fc62850"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.7.0-SNAPSHOT/util-metadata-1.7.0-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.7.0-SNAPSHOT"
      }
    }
  ]
}
