{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "or57dccynrfj7i3n64cav5czii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f85a9fa584177f1cdf1859a6dfa11f4f7a14638757332988eb68eb52f1b5fc61b6fa79967e736090b286b18a7574a275106aaa97cad89b5d520e37f1b96b3c40",
          "sha256": "64c01544b4b26b53d4043ce2787c26bdde1d04948b720bef92d68df08e4aceb7",
          "sha1": "1315c88e3a13e087b4c6d728c34e27d07f7ed611",
          "md5": "568d7573c724ea2eb2211cdd52d044aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f85a9fa584177f1cdf1859a6dfa11f4f7a14638757332988eb68eb52f1b5fc61b6fa79967e736090b286b18a7574a275106aaa97cad89b5d520e37f1b96b3c40",
          "sha256": "64c01544b4b26b53d4043ce2787c26bdde1d04948b720bef92d68df08e4aceb7",
          "sha1": "1315c88e3a13e087b4c6d728c34e27d07f7ed611",
          "md5": "568d7573c724ea2eb2211cdd52d044aa"
        }
      ]
    }
  ]
}
