{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-change-recordservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lc4ekwaa25aupaccjktqbxouxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "f835bfa2d13442a31ab8b2d73d26d24e73eb34d5ca7534d5ba314b10eba6556e9fdbd62b8967058043959203a2fc44d077e7699cee7fe76c9509dcf01c1ce99b",
          "sha256": "809eaec0d8f150ff3a61eb4aba07ae03fe1126fd1f5cfcc85cf38c507c4ee7f8",
          "sha1": "62e1b2c030fe051b5b5d0c1c9f80d029ed37e3e0",
          "md5": "4a7d3341ee7bee97d797bf7a23bec0ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "f835bfa2d13442a31ab8b2d73d26d24e73eb34d5ca7534d5ba314b10eba6556e9fdbd62b8967058043959203a2fc44d077e7699cee7fe76c9509dcf01c1ce99b",
          "sha256": "809eaec0d8f150ff3a61eb4aba07ae03fe1126fd1f5cfcc85cf38c507c4ee7f8",
          "sha1": "62e1b2c030fe051b5b5d0c1c9f80d029ed37e3e0",
          "md5": "4a7d3341ee7bee97d797bf7a23bec0ac"
        }
      ]
    }
  ]
}
