{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-jvm/0.0.1-prepare-release-0.1.0-SNAPSHOT/fhir-jvm-0.0.1-prepare-release-0.1.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-jvm",
    "version": "0.0.1-prepare-release-0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "eccipfpq5bfc5a66ui2ni4enwi"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.0.1-prepare-release-0.1.0-SNAPSHOT.jar",
          "url": "fhir-metadata-0.0.1-prepare-release-0.1.0-SNAPSHOT.jar",
          "size": 522470,
          "sha512": "a7644a49b50ad141eda99e842e16be6d1f29df55f4fa66efac6b92dbec8b643c969b12e41bd462f7b5d8f60f085d7d9f847da9193ff295cf2d995f30f4bcc5d4",
          "sha256": "cf92964d82929ec3489d01118a70a227a58bf9ab96ea46bfc8432f12ca3b7b2d",
          "sha1": "825a6fa33973b357419f8f17b587d75cf048f99c",
          "md5": "e0dd89130b7f9138deb10435293f01fb"
        }
      ]
    }
  ]
}
