{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.11.0-change-data-resource-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yd6cmoqvw5gtxadrkzzeeddmfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "sdk-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "4aa100525b8e061ff5af10ae4df39bfac8d3d320f31b2f596ba32a4eb4fd8735058a2fe1fab8c3d69db4f496f843d4cbb6f8a5b7bd50bd9c5bca838fcecd9a3b",
          "sha256": "f45695df8d64ddc450edf3c327a5ba74b34fda0e577d9b84561e8def296ebc27",
          "sha1": "80799fff2e55f48f0acf0e422cc90e232b8f4ce9",
          "md5": "50fa78c88e4ae51305e80ea15d089e33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "sdk-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "4aa100525b8e061ff5af10ae4df39bfac8d3d320f31b2f596ba32a4eb4fd8735058a2fe1fab8c3d69db4f496f843d4cbb6f8a5b7bd50bd9c5bca838fcecd9a3b",
          "sha256": "f45695df8d64ddc450edf3c327a5ba74b34fda0e577d9b84561e8def296ebc27",
          "sha1": "80799fff2e55f48f0acf0e422cc90e232b8f4ce9",
          "md5": "50fa78c88e4ae51305e80ea15d089e33"
        }
      ]
    }
  ]
}
