{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.0-fix-checkRestrictions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uakxpbldmjb6tazl5myxsuvqhi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "aad8420bcc28ca04b28e6b0fba379c89599438bb72a7e3e20ba29bcd3eb1d189d325559d11fb61f8143d7070d131e80b36f103e233aac437045f0dffb5cc5d95",
          "sha256": "ad90d7509aa9aa3c7774b8ea2022a12148d94de32b9f42793f23a21c4fe1f65a",
          "sha1": "02186968ec6185de8538b4290e847e0e6aa4227a",
          "md5": "596774671c383cdd50adf24053afbb23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "hc-fhir-sdk-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "aad8420bcc28ca04b28e6b0fba379c89599438bb72a7e3e20ba29bcd3eb1d189d325559d11fb61f8143d7070d131e80b36f103e233aac437045f0dffb5cc5d95",
          "sha256": "ad90d7509aa9aa3c7774b8ea2022a12148d94de32b9f42793f23a21c4fe1f65a",
          "sha1": "02186968ec6185de8538b4290e847e0e6aa4227a",
          "md5": "596774671c383cdd50adf24053afbb23"
        }
      ]
    }
  ]
}
