{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nj3eagqjd5dxfaflxok73sbxca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "e18926a88d40d36721ffd979200781c194ae60762f6dbd23de91336a3c1617c9f805440548359a675e78cda073b10df2f2d3769a8acb77fb4b1913532e763de7",
          "sha256": "e6c8f855945b023dbf04ac1b7fb560b1bb48356042cc433166f5fa122c24325b",
          "sha1": "7bce06b7f3fcbcaaa66525bf5d102d4233122a44",
          "md5": "6c6d68ad1d06e202a4bf38adf93725cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "e18926a88d40d36721ffd979200781c194ae60762f6dbd23de91336a3c1617c9f805440548359a675e78cda073b10df2f2d3769a8acb77fb4b1913532e763de7",
          "sha256": "e6c8f855945b023dbf04ac1b7fb560b1bb48356042cc433166f5fa122c24325b",
          "sha1": "7bce06b7f3fcbcaaa66525bf5d102d4233122a44",
          "md5": "6c6d68ad1d06e202a4bf38adf93725cf"
        }
      ]
    }
  ]
}
