{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qn2temi5sbc7nbiuu63cd3yfmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d5542d7139d8ba11c5bd7f4757a2fd04842f376b86b2791d12577f55bde38003dcb7d50feee67a013e7ed4ec260321ab596cb5f838d7dcdbce921b7d88ca9364",
          "sha256": "f9670bfa3f997d34919a5d9979eff2be652b2d952c3b192b75fe234dab0e184c",
          "sha1": "190c7017357284c365b3778f9e7cd372601f0205",
          "md5": "8fb5f9f87ab6d05a9df48d54da681251"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d5542d7139d8ba11c5bd7f4757a2fd04842f376b86b2791d12577f55bde38003dcb7d50feee67a013e7ed4ec260321ab596cb5f838d7dcdbce921b7d88ca9364",
          "sha256": "f9670bfa3f997d34919a5d9979eff2be652b2d952c3b192b75fe234dab0e184c",
          "sha1": "190c7017357284c365b3778f9e7cd372601f0205",
          "md5": "8fb5f9f87ab6d05a9df48d54da681251"
        }
      ]
    }
  ]
}
