{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3pyb4puf7bhmlkvuvebv6cilhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0a7b1379e4bf97bbf55592351bf1d497116d977786392d7d69141cb01bca8d5e92846fdc0065a44fd60f4cd9ff971c7017634ad07bf8cb56683a7002604426d6",
          "sha256": "1f8e666613ed6516fab649fa9d15e4ec24c50ba9ccc17a8b013d8f6db8134d45",
          "sha1": "959a78ed419013d9ef60bc957aecc7fbc00d0b06",
          "md5": "422bdb44459c6a5177545484c459e2e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0a7b1379e4bf97bbf55592351bf1d497116d977786392d7d69141cb01bca8d5e92846fdc0065a44fd60f4cd9ff971c7017634ad07bf8cb56683a7002604426d6",
          "sha256": "1f8e666613ed6516fab649fa9d15e4ec24c50ba9ccc17a8b013d8f6db8134d45",
          "sha1": "959a78ed419013d9ef60bc957aecc7fbc00d0b06",
          "md5": "422bdb44459c6a5177545484c459e2e1"
        }
      ]
    }
  ]
}
