{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "m7aaxujckjf7zf6fwpkjzmpblm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "006ac90d34c8e6150c5493a3133421f2a900d883cdc0ffec47b4163605808cec6858ed58ec620b99edaa6a3cf352b71eea78b7460db8ece984c75353604edb0b",
          "sha256": "c429524087be747a9307f91a2933a3a90f41f82568a73f43b8ae8d3926dc8f66",
          "sha1": "ecd318a0cea331580beae29587ae6c5d01c9bae3",
          "md5": "38e3b8bca3f795c3557335a0328d8a07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "006ac90d34c8e6150c5493a3133421f2a900d883cdc0ffec47b4163605808cec6858ed58ec620b99edaa6a3cf352b71eea78b7460db8ece984c75353604edb0b",
          "sha256": "c429524087be747a9307f91a2933a3a90f41f82568a73f43b8ae8d3926dc8f66",
          "sha1": "ecd318a0cea331580beae29587ae6c5d01c9bae3",
          "md5": "38e3b8bca3f795c3557335a0328d8a07"
        }
      ]
    }
  ]
}
