{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dpegcwlaknhglexe5z7dicohte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "900708facd675a81b93a564e3fcf4fdecd6ba081c5fd84ca2600c7c4c5395941c2a149525ab6fca84d34097bc1e7f721d739039f9a3cb17875bf626ea963ae92",
          "sha256": "1f9cc1772eb2af89197ebec25640215dcff46b30546c7f246fda811a1c680ec3",
          "sha1": "e6e6201871d0a3532a8d74e3e4e62a601c4802f2",
          "md5": "17133817742840b54c9ada1a5b86574a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "900708facd675a81b93a564e3fcf4fdecd6ba081c5fd84ca2600c7c4c5395941c2a149525ab6fca84d34097bc1e7f721d739039f9a3cb17875bf626ea963ae92",
          "sha256": "1f9cc1772eb2af89197ebec25640215dcff46b30546c7f246fda811a1c680ec3",
          "sha1": "e6e6201871d0a3532a8d74e3e4e62a601c4802f2",
          "md5": "17133817742840b54c9ada1a5b86574a"
        }
      ]
    }
  ]
}
