{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5vftwxu55vbqtdydsvviqdxsi4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a78c9f20b90ae2d171033d1e89386b91b96fdde7e87227410b87d65228b063a26380093975902b121a334599cc2736819189880964a6443a3b468d2f3bec3051",
          "sha256": "5d37cee72752025cd1bc8bbc9cc93a84f9ca920e3e80e0620d088397f8fd0839",
          "sha1": "7a646a3ef2791cf4391e262026ab1bb563fe0503",
          "md5": "b0d6ae5bff6294da8c5fe20ce9ceff31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "a78c9f20b90ae2d171033d1e89386b91b96fdde7e87227410b87d65228b063a26380093975902b121a334599cc2736819189880964a6443a3b468d2f3bec3051",
          "sha256": "5d37cee72752025cd1bc8bbc9cc93a84f9ca920e3e80e0620d088397f8fd0839",
          "sha1": "7a646a3ef2791cf4391e262026ab1bb563fe0503",
          "md5": "b0d6ae5bff6294da8c5fe20ce9ceff31"
        }
      ]
    }
  ]
}
