{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3kvozxbwrjemvmfb6mgha43lp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "85b85f4e808c6774272bc19989de686910345851588e686fb3293f75ec6ae06383666d99144280a6004d6033536f34e2244391a15fcaa5d8f5b3379fdeb4b2ca",
          "sha256": "dda6990d92d0a57ad4cebbffa2fd1e8b1647266c49eaa49a4c8d94d76717484c",
          "sha1": "eb3d9fe31c243a09ad51bfead7c475fa8099a3be",
          "md5": "1cedd0cd42de14a65b38098a1f1ea1ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "85b85f4e808c6774272bc19989de686910345851588e686fb3293f75ec6ae06383666d99144280a6004d6033536f34e2244391a15fcaa5d8f5b3379fdeb4b2ca",
          "sha256": "dda6990d92d0a57ad4cebbffa2fd1e8b1647266c49eaa49a4c8d94d76717484c",
          "sha1": "eb3d9fe31c243a09ad51bfead7c475fa8099a3be",
          "md5": "1cedd0cd42de14a65b38098a1f1ea1ed"
        }
      ]
    }
  ]
}
