{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m7nxczhs6vhnbej7f63yi3rily"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "138167ae57ae4f32caf4cb1c99865a7fe1b7595e5e8123c73277e71909af0069003e3ce28efd29f5d6cbcfadaa1a9fce463121a4ba489f384bfa0faaaa3dd7eb",
          "sha256": "b5708d0cd2a7d0f1efb7a3a48d705caa0b5bd937995862a978caed1ca5701385",
          "sha1": "6b58fd6c2265a46fb93a80523d2373451aba83c0",
          "md5": "d3b9a3d269bae73f932ac0c55f4545cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "138167ae57ae4f32caf4cb1c99865a7fe1b7595e5e8123c73277e71909af0069003e3ce28efd29f5d6cbcfadaa1a9fce463121a4ba489f384bfa0faaaa3dd7eb",
          "sha256": "b5708d0cd2a7d0f1efb7a3a48d705caa0b5bd937995862a978caed1ca5701385",
          "sha1": "6b58fd6c2265a46fb93a80523d2373451aba83c0",
          "md5": "d3b9a3d269bae73f932ac0c55f4545cf"
        }
      ]
    }
  ]
}
