{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jg5ko5y4ovhxdlp55ilmkj7dtu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "6d972a2219f0e3c1fbdaa02d522f4970963124a749fb34be4071c3e7a9c4275997262b19d69ec8ffa40d639530060e7a089ba04c66eb81397bd48529010488ea",
          "sha256": "9a3c71fdd67c2aa1ef2241f3b4f7bd4fe323f9dae4ec0072826c633e05b9e25f",
          "sha1": "fa7eda60848de5559ef8a59c43aabe8792cb2c16",
          "md5": "5001147e626a95722526b606482dcdde"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "6d972a2219f0e3c1fbdaa02d522f4970963124a749fb34be4071c3e7a9c4275997262b19d69ec8ffa40d639530060e7a089ba04c66eb81397bd48529010488ea",
          "sha256": "9a3c71fdd67c2aa1ef2241f3b4f7bd4fe323f9dae4ec0072826c633e05b9e25f",
          "sha1": "fa7eda60848de5559ef8a59c43aabe8792cb2c16",
          "md5": "5001147e626a95722526b606482dcdde"
        }
      ]
    }
  ]
}
