{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "34py5462pfbkfouviwjuylmjiy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "4a783805e3c8b2eb76070587be2a50f7b64fa509f1f865f3d5cf954eec5c853fc18d9853d1be966daa3f7fa5bd0ca7f22eda82b5b80b44d0b2083d1a3c7ca662",
          "sha256": "c908b7f520c0bcc01aa6f6c9eab42f80c2c4d4ad8c21f2c0456282c99c015bf1",
          "sha1": "25fb0811a8c7e130351c9d35f90c4bd4db066b75",
          "md5": "2445fe018211fb23cb301514731c7fe5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "4a783805e3c8b2eb76070587be2a50f7b64fa509f1f865f3d5cf954eec5c853fc18d9853d1be966daa3f7fa5bd0ca7f22eda82b5b80b44d0b2083d1a3c7ca662",
          "sha256": "c908b7f520c0bcc01aa6f6c9eab42f80c2c4d4ad8c21f2c0456282c99c015bf1",
          "sha1": "25fb0811a8c7e130351c9d35f90c4bd4db066b75",
          "md5": "2445fe018211fb23cb301514731c7fe5"
        }
      ]
    }
  ]
}
