{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "o6anqkxag5exnimorkqqtvpdla"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "60abdb47f74a825f6e6bf2dd647ee12befffe71d61f87ce5423c5322357776b2226925d0414b26808318e100b72d9e93ddbc794e310f0594cbcd195554255aa1",
          "sha256": "6bc57fe9f3a0b1e4eea02e80a4f641cc5a3ceedd9523b3d5bf723d196a5f7dd1",
          "sha1": "10713ddd402041685ced7c7c1d52fcf5fc14cb88",
          "md5": "6f4ad1efa5d14e419a2cdbf828612ed6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "60abdb47f74a825f6e6bf2dd647ee12befffe71d61f87ce5423c5322357776b2226925d0414b26808318e100b72d9e93ddbc794e310f0594cbcd195554255aa1",
          "sha256": "6bc57fe9f3a0b1e4eea02e80a4f641cc5a3ceedd9523b3d5bf723d196a5f7dd1",
          "sha1": "10713ddd402041685ced7c7c1d52fcf5fc14cb88",
          "md5": "6f4ad1efa5d14e419a2cdbf828612ed6"
        }
      ]
    }
  ]
}
