{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mfprk45s25axdkmq3qj2tphg7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "753b889fd1e4474921095d7846afa10540eb0bcfc1bc559b313037c6223bc598fe4a23a1d07699759bc98d059f53b8c6e512bb778a84ff43664259c38ed43f49",
          "sha256": "4ad4b59d3a7a0605f9b4e1936d2c5918ba6ae80613d1364fb15af73a9f2e9194",
          "sha1": "94bb44e41b0f2eae9322f87bb21f6e406f7b8617",
          "md5": "2c9ef3fb229fc2848cd629e6467d3f57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "753b889fd1e4474921095d7846afa10540eb0bcfc1bc559b313037c6223bc598fe4a23a1d07699759bc98d059f53b8c6e512bb778a84ff43664259c38ed43f49",
          "sha256": "4ad4b59d3a7a0605f9b4e1936d2c5918ba6ae80613d1364fb15af73a9f2e9194",
          "sha1": "94bb44e41b0f2eae9322f87bb21f6e406f7b8617",
          "md5": "2c9ef3fb229fc2848cd629e6467d3f57"
        }
      ]
    }
  ]
}
