{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-userid-on-client-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wd43gdahbje6jkpbzmqxe6tv2i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "386bfef3399b0f16fbc969cfc0c45c5ee54152dca01afc10419dc4737823b32d5cf934572d4193320c5d526217702429d4e77e26cbe2e560ca8c2ca2cbadab17",
          "sha256": "9101cfac19713a0ed79181e26e32286623c5cfd67e8c3dfaa451f480968f5985",
          "sha1": "80f17733fc5b05c8d6f177a237ae2a58eb083ae6",
          "md5": "15feaddbabe6419c35829a8da61b52ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "386bfef3399b0f16fbc969cfc0c45c5ee54152dca01afc10419dc4737823b32d5cf934572d4193320c5d526217702429d4e77e26cbe2e560ca8c2ca2cbadab17",
          "sha256": "9101cfac19713a0ed79181e26e32286623c5cfd67e8c3dfaa451f480968f5985",
          "sha1": "80f17733fc5b05c8d6f177a237ae2a58eb083ae6",
          "md5": "15feaddbabe6419c35829a8da61b52ef"
        }
      ]
    }
  ]
}
