{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-userid-on-client-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kupdmgur6bbnzmbzxuws6kjkhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "2974f1c34e2ffd85cd77bdc96e41feab9bf5918838ec02768b259b4305eaea498c7e00d5208f9678068015bb689bb6565c39e5a162ccc7c699699f681fee33be",
          "sha256": "1132cf8db1f0894a3236dc04145f96289694b773913394d0aac5dca4c31004f1",
          "sha1": "bf6b2c20e59bb12078329f7a27f6343171d548db",
          "md5": "4606a7245a4198d964ca4bcd89494075"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "2974f1c34e2ffd85cd77bdc96e41feab9bf5918838ec02768b259b4305eaea498c7e00d5208f9678068015bb689bb6565c39e5a162ccc7c699699f681fee33be",
          "sha256": "1132cf8db1f0894a3236dc04145f96289694b773913394d0aac5dca4c31004f1",
          "sha1": "bf6b2c20e59bb12078329f7a27f6343171d548db",
          "md5": "4606a7245a4198d964ca4bcd89494075"
        }
      ]
    }
  ]
}
