{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ja4kd4bnprgrfmhhxdwdqdqjqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2.jar",
          "url": "securestore-common-1.9.2.jar",
          "size": 6921,
          "sha512": "c6094b9ab89302354914eac3a42b40b49b291b49ce29b177f37cea1478de6ba8830d933ad30a11efa4ee352881c37759684e6cba4e70cf1bd92921774e94b653",
          "sha256": "3fb6f76cb4222d04d578842d811c1b0cb03fd61211d1d2436101fd815280631b",
          "sha1": "b318e465d7dc83db187e519e65882feb06fe277a",
          "md5": "192a6175f8a8311c5c3695dee514e360"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2.jar",
          "url": "securestore-common-1.9.2.jar",
          "size": 6921,
          "sha512": "c6094b9ab89302354914eac3a42b40b49b291b49ce29b177f37cea1478de6ba8830d933ad30a11efa4ee352881c37759684e6cba4e70cf1bd92921774e94b653",
          "sha256": "3fb6f76cb4222d04d578842d811c1b0cb03fd61211d1d2436101fd815280631b",
          "sha1": "b318e465d7dc83db187e519e65882feb06fe277a",
          "md5": "192a6175f8a8311c5c3695dee514e360"
        }
      ]
    }
  ]
}
