{
  "formatVersion": "1.1",
  "component": {
    "url": "../../data-donation-sdk/0.0.1-SNAPSHOT/data-donation-sdk-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.d4l-data-donation-sdk-kmp",
    "module": "data-donation-sdk",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "j4se3nznijcelot23e6lfubjdi"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-common",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-core",
          "version": {
            "requires": "3.0.1-alpha-2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2-native-mt"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-kmp",
          "module": "fhir",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.benasher44",
          "module": "uuid",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.2-native-mt",
            "requires": "1.4.2-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "data-donation-sdk.klib",
          "url": "data-donation-sdk-iosx64-0.0.1-SNAPSHOT.klib",
          "size": 7279037,
          "sha512": "ddc5f6c0342ab997690667213700f82b0eef28eccc5ca0b439634b84f2f68993873b2a05e2231cdcbb8329d64334b1e06cfb966d8b7538505d3425e7faeddd4b",
          "sha256": "8aa3d8e9ba47d656abc733cb302deeba6f566104c75c88d7d33bd634d0c714f5",
          "sha1": "96ea098d6dc3a87538aa46054196009e03b85c33",
          "md5": "0162bb5058aa471e9a0e56bdfafcba54"
        },
        {
          "name": "data-donation-sdk-cinterop-iOSDCryptoDD.klib",
          "url": "data-donation-sdk-iosx64-0.0.1-SNAPSHOT-cinterop-iOSDCryptoDD.klib",
          "size": 5937,
          "sha512": "8bba5116b9feb5eb7a80eca6f77575cf15be88558d0cc562be069fe53244aa76c638f0be4cc67fb352bba3d4af9e99a791b9ea09bb08ee5faf4bd2ea7e1a22ba",
          "sha256": "d013336157fdaf36ca72d9f2cdc4e6eb46d1b44ce7244b0f2bc1dd7ecd9bdf1e",
          "sha1": "f329e81088d41a195dc9e7b66086fabf1eb3a879",
          "md5": "8ee6b665e12cec76ff326a821ff76dc5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../data-donation-sdk-metadata/0.0.1-SNAPSHOT/data-donation-sdk-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.d4l-data-donation-sdk-kmp",
        "module": "data-donation-sdk-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
