{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "irpxytyxefdkdflntqxn4tbtae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0539897ecbfbc9d13c51d8b8d6393f47d0178e0c333dd48bc341c152441f34f2776d9afae844df9c9668a4893580206733eba8a8da5ba179e0ee49f5c03b1265",
          "sha256": "9954f3fead224377fba67f48336bafdbf98bade5cba1d6e3035f33236bd55dc6",
          "sha1": "cf7f383e279cf2c08751179bda7594880fabdae6",
          "md5": "52d206511aa986c80a5dce703a8f0e3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0539897ecbfbc9d13c51d8b8d6393f47d0178e0c333dd48bc341c152441f34f2776d9afae844df9c9668a4893580206733eba8a8da5ba179e0ee49f5c03b1265",
          "sha256": "9954f3fead224377fba67f48336bafdbf98bade5cba1d6e3035f33236bd55dc6",
          "sha1": "cf7f383e279cf2c08751179bda7594880fabdae6",
          "md5": "52d206511aa986c80a5dce703a8f0e3a"
        }
      ]
    }
  ]
}
