{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "b2jdpwlhsbdaderp7fakrbig5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "b88af8613728dc3177c21be2470a3a980dae33a069203b65f18b2e61328f42cf91206c576c6df321d3f7263677e145121c24685b4265760e8e97e844d3e6f39e",
          "sha256": "6460cb9fb8f6633f4cda3a4637426e11298d85e1654c755e2e9ae0935d8ffaf1",
          "sha1": "24abc991e5219a6589a911a8ed65c79342f1cfc8",
          "md5": "233f1ecf6b309853b4918a04a2e367e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "b88af8613728dc3177c21be2470a3a980dae33a069203b65f18b2e61328f42cf91206c576c6df321d3f7263677e145121c24685b4265760e8e97e844d3e6f39e",
          "sha256": "6460cb9fb8f6633f4cda3a4637426e11298d85e1654c755e2e9ae0935d8ffaf1",
          "sha1": "24abc991e5219a6589a911a8ed65c79342f1cfc8",
          "md5": "233f1ecf6b309853b4918a04a2e367e0"
        }
      ]
    }
  ]
}
