{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-jvm/0.0.1-SNAPSHOT/fhir-jvm-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-jvm",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "kov5wb6umrbs3gm2kpvmocqo74"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.0.1-SNAPSHOT.jar",
          "url": "fhir-metadata-0.0.1-SNAPSHOT.jar",
          "size": 522470,
          "sha512": "2b75ded824475859074be085e7d6f4d7c18ae9b682557e510e5168a84cc1a343831debeb29b178b8596adfabc67ac619ba171905c1ff7b976e1b5606e702015f",
          "sha256": "2ba575974f3a13c00fa93039cf85681ac8430fdc649876925ac9e3fd4531cabd",
          "sha1": "97a54684c4ddde88dae600d174cbf1c56ba2d020",
          "md5": "240617f95e2d35fd11b82d1b2e33022b"
        }
      ]
    }
  ]
}
