{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "y5px6cxa5jc3fi6srkqhuchaua"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "9c503c4a47d1f5349ae04963659426095ee383fc4dc22620ba40f7f9379142bcd2e21bac73493809403462e031dd55e7ac1f37c016c4855698fcdfebcf1f8eb9",
          "sha256": "9f1cf52f3b1a7f68267405abdc3719c8f50334ae5929235cbb141626a4b6fcb3",
          "sha1": "220ab5f62cb2139228f120382701e7e95c565d44",
          "md5": "1ddd5f203fd801e4f0ef1fda498f889a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "9c503c4a47d1f5349ae04963659426095ee383fc4dc22620ba40f7f9379142bcd2e21bac73493809403462e031dd55e7ac1f37c016c4855698fcdfebcf1f8eb9",
          "sha256": "9f1cf52f3b1a7f68267405abdc3719c8f50334ae5929235cbb141626a4b6fcb3",
          "sha1": "220ab5f62cb2139228f120382701e7e95c565d44",
          "md5": "1ddd5f203fd801e4f0ef1fda498f889a"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-metadata-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT"
      }
    }
  ]
}
