{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "pqmi5wxfjra6dn3erhclerokwa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "fd75edad371b4d95807dae1f7607b81c6ce6400fb89a43226504010da25d68eee32d6d24a4bc0ac625e65797974542e83820f9c85d52bdfc8daf68ddca398385",
          "sha256": "ab78ad16195909de01c87ad84f5976ead98a1b5cca1dcb1fc68c2543efd78f19",
          "sha1": "6193ae085a7c680b6b26ddfeb1d26a1769fecfe3",
          "md5": "b3855513868bf59cc21febdd980c048b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "size": 20014,
          "sha512": "fd75edad371b4d95807dae1f7607b81c6ce6400fb89a43226504010da25d68eee32d6d24a4bc0ac625e65797974542e83820f9c85d52bdfc8daf68ddca398385",
          "sha256": "ab78ad16195909de01c87ad84f5976ead98a1b5cca1dcb1fc68c2543efd78f19",
          "sha1": "6193ae085a7c680b6b26ddfeb1d26a1769fecfe3",
          "md5": "b3855513868bf59cc21febdd980c048b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-metadata-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT"
      }
    }
  ]
}
