{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-add-api-service-unit-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "c7kv3sbzo5b5xakqhskkutrzzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-api-service-unit-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "3946342c11937a627e446e7fb0556a4293d3b6f347123761296dec86488214b323ed33cfb8c611975b9f7b04328152c134c043d0050c059913c5c4aa917ec70b",
          "sha256": "bed32b08ea3ddf7bb6b2de50cc71a0277420d8a445a1ccebd9202788f2a65093",
          "sha1": "b1708ecdeb7b4b4a1d528dd04cc93e1e1cca16e8",
          "md5": "cdc7018aeb88d28e1c32de15cfb0d868"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-add-api-service-unit-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "3946342c11937a627e446e7fb0556a4293d3b6f347123761296dec86488214b323ed33cfb8c611975b9f7b04328152c134c043d0050c059913c5c4aa917ec70b",
          "sha256": "bed32b08ea3ddf7bb6b2de50cc71a0277420d8a445a1ccebd9202788f2a65093",
          "sha1": "b1708ecdeb7b4b4a1d528dd04cc93e1e1cca16e8",
          "md5": "cdc7018aeb88d28e1c32de15cfb0d868"
        }
      ]
    }
  ]
}
