{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hpnd2u6qujgqjgfw54y4rvr2fe"
    }
  },
  "variants": [
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.0.1-add-custom-maven-deployment-SNAPSHOT/fhir-android-0.0.1-add-custom-maven-deployment-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT"
      }
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.0.1-add-custom-maven-deployment-SNAPSHOT/fhir-android-0.0.1-add-custom-maven-deployment-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.0.1-add-custom-maven-deployment-SNAPSHOT/fhir-iosarm64-0.0.1-add-custom-maven-deployment-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT"
      }
    },
    {
      "name": "iosX64-api",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.0.1-add-custom-maven-deployment-SNAPSHOT/fhir-iosx64-0.0.1-add-custom-maven-deployment-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.0.1-add-custom-maven-deployment-SNAPSHOT/fhir-jvm-0.0.1-add-custom-maven-deployment-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.0.1-add-custom-maven-deployment-SNAPSHOT/fhir-jvm-0.0.1-add-custom-maven-deployment-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-add-custom-maven-deployment-SNAPSHOT/fhir-metadata-0.0.1-add-custom-maven-deployment-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-add-custom-maven-deployment-SNAPSHOT"
      }
    }
  ]
}
