{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-add-public-userid-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "l6ztkekqtzc27fitvroekqzi2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e2fb75e13544a18471058f0ea4c7b93297804a63fa688b2f73fbe5df12880caa66c2c0d347048d6194b69bd4c0fe13bcd14a2b4ccecb00c19be3e6e663ed9219",
          "sha256": "0b5a2dd4279332cdcb2a934852e4a07f2bcb095b1763564735b7f601fd0eef90",
          "sha1": "4f9251132cc8efb6590f6d2013e88ea7e168c8e7",
          "md5": "e950850ba60764ceb2d58ed7444c9324"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e2fb75e13544a18471058f0ea4c7b93297804a63fa688b2f73fbe5df12880caa66c2c0d347048d6194b69bd4c0fe13bcd14a2b4ccecb00c19be3e6e663ed9219",
          "sha256": "0b5a2dd4279332cdcb2a934852e4a07f2bcb095b1763564735b7f601fd0eef90",
          "sha1": "4f9251132cc8efb6590f6d2013e88ea7e168c8e7",
          "md5": "e950850ba60764ceb2d58ed7444c9324"
        }
      ]
    }
  ]
}
