{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-fix-release-ci-job-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xur4nmttufginmopoalmcfnbeu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "90a6a07f94e21ecdb088fa45564ec836411d8c7206ab04de8b836ae602bc5bec285c9eac6649db92a5db053dc349fc15997e01148a2043be9ee52b9152bd05e4",
          "sha256": "559dcf70a516793606f060dce18845f82af9f359ffe1236bbdcbd4c99d296a96",
          "sha1": "f806092c38e4d2d8980b00366da74cfcb6a0c405",
          "md5": "7478306e39aae6b1a298c256f05d5eae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-release-ci-job-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "90a6a07f94e21ecdb088fa45564ec836411d8c7206ab04de8b836ae602bc5bec285c9eac6649db92a5db053dc349fc15997e01148a2043be9ee52b9152bd05e4",
          "sha256": "559dcf70a516793606f060dce18845f82af9f359ffe1236bbdcbd4c99d296a96",
          "sha1": "f806092c38e4d2d8980b00366da74cfcb6a0c405",
          "md5": "7478306e39aae6b1a298c256f05d5eae"
        }
      ]
    }
  ]
}
