{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vfimpztftbhm5prj6mfe64n5hu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8015231bca6b3063f82d43f5211600814a92a836df5318def4bab9eaf6037abc3a1e95040a6cf76694a2c4977a52e9a62cb05ca6ef5d9ec6152eea81ce4da395",
          "sha256": "faba86c13265b446a196a96a94573a27bfb52588d83eff93b1361a999f052a14",
          "sha1": "4034b9d4066cb006a95ba2a958ffc69f75487033",
          "md5": "63e54423b17a2c0a1115c525cd2e4d33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "8015231bca6b3063f82d43f5211600814a92a836df5318def4bab9eaf6037abc3a1e95040a6cf76694a2c4977a52e9a62cb05ca6ef5d9ec6152eea81ce4da395",
          "sha256": "faba86c13265b446a196a96a94573a27bfb52588d83eff93b1361a999f052a14",
          "sha1": "4034b9d4066cb006a95ba2a958ffc69f75487033",
          "md5": "63e54423b17a2c0a1115c525cd2e4d33"
        }
      ]
    }
  ]
}
