{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6oau6ptl7va6rdgaejx6j2j2um"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "cf278b057b6ad08f110440914960af8c864dfc237484210df78f18a77b94ff52c4fce375b1a1cb5d5a4c09dcd29adf35ad92bb360ab57bcd61c1c0940589ec50",
          "sha256": "2a9bbef742f3702d99400346c35dcaa1199bd49751bb5b1bce71676158abb977",
          "sha1": "6b6d98d2f3724b3aa8559bcfabeb8777689c1b2c",
          "md5": "dca4aae0b9c5a7b39a1237d2791dd3ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "cf278b057b6ad08f110440914960af8c864dfc237484210df78f18a77b94ff52c4fce375b1a1cb5d5a4c09dcd29adf35ad92bb360ab57bcd61c1c0940589ec50",
          "sha256": "2a9bbef742f3702d99400346c35dcaa1199bd49751bb5b1bce71676158abb977",
          "sha1": "6b6d98d2f3724b3aa8559bcfabeb8777689c1b2c",
          "md5": "dca4aae0b9c5a7b39a1237d2791dd3ec"
        }
      ]
    }
  ]
}
