{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.2.0-fix-ci-job-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4wbuzeksb5bcjlj5jhbhyvnypu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.2.0-fix-ci-job-SNAPSHOT.jar",
          "url": "fhir-java-1.2.0-fix-ci-job-SNAPSHOT.jar",
          "size": 982177,
          "sha512": "51fad4a70e70dfe03a2d534c0e53882bd4cddf9c157f1834d66559ef150acd8644bee502d5d3d5e24ae8e03b6811c2f043671182ca50df061050407975099b76",
          "sha256": "c1bf212d7c1f358c901560b98e1b70c615f26c8baee3fcb553b0f26d69196845",
          "sha1": "689bf9e826ae9382b8ee8cbc1af3bdd88265c02e",
          "md5": "44b026db88d516cb366a59811e129323"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.2.0-fix-ci-job-SNAPSHOT.jar",
          "url": "fhir-java-1.2.0-fix-ci-job-SNAPSHOT.jar",
          "size": 982177,
          "sha512": "51fad4a70e70dfe03a2d534c0e53882bd4cddf9c157f1834d66559ef150acd8644bee502d5d3d5e24ae8e03b6811c2f043671182ca50df061050407975099b76",
          "sha256": "c1bf212d7c1f358c901560b98e1b70c615f26c8baee3fcb553b0f26d69196845",
          "sha1": "689bf9e826ae9382b8ee8cbc1af3bdd88265c02e",
          "md5": "44b026db88d516cb366a59811e129323"
        }
      ]
    }
  ]
}
