{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.0-fix-api-task-exposure-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cn7fqykbvjcrjihqtpnphfsqyi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-api-task-exposure-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.0-fix-api-task-exposure-SNAPSHOT.aar",
          "url": "auth-android-1.9.0-fix-api-task-exposure-SNAPSHOT.aar",
          "size": 44896,
          "sha512": "87e6a95f1fed72797ad7dc4d0217af6083507d6948a62c9f2fcdee77adb548ec581bd071fe4dee80240e53822381fc0d8b7dccb6070610308a64b5ccacd78552",
          "sha256": "9efca831ae15aeff8b8b84178aa6856d0ddf9818a387601968fc87eb0baf12ef",
          "sha1": "b3d9345b8bbaacd86e57fea4fbbc4a2757eaacc7",
          "md5": "157b89ffa2a26a33c477b016e2286800"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-api-task-exposure-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.0-fix-api-task-exposure-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.0-fix-api-task-exposure-SNAPSHOT.aar",
          "url": "auth-android-1.9.0-fix-api-task-exposure-SNAPSHOT.aar",
          "size": 44896,
          "sha512": "87e6a95f1fed72797ad7dc4d0217af6083507d6948a62c9f2fcdee77adb548ec581bd071fe4dee80240e53822381fc0d8b7dccb6070610308a64b5ccacd78552",
          "sha256": "9efca831ae15aeff8b8b84178aa6856d0ddf9818a387601968fc87eb0baf12ef",
          "sha1": "b3d9345b8bbaacd86e57fea4fbbc4a2757eaacc7",
          "md5": "157b89ffa2a26a33c477b016e2286800"
        }
      ]
    }
  ]
}
