{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ftwtfdrpvfhkrou5hlpm2ogkc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 9515,
          "sha512": "f20cd405053a15945c6bf5054f283a35573b59ebafe5dc5fc0873fcacdc695de007aa018c6ea9aa5b3db4758af68a76738063ca6c12e71fcad1dc7a3f9d6b5b2",
          "sha256": "837bdae59339020d22e00fb795a2000c0e58cd21c8d259a02abd006fe44a035b",
          "sha1": "9ccb6e963dca7b47d61b59bf5944b717774744cf",
          "md5": "d10e82127df8a2a271729fc53d5604d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 9515,
          "sha512": "f20cd405053a15945c6bf5054f283a35573b59ebafe5dc5fc0873fcacdc695de007aa018c6ea9aa5b3db4758af68a76738063ca6c12e71fcad1dc7a3f9d6b5b2",
          "sha256": "837bdae59339020d22e00fb795a2000c0e58cd21c8d259a02abd006fe44a035b",
          "sha1": "9ccb6e963dca7b47d61b59bf5944b717774744cf",
          "md5": "d10e82127df8a2a271729fc53d5604d8"
        }
      ]
    }
  ]
}
