{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5ph2gi7uebgnrcbd2s4f6dhuxe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.aar",
          "size": 51840,
          "sha512": "741cb0565a17a96ac75c3540e966388a9485ec82b7ba349a6530ad3d2790e976304216f60821d49d07ae1418e8d1a34a8cf41a95d6f5e27f7c430fd159e9df26",
          "sha256": "bd08c4e89ce38f3d242c77c35b56eb3f60239e74ffc57f421aae5ecda77c188b",
          "sha1": "70f070df0516b7720a5b8858ca45cca5fbeab193",
          "md5": "338c670db16de6846753cf6a567bccfa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.aar",
          "size": 51840,
          "sha512": "741cb0565a17a96ac75c3540e966388a9485ec82b7ba349a6530ad3d2790e976304216f60821d49d07ae1418e8d1a34a8cf41a95d6f5e27f7c430fd159e9df26",
          "sha256": "bd08c4e89ce38f3d242c77c35b56eb3f60239e74ffc57f421aae5ecda77c188b",
          "sha1": "70f070df0516b7720a5b8858ca45cca5fbeab193",
          "md5": "338c670db16de6846753cf6a567bccfa"
        }
      ]
    }
  ]
}
