{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-add-cryptoservice-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "aazr5moqkbbyfcrojkj4zbj3fy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "e78afd5a2ff66fdf022a8c93a54a8dc8fd2d2bc5a9c4cb406af8e8ac7be3cbe6c05889c6368209a409baa1c56b83c47a1bf4303cf9103944f3102ebed084fe33",
          "sha256": "2eeb0a8cb415e8f82a36b897fad214d56576b9d77b8212d7a3fbd2ad3869a87d",
          "sha1": "00bd6e8fe4b5e2b3c09e294ab8597e530171eb6d",
          "md5": "10aa4939552421542daaf126f4bca710"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-add-cryptoservice-fake-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "e78afd5a2ff66fdf022a8c93a54a8dc8fd2d2bc5a9c4cb406af8e8ac7be3cbe6c05889c6368209a409baa1c56b83c47a1bf4303cf9103944f3102ebed084fe33",
          "sha256": "2eeb0a8cb415e8f82a36b897fad214d56576b9d77b8212d7a3fbd2ad3869a87d",
          "sha1": "00bd6e8fe4b5e2b3c09e294ab8597e530171eb6d",
          "md5": "10aa4939552421542daaf126f4bca710"
        }
      ]
    }
  ]
}
