{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "imzeqhalfzfrdk3qxsrewgyble"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a7621a081d4febf45507017f35d2c3b6593f0447399196a9c2c1ee2120183cca24cab6ed9e494f2065dd1f48c6751ccacd2bc29ac580054f37b4399f0cf6b905",
          "sha256": "f4a8022675394e6303a6618db1249e65ce74e3c7b5e41745a7901f3fcc222755",
          "sha1": "356b78cd1115fcb56c92b79bfa710ca963cad069",
          "md5": "b2910d5d8313dc722b088ddc736be85d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a7621a081d4febf45507017f35d2c3b6593f0447399196a9c2c1ee2120183cca24cab6ed9e494f2065dd1f48c6751ccacd2bc29ac580054f37b4399f0cf6b905",
          "sha256": "f4a8022675394e6303a6618db1249e65ce74e3c7b5e41745a7901f3fcc222755",
          "sha1": "356b78cd1115fcb56c92b79bfa710ca963cad069",
          "md5": "b2910d5d8313dc722b088ddc736be85d"
        }
      ]
    }
  ]
}
