{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-change-tag-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "keu5ccvxpvhf3alvj7bjdptbca"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "size": 44945,
          "sha512": "90c05c1712b8aaacde199f56dfe564431c60cf6af8da08cc7103ce9a1e2b9d4b3006d731ff4b3d5ba578c7a08c8bfd587a870a37a3877949e2b104e2c4708d72",
          "sha256": "71d36ec9deb526d139ec7326ef1ef6d9f0bf05e6b9bc828aaf4ccedaf817204b",
          "sha1": "2d278b32e177f4f0e32ce6c685efa18ad61c49fa",
          "md5": "47be1997109aeddafb4f9c3b4d3d0d6a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "size": 44945,
          "sha512": "90c05c1712b8aaacde199f56dfe564431c60cf6af8da08cc7103ce9a1e2b9d4b3006d731ff4b3d5ba578c7a08c8bfd587a870a37a3877949e2b104e2c4708d72",
          "sha256": "71d36ec9deb526d139ec7326ef1ef6d9f0bf05e6b9bc828aaf4ccedaf817204b",
          "sha1": "2d278b32e177f4f0e32ce6c685efa18ad61c49fa",
          "md5": "47be1997109aeddafb4f9c3b4d3d0d6a"
        }
      ]
    }
  ]
}
