{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-change-tag-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fgehbeg3onclrdcsgzga4v7z4a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "size": 44958,
          "sha512": "733a2725e13573610ca3e21b284d3b2de24b5cc865dc262995612bfa94ca39b5acf0508084b60e64ee8a87164280fde15f644506bb802fead7f4e0fb71047988",
          "sha256": "d215ef04ce6a224515bcc32034383aec8fc757830ab6404a49241cb37d2aa003",
          "sha1": "341ac799f91b58cd85cb7c8fe38996fb7e97ef56",
          "md5": "204d1d0247ae4fe9c32ae9bf3bafceac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "size": 44958,
          "sha512": "733a2725e13573610ca3e21b284d3b2de24b5cc865dc262995612bfa94ca39b5acf0508084b60e64ee8a87164280fde15f644506bb802fead7f4e0fb71047988",
          "sha256": "d215ef04ce6a224515bcc32034383aec8fc757830ab6404a49241cb37d2aa003",
          "sha1": "341ac799f91b58cd85cb7c8fe38996fb7e97ef56",
          "md5": "204d1d0247ae4fe9c32ae9bf3bafceac"
        }
      ]
    }
  ]
}
