{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zriivgusrng6bavxn7or772wey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "851ba0108f86ed08c97819b5be879548849d8c2f5169dba4aa5735307b5e8ec7b3917a524d90fd267b56aefcdbadae30ca581966203537fc4bec16cc81627333",
          "sha256": "8caf12f428699d76a381aecefec722615c210ec1cb9a9d40b1e6fc2bf0b8c320",
          "sha1": "4d1ebc3825c980ea07e8c8c3a0d7d9b83c49c6f1",
          "md5": "e698e8fdcef6243fe1a331d8ca01bfff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "851ba0108f86ed08c97819b5be879548849d8c2f5169dba4aa5735307b5e8ec7b3917a524d90fd267b56aefcdbadae30ca581966203537fc4bec16cc81627333",
          "sha256": "8caf12f428699d76a381aecefec722615c210ec1cb9a9d40b1e6fc2bf0b8c320",
          "sha1": "4d1ebc3825c980ea07e8c8c3a0d7d9b83c49c6f1",
          "md5": "e698e8fdcef6243fe1a331d8ca01bfff"
        }
      ]
    }
  ]
}
