{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vfimpztftbhm5prj6mfe64n5hu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ae561b87e2485f78b21adbe5f1c97d75e6582bbca554056293bd7ac9030baf5972e9bcf56915a216fd1e854ab6ba99ef0f6ca4a9cad00c9b7150152b54bd66c3",
          "sha256": "302dbfa0b4eea8f55e91e988e37e0140e4819032ef7e39d768c2766dfc6fa677",
          "sha1": "7add095f0ccd4e3d5ac6b59d7c1a0066ecde0c01",
          "md5": "2126fe9f5683bd4bd9ab3ba3c1d5327b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "ae561b87e2485f78b21adbe5f1c97d75e6582bbca554056293bd7ac9030baf5972e9bcf56915a216fd1e854ab6ba99ef0f6ca4a9cad00c9b7150152b54bd66c3",
          "sha256": "302dbfa0b4eea8f55e91e988e37e0140e4819032ef7e39d768c2766dfc6fa677",
          "sha1": "7add095f0ccd4e3d5ac6b59d7c1a0066ecde0c01",
          "md5": "2126fe9f5683bd4bd9ab3ba3c1d5327b"
        }
      ]
    }
  ]
}
