{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "b645qhpounhvbn4genyfu62jb4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1c411f847e7edfe099fbe06d9232fa0ea3685da52aa45d137093650baecb0b4c7bf12efb471ca1934fb0c52832959da235ab036e0b9cd4cc4eca8b127709b9ad",
          "sha256": "10ef8c5038b48c30d8bc8d99d8f18be4d426908b5a95a4ec6dbb29bd193a1f7b",
          "sha1": "8084db8fd48f035950629b7d11a75361e19fc840",
          "md5": "c38a3605cfa3815ef956bb2c127690f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1c411f847e7edfe099fbe06d9232fa0ea3685da52aa45d137093650baecb0b4c7bf12efb471ca1934fb0c52832959da235ab036e0b9cd4cc4eca8b127709b9ad",
          "sha256": "10ef8c5038b48c30d8bc8d99d8f18be4d426908b5a95a4ec6dbb29bd193a1f7b",
          "sha1": "8084db8fd48f035950629b7d11a75361e19fc840",
          "md5": "c38a3605cfa3815ef956bb2c127690f9"
        }
      ]
    }
  ]
}
