{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wgde7xnbkzhrjkwotraczy5wyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d47aa38e1514fc129e61cf845915f6ca2e95e8497cec54d13bb14d572c4c097c346b000f8279a65e0c1e6b8800c11deaaaf0a07f644f9196e2b237135d6bb084",
          "sha256": "9c91223efcaa7bf94da025b139d45fb6a5e6534a101fd228dd297fafa95f7861",
          "sha1": "484d6011c8eb9bcb5fe6c3970d14f8b94e7d163d",
          "md5": "98319bb0dcb9dd49c48763af31df53c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d47aa38e1514fc129e61cf845915f6ca2e95e8497cec54d13bb14d572c4c097c346b000f8279a65e0c1e6b8800c11deaaaf0a07f644f9196e2b237135d6bb084",
          "sha256": "9c91223efcaa7bf94da025b139d45fb6a5e6534a101fd228dd297fafa95f7861",
          "sha1": "484d6011c8eb9bcb5fe6c3970d14f8b94e7d163d",
          "md5": "98319bb0dcb9dd49c48763af31df53c0"
        }
      ]
    }
  ]
}
