{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-remove-bintray-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hau4h3odnfdqrd3kcmmfixmrqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "c56bd9338fb9ba69c1284bd2099e49f6d233912a23f2f8fd5381ba1a703313a913a0c47ad9661ee3a94ba7b7e520ab27cb4556fae399069a47cbee4a6406360b",
          "sha256": "0143edd75377356b1bf806fb764604e02c5e7e4b117c1412c7fdbd4b3476ebd5",
          "sha1": "3ae63e6ee6041e391cc084d7f45c523d2f96ec10",
          "md5": "dce87cb27440b344212f8ae231912915"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "c56bd9338fb9ba69c1284bd2099e49f6d233912a23f2f8fd5381ba1a703313a913a0c47ad9661ee3a94ba7b7e520ab27cb4556fae399069a47cbee4a6406360b",
          "sha256": "0143edd75377356b1bf806fb764604e02c5e7e4b117c1412c7fdbd4b3476ebd5",
          "sha1": "3ae63e6ee6041e391cc084d7f45c523d2f96ec10",
          "md5": "dce87cb27440b344212f8ae231912915"
        }
      ]
    }
  ]
}
