{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-fix-release-ci-job-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xur4nmttufginmopoalmcfnbeu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "abfc3fe97b91c946f0105360fef23e2ffbffa100a1d8071da1f30d42a4b5bd31ed6e7bd993f8e460250331e089c82a6b145a39c5e1ecd388bdee8e17fe4aaad7",
          "sha256": "a109da83ee60d3ea34a44cf811758049e55a7d1aeacd722a5272691a1d515373",
          "sha1": "1b7ffec91b6ed5b2d0271927208abb5e87abae26",
          "md5": "b1a579e5023a1e56fbcf7292822fb67e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "abfc3fe97b91c946f0105360fef23e2ffbffa100a1d8071da1f30d42a4b5bd31ed6e7bd993f8e460250331e089c82a6b145a39c5e1ecd388bdee8e17fe4aaad7",
          "sha256": "a109da83ee60d3ea34a44cf811758049e55a7d1aeacd722a5272691a1d515373",
          "sha1": "1b7ffec91b6ed5b2d0271927208abb5e87abae26",
          "md5": "b1a579e5023a1e56fbcf7292822fb67e"
        }
      ]
    }
  ]
}
