{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "32azslkqffd3znzgmhvi44kjza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "8e1dc0e841a4b517fee1a0f275cdbacb861fbcaf746eaa81e2a48d8ab40dedc11046c6eafe956394b867aa87fd495b9b51590fd0a7e88681550bc67c315ee568",
          "sha256": "6698188bb5ace398605bd1648190dfad3bb13fb710bdfe5e856bf11a47165c56",
          "sha1": "aebe72fe46adffea1fcb52d5dfe00bf49c4739a7",
          "md5": "11088d8a33eed8cb826f910f4f68e1e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "8e1dc0e841a4b517fee1a0f275cdbacb861fbcaf746eaa81e2a48d8ab40dedc11046c6eafe956394b867aa87fd495b9b51590fd0a7e88681550bc67c315ee568",
          "sha256": "6698188bb5ace398605bd1648190dfad3bb13fb710bdfe5e856bf11a47165c56",
          "sha1": "aebe72fe46adffea1fcb52d5dfe00bf49c4739a7",
          "md5": "11088d8a33eed8cb826f910f4f68e1e4"
        }
      ]
    }
  ]
}
