{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qn2temi5sbc7nbiuu63cd3yfmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "beef4821c3510555df399bc45f180efdb120f2816f1fea91cbcea3e448258c88de6758623a59088691b5ac2b7427e9985f8da1e7c412a9d213a2692c41c77e97",
          "sha256": "48b7e199a3b81bf67d4de6f96af17a8032e756220c7041b92fbf251dd56a22d5",
          "sha1": "978d79d8c4eee8a051924badcf32d529f85617e1",
          "md5": "7fb3abf4894a3ea0d5ec95a7f6a887dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "beef4821c3510555df399bc45f180efdb120f2816f1fea91cbcea3e448258c88de6758623a59088691b5ac2b7427e9985f8da1e7c412a9d213a2692c41c77e97",
          "sha256": "48b7e199a3b81bf67d4de6f96af17a8032e756220c7041b92fbf251dd56a22d5",
          "sha1": "978d79d8c4eee8a051924badcf32d529f85617e1",
          "md5": "7fb3abf4894a3ea0d5ec95a7f6a887dd"
        }
      ]
    }
  ]
}
