{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jg5ko5y4ovhxdlp55ilmkj7dtu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "5c9f693d66b7304429a44a29b683e4790806f1d850e1301f08ecaccf837ec60ef1d9aec4580913a86b9541a002e00ae95d0c8dcb32fd181b3c1890837d9abd9d",
          "sha256": "996518f74e53f2be4961f76d8939cbb61b457fe2b5d7697c6c58ede4d8b0ca41",
          "sha1": "807523abee8fc4e00cceaf51af4566a9832fa4d8",
          "md5": "df645632ad6b093c969a8c0a43ffa2c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "5c9f693d66b7304429a44a29b683e4790806f1d850e1301f08ecaccf837ec60ef1d9aec4580913a86b9541a002e00ae95d0c8dcb32fd181b3c1890837d9abd9d",
          "sha256": "996518f74e53f2be4961f76d8939cbb61b457fe2b5d7697c6c58ede4d8b0ca41",
          "sha1": "807523abee8fc4e00cceaf51af4566a9832fa4d8",
          "md5": "df645632ad6b093c969a8c0a43ffa2c3"
        }
      ]
    }
  ]
}
