{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5vftwxu55vbqtdydsvviqdxsi4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "8171bd7528ac2e04cbce59d697daf4d47ad371a3556909f26ac8aa8f04e9fc032ba8e61daa0019a1a014f52d2d5e03c610e15df3f72a37a4b8e10018b473ab1e",
          "sha256": "385a2c56faebd313137d177debe6d4abf3c50de465bd00342f63e182f52e6692",
          "sha1": "52c6a535421278beb4c48e95f2875e4985cf3c6c",
          "md5": "57dd9c9fcd4c6c40b29264cc78acd9c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "8171bd7528ac2e04cbce59d697daf4d47ad371a3556909f26ac8aa8f04e9fc032ba8e61daa0019a1a014f52d2d5e03c610e15df3f72a37a4b8e10018b473ab1e",
          "sha256": "385a2c56faebd313137d177debe6d4abf3c50de465bd00342f63e182f52e6692",
          "sha1": "52c6a535421278beb4c48e95f2875e4985cf3c6c",
          "md5": "57dd9c9fcd4c6c40b29264cc78acd9c0"
        }
      ]
    }
  ]
}
