{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jl2qil3tzff25k2hct3m6p7nya"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "f5b3e6b9d9fd19deeb79b2e1f8ee9f3941110790298cab9ed9e1521a8c52f016d0887e2bf3f8e8f2e3fefe3da37f546358ed15e9bb0ab12adf8bdb0ac8ee8291",
          "sha256": "486582eb6d048ec87ebf809adb4da651b3067caf040615c827330a0784addb71",
          "sha1": "3a5b284dbfa972553e1b825be2a8c1bf2b8d5e3f",
          "md5": "f3bcb33d60003f94a85c0a8e43200add"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "f5b3e6b9d9fd19deeb79b2e1f8ee9f3941110790298cab9ed9e1521a8c52f016d0887e2bf3f8e8f2e3fefe3da37f546358ed15e9bb0ab12adf8bdb0ac8ee8291",
          "sha256": "486582eb6d048ec87ebf809adb4da651b3067caf040615c827330a0784addb71",
          "sha1": "3a5b284dbfa972553e1b825be2a8c1bf2b8d5e3f",
          "md5": "f3bcb33d60003f94a85c0a8e43200add"
        }
      ]
    }
  ]
}
