{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zwszjccqwje4xp5po7bm7dzidi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "a8f016ed52bfac804eae20555e1ceefc0ca8681f93df90c8a18f5208cabb25d5e308a1c70ac795c94af0303a260262e92f88edfa427f198950ca1dd58a7400c7",
          "sha256": "85f3490edc24e2c7e38c8dd65c294a973c3d91aa67fbfc8169d52d2a28be2842",
          "sha1": "0cbc0e0ccf202cb441ed4e32aadee512be3e58d8",
          "md5": "c06d39adf0e79c6ecb5d427fe915a908"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "a8f016ed52bfac804eae20555e1ceefc0ca8681f93df90c8a18f5208cabb25d5e308a1c70ac795c94af0303a260262e92f88edfa427f198950ca1dd58a7400c7",
          "sha256": "85f3490edc24e2c7e38c8dd65c294a973c3d91aa67fbfc8169d52d2a28be2842",
          "sha1": "0cbc0e0ccf202cb441ed4e32aadee512be3e58d8",
          "md5": "c06d39adf0e79c6ecb5d427fe915a908"
        }
      ]
    }
  ]
}
