{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uh3ziqrwgbe6tp4p7bcp6y3w2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16425,
          "sha512": "5060087a221c3122863d71182767f7b875adc27f353628f79c450e25f2fa0eb891dead99193807ff16a839857eca59039c6fa358a34ad5bae733d64ecb585284",
          "sha256": "4ee5e86ca04e15f859f2807d9a96eeeeff5f46ca573175189c45d47dffabb2f7",
          "sha1": "55896588cf579a87d752bbedcb31abe870a14e3c",
          "md5": "beb472acfcc492cbefa00f0a2546d5c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16425,
          "sha512": "5060087a221c3122863d71182767f7b875adc27f353628f79c450e25f2fa0eb891dead99193807ff16a839857eca59039c6fa358a34ad5bae733d64ecb585284",
          "sha256": "4ee5e86ca04e15f859f2807d9a96eeeeff5f46ca573175189c45d47dffabb2f7",
          "sha1": "55896588cf579a87d752bbedcb31abe870a14e3c",
          "md5": "beb472acfcc492cbefa00f0a2546d5c9"
        }
      ]
    }
  ]
}
