{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "swlchhbfvrhc5hcb5szgxujo7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "0288010591b3e4533aba1fb6d537077c0593167656c93207384ef4d92534cacd78a8bd5deed372c48641a2d68e502d0640648545a0e0d66a377d82bf96aca367",
          "sha256": "3631d372592b3e5d61c5ce74f154a9eda1015fe3d20b449e820d2b1752a4435d",
          "sha1": "59a94c1c00cbbb518341aafaa427d797be0a30cb",
          "md5": "95a218708e34001c7dc243b9f862c19e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "0288010591b3e4533aba1fb6d537077c0593167656c93207384ef4d92534cacd78a8bd5deed372c48641a2d68e502d0640648545a0e0d66a377d82bf96aca367",
          "sha256": "3631d372592b3e5d61c5ce74f154a9eda1015fe3d20b449e820d2b1752a4435d",
          "sha1": "59a94c1c00cbbb518341aafaa427d797be0a30cb",
          "md5": "95a218708e34001c7dc243b9f862c19e"
        }
      ]
    }
  ]
}
