{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "o6anqkxag5exnimorkqqtvpdla"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "5e862325f8404e4fa5c51bc7835591f0a0e89c7402398d2e6708cd1213b64c8e52878e8795daa10df9d11f4b15fb030940fdb9ae9e4ca936b2428bfc893b9d41",
          "sha256": "2cab3dc5c7b4b3d22a5adba54f4be492dd03691f4eb9f21e622adcff665df3df",
          "sha1": "a5792d001ffa10843b8e9569e94782b675619906",
          "md5": "4dd88681c50abebbfddb536a1fd80546"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "5e862325f8404e4fa5c51bc7835591f0a0e89c7402398d2e6708cd1213b64c8e52878e8795daa10df9d11f4b15fb030940fdb9ae9e4ca936b2428bfc893b9d41",
          "sha256": "2cab3dc5c7b4b3d22a5adba54f4be492dd03691f4eb9f21e622adcff665df3df",
          "sha1": "a5792d001ffa10843b8e9569e94782b675619906",
          "md5": "4dd88681c50abebbfddb536a1fd80546"
        }
      ]
    }
  ]
}
