{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xtab6kvin5hyvejvr2kts7vwpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "d1f9b55fa55f2c4a118152eea06f3760254126e39f9e15d3f97bae107f69e46f2094eeccf2b394d9b8e607a730ad7f19f8dea286db393dcbda65b349350387be",
          "sha256": "f59227d48446ac1c53c05171e08010c33cddb8e88677453ff2960d4d5dfb4829",
          "sha1": "36bc72fffe935c16b55ca4a19309f8e568727e00",
          "md5": "ddc300553698908c5bf4f0be859fb2f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "d1f9b55fa55f2c4a118152eea06f3760254126e39f9e15d3f97bae107f69e46f2094eeccf2b394d9b8e607a730ad7f19f8dea286db393dcbda65b349350387be",
          "sha256": "f59227d48446ac1c53c05171e08010c33cddb8e88677453ff2960d4d5dfb4829",
          "sha1": "36bc72fffe935c16b55ca4a19309f8e568727e00",
          "md5": "ddc300553698908c5bf4f0be859fb2f1"
        }
      ]
    }
  ]
}
