{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.6.1-change-project-to-kotlin-script-SNAPSHOT/util-1.6.1-change-project-to-kotlin-script-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.6.1-change-project-to-kotlin-script-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g3rumfbscjggdcbu6nytlqdic4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "size": 19961,
          "sha512": "a692a60dbc97d68ba0cd6cc8065d5ce1a896178d8c6390a952d49749ed2ac5d80a89f6ea559bdbb5b6db5ca67300c52ffa77fea400edd333ac02514a302a3ef4",
          "sha256": "812e5d5ce0460fc79c96a52698c8535dc3c566899fb0eae356f4f66c981d6f8b",
          "sha1": "608ee541edf889bb9b947e28818d69d41fa19376",
          "md5": "98c4be3e9c91923831dfa0657a490ed1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "size": 19961,
          "sha512": "a692a60dbc97d68ba0cd6cc8065d5ce1a896178d8c6390a952d49749ed2ac5d80a89f6ea559bdbb5b6db5ca67300c52ffa77fea400edd333ac02514a302a3ef4",
          "sha256": "812e5d5ce0460fc79c96a52698c8535dc3c566899fb0eae356f4f66c981d6f8b",
          "sha1": "608ee541edf889bb9b947e28818d69d41fa19376",
          "md5": "98c4be3e9c91923831dfa0657a490ed1"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.6.1-change-project-to-kotlin-script-SNAPSHOT/util-metadata-1.6.1-change-project-to-kotlin-script-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.6.1-change-project-to-kotlin-script-SNAPSHOT"
      }
    }
  ]
}
