{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util/1.6.1-change-project-to-kotlin-script-SNAPSHOT/util-1.6.1-change-project-to-kotlin-script-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.6.1-change-project-to-kotlin-script-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ytq6c4hgevdnrdip4bqdbh4l5i"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "size": 19941,
          "sha512": "d32b3a90133aff0680c496dea12401d67a0e36d5048b65e326891cc23ef4b93babe8f7c9920505051ee7ffd6d557275e4e378b97424f3164305c52e35badd68d",
          "sha256": "ad0598beddd1941a47f21a8d31131ee1de296fe83907f5cefbee1aaa254b8ff2",
          "sha1": "506c54569f14461188949c967d400e52db7a880c",
          "md5": "9b1ff04e75b3478ed06a82ee33ceba86"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "url": "util-jvm-1.6.1-change-project-to-kotlin-script-SNAPSHOT.jar",
          "size": 19941,
          "sha512": "d32b3a90133aff0680c496dea12401d67a0e36d5048b65e326891cc23ef4b93babe8f7c9920505051ee7ffd6d557275e4e378b97424f3164305c52e35badd68d",
          "sha256": "ad0598beddd1941a47f21a8d31131ee1de296fe83907f5cefbee1aaa254b8ff2",
          "sha1": "506c54569f14461188949c967d400e52db7a880c",
          "md5": "9b1ff04e75b3478ed06a82ee33ceba86"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../util-metadata/1.6.1-change-project-to-kotlin-script-SNAPSHOT/util-metadata-1.6.1-change-project-to-kotlin-script-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-metadata",
        "version": "1.6.1-change-project-to-kotlin-script-SNAPSHOT"
      }
    }
  ]
}
