{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-add-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "f2ujxy6ikjbezh2mz67jn6phle"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-danger-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-add-danger-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-add-danger-SNAPSHOT.aar",
          "size": 44887,
          "sha512": "43e6338b1c0e313582126690282a5f163570c07dda6889df84db07e2ee16cdd4460b006d595ae17fd21fe36242ad138dff91565bebc0dadd8c04450d149a3aeb",
          "sha256": "dd744e4261f3095bd20bb6fc440523062eaddd6e9248a75c9f1f968114f66e5a",
          "sha1": "7642abb959643bf319d81c18847d9cac78f82f30",
          "md5": "fb07cdab1cdcbbd19153b8e71501bfb7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-danger-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-add-danger-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-add-danger-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-add-danger-SNAPSHOT.aar",
          "size": 44887,
          "sha512": "43e6338b1c0e313582126690282a5f163570c07dda6889df84db07e2ee16cdd4460b006d595ae17fd21fe36242ad138dff91565bebc0dadd8c04450d149a3aeb",
          "sha256": "dd744e4261f3095bd20bb6fc440523062eaddd6e9248a75c9f1f968114f66e5a",
          "sha1": "7642abb959643bf319d81c18847d9cac78f82f30",
          "md5": "fb07cdab1cdcbbd19153b8e71501bfb7"
        }
      ]
    }
  ]
}
