{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-change-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5ra3tyqeafcl5cwiigzp2kmum4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0b85501f842b2ee443dd76b11d8ca802cc4a9facf56a16a56aac4ff15fa4f805ebfcd3c3b130e0b87e69380374b5fd2656e8c592932c74d2d5185989b2d28a76",
          "sha256": "cc6d4a735e6a818b499d1cbf546f6d96163ca9fd9278a08f4ce04508bdea5eaf",
          "sha1": "a88dba590513f2f8705d1aec14731a0925507745",
          "md5": "7052ae88678e15f0a14440967f8d98d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0b85501f842b2ee443dd76b11d8ca802cc4a9facf56a16a56aac4ff15fa4f805ebfcd3c3b130e0b87e69380374b5fd2656e8c592932c74d2d5185989b2d28a76",
          "sha256": "cc6d4a735e6a818b499d1cbf546f6d96163ca9fd9278a08f4ce04508bdea5eaf",
          "sha1": "a88dba590513f2f8705d1aec14731a0925507745",
          "md5": "7052ae88678e15f0a14440967f8d98d8"
        }
      ]
    }
  ]
}
