{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4yb35zvb7bedzljq34ph7gdroq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "5152fc9bbb44b26b40001da7f1c3f9bb1da7ce582d1d12e5a72caacdce16c86283f4b4fe2eb0ee18df170666a35055a7934d6c48a883a18f41a946333df457ff",
          "sha256": "1e7f96b9006b58c2cdf7c1f20ddeb72540183a8bb52feb8b0a86e6dfdce8e2ca",
          "sha1": "f2654c4bc2afc12bdae44206c4b7c6a3ee2e902c",
          "md5": "6434b0179cb8860e42abf7cf77988b10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "5152fc9bbb44b26b40001da7f1c3f9bb1da7ce582d1d12e5a72caacdce16c86283f4b4fe2eb0ee18df170666a35055a7934d6c48a883a18f41a946333df457ff",
          "sha256": "1e7f96b9006b58c2cdf7c1f20ddeb72540183a8bb52feb8b0a86e6dfdce8e2ca",
          "sha1": "f2654c4bc2afc12bdae44206c4b7c6a3ee2e902c",
          "md5": "6434b0179cb8860e42abf7cf77988b10"
        }
      ]
    }
  ]
}
