{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "l2ybysrhkzbpbl6dccawjm2vum"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.aar",
          "size": 41924,
          "sha512": "6b03254f54adf6bb7a27e670d2dc05c5f78a4c62ea24f98e792c8e71e6b157973e0d43302976e8a20675628b465e47ab255bcc3cfa7f7c9943740d1f6b3841cf",
          "sha256": "5d79cfa0e620b13780de1e453cb03516a922d9f6453a9270ed6fb52631e18386",
          "sha1": "08dd3fb55e594eca7aeb2ef7161dca5fa7539ec5",
          "md5": "2c4586da35c6636915178baa4144b62b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.aar",
          "size": 41924,
          "sha512": "6b03254f54adf6bb7a27e670d2dc05c5f78a4c62ea24f98e792c8e71e6b157973e0d43302976e8a20675628b465e47ab255bcc3cfa7f7c9943740d1f6b3841cf",
          "sha256": "5d79cfa0e620b13780de1e453cb03516a922d9f6453a9270ed6fb52631e18386",
          "sha1": "08dd3fb55e594eca7aeb2ef7161dca5fa7539ec5",
          "md5": "2c4586da35c6636915178baa4144b62b"
        }
      ]
    }
  ]
}
