{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-fix-versioning-with-github-action-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2bpvqtigovaijblxhc2k5zwyaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "60c5de4e651a891fb6b8876da962c7b76f8ea8f3e135a4476cb5b86c0263b473271e3c7f69f76e2fdfdd5c107ca289ad75eedd811268a806119f10053a86d4fb",
          "sha256": "67a5cbf3eaefe620c7cb7ad7a8f9e273a96665aab1a3be1690b8cf9d1d2c93db",
          "sha1": "3f7b18a3531e67cf170d5ef182b74d79d2abb5c0",
          "md5": "e452d883c8ec8f02e054521b412b17c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "60c5de4e651a891fb6b8876da962c7b76f8ea8f3e135a4476cb5b86c0263b473271e3c7f69f76e2fdfdd5c107ca289ad75eedd811268a806119f10053a86d4fb",
          "sha256": "67a5cbf3eaefe620c7cb7ad7a8f9e273a96665aab1a3be1690b8cf9d1d2c93db",
          "sha1": "3f7b18a3531e67cf170d5ef182b74d79d2abb5c0",
          "md5": "e452d883c8ec8f02e054521b412b17c4"
        }
      ]
    }
  ]
}
