{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-fix-versioning-with-github-action-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mhf6pbue2rcavclvj65ednvehq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "aadbdbe0dcca7d891cef555684db515a5fd724ebf13be7e3e2f7c810c4cb3465b289241a5c8e1650e943f09c4310c1aeb76f9560c978305438d8ecb0e9587e3c",
          "sha256": "3eef45d57f9d14a46cbb99f3ed07f7fdee2d861515828f483783e4655a18dd30",
          "sha1": "c231188ff515ec0fc73944c92d98ce883ac756c7",
          "md5": "1c9b2d6b529aa933a1762aa2c4bce012"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "aadbdbe0dcca7d891cef555684db515a5fd724ebf13be7e3e2f7c810c4cb3465b289241a5c8e1650e943f09c4310c1aeb76f9560c978305438d8ecb0e9587e3c",
          "sha256": "3eef45d57f9d14a46cbb99f3ed07f7fdee2d861515828f483783e4655a18dd30",
          "sha1": "c231188ff515ec0fc73944c92d98ce883ac756c7",
          "md5": "1c9b2d6b529aa933a1762aa2c4bce012"
        }
      ]
    }
  ]
}
