{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-tags-and-annotations-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "c64kvleewfbv7gv3dfpz3wrevy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-tags-and-annotations-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 16425,
          "sha512": "6a6ccf611282dd58b9580cc156ff25248878b2d282931e54ffb6cd904aedb3cc7a2132337083ec4da4630f998a741c0ee24618fa4aa799b00c303c213ec27717",
          "sha256": "aafbf31aa03a6208bd95737efa06ed754f6fd955595be250363c495ad894b752",
          "sha1": "444a08e9ccc56f87426bb6266610126364299378",
          "md5": "9e4dbd88377507997a337a65f8ad9f35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-tags-and-annotations-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 16425,
          "sha512": "6a6ccf611282dd58b9580cc156ff25248878b2d282931e54ffb6cd904aedb3cc7a2132337083ec4da4630f998a741c0ee24618fa4aa799b00c303c213ec27717",
          "sha256": "aafbf31aa03a6208bd95737efa06ed754f6fd955595be250363c495ad894b752",
          "sha1": "444a08e9ccc56f87426bb6266610126364299378",
          "md5": "9e4dbd88377507997a337a65f8ad9f35"
        }
      ]
    }
  ]
}
