{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "t527aty2rrfvzdvyp4l3sj4ckm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "29a67b4a938c1cf08178cbeb8ec7072fc0bee97740ba194193a95be90989acdcc12e15a7a197538f0a46465fe2360320981211c1456561f5f7a7f4e1c711f727",
          "sha256": "2b5ce4e8b88a578c1dbd8faf2efa8fcafb1961a6b3b77fe33881d71e8fcb3e87",
          "sha1": "12093928289b1dd52b16df6653fee3a3f1e99dfb",
          "md5": "8c1a11779f08d1e7da453d261a7956fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "29a67b4a938c1cf08178cbeb8ec7072fc0bee97740ba194193a95be90989acdcc12e15a7a197538f0a46465fe2360320981211c1456561f5f7a7f4e1c711f727",
          "sha256": "2b5ce4e8b88a578c1dbd8faf2efa8fcafb1961a6b3b77fe33881d71e8fcb3e87",
          "sha1": "12093928289b1dd52b16df6653fee3a3f1e99dfb",
          "md5": "8c1a11779f08d1e7da453d261a7956fb"
        }
      ]
    }
  ]
}
