{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgvack6m45gb5ff6rbnpy2t3ji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d46b997beddad7a6bcf7a4f73315c51044ce1412fb1cbfdc20df39dd36dedb2a3c4149f5cb11a8c7885589a89ba60f171c2a200f3999abef513d7479ad68d4ea",
          "sha256": "574622b6953ab4ab2f163bcf94a4d1cdc31b44dc7e0855507e5aa68e32653f2b",
          "sha1": "93a349427cd84d42dbb4be9f2947771d4f37191e",
          "md5": "3aad11782e7c9b7b38e4c1a2899e9d1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d46b997beddad7a6bcf7a4f73315c51044ce1412fb1cbfdc20df39dd36dedb2a3c4149f5cb11a8c7885589a89ba60f171c2a200f3999abef513d7479ad68d4ea",
          "sha256": "574622b6953ab4ab2f163bcf94a4d1cdc31b44dc7e0855507e5aa68e32653f2b",
          "sha1": "93a349427cd84d42dbb4be9f2947771d4f37191e",
          "md5": "3aad11782e7c9b7b38e4c1a2899e9d1a"
        }
      ]
    }
  ]
}
