{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vjsmew4pmfah3h2anggjyebl2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "70183550a3145f70751ecbd6f1157b4677daf714edc145930e426c08080587413c9cccde36298920862f35d3fa33fab9254e249d377424b6d470085d53d1a69e",
          "sha256": "84adf121a20e93c9c1c5d6abc51ebd76f39d949854d641dd4295b2f5e9b3d21a",
          "sha1": "d0c86a10e492e1e81c8b44f575adc05c23a3e20b",
          "md5": "312f2c406e2835b6c1fdc118dc3c6207"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "70183550a3145f70751ecbd6f1157b4677daf714edc145930e426c08080587413c9cccde36298920862f35d3fa33fab9254e249d377424b6d470085d53d1a69e",
          "sha256": "84adf121a20e93c9c1c5d6abc51ebd76f39d949854d641dd4295b2f5e9b3d21a",
          "sha1": "d0c86a10e492e1e81c8b44f575adc05c23a3e20b",
          "md5": "312f2c406e2835b6c1fdc118dc3c6207"
        }
      ]
    }
  ]
}
