{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7ga2izlde5brnltluj3vpdmhtu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "57640aa41c6a16338e05bc085cb58dfd5c8191fdf2a46bb8fa926342c189d6506482b61526312bacc54ccaa809d94bd70b50196c6ffb01b3a271e3ac6aac706f",
          "sha256": "d3097811faa9f49ae590be7e9da0eedc3ff27346d720562a6951fd227d9acc19",
          "sha1": "031650b925439e9af6e32f39123a75f0c4890c54",
          "md5": "a21d32f569bc7b15bfd045f5d76527f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "57640aa41c6a16338e05bc085cb58dfd5c8191fdf2a46bb8fa926342c189d6506482b61526312bacc54ccaa809d94bd70b50196c6ffb01b3a271e3ac6aac706f",
          "sha256": "d3097811faa9f49ae590be7e9da0eedc3ff27346d720562a6951fd227d9acc19",
          "sha1": "031650b925439e9af6e32f39123a75f0c4890c54",
          "md5": "a21d32f569bc7b15bfd045f5d76527f8"
        }
      ]
    }
  ]
}
