{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yp7z5oiz25aqpmpsdxx3ufaiwu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1f0e520dd8b13cac00fb4cbf45d2586bffadadc412f2f7451c3f57b6e367ff54ed6e769034aa941324c82818b4e42c5b6c282f981732a370895fcea218ebf2ed",
          "sha256": "d3d79a1f31b4e3282bf2cad2349bc8e89d71e1d70bd875fdb2ca8951bb9a139e",
          "sha1": "46ab9ebdfcf5986c2d4252783f0a437626f752e9",
          "md5": "eaf0e0660948077ac1d69c6f55cec644"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1f0e520dd8b13cac00fb4cbf45d2586bffadadc412f2f7451c3f57b6e367ff54ed6e769034aa941324c82818b4e42c5b6c282f981732a370895fcea218ebf2ed",
          "sha256": "d3d79a1f31b4e3282bf2cad2349bc8e89d71e1d70bd875fdb2ca8951bb9a139e",
          "sha1": "46ab9ebdfcf5986c2d4252783f0a437626f752e9",
          "md5": "eaf0e0660948077ac1d69c6f55cec644"
        }
      ]
    }
  ]
}
