{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-add-resource-encryption-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qh5gbqk3vze6jbl2o3umojltca"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "size": 44953,
          "sha512": "613a4b6e8da7bb6f9df8c54c902bf09eb78f044115b6c606da29f615dc8efb6a732435c895bdf9a260a9a497f000c2317174785ccfc97c45d4e5694b6e80b4cb",
          "sha256": "2accf29006c2b0952fd8bae2637d8da92f7f31fe1926e8e21e5c3df5109b9c75",
          "sha1": "80304367f397953caaaf2f4374abc3488ec2634c",
          "md5": "add8fed86bad914e187e459da5c104d5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "size": 44953,
          "sha512": "613a4b6e8da7bb6f9df8c54c902bf09eb78f044115b6c606da29f615dc8efb6a732435c895bdf9a260a9a497f000c2317174785ccfc97c45d4e5694b6e80b4cb",
          "sha256": "2accf29006c2b0952fd8bae2637d8da92f7f31fe1926e8e21e5c3df5109b9c75",
          "sha1": "80304367f397953caaaf2f4374abc3488ec2634c",
          "md5": "add8fed86bad914e187e459da5c104d5"
        }
      ]
    }
  ]
}
