{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-fix-checkRestrictions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gbqswir435dwfezsrguuckfvhq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5a3d8eb23792589bc4c9ac343ebce0c3d2666524a6c76c03a690aa34351b44f304100ac26f1d972a73b70a41c97570bc31deea7bc4935d8767958d29308d6f14",
          "sha256": "65fcd1febdb46d4bc3f4cd31fa643fcee6f1c516d59b891e837ede10922fffcf",
          "sha1": "13743dee8b0c91462d85c59d48da8c7a3c90ce52",
          "md5": "0e13cff530428ff54f2666d0bfdef0d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5a3d8eb23792589bc4c9ac343ebce0c3d2666524a6c76c03a690aa34351b44f304100ac26f1d972a73b70a41c97570bc31deea7bc4935d8767958d29308d6f14",
          "sha256": "65fcd1febdb46d4bc3f4cd31fa643fcee6f1c516d59b891e837ede10922fffcf",
          "sha1": "13743dee8b0c91462d85c59d48da8c7a3c90ce52",
          "md5": "0e13cff530428ff54f2666d0bfdef0d2"
        }
      ]
    }
  ]
}
