{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tgoacre5dre7zktx7r4f7zjxcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "ec0ce68091eb3bfcb85f13ffa38627982d0b49a519df7d2ee1301350a2c8d783ca582135ea0b4b273a11f9e4ae82dd5569fbd5a9eef189e590537fae77e9ba08",
          "sha256": "ebeff4d7026b2a19347b11e1eb8404bfe2fc06c7957d70a7c6413b0003bbc643",
          "sha1": "4264392e09c2f8edcaaa125a70fdf87460bac3ad",
          "md5": "2428a9f9babd72885d7dc2c8ca0bbfcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "ec0ce68091eb3bfcb85f13ffa38627982d0b49a519df7d2ee1301350a2c8d783ca582135ea0b4b273a11f9e4ae82dd5569fbd5a9eef189e590537fae77e9ba08",
          "sha256": "ebeff4d7026b2a19347b11e1eb8404bfe2fc06c7957d70a7c6413b0003bbc643",
          "sha1": "4264392e09c2f8edcaaa125a70fdf87460bac3ad",
          "md5": "2428a9f9babd72885d7dc2c8ca0bbfcf"
        }
      ]
    }
  ]
}
