{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-android",
    "version": "1.9.1-change-recordservice-test-attachments-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dg4sg4dhcreyhomzkf7vlsvj2a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.9.1-change-recordservice-test-attachments-SNAPSHOT.aar",
          "url": "sdk-android-1.9.1-change-recordservice-test-attachments-SNAPSHOT.aar",
          "size": 27502,
          "sha512": "d5f16676f5b8baec90104aa8757b3a53b5e7dfdd73a77e08ab1e4293acbcb00a866e1ed83b6e2a8c6e6fd8b2010c0168b1bb031f2903cdde0c503512b53ebf08",
          "sha256": "cf14e605d16868d63105814b8735d7b88e4d6d022c10d488faa60d70aed5190c",
          "sha1": "942e75b557b4a382b80dde1e8739f00121cbb107",
          "md5": "b726c4985289d73a894e8e3b732e0f11"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-android",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-android",
          "version": {
            "requires": "1.9.1-change-recordservice-test-attachments-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.9.1-change-recordservice-test-attachments-SNAPSHOT.aar",
          "url": "sdk-android-1.9.1-change-recordservice-test-attachments-SNAPSHOT.aar",
          "size": 27502,
          "sha512": "d5f16676f5b8baec90104aa8757b3a53b5e7dfdd73a77e08ab1e4293acbcb00a866e1ed83b6e2a8c6e6fd8b2010c0168b1bb031f2903cdde0c503512b53ebf08",
          "sha256": "cf14e605d16868d63105814b8735d7b88e4d6d022c10d488faa60d70aed5190c",
          "sha1": "942e75b557b4a382b80dde1e8739f00121cbb107",
          "md5": "b726c4985289d73a894e8e3b732e0f11"
        }
      ]
    }
  ]
}
