{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-naming-crypto-convention-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "i2h2nwcxybe6la4yy327lnmiva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f730d551c8c64f3ba20829df6131704864e97a2acf063fb01e5d25d81df3b1706147f358cccf747e59097b78b322fa25c51747a072dc596b754c77fa1d5eed76",
          "sha256": "e25118c86a93b843ccd27ae9cab5b09fe1fc901c3b02cfc44a99813c43932a5d",
          "sha1": "9406ab1c327e1d6d6f1bc1eaa13643dcc53f6e2e",
          "md5": "8ad4331ee2c7a655b2d74c782261014c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "f730d551c8c64f3ba20829df6131704864e97a2acf063fb01e5d25d81df3b1706147f358cccf747e59097b78b322fa25c51747a072dc596b754c77fa1d5eed76",
          "sha256": "e25118c86a93b843ccd27ae9cab5b09fe1fc901c3b02cfc44a99813c43932a5d",
          "sha1": "9406ab1c327e1d6d6f1bc1eaa13643dcc53f6e2e",
          "md5": "8ad4331ee2c7a655b2d74c782261014c"
        }
      ]
    }
  ]
}
