{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-fix-versioning-with-github-action-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ljn5urcp7baupbxpwvg55dqkt4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "93aa258b12082aad544739aae98070f1493b57066750a73c80fef77256b9ba903eccb1d6128bb8961283f00e3aecd4db5d4d38851e8aaea5fc4cb5a274cb747d",
          "sha256": "06cc52761ad101fc79be11887d64882f99692a632777adcb64bdbcf82cccef6b",
          "sha1": "4dfb8bb56ee3f12765301499c4c04addb64cba31",
          "md5": "9ee67ceac36839d43b5a7feca482f193"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "93aa258b12082aad544739aae98070f1493b57066750a73c80fef77256b9ba903eccb1d6128bb8961283f00e3aecd4db5d4d38851e8aaea5fc4cb5a274cb747d",
          "sha256": "06cc52761ad101fc79be11887d64882f99692a632777adcb64bdbcf82cccef6b",
          "sha1": "4dfb8bb56ee3f12765301499c4c04addb64cba31",
          "md5": "9ee67ceac36839d43b5a7feca482f193"
        }
      ]
    }
  ]
}
