{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-fix-versioning-with-github-action-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ehnli4vs2vfejcos5mb2o6ibdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d3834880e3a954643e44f5cfd03b9c6bf15f04050462a67656274b5bd7d17ad1634b697a7dc1d412efa5b3a59eefa56d1982c71f43b84265f3d6f45f36363f29",
          "sha256": "d7468cf185b9daa75454ee4f9b09356254f0021e64ecab1411750d235fb6f837",
          "sha1": "45e753d04296aaf5fd4eae4b13000dfaf5aedbcc",
          "md5": "af5bc1cc76af6ee9cab5880068b49098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-versioning-with-github-action-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-versioning-with-github-action-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d3834880e3a954643e44f5cfd03b9c6bf15f04050462a67656274b5bd7d17ad1634b697a7dc1d412efa5b3a59eefa56d1982c71f43b84265f3d6f45f36363f29",
          "sha256": "d7468cf185b9daa75454ee4f9b09356254f0021e64ecab1411750d235fb6f837",
          "sha1": "45e753d04296aaf5fd4eae4b13000dfaf5aedbcc",
          "md5": "af5bc1cc76af6ee9cab5880068b49098"
        }
      ]
    }
  ]
}
