{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-update-record-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gms5ane4vfaijmuqxchmkqqlsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "611b3a1c05ac3ab22a8e33360992855f4dfb602de5cf34bcade1caae3e8fee804e7d427a6cba6931dba7b3929f4d421c7a1b4b5d91e0503b2db741278c858af8",
          "sha256": "3fb78b5323e10dc3a09afc8a2a8c58025ddba09568902467831890625d7209e6",
          "sha1": "93f026bb3ed7f901843c6ceb8898bb3f0c79955d",
          "md5": "1cb353ff7786798a286fd8b1e84059ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "611b3a1c05ac3ab22a8e33360992855f4dfb602de5cf34bcade1caae3e8fee804e7d427a6cba6931dba7b3929f4d421c7a1b4b5d91e0503b2db741278c858af8",
          "sha256": "3fb78b5323e10dc3a09afc8a2a8c58025ddba09568902467831890625d7209e6",
          "sha1": "93f026bb3ed7f901843c6ceb8898bb3f0c79955d",
          "md5": "1cb353ff7786798a286fd8b1e84059ee"
        }
      ]
    }
  ]
}
