{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-update-record-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "slieyfkueza7xlsgkkerzpcicu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "d6548220fc07acd595567627a70c12b32dcd7d24218e81d5ce3954855b55927188ec6729ce7ce8f62529ada3d091ed1da459ac2cc598843813a00ba60de88af4",
          "sha256": "baf25d2ca7bd057ec09ad42a17ad89ce227d476003aaca19c9b352f99c6f4c13",
          "sha1": "db16960f6136c918b98c1f73943403a53b601c5d",
          "md5": "ca827b29491f07eb68a66cab6d7973d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "d6548220fc07acd595567627a70c12b32dcd7d24218e81d5ce3954855b55927188ec6729ce7ce8f62529ada3d091ed1da459ac2cc598843813a00ba60de88af4",
          "sha256": "baf25d2ca7bd057ec09ad42a17ad89ce227d476003aaca19c9b352f99c6f4c13",
          "sha1": "db16960f6136c918b98c1f73943403a53b601c5d",
          "md5": "ca827b29491f07eb68a66cab6d7973d8"
        }
      ]
    }
  ]
}
