{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-add-public-userid-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6rownicaifc75pidpscs3pwvki"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c5273595808392e3a3406227f16a44730d05c13e3a656ceca34f40e9a99e4e65ed8d7872e7f2bb8a13b876c06ef2bb340f6947ed8d92a2e75ee0974314b8842d",
          "sha256": "4d98aa36b0e2a1abb6d72e6922e53f3ea1a7a85f1f7a0501f8b1137ac3c3e12a",
          "sha1": "ccf1cad35bd91f723f275edf4f1f588ed72a0204",
          "md5": "f9fa0021405a7998edd83811426860f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-public-userid-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c5273595808392e3a3406227f16a44730d05c13e3a656ceca34f40e9a99e4e65ed8d7872e7f2bb8a13b876c06ef2bb340f6947ed8d92a2e75ee0974314b8842d",
          "sha256": "4d98aa36b0e2a1abb6d72e6922e53f3ea1a7a85f1f7a0501f8b1137ac3c3e12a",
          "sha1": "ccf1cad35bd91f723f275edf4f1f588ed72a0204",
          "md5": "f9fa0021405a7998edd83811426860f4"
        }
      ]
    }
  ]
}
