{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-fix-document-upload-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5khqrztukbbz5mtsjprwk7j7wi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8b5baa252b227039c5b33563a202214520d10247a21d74c4a2a0bcacdb23f44c2d54446fe1665bc5aa01bab9a3088060c5f4a9a5e4d192bab70d0da001ed8a67",
          "sha256": "2cb5cb45295b8df773f222726d91d908b674cab629ea90a7c15cf3ca4fcbb1ba",
          "sha1": "3b08d586db19e5c172ecfdef263b2a04e5ee2e04",
          "md5": "f8bbd3147b96ca434b8f4183719e3779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8b5baa252b227039c5b33563a202214520d10247a21d74c4a2a0bcacdb23f44c2d54446fe1665bc5aa01bab9a3088060c5f4a9a5e4d192bab70d0da001ed8a67",
          "sha256": "2cb5cb45295b8df773f222726d91d908b674cab629ea90a7c15cf3ca4fcbb1ba",
          "sha1": "3b08d586db19e5c172ecfdef263b2a04e5ee2e04",
          "md5": "f8bbd3147b96ca434b8f4183719e3779"
        }
      ]
    }
  ]
}
