{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rcxffq6mmvecnovyph2o3337tq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "3f43384950b5a29456c8bc40e2d4914baf72890cf5ca65967876a7e5579dba72d79f4075d0f018d4650978e00b6adfa6518c20a8e109c2b9628afbf15bb97530",
          "sha256": "e6490089222c0dc4c23f4a31d2ef3f723ca72b7a57deb04af261cca7189130b1",
          "sha1": "3d73df380b1b22a351c8afb72730889cf587966c",
          "md5": "3be80821faf45a551b6ad0778789312d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "3f43384950b5a29456c8bc40e2d4914baf72890cf5ca65967876a7e5579dba72d79f4075d0f018d4650978e00b6adfa6518c20a8e109c2b9628afbf15bb97530",
          "sha256": "e6490089222c0dc4c23f4a31d2ef3f723ca72b7a57deb04af261cca7189130b1",
          "sha1": "3d73df380b1b22a351c8afb72730889cf587966c",
          "md5": "3be80821faf45a551b6ad0778789312d"
        }
      ]
    }
  ]
}
