{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-data-resource-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vtq5ykq5jndbngibx2fzqtishy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "a777f24e11658b829da3854b214576b023aefe5cd5cd27da4439689b7b856e6831a21d9b5d202697e4aca662965db2b02855334416d448ed8efddfd04bd98aa6",
          "sha256": "98c058bc211332900be354af94132d4f116ec83088ec099c21ef7bdeb369e965",
          "sha1": "677ef015f8f11955c00f6a7d47fc020cd82d895d",
          "md5": "f464f3b475a8b8e16b164c351aa75265"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "a777f24e11658b829da3854b214576b023aefe5cd5cd27da4439689b7b856e6831a21d9b5d202697e4aca662965db2b02855334416d448ed8efddfd04bd98aa6",
          "sha256": "98c058bc211332900be354af94132d4f116ec83088ec099c21ef7bdeb369e965",
          "sha1": "677ef015f8f11955c00f6a7d47fc020cd82d895d",
          "md5": "f464f3b475a8b8e16b164c351aa75265"
        }
      ]
    }
  ]
}
