{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-model-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tz5mqbfd7fh23bjnwme5ogmpru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-model-version-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-model-version-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e4ea35ccacdfb24e771530d03c666e41476d16194f7bab0bbcb68f44eed987c756cfd5a75de9392dfb93e3da5a53e0fed889386574663c4819378758ca5ae8be",
          "sha256": "ac065ea5c3d19537b36f76d752d9778b1cc722e38381e03bcad52e1c22d092b2",
          "sha1": "324b11f7e7ca694675e6226c326c2c483a8c8518",
          "md5": "4d06e7b35d611f7cba69ac7f84e54ea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-model-version-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-model-version-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e4ea35ccacdfb24e771530d03c666e41476d16194f7bab0bbcb68f44eed987c756cfd5a75de9392dfb93e3da5a53e0fed889386574663c4819378758ca5ae8be",
          "sha256": "ac065ea5c3d19537b36f76d752d9778b1cc722e38381e03bcad52e1c22d092b2",
          "sha1": "324b11f7e7ca694675e6226c326c2c483a8c8518",
          "md5": "4d06e7b35d611f7cba69ac7f84e54ea3"
        }
      ]
    }
  ]
}
