{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-add-cryptoservice-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "v7z4nxv5nfhlfk6xtmuo7bdg5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-add-cryptoservice-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "27b4d246e58fb28836e745fe8870380f2470f32f73b8e32e91e7482e3be3ad8b3f33772e776593e18237390ca9fc98cb1d8eec510d5b810cc4b791fe7e803e63",
          "sha256": "24004da43d42091f0149c22e93cfd3d612cd6702401be2cc7bac98dd7fba1d1b",
          "sha1": "32b9088a4b607d48eeb6edb48ddaaaa4091b20f9",
          "md5": "7390c72597ce81a26aaeace64fcf6ee9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-add-cryptoservice-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-add-cryptoservice-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "27b4d246e58fb28836e745fe8870380f2470f32f73b8e32e91e7482e3be3ad8b3f33772e776593e18237390ca9fc98cb1d8eec510d5b810cc4b791fe7e803e63",
          "sha256": "24004da43d42091f0149c22e93cfd3d612cd6702401be2cc7bac98dd7fba1d1b",
          "sha1": "32b9088a4b607d48eeb6edb48ddaaaa4091b20f9",
          "md5": "7390c72597ce81a26aaeace64fcf6ee9"
        }
      ]
    }
  ]
}
