{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ed42tcj7wvazldtj4ajihfe3uu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 11326,
          "sha512": "88a896be99e96297600747dccca341a546e77d81ae98d0e27428a20deaad4fb528af227e3e710913afb81cb8e54efaa58e90da892bcfb8e42186957ce86fb9f9",
          "sha256": "682c22f036059033e25fb3346cf15f98d972930f16b97fac88cab18743c7beeb",
          "sha1": "1a3782c27796297c5644faaf34f096a82a9a8b56",
          "md5": "2671610e8e19ec4951d8c2145af7fe4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 11326,
          "sha512": "88a896be99e96297600747dccca341a546e77d81ae98d0e27428a20deaad4fb528af227e3e710913afb81cb8e54efaa58e90da892bcfb8e42186957ce86fb9f9",
          "sha256": "682c22f036059033e25fb3346cf15f98d972930f16b97fac88cab18743c7beeb",
          "sha1": "1a3782c27796297c5644faaf34f096a82a9a8b56",
          "md5": "2671610e8e19ec4951d8c2145af7fe4c"
        }
      ]
    }
  ]
}
