{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-remove-mimetype-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nrjo63b4fne4pkvqkmxmqmusde"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-remove-mimetype-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-remove-mimetype-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-remove-mimetype-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "19ce574440d864ba8a8d1989894899e75ce551f7d04aaf5866903438ebe2896b7c43bc7afad5ee1626c42416cb7af250b5dd61dc4f866ff318948a90ac14e9c0",
          "sha256": "6c60bce562f6a4842004b2fb53d31fac594d073741244590501fd738bf5d6376",
          "sha1": "b6ac47edc34996defee7cb85d5878edd5296a90c",
          "md5": "f55ea209df5cb74ab3dee2fbb402ea10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-remove-mimetype-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-remove-mimetype-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-remove-mimetype-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "19ce574440d864ba8a8d1989894899e75ce551f7d04aaf5866903438ebe2896b7c43bc7afad5ee1626c42416cb7af250b5dd61dc4f866ff318948a90ac14e9c0",
          "sha256": "6c60bce562f6a4842004b2fb53d31fac594d073741244590501fd738bf5d6376",
          "sha1": "b6ac47edc34996defee7cb85d5878edd5296a90c",
          "md5": "f55ea209df5cb74ab3dee2fbb402ea10"
        }
      ]
    }
  ]
}
