{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5ph2gi7uebgnrcbd2s4f6dhuxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "bab521df6361d536d6076c4e29c9c482d026c6b4285070c49fd8c1493fedd5226ac127de5765cf45edcb841b9caceb7000f2e3566d58bbccfa07cb2cfc1c280b",
          "sha256": "5b3e4f7808a61253c127687e177412498b6f06e093ffba0d82ce916f817a8205",
          "sha1": "78147fe2c4b3e00d38114e08c7c93baa7d9e9b7c",
          "md5": "053804bef3e61981f32d375f80bcd62c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "bab521df6361d536d6076c4e29c9c482d026c6b4285070c49fd8c1493fedd5226ac127de5765cf45edcb841b9caceb7000f2e3566d58bbccfa07cb2cfc1c280b",
          "sha256": "5b3e4f7808a61253c127687e177412498b6f06e093ffba0d82ce916f817a8205",
          "sha1": "78147fe2c4b3e00d38114e08c7c93baa7d9e9b7c",
          "md5": "053804bef3e61981f32d375f80bcd62c"
        }
      ]
    }
  ]
}
