{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-recordservice-crypto-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wbrwgj5hnfap3l6ykkhhzzxwge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "6e57e10d044d02de15c6d610a0bdf134ca47c047f6999fca74891fffa4d2e94c8b951282801f3595c68d7acf60ca83c8d36bd9d187065df9ee11a9c1d2b46828",
          "sha256": "7aa0c3059203566445f1dc68a78b9f143552e62cf23c2c02231cf8d867cc7158",
          "sha1": "91ec9f0678fb2d7f215ce387960ef3a892eecfdd",
          "md5": "455a7b0638f9d3a3f53367ea94e576af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "6e57e10d044d02de15c6d610a0bdf134ca47c047f6999fca74891fffa4d2e94c8b951282801f3595c68d7acf60ca83c8d36bd9d187065df9ee11a9c1d2b46828",
          "sha256": "7aa0c3059203566445f1dc68a78b9f143552e62cf23c2c02231cf8d867cc7158",
          "sha1": "91ec9f0678fb2d7f215ce387960ef3a892eecfdd",
          "md5": "455a7b0638f9d3a3f53367ea94e576af"
        }
      ]
    }
  ]
}
