{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7op5de2pfndz3cwumr5lpk7lqq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "61136415264c3a0a98297d9dd594478e5becab181a52d87ddc2e676092e257ba377584cf1c0b5947ffba460415fc2cb0a812c54025f7cd4c4ee63728dd30e7f5",
          "sha256": "275675195373b15eeb8681836a674d1b718e44daa449f29784a5dd6c524d8e5e",
          "sha1": "76895ea53d29086663660afae6da04c14eb4d8da",
          "md5": "a2f6f64feb77c1624522701f91f083d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "61136415264c3a0a98297d9dd594478e5becab181a52d87ddc2e676092e257ba377584cf1c0b5947ffba460415fc2cb0a812c54025f7cd4c4ee63728dd30e7f5",
          "sha256": "275675195373b15eeb8681836a674d1b718e44daa449f29784a5dd6c524d8e5e",
          "sha1": "76895ea53d29086663660afae6da04c14eb4d8da",
          "md5": "a2f6f64feb77c1624522701f91f083d8"
        }
      ]
    }
  ]
}
