{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rwszed26yrcmfggg4ln3iezvbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "ce6703b645ef302bc621e4f308e8ebf4bca4e7a3c0985638e269a050604ee95b6393bdc5b921bf1df13a20245319d9e8c09e4ba9be0e79b08ae35f43493562e4",
          "sha256": "ede126ee8b8184e6c13fc38a5e72dfc441cf9b01b5d338bea947ec096d5811a8",
          "sha1": "0658eb497409f16dff10eec31cc2d4f2ffd8556e",
          "md5": "d64c9629d4e4ff7ee7b7a450ab7eb2b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "ce6703b645ef302bc621e4f308e8ebf4bca4e7a3c0985638e269a050604ee95b6393bdc5b921bf1df13a20245319d9e8c09e4ba9be0e79b08ae35f43493562e4",
          "sha256": "ede126ee8b8184e6c13fc38a5e72dfc441cf9b01b5d338bea947ec096d5811a8",
          "sha1": "0658eb497409f16dff10eec31cc2d4f2ffd8556e",
          "md5": "d64c9629d4e4ff7ee7b7a450ab7eb2b4"
        }
      ]
    }
  ]
}
