{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sz3r3xffkfbm7h4fijct73k7fm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "b7e4f050093d6ac243f5972fc0a249a63809dc32595e15a7767177f90c9ea32142c295ffe35607e5f57188bd69687358d2b57acaa47116a3053de67e3285e150",
          "sha256": "799774ac4eb60843320cc3095313da7041120c0665f3503611782e55dd6d5bcd",
          "sha1": "fb5a4a053c062c0403af3cae4bca5e112b9e0942",
          "md5": "a59c0ebe270d571248f5d376dc261331"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "b7e4f050093d6ac243f5972fc0a249a63809dc32595e15a7767177f90c9ea32142c295ffe35607e5f57188bd69687358d2b57acaa47116a3053de67e3285e150",
          "sha256": "799774ac4eb60843320cc3095313da7041120c0665f3503611782e55dd6d5bcd",
          "sha1": "fb5a4a053c062c0403af3cae4bca5e112b9e0942",
          "md5": "a59c0ebe270d571248f5d376dc261331"
        }
      ]
    }
  ]
}
