{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.2-change-commkey-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7xpblakkrfamdmuu36e5rvf5g4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-commkey-response-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-commkey-response-SNAPSHOT.aar",
          "size": 44896,
          "sha512": "47ab721b53a01c3515e38c7326ad079eaec7178239dd4e4be965a1599cf0b0bfc980eea9859ddee50f9222bbeefe0a88cdd492b0b7dc664fde8b4001100ba27f",
          "sha256": "e17d3fd877b5f7e8dab1f5d7d6b89ad8771aeb91e7e222626a5ae2ad01dc644e",
          "sha1": "19caf7ad1128a78dbe44a29762c8d6bf6be2a6ff",
          "md5": "4498cb220216636225029cc301acea65"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-commkey-response-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-commkey-response-SNAPSHOT.aar",
          "size": 44896,
          "sha512": "47ab721b53a01c3515e38c7326ad079eaec7178239dd4e4be965a1599cf0b0bfc980eea9859ddee50f9222bbeefe0a88cdd492b0b7dc664fde8b4001100ba27f",
          "sha256": "e17d3fd877b5f7e8dab1f5d7d6b89ad8771aeb91e7e222626a5ae2ad01dc644e",
          "sha1": "19caf7ad1128a78dbe44a29762c8d6bf6be2a6ff",
          "md5": "4498cb220216636225029cc301acea65"
        }
      ]
    }
  ]
}
