{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-android",
    "version": "1.11.0-add-resource-encryption-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5tqp76wi4jervi27f2o3t5lauu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "url": "sdk-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "size": 27681,
          "sha512": "faed14bbb9909ff2aa765f7b1d2ed36fe98885f1250fc542bb856a42dbaa091b7887e8b181071e41a9581e368635c055555982301b808db9ff391aa224009c15",
          "sha256": "dc74092aa0ea502d61dbf2c2d10e699ea6a7f09d50968c98fcb818389f74c1b5",
          "sha1": "1cecc2e09cd3052ab16a06fbfc2b3ad29cbc9ddb",
          "md5": "3c0020d1a79a90a88d33bbeb6143655b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "auth-jvm"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "*",
              "module": "securestore-jvm"
            },
            {
              "group": "*",
              "module": "crypto-jvm"
            },
            {
              "group": "org.threeten",
              "module": "threetenbp"
            }
          ]
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-android",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-android",
          "version": {
            "requires": "1.11.0-add-resource-encryption-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.jakewharton.threetenabp",
          "module": "threetenabp",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "url": "sdk-android-1.11.0-add-resource-encryption-service-SNAPSHOT.aar",
          "size": 27681,
          "sha512": "faed14bbb9909ff2aa765f7b1d2ed36fe98885f1250fc542bb856a42dbaa091b7887e8b181071e41a9581e368635c055555982301b808db9ff391aa224009c15",
          "sha256": "dc74092aa0ea502d61dbf2c2d10e699ea6a7f09d50968c98fcb818389f74c1b5",
          "sha1": "1cecc2e09cd3052ab16a06fbfc2b3ad29cbc9ddb",
          "md5": "3c0020d1a79a90a88d33bbeb6143655b"
        }
      ]
    }
  ]
}
