{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-add-cryptoservice-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "v7z4nxv5nfhlfk6xtmuo7bdg5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-add-cryptoservice-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "7d71622d9f7edc4108fbf8c3d1ffe462ae83452633413f47d1e161da720aee4b056b1d767c9f218271e999bf72fc3aed47ba49a9eae27bbd4655d9d45a3ba9ab",
          "sha256": "c7fb27901c87cf1d4d0c0cb6b81c982f72a3e6eac2cc93c92ea316bf908572ff",
          "sha1": "354739a0676b0627b2a63943d78b139eb784ec7e",
          "md5": "8e1488fc6ffab9dfcffd165c4318696d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-add-cryptoservice-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "7d71622d9f7edc4108fbf8c3d1ffe462ae83452633413f47d1e161da720aee4b056b1d767c9f218271e999bf72fc3aed47ba49a9eae27bbd4655d9d45a3ba9ab",
          "sha256": "c7fb27901c87cf1d4d0c0cb6b81c982f72a3e6eac2cc93c92ea316bf908572ff",
          "sha1": "354739a0676b0627b2a63943d78b139eb784ec7e",
          "md5": "8e1488fc6ffab9dfcffd165c4318696d"
        }
      ]
    }
  ]
}
