{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hmnqseqkznhyxe23rrp5xfemo4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "58a7836c9bcd31f394cc6f35c44b31b7bbbb1d35eadf5262f242b76e80fb10c2a55078d3dc45f2c6472d4641b5ab44ed13fec57e8f8d466c18619db9a22855f5",
          "sha256": "39a4f2473dc5b04a484d60d30c2224eb0b6b8b93510f33b6f38d7d9d54636eed",
          "sha1": "aa56ee5d19fd3efb36bb67fc1f8f9e07235a320c",
          "md5": "2333bff8a406c1d542fabaf4662df83c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "58a7836c9bcd31f394cc6f35c44b31b7bbbb1d35eadf5262f242b76e80fb10c2a55078d3dc45f2c6472d4641b5ab44ed13fec57e8f8d466c18619db9a22855f5",
          "sha256": "39a4f2473dc5b04a484d60d30c2224eb0b6b8b93510f33b6f38d7d9d54636eed",
          "sha1": "aa56ee5d19fd3efb36bb67fc1f8f9e07235a320c",
          "md5": "2333bff8a406c1d542fabaf4662df83c"
        }
      ]
    }
  ]
}
