{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zvlk2lssgjc3fmyvtevopt7wgm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "feb2ac0861706b80e63aa3380f743574c43dde61e090ea48c3e5e770a28f846d6178b69e606be9bd85c1fa03fdb8d170481389061e89f2b73fa5bf3ebf506cbd",
          "sha256": "804296c37b99031e47daacd111fb1fe634ac9c6e956ed61885e3ea67a16e91b8",
          "sha1": "8f8b9c653dc3876d40ee3e2e80f2baee2935e41f",
          "md5": "7f4605c036b1b62913a9dc47d57ab62e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "feb2ac0861706b80e63aa3380f743574c43dde61e090ea48c3e5e770a28f846d6178b69e606be9bd85c1fa03fdb8d170481389061e89f2b73fa5bf3ebf506cbd",
          "sha256": "804296c37b99031e47daacd111fb1fe634ac9c6e956ed61885e3ea67a16e91b8",
          "sha1": "8f8b9c653dc3876d40ee3e2e80f2baee2935e41f",
          "md5": "7f4605c036b1b62913a9dc47d57ab62e"
        }
      ]
    }
  ]
}
