{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "d5y5vfqtl5gp5ecerwsgh5sphi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4a206108c1f3713e32593371d3c3f50dc5b2e37bde5e36c7b7d45981100fc6137e13f3d2f91b5e5c61743ba354aead6e71a84fdd94331ec98d783d610f7aaa06",
          "sha256": "3b952778ae73119145533f602efe90c3c4874166356b3b8b7d9e1e28dba59567",
          "sha1": "c96a37134ed4a314a85f1c4532ac5487ec6d05a0",
          "md5": "e34fefa71bfb5d07fef86a43d513a492"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4a206108c1f3713e32593371d3c3f50dc5b2e37bde5e36c7b7d45981100fc6137e13f3d2f91b5e5c61743ba354aead6e71a84fdd94331ec98d783d610f7aaa06",
          "sha256": "3b952778ae73119145533f602efe90c3c4874166356b3b8b7d9e1e28dba59567",
          "sha1": "c96a37134ed4a314a85f1c4532ac5487ec6d05a0",
          "md5": "e34fefa71bfb5d07fef86a43d513a492"
        }
      ]
    }
  ]
}
