{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vjsmew4pmfah3h2anggjyebl2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "058d88397244a02b110c6ae590c53a279838fa9efccfd42b04522a72007b18f849f07790f1ab5329210ea071148ad763e80c4553a9c294eb6cc20d654198fd57",
          "sha256": "95101db9fb475ba1293bc02eb1627191830754934b13361adc2ac0537f10bfec",
          "sha1": "21fbc53166a3a7e93cf6762961a33a0c86d5c6d2",
          "md5": "c0881ee6ce24bc11c5f2aa78643e8579"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "058d88397244a02b110c6ae590c53a279838fa9efccfd42b04522a72007b18f849f07790f1ab5329210ea071148ad763e80c4553a9c294eb6cc20d654198fd57",
          "sha256": "95101db9fb475ba1293bc02eb1627191830754934b13361adc2ac0537f10bfec",
          "sha1": "21fbc53166a3a7e93cf6762961a33a0c86d5c6d2",
          "md5": "c0881ee6ce24bc11c5f2aa78643e8579"
        }
      ]
    }
  ]
}
