{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xtab6kvin5hyvejvr2kts7vwpi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7d97534fcb5b0ae5cfd33211766153f9bb287c7d1990e8cba0b8f71630f1a40ec25240985268ea7ca8ed3fcb78999096cd93e696f17f508269efb9b037a000d5",
          "sha256": "b054db113deaf51d69d76425fbc8cec6c268ad8b4d8ac59e4fe4e7f24fa292b4",
          "sha1": "1c90771ffcd3462e0299f7a7bce8826073cc1f6a",
          "md5": "993096b75726e3cbda51f70bcdee752a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7d97534fcb5b0ae5cfd33211766153f9bb287c7d1990e8cba0b8f71630f1a40ec25240985268ea7ca8ed3fcb78999096cd93e696f17f508269efb9b037a000d5",
          "sha256": "b054db113deaf51d69d76425fbc8cec6c268ad8b4d8ac59e4fe4e7f24fa292b4",
          "sha1": "1c90771ffcd3462e0299f7a7bce8826073cc1f6a",
          "md5": "993096b75726e3cbda51f70bcdee752a"
        }
      ]
    }
  ]
}
