{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yp7z5oiz25aqpmpsdxx3ufaiwu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d2d76bdb4c166fa8b61f1ac036d0fe18678992774757dec57f97dbaafd0a3ab6d33eb913db1cff8fa5bc890ba72942ea5461cbe49ecabe5e8c4f7cf990cb76d8",
          "sha256": "0ed40e061a229573bc353d4dacf54416752bd465b08fbbffef020b543294fa10",
          "sha1": "4153b8bdd7b81ac6aaffccb6462ea9a56355526c",
          "md5": "894aa811d8e2cc665d865b6fe4363d08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d2d76bdb4c166fa8b61f1ac036d0fe18678992774757dec57f97dbaafd0a3ab6d33eb913db1cff8fa5bc890ba72942ea5461cbe49ecabe5e8c4f7cf990cb76d8",
          "sha256": "0ed40e061a229573bc353d4dacf54416752bd465b08fbbffef020b543294fa10",
          "sha1": "4153b8bdd7b81ac6aaffccb6462ea9a56355526c",
          "md5": "894aa811d8e2cc665d865b6fe4363d08"
        }
      ]
    }
  ]
}
