{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qeiianuer5bo7jqwfx5vq6plre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e6bb19db3ff8706223dcb4f392dcfc9c8f812e434b9a0ceab032ddf55bb55f9f46029dbd1ce46950932744a99edb699232d64f857d14e0eaa3a8027ef6fa6b7c",
          "sha256": "0f9dc0399d127a1d963452fff0cc1ad4e62aa70333528f807f30e30518bb4609",
          "sha1": "9676cc2176122504f09e7a36076a3a0ce081d695",
          "md5": "1ccaa2e3db51e513d391e910ab158d52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "e6bb19db3ff8706223dcb4f392dcfc9c8f812e434b9a0ceab032ddf55bb55f9f46029dbd1ce46950932744a99edb699232d64f857d14e0eaa3a8027ef6fa6b7c",
          "sha256": "0f9dc0399d127a1d963452fff0cc1ad4e62aa70333528f807f30e30518bb4609",
          "sha1": "9676cc2176122504f09e7a36076a3a0ce081d695",
          "md5": "1ccaa2e3db51e513d391e910ab158d52"
        }
      ]
    }
  ]
}
