{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xemhxe2ocfhtrfa6bnx72cqobm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b9b24d3b0d409c13d282e5c54e886df6a59776232b995edaee2f8c2241436a9022bb896ac70f149a2ab591fb5d2101aa0ea64f75c7e210c177c7eecade069266",
          "sha256": "6dae85c74ac46db577a11f0d637f9aa2b69b0a0681d65c11b30c577513db99b0",
          "sha1": "f3492d027641a3cd3cec7b96e147a006c4ad77da",
          "md5": "d9b833e71aa1092445c1c0d5311ee471"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b9b24d3b0d409c13d282e5c54e886df6a59776232b995edaee2f8c2241436a9022bb896ac70f149a2ab591fb5d2101aa0ea64f75c7e210c177c7eecade069266",
          "sha256": "6dae85c74ac46db577a11f0d637f9aa2b69b0a0681d65c11b30c577513db99b0",
          "sha1": "f3492d027641a3cd3cec7b96e147a006c4ad77da",
          "md5": "d9b833e71aa1092445c1c0d5311ee471"
        }
      ]
    }
  ]
}
