{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lclp3iaurrdqxojmivtwu5dhcy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "55cd0281e2712eb1d4b66d35d490d26a0561ec260dfd8f8617274ab9dd18c1565cc8d36372a54fdf39d74976edb71ea1eb14cc57596585e6bec4f331e2e1647a",
          "sha256": "2d5715b06ba14c2dfef7ee040753ab270099a00f27e6a2c3ca64e4da2acdbe2d",
          "sha1": "8a21d7a6cd89b85ac00a398a1b75529f075b8647",
          "md5": "fb40b507f2f17b561e2c0bde1c282d08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "55cd0281e2712eb1d4b66d35d490d26a0561ec260dfd8f8617274ab9dd18c1565cc8d36372a54fdf39d74976edb71ea1eb14cc57596585e6bec4f331e2e1647a",
          "sha256": "2d5715b06ba14c2dfef7ee040753ab270099a00f27e6a2c3ca64e4da2acdbe2d",
          "sha1": "8a21d7a6cd89b85ac00a398a1b75529f075b8647",
          "md5": "fb40b507f2f17b561e2c0bde1c282d08"
        }
      ]
    }
  ]
}
