{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-prepare-release-1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qxnhzhcfdnf4xhl6xin2es7xv4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "2bd104c31658eb1e95e6f6af34f84ae2f8b1b4de6d2c35f86a56717676173013ef5ab29c00eff81db3ad3f8e24a76f64ac31c708f162fcb5271307bbbef0092b",
          "sha256": "4ca778ce6b05a0f5d9086850009b0a350e636dd62e104a18823e14989cd9e695",
          "sha1": "f7fe950079304a914298311db2b4b7cf936a4c2f",
          "md5": "c8a92fc21af915ca52a8582630e9f51a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "2bd104c31658eb1e95e6f6af34f84ae2f8b1b4de6d2c35f86a56717676173013ef5ab29c00eff81db3ad3f8e24a76f64ac31c708f162fcb5271307bbbef0092b",
          "sha256": "4ca778ce6b05a0f5d9086850009b0a350e636dd62e104a18823e14989cd9e695",
          "sha1": "f7fe950079304a914298311db2b4b7cf936a4c2f",
          "md5": "c8a92fc21af915ca52a8582630e9f51a"
        }
      ]
    }
  ]
}
