{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "s65lxdex2faa5he6eyhs347mvi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "9b0a6531af46ae31f3987651aa252a7b330390bb2327b26bcd5c272acc2e3a9ce585c79213f853065f16e166dcfb03e4751aa695ee5802ac148fc77492b31ec6",
          "sha256": "f84d7469d9fcb0f8c5349df5fe8d632c3c66c3f8016e908a5ceb2ff32d7303b6",
          "sha1": "d56cca2b6145d1fb78765cadc245cbaa0744ad8e",
          "md5": "5b237244b8537f97b852083aafb25958"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "9b0a6531af46ae31f3987651aa252a7b330390bb2327b26bcd5c272acc2e3a9ce585c79213f853065f16e166dcfb03e4751aa695ee5802ac148fc77492b31ec6",
          "sha256": "f84d7469d9fcb0f8c5349df5fe8d632c3c66c3f8016e908a5ceb2ff32d7303b6",
          "sha1": "d56cca2b6145d1fb78765cadc245cbaa0744ad8e",
          "md5": "5b237244b8537f97b852083aafb25958"
        }
      ]
    }
  ]
}
