{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-naming-crypto-convention-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "d46pnr2s4rggvb6lxrm4qxpeay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-naming-crypto-convention-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "7846aadfd318d1cf775e842463a56328f3eb85c1e619767091a290c04c955b84bb5fa3baee6e8d48cff057a9faabf02b09ae2c384349ccd89ad3f4dc934d6fb7",
          "sha256": "def8bcacbe81874b2f808238c28afac4d563aef25ba4b78acc47ffb1732228c7",
          "sha1": "abdfa9a2d8553533c4f89ec7d9093a4f77f13ec5",
          "md5": "0de736b823f38911967de37f9c657610"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-naming-crypto-convention-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "7846aadfd318d1cf775e842463a56328f3eb85c1e619767091a290c04c955b84bb5fa3baee6e8d48cff057a9faabf02b09ae2c384349ccd89ad3f4dc934d6fb7",
          "sha256": "def8bcacbe81874b2f808238c28afac4d563aef25ba4b78acc47ffb1732228c7",
          "sha1": "abdfa9a2d8553533c4f89ec7d9093a4f77f13ec5",
          "md5": "0de736b823f38911967de37f9c657610"
        }
      ]
    }
  ]
}
