{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-change-tags-and-annotations-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wpmpnmkxcfhjdardqdbyexbrda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "5c23e3b80da2ff5d9efe34d2cf5bfc1cae426c6ea7dc94068b1f4d8c7a9891e48c5eba18ceb4ec75e9154dc3fb7630c799eb21e77c94e7fd640086e5ba636605",
          "sha256": "b428db762f31f97f7bb734f4d3b6bd70239738a17a12f478103dbad948b9457f",
          "sha1": "44d9979eb860c5166c44ac3b43fa5e3189ddd9df",
          "md5": "cc8c6b9186640a0aedf0093321ff3aac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "5c23e3b80da2ff5d9efe34d2cf5bfc1cae426c6ea7dc94068b1f4d8c7a9891e48c5eba18ceb4ec75e9154dc3fb7630c799eb21e77c94e7fd640086e5ba636605",
          "sha256": "b428db762f31f97f7bb734f4d3b6bd70239738a17a12f478103dbad948b9457f",
          "sha1": "44d9979eb860c5166c44ac3b43fa5e3189ddd9df",
          "md5": "cc8c6b9186640a0aedf0093321ff3aac"
        }
      ]
    }
  ]
}
