{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-user-info-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "u5bxpdwerngenmfclkic4dxq6u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-user-info-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "2c47dc7ad9d2b01ddba42836f9e02f324f32c0b0c03734e2fb437c88c84bb76f44da830c580996e23842a4abd970086744719ae8fa2e44f3646d6ee80858824a",
          "sha256": "d3f43ed1dfee4b7c3744dc6f667c728d5e3cbfac097581b9e3f4bf3eaf6d6edd",
          "sha1": "ee431ed4b7ce342daf2d9f4198d3cdc7e2108980",
          "md5": "d6a80c5c23daf43a714f2ebeda051a88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-user-info-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "2c47dc7ad9d2b01ddba42836f9e02f324f32c0b0c03734e2fb437c88c84bb76f44da830c580996e23842a4abd970086744719ae8fa2e44f3646d6ee80858824a",
          "sha256": "d3f43ed1dfee4b7c3744dc6f667c728d5e3cbfac097581b9e3f4bf3eaf6d6edd",
          "sha1": "ee431ed4b7ce342daf2d9f4198d3cdc7e2108980",
          "md5": "d6a80c5c23daf43a714f2ebeda051a88"
        }
      ]
    }
  ]
}
