{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.0-add-git-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cikq23s6vfdxdjt4j2js6daa4i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "772377adfddfe0ecec9e2d4bfce84c5192c840eb3d8c8c6c3932103e6e6de0be256a4a671b362113bf491475bc267b2cd97335a3f6f0838e6ec85e74ca2bc4ec",
          "sha256": "fd764d818b8da10a56b5b00e330ae709f3716b5aafb6360197a476b038d074d6",
          "sha1": "ce0060f13c378dc9bd6724defab30cd0a5c81414",
          "md5": "8f01802a16c8ac0fc74fcf69f8f41d28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-git-version-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "772377adfddfe0ecec9e2d4bfce84c5192c840eb3d8c8c6c3932103e6e6de0be256a4a671b362113bf491475bc267b2cd97335a3f6f0838e6ec85e74ca2bc4ec",
          "sha256": "fd764d818b8da10a56b5b00e330ae709f3716b5aafb6360197a476b038d074d6",
          "sha1": "ce0060f13c378dc9bd6724defab30cd0a5c81414",
          "md5": "8f01802a16c8ac0fc74fcf69f8f41d28"
        }
      ]
    }
  ]
}
