{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-commkey-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7xpblakkrfamdmuu36e5rvf5g4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "056897405501f32b863645b1ea658bbdb9a3781c0bd284c3b9c296947e366734a846c0eb675282937f608b3a155b961ad190cc6d68c86f6aa01a368fdc3bd510",
          "sha256": "ce19805674815f138b5d8d310afa513df87c0bb290457a8f548e681ad775f93a",
          "sha1": "bd45ec5a2f7c2579ccded7b804584b3b44dfd10a",
          "md5": "1d490525d80c37b3cb8c1b7b47530cd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "056897405501f32b863645b1ea658bbdb9a3781c0bd284c3b9c296947e366734a846c0eb675282937f608b3a155b961ad190cc6d68c86f6aa01a368fdc3bd510",
          "sha256": "ce19805674815f138b5d8d310afa513df87c0bb290457a8f548e681ad775f93a",
          "sha1": "bd45ec5a2f7c2579ccded7b804584b3b44dfd10a",
          "md5": "1d490525d80c37b3cb8c1b7b47530cd7"
        }
      ]
    }
  ]
}
