{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.1-fix-RecordService-fetchRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gkodvhut2fc7bd7fhe6ecgdtiq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.jar",
          "size": 448101,
          "sha512": "7feab505b060cc5069566f4d2c364f23ce675b106e79a48f7adcec6d1389a4f975a77048763c212bd68d1411fa12be3ba91c00add82ad0fdf150f47d0373fe57",
          "sha256": "5b7b1cf15f93134179e6bee03aeaa0d08965b777bbd890be665ac7582e9d7e04",
          "sha1": "4218ad161509b2c17c39f02a7ccdab7635ae2ce4",
          "md5": "9052581b82aa4851f45ae7fcf48cd2af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-fix-RecordService-fetchRecords-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-fix-RecordService-fetchRecords-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-fix-RecordService-fetchRecords-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.jar",
          "size": 448101,
          "sha512": "7feab505b060cc5069566f4d2c364f23ce675b106e79a48f7adcec6d1389a4f975a77048763c212bd68d1411fa12be3ba91c00add82ad0fdf150f47d0373fe57",
          "sha256": "5b7b1cf15f93134179e6bee03aeaa0d08965b777bbd890be665ac7582e9d7e04",
          "sha1": "4218ad161509b2c17c39f02a7ccdab7635ae2ce4",
          "md5": "9052581b82aa4851f45ae7fcf48cd2af"
        }
      ]
    }
  ]
}
