{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.1-change-recordservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "436bzr52rfca5pfnj2siq42v6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 456003,
          "sha512": "730478e849cd0f3784ac6122d542ae2e5fbd5726bb51fd2b1e76089e79c80f2eb155e300f3b80b5db9b371b044c9a7f9daf4193a909643303f9e50a138adc851",
          "sha256": "0f764f3c57fb75f6c2d5ee986fe9deb5cf674095e1ca6c129827ea207b93cbc7",
          "sha1": "b81e7b5c52aac7ce4c222442008a7618fdf9058e",
          "md5": "0ffbb33f71e496e1989f4c2760acf2d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-change-recordservice-tests-SNAPSHOT.jar",
          "size": 456003,
          "sha512": "730478e849cd0f3784ac6122d542ae2e5fbd5726bb51fd2b1e76089e79c80f2eb155e300f3b80b5db9b371b044c9a7f9daf4193a909643303f9e50a138adc851",
          "sha256": "0f764f3c57fb75f6c2d5ee986fe9deb5cf674095e1ca6c129827ea207b93cbc7",
          "sha1": "b81e7b5c52aac7ce4c222442008a7618fdf9058e",
          "md5": "0ffbb33f71e496e1989f4c2760acf2d9"
        }
      ]
    }
  ]
}
