{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vjsmew4pmfah3h2anggjyebl2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "bfe70d0be3e153578ec74592fa00ec94ad0d116c4f91f838d428c3be182741167429c63f93659f9f1a9f2e47fa3cc210ad1f8520215519ae619159caf18b42a9",
          "sha256": "e772b97de819c93c02480bc37996618c2c07959d299804ebbdd4c439d8d13385",
          "sha1": "5802bbfd2ae734077b9982a3fb0ec257af6e633e",
          "md5": "a2160562abfecdf22acbf23b05f9a4a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "bfe70d0be3e153578ec74592fa00ec94ad0d116c4f91f838d428c3be182741167429c63f93659f9f1a9f2e47fa3cc210ad1f8520215519ae619159caf18b42a9",
          "sha256": "e772b97de819c93c02480bc37996618c2c07959d299804ebbdd4c439d8d13385",
          "sha1": "5802bbfd2ae734077b9982a3fb0ec257af6e633e",
          "md5": "a2160562abfecdf22acbf23b05f9a4a5"
        }
      ]
    }
  ]
}
