{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lclp3iaurrdqxojmivtwu5dhcy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a5efc5b3523e9e51a3563ae794be20c5dcdc49e2828120ad09ba1833a6037a92c2a34fab194c2a53ccdbe82f92afbb76a1cda69480b3f060153b89b9a120850e",
          "sha256": "639dbae2819b80a289c492c4fef4675450203404bdcc2d7f321ed63af2e047c0",
          "sha1": "0f031242414e2b22969d2ce418196088f4efd176",
          "md5": "f0b6d867aea435800a49b7c3413f1650"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a5efc5b3523e9e51a3563ae794be20c5dcdc49e2828120ad09ba1833a6037a92c2a34fab194c2a53ccdbe82f92afbb76a1cda69480b3f060153b89b9a120850e",
          "sha256": "639dbae2819b80a289c492c4fef4675450203404bdcc2d7f321ed63af2e047c0",
          "sha1": "0f031242414e2b22969d2ce418196088f4efd176",
          "md5": "f0b6d867aea435800a49b7c3413f1650"
        }
      ]
    }
  ]
}
