{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-test-utils-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7rfhydy4b5eerh5ew26qydql7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-test-utils-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "9260aa2290435b942cae8b91f0533817394836ebd3484fa9c534540ea7ebf713246b5872e984ecd5939bad348b3be9bdc404ae201daace31484817fe79ba0504",
          "sha256": "e2e683190930ef47894745cb88b87c84d1d308d8a5be76c76ba4211e4611dd5f",
          "sha1": "70d729f513aabb640629323e8c957fa95d785595",
          "md5": "fa32a8b42f7b704fcde551fe18579f06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-test-utils-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "9260aa2290435b942cae8b91f0533817394836ebd3484fa9c534540ea7ebf713246b5872e984ecd5939bad348b3be9bdc404ae201daace31484817fe79ba0504",
          "sha256": "e2e683190930ef47894745cb88b87c84d1d308d8a5be76c76ba4211e4611dd5f",
          "sha1": "70d729f513aabb640629323e8c957fa95d785595",
          "md5": "fa32a8b42f7b704fcde551fe18579f06"
        }
      ]
    }
  ]
}
