{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-test-utils-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kfkubimiv5htnlqvkjf4ozuutu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-test-utils-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "a3e33163b385a76f3f9f9d051d6b867d90244ca1d3f1b3aab6209c9257d734e8405b443c1cce74fb41f2782426344cd2747f133a9452c123983918cec504ea52",
          "sha256": "0762bcf017279d5da530c0233af36ad801e41a5f019a23b90138312f4df4e687",
          "sha1": "c14abc0b451584983af9bf11f0eea30e437e8cde",
          "md5": "738cb62a642cc4a4874c94281fc69ee4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-test-utils-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "a3e33163b385a76f3f9f9d051d6b867d90244ca1d3f1b3aab6209c9257d734e8405b443c1cce74fb41f2782426344cd2747f133a9452c123983918cec504ea52",
          "sha256": "0762bcf017279d5da530c0233af36ad801e41a5f019a23b90138312f4df4e687",
          "sha1": "c14abc0b451584983af9bf11f0eea30e437e8cde",
          "md5": "738cb62a642cc4a4874c94281fc69ee4"
        }
      ]
    }
  ]
}
