{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-change-network-model-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rytikfyslvfxbcghpiw35okugy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-network-model-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-change-network-model-tests-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-change-network-model-tests-SNAPSHOT.aar",
          "size": 44950,
          "sha512": "9c334f4f6a7b13a815838ecbd6923f936590655fd32d34f82c3f2c1785c546447187548f78541facd7f030362079965b00101f088d64251784a71c87c88e733f",
          "sha256": "03a9e34b7e4e5d6509c47536575aec2ee82502af7e169b875c0d5ebe9a04a2f6",
          "sha1": "b6e029b84336ee3c3d20e7bc81c26f2b3df9b797",
          "md5": "6748c6460f4442230108e7d33f0e8c20"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-network-model-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-change-network-model-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-change-network-model-tests-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-change-network-model-tests-SNAPSHOT.aar",
          "size": 44950,
          "sha512": "9c334f4f6a7b13a815838ecbd6923f936590655fd32d34f82c3f2c1785c546447187548f78541facd7f030362079965b00101f088d64251784a71c87c88e733f",
          "sha256": "03a9e34b7e4e5d6509c47536575aec2ee82502af7e169b875c0d5ebe9a04a2f6",
          "sha1": "b6e029b84336ee3c3d20e7bc81c26f2b3df9b797",
          "md5": "6748c6460f4442230108e7d33f0e8c20"
        }
      ]
    }
  ]
}
