{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dzv35tvuw5g75orrm34hqptk2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "826642c9a2c8fd78a7f4cac1781e8ac4eb999ba69d8f86715a70eab067d069eb91ed19a562e8d9cec1b0658481375f2b5bd40c71e4fc959cb7bd590504193ca6",
          "sha256": "f7a8dad5f1a6addcf5d7f921eeadf3771451d01fa586523d7649723312a53be3",
          "sha1": "df0d409b418c1e90839a352e5bad33d56426753b",
          "md5": "783af9710f3caf7f8e9d26bbef34690f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "826642c9a2c8fd78a7f4cac1781e8ac4eb999ba69d8f86715a70eab067d069eb91ed19a562e8d9cec1b0658481375f2b5bd40c71e4fc959cb7bd590504193ca6",
          "sha256": "f7a8dad5f1a6addcf5d7f921eeadf3771451d01fa586523d7649723312a53be3",
          "sha1": "df0d409b418c1e90839a352e5bad33d56426753b",
          "md5": "783af9710f3caf7f8e9d26bbef34690f"
        }
      ]
    }
  ]
}
