{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.10.0-bump-fhir-lib-1-4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ctzmyecinjcjzlrgyyvbevqn5e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-fhir-lib-1-4-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.aar",
          "url": "securestore-android-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.aar",
          "size": 41956,
          "sha512": "4c332c1baa827ce4c6d6f42db8dea62028dd76de093db33a0fd14f7897a2c8dac98b2ba3997f14ad6be0a4d0f921aa4ff150135e1ac7b6663d955632420afb04",
          "sha256": "9f68b7bf5d41fc5fc74bf12501def4f3ccc90cff46b95d9ac13d600675692047",
          "sha1": "6eabe2ed9e9c5ed96f16fbf46040c29d09fbcccd",
          "md5": "0878c0c2389bb024b7df5bf19d8e899c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-fhir-lib-1-4-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.aar",
          "url": "securestore-android-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.aar",
          "size": 41956,
          "sha512": "4c332c1baa827ce4c6d6f42db8dea62028dd76de093db33a0fd14f7897a2c8dac98b2ba3997f14ad6be0a4d0f921aa4ff150135e1ac7b6663d955632420afb04",
          "sha256": "9f68b7bf5d41fc5fc74bf12501def4f3ccc90cff46b95d9ac13d600675692047",
          "sha1": "6eabe2ed9e9c5ed96f16fbf46040c29d09fbcccd",
          "md5": "0878c0c2389bb024b7df5bf19d8e899c"
        }
      ]
    }
  ]
}
