{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ih5xjviyszesvhtokz2lpfo6m4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.aar",
          "size": 44909,
          "sha512": "153e59b4644e1502c6a7a511b30d1a0f5a28cde7fa13d92983e447fc66cbfbdc0421d1c0e5c3136576204e8ed9719ac936b49d7e2d108f5ed258ca7e3d6e5dd7",
          "sha256": "0b73f443b2520e6daebf268803e9f346ade330ec1d36249a9a596174de59ec37",
          "sha1": "cab34688eb59ccebfc13a772031b94082cd05567",
          "md5": "110f54be157cf27864b992bee9a5b5cf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.aar",
          "size": 44909,
          "sha512": "153e59b4644e1502c6a7a511b30d1a0f5a28cde7fa13d92983e447fc66cbfbdc0421d1c0e5c3136576204e8ed9719ac936b49d7e2d108f5ed258ca7e3d6e5dd7",
          "sha256": "0b73f443b2520e6daebf268803e9f346ade330ec1d36249a9a596174de59ec37",
          "sha1": "cab34688eb59ccebfc13a772031b94082cd05567",
          "md5": "110f54be157cf27864b992bee9a5b5cf"
        }
      ]
    }
  ]
}
