{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ec4ea6r24vevhm4cwchkbgeolm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "6a1c3ac6ca0da452641dfef6cb903d05f962ba26a158db8c2d46afcff38c33dd5dac52fe3d557734e337c7ade870c7d1fbf9c1c24ffb97149b6d4d5f47547ac5",
          "sha256": "0a3335a8333945d3faba9adbbc210ef41384d0e34dab294bb85824b2bc6ca138",
          "sha1": "ebe94ac8512e6d3451d4938d758492a8e34c0693",
          "md5": "3c1c336ef63b6ffd46aa50402e644958"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "6a1c3ac6ca0da452641dfef6cb903d05f962ba26a158db8c2d46afcff38c33dd5dac52fe3d557734e337c7ade870c7d1fbf9c1c24ffb97149b6d4d5f47547ac5",
          "sha256": "0a3335a8333945d3faba9adbbc210ef41384d0e34dab294bb85824b2bc6ca138",
          "sha1": "ebe94ac8512e6d3451d4938d758492a8e34c0693",
          "md5": "3c1c336ef63b6ffd46aa50402e644958"
        }
      ]
    }
  ]
}
