{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.1-fix-RecordService-fetchRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xud6ebqvlzh5ndholrtj75amoq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-RecordService-fetchRecords-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.aar",
          "size": 51839,
          "sha512": "f22611984f18448602a6955b775a6cccea3a255d43f4f994535b5219d6b12fc0cd452d6b5588e95cdb1c50fc72b9a99d06c978103c225177c2ef007d8a20fd4c",
          "sha256": "983f4a3e15575491aaf0f4fdcc09b57ee8fa4b54662a712b1ec724e6839c4335",
          "sha1": "dbb9ad80e1a4583a96facec28330a5b06da2cb35",
          "md5": "d5c340e89258cb95ab00acdb03c81c53"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-RecordService-fetchRecords-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-fix-RecordService-fetchRecords-SNAPSHOT.aar",
          "size": 51839,
          "sha512": "f22611984f18448602a6955b775a6cccea3a255d43f4f994535b5219d6b12fc0cd452d6b5588e95cdb1c50fc72b9a99d06c978103c225177c2ef007d8a20fd4c",
          "sha256": "983f4a3e15575491aaf0f4fdcc09b57ee8fa4b54662a712b1ec724e6839c4335",
          "sha1": "dbb9ad80e1a4583a96facec28330a5b06da2cb35",
          "md5": "d5c340e89258cb95ab00acdb03c81c53"
        }
      ]
    }
  ]
}
