{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-add-package-hl7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "eyh5tibf7jbv5io3szeis4etva"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.0.1-add-package-hl7-SNAPSHOT.jar",
          "url": "fhir-0.0.1-add-package-hl7-SNAPSHOT.jar",
          "size": 509086,
          "sha512": "eb1e1946fa5eb293e9c09f36c7893f1f6e6a0da9ab36d5228a77ea3725a4e2c64b30e6b70ab2b6ef72b16e5252f5db7fb426fe770c876ebd5e7f8b6cb30284e3",
          "sha256": "f7788bc66329b0305155649a1785456f53004d4e10978b4500ced822a8d2e49a",
          "sha1": "2ec580c0212728ddd2a2461367e303097667871a",
          "md5": "183f2590d1b90246e3cae135df0978df"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.0.1-add-package-hl7-SNAPSHOT/fhir-android-0.0.1-add-package-hl7-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.0.1-add-package-hl7-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../fhir-android/0.0.1-add-package-hl7-SNAPSHOT/fhir-android-0.0.1-add-package-hl7-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-android",
        "version": "0.0.1-add-package-hl7-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosarm64/0.0.1-add-package-hl7-SNAPSHOT/fhir-iosarm64-0.0.1-add-package-hl7-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosarm64",
        "version": "0.0.1-add-package-hl7-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../fhir-iosx64/0.0.1-add-package-hl7-SNAPSHOT/fhir-iosx64-0.0.1-add-package-hl7-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-iosx64",
        "version": "0.0.1-add-package-hl7-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.0.1-add-package-hl7-SNAPSHOT/fhir-jvm-0.0.1-add-package-hl7-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.0.1-add-package-hl7-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../fhir-jvm/0.0.1-add-package-hl7-SNAPSHOT/fhir-jvm-0.0.1-add-package-hl7-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-jvm",
        "version": "0.0.1-add-package-hl7-SNAPSHOT"
      }
    }
  ]
}
