{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bjlqrxtr6feqvdwnzzqsiaiir4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "76b9874205452adad794c378c62e63946e810a0c421ec6c3d0e126bb8efc41d2cc93a850ab39cfce96594f3af6ff89e076d3b60c4ff5729ff1da631b8418261f",
          "sha256": "f561837e5583e8f0da3484b315a759d853efaea2f516afa3d7e8ce3b819e3c2f",
          "sha1": "7b6afe1ef8a7bacac63f2e50599efdaa0970bf4b",
          "md5": "5eec58bd0ef69db1f3613e4eec0063c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "76b9874205452adad794c378c62e63946e810a0c421ec6c3d0e126bb8efc41d2cc93a850ab39cfce96594f3af6ff89e076d3b60c4ff5729ff1da631b8418261f",
          "sha256": "f561837e5583e8f0da3484b315a759d853efaea2f516afa3d7e8ce3b819e3c2f",
          "sha1": "7b6afe1ef8a7bacac63f2e50599efdaa0970bf4b",
          "md5": "5eec58bd0ef69db1f3613e4eec0063c8"
        }
      ]
    }
  ]
}
