{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-add-git-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mtp2u54msraa3oko6ir3i6imnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "4ac24b4092b4dc430cd24541401db28ed5d7394da677e21f761f7ba2684ea6b8a11cd229da58ad56447db0fa6b222782c738af79c8b07353efaa5c919b64a608",
          "sha256": "b97bc08c72bf84dd1b73edb0ee69e09d938c63d01d3af899da4b4b8691f5e822",
          "sha1": "6a22b162916bb4fd8f402b0ca93b439da5486c2e",
          "md5": "4bc0a30fa258d0c76ba564b4484903fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-add-git-version-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "4ac24b4092b4dc430cd24541401db28ed5d7394da677e21f761f7ba2684ea6b8a11cd229da58ad56447db0fa6b222782c738af79c8b07353efaa5c919b64a608",
          "sha256": "b97bc08c72bf84dd1b73edb0ee69e09d938c63d01d3af899da4b4b8691f5e822",
          "sha1": "6a22b162916bb4fd8f402b0ca93b439da5486c2e",
          "md5": "4bc0a30fa258d0c76ba564b4484903fe"
        }
      ]
    }
  ]
}
