{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zkxoh34wznbunau4vjop3pk6dy"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "size": 44909,
          "sha512": "03843b0250cd5bffc098388f2434b08423b7bf4be8a11279c46c420de4cccab6785f5af0094b3ed34c8cefa4ffd590c8ec0b2ed2c1d75898123ca2b14bf42479",
          "sha256": "1db6e57f9236bce2715b7ac9138ede875fac7509bb7ff153dbc3ba192dc64e43",
          "sha1": "4f587de0db01288d05f75fd7941bea2e875d1b77",
          "md5": "1831d62b52db26956527627ed72d0bb1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "size": 44909,
          "sha512": "03843b0250cd5bffc098388f2434b08423b7bf4be8a11279c46c420de4cccab6785f5af0094b3ed34c8cefa4ffd590c8ec0b2ed2c1d75898123ca2b14bf42479",
          "sha256": "1db6e57f9236bce2715b7ac9138ede875fac7509bb7ff153dbc3ba192dc64e43",
          "sha1": "4f587de0db01288d05f75fd7941bea2e875d1b77",
          "md5": "1831d62b52db26956527627ed72d0bb1"
        }
      ]
    }
  ]
}
