{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-fix-release-ci-job-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pr6loosk2fa5jlcqcqncxhbwra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8763b65d1fb6d040e8e6f43c9ca3d59f23ef74dac859d790429df676952536aaeed76fe77a16733bf8ae3ffb49ac6f6d63d3e63100388c796db5b53ce8f2c766",
          "sha256": "6c66e4b16945f45798dca7db5ad69fbe6cf552055ac62d7b4a7c5a2c4a8e3390",
          "sha1": "3ebc63041b9a931031b478f29520602c271111ac",
          "md5": "e4273c8e52e394ba038022c3deda13d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-release-ci-job-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8763b65d1fb6d040e8e6f43c9ca3d59f23ef74dac859d790429df676952536aaeed76fe77a16733bf8ae3ffb49ac6f6d63d3e63100388c796db5b53ce8f2c766",
          "sha256": "6c66e4b16945f45798dca7db5ad69fbe6cf552055ac62d7b4a7c5a2c4a8e3390",
          "sha1": "3ebc63041b9a931031b478f29520602c271111ac",
          "md5": "e4273c8e52e394ba038022c3deda13d1"
        }
      ]
    }
  ]
}
