{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-change-attachment-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wl4mwif3s5dmhgdrycqkf45cp4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-attachment-contract-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-attachment-contract-SNAPSHOT.aar",
          "size": 44896,
          "sha512": "25d1f4162db734b1ebda790e8b45fe3130d73641d273058dc30cf3c7a5486af2c322acb3eb776bf61a6e647b6b55c5c3e3171eec1b4d1b8c2491a4c93e3a2879",
          "sha256": "7593d4250ff529137218761f18c9f8ed0902d5272ccda786d867ea0420be7739",
          "sha1": "6e6013ee57e8ba95880844b27d4210545367a449",
          "md5": "cb35822d4635c7a3d5ed890889cb70d5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-attachment-contract-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-attachment-contract-SNAPSHOT.aar",
          "size": 44896,
          "sha512": "25d1f4162db734b1ebda790e8b45fe3130d73641d273058dc30cf3c7a5486af2c322acb3eb776bf61a6e647b6b55c5c3e3171eec1b4d1b8c2491a4c93e3a2879",
          "sha256": "7593d4250ff529137218761f18c9f8ed0902d5272ccda786d867ea0420be7739",
          "sha1": "6e6013ee57e8ba95880844b27d4210545367a449",
          "md5": "cb35822d4635c7a3d5ed890889cb70d5"
        }
      ]
    }
  ]
}
