{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rwszed26yrcmfggg4ln3iezvbu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "size": 51969,
          "sha512": "f83ab1340039fd2ba40505beecd6843fa3b5c52967fb906f98e31a37ac62677223648d0243c3c6912a4ddf5be4a988d4a9d526e62978fb2a881ea98ed7e4a968",
          "sha256": "a4dacbd0c7e35020383497a141bda4dd0d48572da8941c96bda51bef02805ec9",
          "sha1": "044c9b8a4d79069523e96e17da51566110fbc4d1",
          "md5": "856dac7d19cbfb89659f0c75ff9f2af3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "size": 51969,
          "sha512": "f83ab1340039fd2ba40505beecd6843fa3b5c52967fb906f98e31a37ac62677223648d0243c3c6912a4ddf5be4a988d4a9d526e62978fb2a881ea98ed7e4a968",
          "sha256": "a4dacbd0c7e35020383497a141bda4dd0d48572da8941c96bda51bef02805ec9",
          "sha1": "044c9b8a4d79069523e96e17da51566110fbc4d1",
          "md5": "856dac7d19cbfb89659f0c75ff9f2af3"
        }
      ]
    }
  ]
}
