{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "goufc3wiczh2bdgk33euwm7coi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "c4a2e932dae593536fb3b43402bc8903b671a9586afd63295f5eac714c2dc02b49d6374090bb1f6cc97ad77d97081fde0050a1436d55c9913cebc1d42b7abab5",
          "sha256": "372bdbe3100dc471a13dd62400937af2f7d577653b07f56fafa0969a056970d6",
          "sha1": "bd1b475fd5cb470aa32311021eb7ef83b84e7677",
          "md5": "0596742d06264335496f5bce76549b9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "c4a2e932dae593536fb3b43402bc8903b671a9586afd63295f5eac714c2dc02b49d6374090bb1f6cc97ad77d97081fde0050a1436d55c9913cebc1d42b7abab5",
          "sha256": "372bdbe3100dc471a13dd62400937af2f7d577653b07f56fafa0969a056970d6",
          "sha1": "bd1b475fd5cb470aa32311021eb7ef83b84e7677",
          "md5": "0596742d06264335496f5bce76549b9c"
        }
      ]
    }
  ]
}
