{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tgoacre5dre7zktx7r4f7zjxcm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8c1322e088cc939a29317d2e2424ad73e0e17569010d361fa15173af41d801c440b176dc7aac36447adce71db548f8d430703b1f64f4f1e0bb1096bc3507bb84",
          "sha256": "6552c6a352451ebc185ef5c1ee171224d6d6ee21bc892d27518ca4718065d090",
          "sha1": "01f28585232120510739fb3088036f840f4130a2",
          "md5": "1ec250e71048f9cd55aabe0855126fe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-change-EncryptedRecord-and-EncryptedKey-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8c1322e088cc939a29317d2e2424ad73e0e17569010d361fa15173af41d801c440b176dc7aac36447adce71db548f8d430703b1f64f4f1e0bb1096bc3507bb84",
          "sha256": "6552c6a352451ebc185ef5c1ee171224d6d6ee21bc892d27518ca4718065d090",
          "sha1": "01f28585232120510739fb3088036f840f4130a2",
          "md5": "1ec250e71048f9cd55aabe0855126fe3"
        }
      ]
    }
  ]
}
