{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util",
    "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "uxnwxmbqrbgilnpli3ce5fgupu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "url": "util-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "size": 6584,
          "sha512": "a4de51e9718d25bf491411e2a43c6d192582b3724d9c5f73bced70af4fb77438b58579536867ca39796fcc18e1f496eb2dfea54e0950ce1fa6ecc3bf902de9da",
          "sha256": "0edbf8fc23f9b12c80e7c0bbb82a319080c0f6bd1a9674c228fc82bb885c4fe0",
          "sha1": "b6d76c5e7ba0e11efe576934e6cfba11f66c4975",
          "md5": "5bbf37f0a100eed760c6be2210adc03a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-android-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../util-android/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-android-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-android",
        "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../util-jvm/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
        "group": "care.data4life.hc-util-sdk-kmp",
        "module": "util-jvm",
        "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT"
      }
    }
  ]
}
