{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wgde7xnbkzhrjkwotraczy5wyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "c49996c7fc252c35c5dcd6398f09957403986ea6e94203edfc9338c3c5e95356bcac5e272fe018cca2ca74760ef8552d8a3a5811f29e3028611b0894b3b8c653",
          "sha256": "05746081ac13607ddc7c7c3f32114dd91d0ecfd405e1f02e777f0d7ae673cf14",
          "sha1": "dc16b6fa6d381429d37d47508413a4c987a416b0",
          "md5": "345a3581888ce43d94ed80b1ab3a5046"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "c49996c7fc252c35c5dcd6398f09957403986ea6e94203edfc9338c3c5e95356bcac5e272fe018cca2ca74760ef8552d8a3a5811f29e3028611b0894b3b8c653",
          "sha256": "05746081ac13607ddc7c7c3f32114dd91d0ecfd405e1f02e777f0d7ae673cf14",
          "sha1": "dc16b6fa6d381429d37d47508413a4c987a416b0",
          "md5": "345a3581888ce43d94ed80b1ab3a5046"
        }
      ]
    }
  ]
}
