{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4q5aidtacncpffnbb72gqh2uuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7c782a068038d2bca9bccee6b74b856585cf21ac070cdae9212684250a2f48f91b0a6414b7697e46fe5a296232944b412cf6e0beb150c35046483866df42eefd",
          "sha256": "942f201634e313ae1eaa93c5b0424e2d65c1c565e17e873e2cb8561a00430ea7",
          "sha1": "146c5ac7554e66eeb3e5a4ce47de50f14c95d406",
          "md5": "271d7ed3a90106e383cd317e54ea3faa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7c782a068038d2bca9bccee6b74b856585cf21ac070cdae9212684250a2f48f91b0a6414b7697e46fe5a296232944b412cf6e0beb150c35046483866df42eefd",
          "sha256": "942f201634e313ae1eaa93c5b0424e2d65c1c565e17e873e2cb8561a00430ea7",
          "sha1": "146c5ac7554e66eeb3e5a4ce47de50f14c95d406",
          "md5": "271d7ed3a90106e383cd317e54ea3faa"
        }
      ]
    }
  ]
}
