{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.6.1-SNAPSHOT/util-jvm-1.6.1-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mtj6q5tdt5f4doy2k2kek2ng4i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.6.1-SNAPSHOT.jar",
          "url": "util-metadata-1.6.1-SNAPSHOT.jar",
          "size": 6584,
          "sha512": "15c249174748c921be062d67a18ef09f3a5462fd364a8b60718a03cf00b7d078d075ac3ce841dfe899ad2f608d8a3896000bf1dd6f501cb3ac53b9aa87abe147",
          "sha256": "ef9934a604c45e1118527eba1b29d3170982cd847fa1d90af09ab647242838c3",
          "sha1": "1f289b662937dcf7f9eab11f377787a79acb4168",
          "md5": "2a83fc454ef2ac149ee67841b764762a"
        }
      ]
    }
  ]
}
