{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-fix-document-upload-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lgtadhf4xjgj5jbmmvgfljowii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 16425,
          "sha512": "a40e558589cada0611d6cfe129cf30887d38ed1fbb1fecacf3d845669181e886a2f645b8a80f92403738df0f5ac800e27fcff0cd95f89578d082a8a85e77ab35",
          "sha256": "5b4c8d3320a5486fd017ed6d929b9fe6e152c613ca43428ba00979e1f96eafd1",
          "sha1": "119e0d5882f03c016c83d86dbc2b5c10c424e3e2",
          "md5": "6156fdaa513e195efd3554b615adcd1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 16425,
          "sha512": "a40e558589cada0611d6cfe129cf30887d38ed1fbb1fecacf3d845669181e886a2f645b8a80f92403738df0f5ac800e27fcff0cd95f89578d082a8a85e77ab35",
          "sha256": "5b4c8d3320a5486fd017ed6d929b9fe6e152c613ca43428ba00979e1f96eafd1",
          "sha1": "119e0d5882f03c016c83d86dbc2b5c10c424e3e2",
          "md5": "6156fdaa513e195efd3554b615adcd1c"
        }
      ]
    }
  ]
}
