{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6oau6ptl7va6rdgaejx6j2j2um"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5bb0c173df596ffd84c558fd15e6a7f17f70d8e38ca87f75da5d28ad3fcf7f3b142a4fa239fa7ad7d97a2a8c277c6331d6f4e878f9f2b93216d0de575cf8094b",
          "sha256": "6f37aa63b911587bfa1856c5c4287747d8f7ef8fc0e5bf90a94e0d119e88472c",
          "sha1": "d1bd8d6b40dd98d8cf7e42cade84da60862e6b3c",
          "md5": "985cea42a205eb00368059938a4682b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5bb0c173df596ffd84c558fd15e6a7f17f70d8e38ca87f75da5d28ad3fcf7f3b142a4fa239fa7ad7d97a2a8c277c6331d6f4e878f9f2b93216d0de575cf8094b",
          "sha256": "6f37aa63b911587bfa1856c5c4287747d8f7ef8fc0e5bf90a94e0d119e88472c",
          "sha1": "d1bd8d6b40dd98d8cf7e42cade84da60862e6b3c",
          "md5": "985cea42a205eb00368059938a4682b3"
        }
      ]
    }
  ]
}
