{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-add-resource-encryption-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "5tqp76wi4jervi27f2o3t5lauu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "b11d3ebaa6b6de3811718b12bafadc4c77b177d53c695abb1a1aea66f2b35d06a1cd27b56fc6a02598b285ca5290127e8762b7f589ba63c62539560e68e9d27b",
          "sha256": "af5642ce18e8f8ab185cc4e9e6cc4b17e5cad2920e87afb508b473d54ee64c79",
          "sha1": "288fb27631642e51a431e610f441f958f62d0fc9",
          "md5": "698117d24c0b31aba0b17523600851ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "b11d3ebaa6b6de3811718b12bafadc4c77b177d53c695abb1a1aea66f2b35d06a1cd27b56fc6a02598b285ca5290127e8762b7f589ba63c62539560e68e9d27b",
          "sha256": "af5642ce18e8f8ab185cc4e9e6cc4b17e5cad2920e87afb508b473d54ee64c79",
          "sha1": "288fb27631642e51a431e610f441f958f62d0fc9",
          "md5": "698117d24c0b31aba0b17523600851ce"
        }
      ]
    }
  ]
}
