{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hq6usbmvhnbkretz6cmzmfh4z4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "efa03c8551e84effa383bb2e632ed3559faec9263fae9b9263a896f345090f0a54aa8d97f6d615c9182a5402345e066b34e81b16222337b64f61adb289b50c7a",
          "sha256": "9005842f4b4990494844c1eaf97aaf564d276273af8719b5c89f3a556c3166c4",
          "sha1": "c95cead85f0a47ab13416fdbbec87ca5c51109f7",
          "md5": "e71372538238197dd7ea2e931fdb213c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "efa03c8551e84effa383bb2e632ed3559faec9263fae9b9263a896f345090f0a54aa8d97f6d615c9182a5402345e066b34e81b16222337b64f61adb289b50c7a",
          "sha256": "9005842f4b4990494844c1eaf97aaf564d276273af8719b5c89f3a556c3166c4",
          "sha1": "c95cead85f0a47ab13416fdbbec87ca5c51109f7",
          "md5": "e71372538238197dd7ea2e931fdb213c"
        }
      ]
    }
  ]
}
