{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nf4yhlh33zhdhcreqmptyo3smm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "aff56094321882aa56acac0b9006f9b918e1d421cce5e2fb60441d760466126954f6f7ef51dc6f68936c88a54a7b934343867b45a5897483cc6e21d4101711fe",
          "sha256": "365f2d0472e0623f5842903b20db163c587120e479103c7dffa6248007e43779",
          "sha1": "70cb60ab7885d6c5636c303987435357ddc62bc4",
          "md5": "5b6cad4b613df9385d3c2f592029dab6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "aff56094321882aa56acac0b9006f9b918e1d421cce5e2fb60441d760466126954f6f7ef51dc6f68936c88a54a7b934343867b45a5897483cc6e21d4101711fe",
          "sha256": "365f2d0472e0623f5842903b20db163c587120e479103c7dffa6248007e43779",
          "sha1": "70cb60ab7885d6c5636c303987435357ddc62bc4",
          "md5": "5b6cad4b613df9385d3c2f592029dab6"
        }
      ]
    }
  ]
}
