{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rasgwsgqijf7bhg2obw3tli3x4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "6219b72b743552f0d08cae8de1a8b83beee4a2394e70aa6e7ede1986d48a8119afea9f81a4c9e2539467448e860762c1c61aaeaada83290a84d6f6bc3e16a27d",
          "sha256": "ec91fe83efac72e58116cb82106b041b6c5f447bd0c54922e832d8bc38bef81b",
          "sha1": "e22fe6577f58f42d5f30c28825372e80fb7a608f",
          "md5": "1f9b84c19917b3ca73ebb4505ec93f4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "6219b72b743552f0d08cae8de1a8b83beee4a2394e70aa6e7ede1986d48a8119afea9f81a4c9e2539467448e860762c1c61aaeaada83290a84d6f6bc3e16a27d",
          "sha256": "ec91fe83efac72e58116cb82106b041b6c5f447bd0c54922e832d8bc38bef81b",
          "sha1": "e22fe6577f58f42d5f30c28825372e80fb7a608f",
          "md5": "1f9b84c19917b3ca73ebb4505ec93f4e"
        }
      ]
    }
  ]
}
