{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dws5bmwndjfjtlacyyxejjgowm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "c995845e92bdbb516cccb942f42b087bf6d6af9d3b6313b4680503b574a49ee39b99830e1ec6d594238067a5e25698cadbcf89ec4bc18275c99f2048141a4f2f",
          "sha256": "2665840ff82c388f1ad0b0ff8b52d2353b575ab9f7f0814833b87eaf9413fc6a",
          "sha1": "2bb38e213ee8bf082ddd371952308436acbfd849",
          "md5": "fbe037849954648bdbf481eb71ea6af8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "c995845e92bdbb516cccb942f42b087bf6d6af9d3b6313b4680503b574a49ee39b99830e1ec6d594238067a5e25698cadbcf89ec4bc18275c99f2048141a4f2f",
          "sha256": "2665840ff82c388f1ad0b0ff8b52d2353b575ab9f7f0814833b87eaf9413fc6a",
          "sha1": "2bb38e213ee8bf082ddd371952308436acbfd849",
          "md5": "fbe037849954648bdbf481eb71ea6af8"
        }
      ]
    }
  ]
}
