{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6g5pc6v4zrhrplvkcpn3zansiu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "0498b149df0fd19018fad79795f92f9ff0f13cd91b8ac8719b4f9ff0214a7cb2b64155b827e27b50f340f3067fe523e5a4b6a3d8dd9961afcc950b9090a63117",
          "sha256": "660f574c9bf8dccc6c82ba688a3d610b7dadce717f623059f9e81137c6223e80",
          "sha1": "c7ad0fd5e50b9cbff0d3ce6c32aeece592afd41e",
          "md5": "1ac09b84f18f03585dbcb8ada3bf9c97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "0498b149df0fd19018fad79795f92f9ff0f13cd91b8ac8719b4f9ff0214a7cb2b64155b827e27b50f340f3067fe523e5a4b6a3d8dd9961afcc950b9090a63117",
          "sha256": "660f574c9bf8dccc6c82ba688a3d610b7dadce717f623059f9e81137c6223e80",
          "sha1": "c7ad0fd5e50b9cbff0d3ce6c32aeece592afd41e",
          "md5": "1ac09b84f18f03585dbcb8ada3bf9c97"
        }
      ]
    }
  ]
}
