{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.0-bump-fhir-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4576llu3avb23d2tof26t2wwcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "url": "sdk-core-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "size": 451637,
          "sha512": "5de38eac1486011cbad3c193a557e45c92c3c0adcd7ef42cd34a76ed8ae20b5b4328f380b1cfee4c56317a6ee076ee0a433c61da82022a7d0a20b028dabd35cb",
          "sha256": "7f51f2ac32b40ea58e472ba76cf13f9e91edf30924fa5c0d5659f4e52e4da1f0",
          "sha1": "0cc8f3b38b588f2eced204f8ea8a51da769042e8",
          "md5": "8e00e85be47c9e32239c70bbe8a2cd5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-bump-fhir-sdk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.0-bump-fhir-sdk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.0-bump-fhir-sdk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "url": "sdk-core-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "size": 451637,
          "sha512": "5de38eac1486011cbad3c193a557e45c92c3c0adcd7ef42cd34a76ed8ae20b5b4328f380b1cfee4c56317a6ee076ee0a433c61da82022a7d0a20b028dabd35cb",
          "sha256": "7f51f2ac32b40ea58e472ba76cf13f9e91edf30924fa5c0d5659f4e52e4da1f0",
          "sha1": "0cc8f3b38b588f2eced204f8ea8a51da769042e8",
          "md5": "8e00e85be47c9e32239c70bbe8a2cd5e"
        }
      ]
    }
  ]
}
