{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bihq7l3hcfaudpwpbxompm2om4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "25950c111665484b273fddaaeea930a4ea323425b50f497feb82f7850c433c6c858b8e587fd4d6b374b8cc244d31106dbe93e40fd03468fe96672568b7f53dff",
          "sha256": "5d886bfc2226f621576a28a155eb5055ae22b17f1736cdf2a23355c30081ed9e",
          "sha1": "2332d387478502b3de2b59509926bb9f8b239fb2",
          "md5": "180f5406cc575da5fd176771c3fef285"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "25950c111665484b273fddaaeea930a4ea323425b50f497feb82f7850c433c6c858b8e587fd4d6b374b8cc244d31106dbe93e40fd03468fe96672568b7f53dff",
          "sha256": "5d886bfc2226f621576a28a155eb5055ae22b17f1736cdf2a23355c30081ed9e",
          "sha1": "2332d387478502b3de2b59509926bb9f8b239fb2",
          "md5": "180f5406cc575da5fd176771c3fef285"
        }
      ]
    }
  ]
}
