{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qqu3uu4u6zhhrijjnyvvajkysm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "36769b160eb20a1dc20c9c3b85a2cfdf9445ecd8f2883bc38d8ccab27c17967518eed38c5328d0ebd293fdf8d52ad515d14e5fc6fbc322166443f396d270e422",
          "sha256": "23ce2b121c36d31fb0d6ef81398a2764895e015af419aa09887206f7d5ef1acb",
          "sha1": "f99dff781c05199d841d8f84438033b283b5b405",
          "md5": "80b42acd6eea87dd76730702cc828824"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "36769b160eb20a1dc20c9c3b85a2cfdf9445ecd8f2883bc38d8ccab27c17967518eed38c5328d0ebd293fdf8d52ad515d14e5fc6fbc322166443f396d270e422",
          "sha256": "23ce2b121c36d31fb0d6ef81398a2764895e015af419aa09887206f7d5ef1acb",
          "sha1": "f99dff781c05199d841d8f84438033b283b5b405",
          "md5": "80b42acd6eea87dd76730702cc828824"
        }
      ]
    }
  ]
}
