{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "x67am4b4n5f7hmxjbcozwoyare"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "f66466b566132f5e00e3479f364308e58a7868af27b11181b1c0e065b31f0dbf61dd338fd50b904bf30b3f0a7e31947a8dd8469ddb2ef12ed3ad6136b1852ccb",
          "sha256": "a5092262fb9dd8b5afbba765de3469a26e95184837c8f050b7547ff5ded88178",
          "sha1": "c2550f6c44eee44069e98ef1c553d23691c70073",
          "md5": "efdd9d077281e9df013c6c3465603cb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "f66466b566132f5e00e3479f364308e58a7868af27b11181b1c0e065b31f0dbf61dd338fd50b904bf30b3f0a7e31947a8dd8469ddb2ef12ed3ad6136b1852ccb",
          "sha256": "a5092262fb9dd8b5afbba765de3469a26e95184837c8f050b7547ff5ded88178",
          "sha1": "c2550f6c44eee44069e98ef1c553d23691c70073",
          "md5": "efdd9d077281e9df013c6c3465603cb0"
        }
      ]
    }
  ]
}
