{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "a2gxlr67vjd6pgvnmsqrgucg3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "4c431d7a799dd30fc61abb15e362e0032e93474a7d4558fee180d3da352f7775c163e64d824c7b3dc6195729a8e156d37b3c0579f381dadd6da78a88c49d860e",
          "sha256": "d0b3e9eb2edf939a382adb5f7f54902dfb34379c779dd69b25ec6aa97ee6c35f",
          "sha1": "73d24e5b6818f6019b7490579f61db58738053b6",
          "md5": "c68648931aae2c1a9f6d30f8953c617c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "4c431d7a799dd30fc61abb15e362e0032e93474a7d4558fee180d3da352f7775c163e64d824c7b3dc6195729a8e156d37b3c0579f381dadd6da78a88c49d860e",
          "sha256": "d0b3e9eb2edf939a382adb5f7f54902dfb34379c779dd69b25ec6aa97ee6c35f",
          "sha1": "73d24e5b6818f6019b7490579f61db58738053b6",
          "md5": "c68648931aae2c1a9f6d30f8953c617c"
        }
      ]
    }
  ]
}
