{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "b645qhpounhvbn4genyfu62jb4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-fix-code-style-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-fix-code-style-SNAPSHOT.aar",
          "size": 51829,
          "sha512": "a87a2d77d0851e5d1fc4ee5a831db79260c101fa539b1655ca2b6f51d43bab109a6e6799cfa2003b26ee07431f8c20cd8a013960485ed5575c8efb60dc27f54a",
          "sha256": "138600d0316b0b1fa9c8d810fd6a84c433ca2d73436ec99aad6696337b822471",
          "sha1": "dffa1ef992d194e1a95d4cec4cf0b0f6a82bb75f",
          "md5": "2a49efb8329d451b37672a84d9d54d58"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-fix-code-style-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-fix-code-style-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-fix-code-style-SNAPSHOT.aar",
          "size": 51829,
          "sha512": "a87a2d77d0851e5d1fc4ee5a831db79260c101fa539b1655ca2b6f51d43bab109a6e6799cfa2003b26ee07431f8c20cd8a013960485ed5575c8efb60dc27f54a",
          "sha256": "138600d0316b0b1fa9c8d810fd6a84c433ca2d73436ec99aad6696337b822471",
          "sha1": "dffa1ef992d194e1a95d4cec4cf0b0f6a82bb75f",
          "md5": "2a49efb8329d451b37672a84d9d54d58"
        }
      ]
    }
  ]
}
