{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "h3krjl4ru5fflidpkuassdnfgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "64fc642fd8194802297f136fc734ae412c9ca8f02d281a08dd00384675a24dabb6ee9560e2f2f2b75db957771c94914cd85421dc3bec6e3c05eb8ed8f92e6683",
          "sha256": "b50a0359db3410066da80ee9d49bd3b3cae1a9b6009840333a97caadda6771b9",
          "sha1": "5d58f1e45995117e7f530694778af8e3d80a0ef9",
          "md5": "9bac500c411f54e0885b4fc8e2b8f167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "64fc642fd8194802297f136fc734ae412c9ca8f02d281a08dd00384675a24dabb6ee9560e2f2f2b75db957771c94914cd85421dc3bec6e3c05eb8ed8f92e6683",
          "sha256": "b50a0359db3410066da80ee9d49bd3b3cae1a9b6009840333a97caadda6771b9",
          "sha1": "5d58f1e45995117e7f530694778af8e3d80a0ef9",
          "md5": "9bac500c411f54e0885b4fc8e2b8f167"
        }
      ]
    }
  ]
}
