{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "k54ks5kykfawxetn3sqiancbbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d9d1bd50e72bc339a1348fee86af42ae85a31375004b4b03d9e6d70481c78f519324fd6e2f9f45f589b195c62c2970116a0498b3f99d12f48d5afedf69cad929",
          "sha256": "09445738ac0f8d8aaa53eb479fceca19a6519c43a89decaf7504828569b76dad",
          "sha1": "b8cf2a53033418b0035245772db83c058651f5a6",
          "md5": "3ee309e70a0b04d4d6167c6c2f425524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d9d1bd50e72bc339a1348fee86af42ae85a31375004b4b03d9e6d70481c78f519324fd6e2f9f45f589b195c62c2970116a0498b3f99d12f48d5afedf69cad929",
          "sha256": "09445738ac0f8d8aaa53eb479fceca19a6519c43a89decaf7504828569b76dad",
          "sha1": "b8cf2a53033418b0035245772db83c058651f5a6",
          "md5": "3ee309e70a0b04d4d6167c6c2f425524"
        }
      ]
    }
  ]
}
