{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5qc2seelwnhfhfiley3tculkta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "15a15dd9ea5abf7bb302ab20ca9de4cd4d9ba3112e26cd8339e2c27858e517ec1edd3a9b1bbca51d0b87ea9e16b041fc43f6d72b0a58594738d405c5bf410c2e",
          "sha256": "de96107636c7fe33cc5d75af17d9ef4a7b201cf8d8b443a1b210156f1e9750d8",
          "sha1": "cc98fe05cbc139e5ebe06a65124e2b6ce7443bb3",
          "md5": "b1612e046f8ad952979b08510feeec5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "15a15dd9ea5abf7bb302ab20ca9de4cd4d9ba3112e26cd8339e2c27858e517ec1edd3a9b1bbca51d0b87ea9e16b041fc43f6d72b0a58594738d405c5bf410c2e",
          "sha256": "de96107636c7fe33cc5d75af17d9ef4a7b201cf8d8b443a1b210156f1e9750d8",
          "sha1": "cc98fe05cbc139e5ebe06a65124e2b6ce7443bb3",
          "md5": "b1612e046f8ad952979b08510feeec5b"
        }
      ]
    }
  ]
}
