{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uhc6akxktvhrvmzhgrg4srjpwq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "c951ba35ece7865ea451c828663b654913687266a9fd6154db69c48a4a6240896f7466cb6058d671e0d2093e0a37446c43b32b5cc4504fdbe019176e18902b81",
          "sha256": "8c09a5db3182fd09db82b80665c94e3786e11fa391203f7afe06f7cd5319cdfd",
          "sha1": "6b504bf776450cc2ec1ecde9e2feb2596c5b4ba8",
          "md5": "cf0eb6e05f67cc74e489e0e903159503"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "c951ba35ece7865ea451c828663b654913687266a9fd6154db69c48a4a6240896f7466cb6058d671e0d2093e0a37446c43b32b5cc4504fdbe019176e18902b81",
          "sha256": "8c09a5db3182fd09db82b80665c94e3786e11fa391203f7afe06f7cd5319cdfd",
          "sha1": "6b504bf776450cc2ec1ecde9e2feb2596c5b4ba8",
          "md5": "cf0eb6e05f67cc74e489e0e903159503"
        }
      ]
    }
  ]
}
