{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lekq4a2gvbegjdbbjuo7f4rfey"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "038c054803b19bbd6b23108b38e5f91ed3f5053958215ac2b152c9755b9911f0c3751695546acd48dfe31ca8074cf664a3d6a880b9e19c1e685ddf815e2de6d6",
          "sha256": "93fd7af3079f5b27cd43e42efefcbe498c49ef4c13d88112a19b918c9f04866f",
          "sha1": "a187318478a57a401b7ae66b16d51a34cd15efd3",
          "md5": "79e0ee8355cf17434c231a46dffd4145"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "038c054803b19bbd6b23108b38e5f91ed3f5053958215ac2b152c9755b9911f0c3751695546acd48dfe31ca8074cf664a3d6a880b9e19c1e685ddf815e2de6d6",
          "sha256": "93fd7af3079f5b27cd43e42efefcbe498c49ef4c13d88112a19b918c9f04866f",
          "sha1": "a187318478a57a401b7ae66b16d51a34cd15efd3",
          "md5": "79e0ee8355cf17434c231a46dffd4145"
        }
      ]
    }
  ]
}
