{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.1-change-recordservice-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dsyetl2jarfqfakaqxyp3brncq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-change-recordservice-tests-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-change-recordservice-tests-SNAPSHOT.aar",
          "size": 44897,
          "sha512": "4a53d7b85b29eb041f8e04fa595fb684f9662876962abf82027065a0c9e0e00f37975fb3448288c6d5d7dd81f84309ad23b39e19cf8dfff0c3394c2d805e1897",
          "sha256": "ce7cbb9e168e46e5dd580ee3d9b8d038f7d4f8d57bf2d74b95ad2a49391aee88",
          "sha1": "0318d6cf388d08cfd5117b50b953f5c29739d60b",
          "md5": "b9b7a074945e6aa5e47ef1f7ffe28c95"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.1-change-recordservice-tests-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-change-recordservice-tests-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-change-recordservice-tests-SNAPSHOT.aar",
          "size": 44897,
          "sha512": "4a53d7b85b29eb041f8e04fa595fb684f9662876962abf82027065a0c9e0e00f37975fb3448288c6d5d7dd81f84309ad23b39e19cf8dfff0c3394c2d805e1897",
          "sha256": "ce7cbb9e168e46e5dd580ee3d9b8d038f7d4f8d57bf2d74b95ad2a49391aee88",
          "sha1": "0318d6cf388d08cfd5117b50b953f5c29739d60b",
          "md5": "b9b7a074945e6aa5e47ef1f7ffe28c95"
        }
      ]
    }
  ]
}
