{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3vphz7qalbcfflg7mvh6h6hpii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "1224d3cd7a393c31962cbfd9466cae76300312fb3b14ba86c5db2aa7b0031100ec28f183c3faec1f3c2131271b3786a945ee4cfb96fd0e0f7e1d8e4004dfcd8f",
          "sha256": "6435dc442008553b206b22567d0ddd45055751745282396ad640bdcae8bdb5ac",
          "sha1": "075b4772a0cb7c88f6b47956ef7255df384ca329",
          "md5": "962681877f3c17e0f4932f7cc86162fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "1224d3cd7a393c31962cbfd9466cae76300312fb3b14ba86c5db2aa7b0031100ec28f183c3faec1f3c2131271b3786a945ee4cfb96fd0e0f7e1d8e4004dfcd8f",
          "sha256": "6435dc442008553b206b22567d0ddd45055751745282396ad640bdcae8bdb5ac",
          "sha1": "075b4772a0cb7c88f6b47956ef7255df384ca329",
          "md5": "962681877f3c17e0f4932f7cc86162fe"
        }
      ]
    }
  ]
}
