{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4q5aidtacncpffnbb72gqh2uuu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "fd4fd6879b9ef7b3803676ed42c3e965f231125aeb47e717461824c6ee9a06c6144449973772bc9aecd84ae49fe36e8ae300aadee53a1a94b5af301cac33990c",
          "sha256": "f3aba00355ce5da7c00322696caf7771a0b1ed6375946bdb0bed81b19cba0aad",
          "sha1": "e52ae710f8509c4d937f64e77009eab8c450a754",
          "md5": "9fa35a76dc5557607c015b033824855f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "fd4fd6879b9ef7b3803676ed42c3e965f231125aeb47e717461824c6ee9a06c6144449973772bc9aecd84ae49fe36e8ae300aadee53a1a94b5af301cac33990c",
          "sha256": "f3aba00355ce5da7c00322696caf7771a0b1ed6375946bdb0bed81b19cba0aad",
          "sha1": "e52ae710f8509c4d937f64e77009eab8c450a754",
          "md5": "9fa35a76dc5557607c015b033824855f"
        }
      ]
    }
  ]
}
