{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-commkey-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7xpblakkrfamdmuu36e5rvf5g4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bb514cd597bde712ebfa59bf6d0e98ed1323359a5ff1eb2aa88e8f134cdfddd96aa61a874a58312e5e82ae4fab23f52dae2b87d8e57721adbea7a079bdd74f4a",
          "sha256": "6cf72ce48d8d24dc8fdfaa0036caef0264b7bdcc0f5a00fbd131f2048044cdeb",
          "sha1": "93e545790fcaa7d780833585672334b79e1e793c",
          "md5": "3be335c63e962aa949aa71cc2ebc45b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bb514cd597bde712ebfa59bf6d0e98ed1323359a5ff1eb2aa88e8f134cdfddd96aa61a874a58312e5e82ae4fab23f52dae2b87d8e57721adbea7a079bdd74f4a",
          "sha256": "6cf72ce48d8d24dc8fdfaa0036caef0264b7bdcc0f5a00fbd131f2048044cdeb",
          "sha1": "93e545790fcaa7d780833585672334b79e1e793c",
          "md5": "3be335c63e962aa949aa71cc2ebc45b2"
        }
      ]
    }
  ]
}
