{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-commkey-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e72iisdsbzcz7jfyookvsx672m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "686b941876fab7e2811e1669fd604b50e6b0a175dc578afbe241a92bafdf5fc8ac38832efd2e69f32108840cab5d7ea6488ad255245eb7de59b768ac2e873401",
          "sha256": "d76d91374b1feeb9b7b79c2b2806a4a8dbfd86df3856824a13b396c6bedefb4c",
          "sha1": "66a02ec3c3fe05e6f3516b1cde24c049af8bda0b",
          "md5": "8bae6c46f7cdd5fc6b3735ce02348a94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-commkey-response-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-commkey-response-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "686b941876fab7e2811e1669fd604b50e6b0a175dc578afbe241a92bafdf5fc8ac38832efd2e69f32108840cab5d7ea6488ad255245eb7de59b768ac2e873401",
          "sha256": "d76d91374b1feeb9b7b79c2b2806a4a8dbfd86df3856824a13b396c6bedefb4c",
          "sha1": "66a02ec3c3fe05e6f3516b1cde24c049af8bda0b",
          "md5": "8bae6c46f7cdd5fc6b3735ce02348a94"
        }
      ]
    }
  ]
}
