{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6d4fohjin5bthckban4ygjphc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 456011,
          "sha512": "4d655d15ffcfe8346cf08b821d6f857795bfb248257d33aa51663f6b97f03f2a24e06d9fafdd1fdbf1ab283428a399c912c5c6f389e4af29a6a272fd50a10e25",
          "sha256": "b72e1fddeb38288c9ce4531eca8c93e660a44d27563ae9f9f346207442206b77",
          "sha1": "819c7cf08ebea26fab01f35cd60959e1394842c5",
          "md5": "3fc1db3881339e56d59b701c5557cfe2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 456011,
          "sha512": "4d655d15ffcfe8346cf08b821d6f857795bfb248257d33aa51663f6b97f03f2a24e06d9fafdd1fdbf1ab283428a399c912c5c6f389e4af29a6a272fd50a10e25",
          "sha256": "b72e1fddeb38288c9ce4531eca8c93e660a44d27563ae9f9f346207442206b77",
          "sha1": "819c7cf08ebea26fab01f35cd60959e1394842c5",
          "md5": "3fc1db3881339e56d59b701c5557cfe2"
        }
      ]
    }
  ]
}
