{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-rc1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rjsjddkq7jedtpp5e4mwmjlrii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-rc1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-rc1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-rc1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bd039da9418b7f33da8f025a8cdfcf1f5bc379b3043a369b5aba1d331838c7c20269b985c777ad0564bd3973f246dd6641d94f34e6c496154dd105242d192208",
          "sha256": "7bdb996a7a6f7c95df9563a0df5a2ad740250e6e10146ebb07bd323001b53948",
          "sha1": "b8639462ab050532604fead06a5a07aa44db71c4",
          "md5": "9e9f8425191815862a3ec9eb8558cac6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-rc1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-rc1-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-rc1-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "bd039da9418b7f33da8f025a8cdfcf1f5bc379b3043a369b5aba1d331838c7c20269b985c777ad0564bd3973f246dd6641d94f34e6c496154dd105242d192208",
          "sha256": "7bdb996a7a6f7c95df9563a0df5a2ad740250e6e10146ebb07bd323001b53948",
          "sha1": "b8639462ab050532604fead06a5a07aa44db71c4",
          "md5": "9e9f8425191815862a3ec9eb8558cac6"
        }
      ]
    }
  ]
}
