{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-remove-bintray-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hau4h3odnfdqrd3kcmmfixmrqa"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-remove-bintray-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-remove-bintray-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-remove-bintray-SNAPSHOT.aar",
          "size": 44942,
          "sha512": "54db7257aeed0cd16004006d4cb1199601526d397e3cd89b8ac41090a324544aec6b4d533938be039b86e1bc080a7465df8e8901770fa7f727d1acfe2eeb1b65",
          "sha256": "aa6fe78f87bda5500594456a3eab97a50906fcec89b1ec550a710bf491a94bc1",
          "sha1": "16139a95a38e00077c13168267031dea284e746c",
          "md5": "8a9390c712c334d7f39094fbb5d68202"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-remove-bintray-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-remove-bintray-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-remove-bintray-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-remove-bintray-SNAPSHOT.aar",
          "size": 44942,
          "sha512": "54db7257aeed0cd16004006d4cb1199601526d397e3cd89b8ac41090a324544aec6b4d533938be039b86e1bc080a7465df8e8901770fa7f727d1acfe2eeb1b65",
          "sha256": "aa6fe78f87bda5500594456a3eab97a50906fcec89b1ec550a710bf491a94bc1",
          "sha1": "16139a95a38e00077c13168267031dea284e746c",
          "md5": "8a9390c712c334d7f39094fbb5d68202"
        }
      ]
    }
  ]
}
