{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-SNAPSHOT/fhir-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xftr3eusrba3tdotiwyvczzg3a"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2420755,
          "sha512": "c9358f6dd359b3b75a50796db4f960a0bfe045e03acbc46bcaeafb9c62d648188c17d66d09987504bee164ebd01088c6cc43bea245e902ed32c3e6c212df9163",
          "sha256": "ff010584e7d01ac2c1b34f6d33c4af1c041d35d2d0d8228e200b4480acd989d2",
          "sha1": "7baaf2c6995a540550a7aa2350a9ca831923f83a",
          "md5": "c744d0d571ea5bd39f9157b1cab80b58"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0-RC2"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2420755,
          "sha512": "c9358f6dd359b3b75a50796db4f960a0bfe045e03acbc46bcaeafb9c62d648188c17d66d09987504bee164ebd01088c6cc43bea245e902ed32c3e6c212df9163",
          "sha256": "ff010584e7d01ac2c1b34f6d33c4af1c041d35d2d0d8228e200b4480acd989d2",
          "sha1": "7baaf2c6995a540550a7aa2350a9ca831923f83a",
          "md5": "c744d0d571ea5bd39f9157b1cab80b58"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-SNAPSHOT/fhir-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
