{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-SNAPSHOT/fhir-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "4yc4riux5nbvlpniqyv2cq5qey"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2431017,
          "sha512": "11183cd971e1e68d301c6417a0b9d4102f941bcfb227dbf5ef40ff88f0b633de41b009c355a988f71accf77d17a19dde6b016d2e57aa64205633bdf13372df52",
          "sha256": "c879a1c42c32863603a3f19f0dd7105acf9190cdbd967865ea96da5ba5933dd4",
          "sha1": "ac7ff81e5247da43394e0a80f6b72c99066066bd",
          "md5": "557bdf7161ad97151f2e060c1bc12c87"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2431017,
          "sha512": "11183cd971e1e68d301c6417a0b9d4102f941bcfb227dbf5ef40ff88f0b633de41b009c355a988f71accf77d17a19dde6b016d2e57aa64205633bdf13372df52",
          "sha256": "c879a1c42c32863603a3f19f0dd7105acf9190cdbd967865ea96da5ba5933dd4",
          "sha1": "ac7ff81e5247da43394e0a80f6b72c99066066bd",
          "md5": "557bdf7161ad97151f2e060c1bc12c87"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-SNAPSHOT/fhir-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
