{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-SNAPSHOT/fhir-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "4j2abjl35bdu7ojo5psb4jrtoe"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2364195,
          "sha512": "3a655bcabcc766a21b19a22e0af623b5398dca731d5fd2202b69f61502b5a94487ee68ca94409971e12706bdc10f6ab0a08e6f8a754236b4cef202abffcccca3",
          "sha256": "8bc0d54eb68bfaefd8dd22f215a3882c24dbf2375277bc943c51759bf3815fdd",
          "sha1": "43e0b17614b0eee1e08be3597903cd94ab1192b4",
          "md5": "920bc04314314e4c132b13fd2d7c78a6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2364195,
          "sha512": "3a655bcabcc766a21b19a22e0af623b5398dca731d5fd2202b69f61502b5a94487ee68ca94409971e12706bdc10f6ab0a08e6f8a754236b4cef202abffcccca3",
          "sha256": "8bc0d54eb68bfaefd8dd22f215a3882c24dbf2375277bc943c51759bf3815fdd",
          "sha1": "43e0b17614b0eee1e08be3597903cd94ab1192b4",
          "md5": "920bc04314314e4c132b13fd2d7c78a6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-SNAPSHOT/fhir-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
