{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-SNAPSHOT/fhir-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "ezvdh57o4zdqnjlph6ko7xzgre"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2405599,
          "sha512": "625f3ea58c6560a7e3a607ed1affa313ff1698d4e0349e2c52bf39de2621c28307a3d64f046feab7263e0d60bfcb82309319370a6ecdabcf2a95eef6abd10f3f",
          "sha256": "faf440dd14d90c1a97f2cfa643c853d3e0460ab854a30756c64e30e342a471b3",
          "sha1": "bc0750c06a7ad12b611ff1c14c015e893e2c218c",
          "md5": "91258c0c665a59f48303c17798f917c2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-SNAPSHOT.jar",
          "size": 2405599,
          "sha512": "625f3ea58c6560a7e3a607ed1affa313ff1698d4e0349e2c52bf39de2621c28307a3d64f046feab7263e0d60bfcb82309319370a6ecdabcf2a95eef6abd10f3f",
          "sha256": "faf440dd14d90c1a97f2cfa643c853d3e0460ab854a30756c64e30e342a471b3",
          "sha1": "bc0750c06a7ad12b611ff1c14c015e893e2c218c",
          "md5": "91258c0c665a59f48303c17798f917c2"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-SNAPSHOT/fhir-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
