{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "or57dccynrfj7i3n64cav5czii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 445746,
          "sha512": "88e219e7cdd8b4285150cf3283c258f346e22c56b539ef55d08f6cd7e1dc7ba0070573fbfeec01d56c6ee730191fe11ee3f83f5f9241cf3df0f170aefcbec166",
          "sha256": "4ec280e06a4c3759fccf6775cddd66113b508a81cdaa31dd2d7063c4bd9f567d",
          "sha1": "45afbdb24081b0b73c13b34e7671548c393d82f5",
          "md5": "984718cf8e8d694e6d0905f8b4aebdf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 445746,
          "sha512": "88e219e7cdd8b4285150cf3283c258f346e22c56b539ef55d08f6cd7e1dc7ba0070573fbfeec01d56c6ee730191fe11ee3f83f5f9241cf3df0f170aefcbec166",
          "sha256": "4ec280e06a4c3759fccf6775cddd66113b508a81cdaa31dd2d7063c4bd9f567d",
          "sha1": "45afbdb24081b0b73c13b34e7671548c393d82f5",
          "md5": "984718cf8e8d694e6d0905f8b4aebdf2"
        }
      ]
    }
  ]
}
