{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-change-network-model-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qiqytyzdpzgi7kdggmyetgjnlu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "b4016cc67ccb2546c6e610351711b4d2a019ff998448a96cb0d3a41af7a32ba8bcbc53d17ca54ea73996c0703be347827f675e0e3d78cfffc0cad3b70fc32582",
          "sha256": "5b862b8e4a364f6bc982509e3c6b92f361a912df60a3356d3bb4def19b0ac418",
          "sha1": "60960ee9d0ace23cfdad82307cfd89bc60bc1f8b",
          "md5": "768d81c995391836d42f7c10d064b1fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-network-model-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "b4016cc67ccb2546c6e610351711b4d2a019ff998448a96cb0d3a41af7a32ba8bcbc53d17ca54ea73996c0703be347827f675e0e3d78cfffc0cad3b70fc32582",
          "sha256": "5b862b8e4a364f6bc982509e3c6b92f361a912df60a3356d3bb4def19b0ac418",
          "sha1": "60960ee9d0ace23cfdad82307cfd89bc60bc1f8b",
          "md5": "768d81c995391836d42f7c10d064b1fe"
        }
      ]
    }
  ]
}
