{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xhjn3mq3z5fb3ch22v4a32lkse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0db93ed6d12d8e88dc52a3c81b11f986c76f41fb6dcd79eace92eb3f2568c112b77c5b77514cd1e73d57b004d14a647fc87baf9fe4ad0165e745405cbc338e00",
          "sha256": "7006320ff93651e5b1e609f2c0da84088ffa89ba4fe8a909301de38d7ba1f162",
          "sha1": "2b21b9055546c609d7a0ed987dadaf2d88e9c253",
          "md5": "7ee780afdcea9b4456643c5494e7066f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0db93ed6d12d8e88dc52a3c81b11f986c76f41fb6dcd79eace92eb3f2568c112b77c5b77514cd1e73d57b004d14a647fc87baf9fe4ad0165e745405cbc338e00",
          "sha256": "7006320ff93651e5b1e609f2c0da84088ffa89ba4fe8a909301de38d7ba1f162",
          "sha1": "2b21b9055546c609d7a0ed987dadaf2d88e9c253",
          "md5": "7ee780afdcea9b4456643c5494e7066f"
        }
      ]
    }
  ]
}
