{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "chzn6qecbjbffgrbc333qtrp74"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "3796eff75a63c85e4c645df2d217b0fe35a4637b0024e60a82302997f50ea31c656e5183707baa664fdbabe479767780db4b615b23fc3b59d23c06dcbfde3180",
          "sha256": "1741a4437fd6dacb854ba838cc44e7f43a2a3df9df31c101054c1796e6a7819f",
          "sha1": "090269e266162b288e2525fae1f28cea6f0604c3",
          "md5": "63cb059c3cb31049427e57981ff89308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "3796eff75a63c85e4c645df2d217b0fe35a4637b0024e60a82302997f50ea31c656e5183707baa664fdbabe479767780db4b615b23fc3b59d23c06dcbfde3180",
          "sha256": "1741a4437fd6dacb854ba838cc44e7f43a2a3df9df31c101054c1796e6a7819f",
          "sha1": "090269e266162b288e2525fae1f28cea6f0604c3",
          "md5": "63cb059c3cb31049427e57981ff89308"
        }
      ]
    }
  ]
}
