{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-change-versioning-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nlqi4dpq5baftgemygj3kxgg5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "8aa9d0ed8efa4ba896e74f3089eb0b818b0c2f2ae989fe15941205d7366d12cf196914c0cb27bd6ca0734bf1ad9b38d11d2be550b420470b675f0b53a51dc0ab",
          "sha256": "6f3a92462ff347285baf4f58038130f4372d92da808594295824f1aad8056c04",
          "sha1": "1ff2448f31e82a43c6516d2fe627404988628a3c",
          "md5": "acdf49feac9e6e1859fd3833596a3290"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-versioning-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "8aa9d0ed8efa4ba896e74f3089eb0b818b0c2f2ae989fe15941205d7366d12cf196914c0cb27bd6ca0734bf1ad9b38d11d2be550b420470b675f0b53a51dc0ab",
          "sha256": "6f3a92462ff347285baf4f58038130f4372d92da808594295824f1aad8056c04",
          "sha1": "1ff2448f31e82a43c6516d2fe627404988628a3c",
          "md5": "acdf49feac9e6e1859fd3833596a3290"
        }
      ]
    }
  ]
}
