{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rvovbq3pwvbtnj5kvmy6irbkf4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "aaffde7410eb4677a801a2a8d34cb11e3a52c7ba66e9667fea85909050b41895ff9fdd5ea853e904d725d8eef77ca9da7604f8e2f22e114d6b751281e5adf156",
          "sha256": "9e5668821725a38387c6f128f79bd11c9a2796f8f7ee92915b08b446ffc19f27",
          "sha1": "997c4413127eaad0243bfeb4b7b2097c8eeaa298",
          "md5": "d35246a363bdc1b9373390eb1fb35800"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "aaffde7410eb4677a801a2a8d34cb11e3a52c7ba66e9667fea85909050b41895ff9fdd5ea853e904d725d8eef77ca9da7604f8e2f22e114d6b751281e5adf156",
          "sha256": "9e5668821725a38387c6f128f79bd11c9a2796f8f7ee92915b08b446ffc19f27",
          "sha1": "997c4413127eaad0243bfeb4b7b2097c8eeaa298",
          "md5": "d35246a363bdc1b9373390eb1fb35800"
        }
      ]
    }
  ]
}
