{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qcpriuiqafbnpdb6dk66lvkknm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "87277941399fddc84d0cb1ffe3b065c92352daea3f1804acaf2ee3a5d5b27e037a985d8f06df7ca9b0ae762c039c0614ab2755b30f25e37787e0966b4cbd24c0",
          "sha256": "56eaec4b8cee605b363be9327e45c519517edbae49359cde676787ab8a23b039",
          "sha1": "cadb68e3dabf34b36c788658a4cd66d981f52db4",
          "md5": "8810ca4d73fd49ad25c5cc07ae6a538d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "87277941399fddc84d0cb1ffe3b065c92352daea3f1804acaf2ee3a5d5b27e037a985d8f06df7ca9b0ae762c039c0614ab2755b30f25e37787e0966b4cbd24c0",
          "sha256": "56eaec4b8cee605b363be9327e45c519517edbae49359cde676787ab8a23b039",
          "sha1": "cadb68e3dabf34b36c788658a4cd66d981f52db4",
          "md5": "8810ca4d73fd49ad25c5cc07ae6a538d"
        }
      ]
    }
  ]
}
