{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zkxoh34wznbunau4vjop3pk6dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "9abe2fb03fc5c6f9b6d5c92386d43b394279448e3c962e0f05565eda43d3bccb75dc2ee0f57ec066005b0ee5a09ce31d2d8ad467ac2383c169f8256be760a2c8",
          "sha256": "5e3cfd7758b4d0614da375efdd323ee7d74b09ba52a8e473bfa329cf39856d84",
          "sha1": "87b0e351c66eb6fc2cd63a3a6c1edeb5d47f9850",
          "md5": "b4fcc7b6282af6748cacaeed0c71831e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "9abe2fb03fc5c6f9b6d5c92386d43b394279448e3c962e0f05565eda43d3bccb75dc2ee0f57ec066005b0ee5a09ce31d2d8ad467ac2383c169f8256be760a2c8",
          "sha256": "5e3cfd7758b4d0614da375efdd323ee7d74b09ba52a8e473bfa329cf39856d84",
          "sha1": "87b0e351c66eb6fc2cd63a3a6c1edeb5d47f9850",
          "md5": "b4fcc7b6282af6748cacaeed0c71831e"
        }
      ]
    }
  ]
}
