{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hnv2ozbnlbhspbndxpgesli6yy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "57abdfef36c0542c671c5e049c40b0028c91f5a9ae4531812257a616e1982315fa88ab717e066781ef0aec9122bafb621b3fac9ec7366c49d6f480fca55faf22",
          "sha256": "3655587a7dd687353ab62673afabd0dd699dc6157a46f820af7351dd298417f1",
          "sha1": "d625455a764636dce44a72921179fcc04f5f3553",
          "md5": "70ec0b5022d1df0804894200054fc3ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "57abdfef36c0542c671c5e049c40b0028c91f5a9ae4531812257a616e1982315fa88ab717e066781ef0aec9122bafb621b3fac9ec7366c49d6f480fca55faf22",
          "sha256": "3655587a7dd687353ab62673afabd0dd699dc6157a46f820af7351dd298417f1",
          "sha1": "d625455a764636dce44a72921179fcc04f5f3553",
          "md5": "70ec0b5022d1df0804894200054fc3ff"
        }
      ]
    }
  ]
}
