{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-change-wrapper-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wqbcb6m6vjak7i7yto6btu5lzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "0dfe76a2c1aa939fe7733090e9c3358d8b78e34297b6efcf7f548c6239c6a3da11fb61282ccc2a58affd05e00c702f72f1a70843ed185064c0253561b2eb8b31",
          "sha256": "f99dae8991e5f34fc3360e6715a2b64c788eb665819693704740b50fe5953290",
          "sha1": "94655de4887723b3da36327ff34eba23dff9b989",
          "md5": "61adccc4327ecf9e446fc510624848eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "0dfe76a2c1aa939fe7733090e9c3358d8b78e34297b6efcf7f548c6239c6a3da11fb61282ccc2a58affd05e00c702f72f1a70843ed185064c0253561b2eb8b31",
          "sha256": "f99dae8991e5f34fc3360e6715a2b64c788eb665819693704740b50fe5953290",
          "sha1": "94655de4887723b3da36327ff34eba23dff9b989",
          "md5": "61adccc4327ecf9e446fc510624848eb"
        }
      ]
    }
  ]
}
