{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.2-change-record-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lcqrjaa6hfc77mz3hwe4kgmlvi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-record-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.2-change-record-service-SNAPSHOT.aar",
          "url": "securestore-android-1.9.2-change-record-service-SNAPSHOT.aar",
          "size": 41916,
          "sha512": "1955bfd4a5540ac67f1310e76539eacf400b94b408c59b71690ffc7b04b910482985ec9ba6d3bca176ad7fb7f29b43bfbe4827a09e0ffe3191cd6a70fce5e496",
          "sha256": "28e5df0dba70bd6b6f7f25385b2bf4a5ecf7e569ab0618437673eadf87fd4491",
          "sha1": "d4084235af9aef347f7f4e5068790195248aa1ec",
          "md5": "9b46a6a210af3b67e74d7def2867ed52"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-record-service-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.2-change-record-service-SNAPSHOT.aar",
          "url": "securestore-android-1.9.2-change-record-service-SNAPSHOT.aar",
          "size": 41916,
          "sha512": "1955bfd4a5540ac67f1310e76539eacf400b94b408c59b71690ffc7b04b910482985ec9ba6d3bca176ad7fb7f29b43bfbe4827a09e0ffe3191cd6a70fce5e496",
          "sha256": "28e5df0dba70bd6b6f7f25385b2bf4a5ecf7e569ab0618437673eadf87fd4491",
          "sha1": "d4084235af9aef347f7f4e5068790195248aa1ec",
          "md5": "9b46a6a210af3b67e74d7def2867ed52"
        }
      ]
    }
  ]
}
