{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-jvm/0.0.1-add-fhir-primitives-number-support-SNAPSHOT/fhir-jvm-0.0.1-add-fhir-primitives-number-support-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir-jvm",
    "version": "0.0.1-add-fhir-primitives-number-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "gwchk4kcqjagtjpjwydv5kt52e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "fhir-metadata-0.0.1-add-fhir-primitives-number-support-SNAPSHOT.jar",
          "url": "fhir-metadata-0.0.1-add-fhir-primitives-number-support-SNAPSHOT.jar",
          "size": 500231,
          "sha512": "4d86477a77354c4b63d4d046c510c1e277b01b43476aeaeca11d452bc0d6735a7dd419c567723e54a2ecd73378545b0030e7e5d2543cbe0ba4dd759c526e14ec",
          "sha256": "13e947739035a424acea9bd47ce638f3b341c9ad3130607c5c59a1c984c2d0ed",
          "sha1": "bfbb35bb6c15cf2a4a9b5c53017ccfb0ebf4b3d7",
          "md5": "393fad529079dc82a343763f2748d246"
        }
      ]
    }
  ]
}
