{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-add-fhir4-download-record-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yz3pmnwyq5etxpjz2z3357s7xu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "a6ba0676885a354c945df454706adedb63ef1a16869a04b0ca3bd4e3fc7c382669b26d1183f75dd08d6aaed51a0e35e03a9f819cb0e0d167a2bed1798c0caf92",
          "sha256": "89ecd26081ef1977401c82241c05ebed45684364e594d2a3b8e0d22677fde134",
          "sha1": "d06d2b84ca5a47c89f865c29c58fd7a7d663cf13",
          "md5": "08c83bfcd8b7fb2f9886d3ab8c271b67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-fhir4-download-record-support-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "a6ba0676885a354c945df454706adedb63ef1a16869a04b0ca3bd4e3fc7c382669b26d1183f75dd08d6aaed51a0e35e03a9f819cb0e0d167a2bed1798c0caf92",
          "sha256": "89ecd26081ef1977401c82241c05ebed45684364e594d2a3b8e0d22677fde134",
          "sha1": "d06d2b84ca5a47c89f865c29c58fd7a7d663cf13",
          "md5": "08c83bfcd8b7fb2f9886d3ab8c271b67"
        }
      ]
    }
  ]
}
