{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jaop2jc4tfej7kxvvv6ulzacdu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "5c9986fb8a62a6305026deffc593703c1680cc8ffa388006897624bbda9ed823263c8b58b9813b62d9161ed93855b80ae9158bb4246575af6ade5a9fbc51d9d2",
          "sha256": "d11a25fb5d4a0d3b10a048e6dc5199dbc8deb5e73212b10a03e9a4c5cefa9fb9",
          "sha1": "fe0c05c4334e2252cfd4cccdf65bbbd15de6049e",
          "md5": "33de19376e5a0155bf378ff4760fdafc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "5c9986fb8a62a6305026deffc593703c1680cc8ffa388006897624bbda9ed823263c8b58b9813b62d9161ed93855b80ae9158bb4246575af6ade5a9fbc51d9d2",
          "sha256": "d11a25fb5d4a0d3b10a048e6dc5199dbc8deb5e73212b10a03e9a4c5cefa9fb9",
          "sha1": "fe0c05c4334e2252cfd4cccdf65bbbd15de6049e",
          "md5": "33de19376e5a0155bf378ff4760fdafc"
        }
      ]
    }
  ]
}
