{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.5.0-SNAPSHOT/fhir-helper-1.5.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bd2wk2wgtnf47i33zx6rehyolu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113469,
          "sha512": "e96f5fd30e24bcfe8cdb8f9da4be13ea45ab9fdbba07b88464feb7fdb289c3faf2202c399e1d6b733e337b65cec14ec11d3706bf4caa6db298ad22860b666f21",
          "sha256": "85d3f45208e6fddd22c978ba2b91808bf1a423251f7f2bb6034992ff9e0c11a1",
          "sha1": "8345882bb1196d6be58b4611dc186290862710e5",
          "md5": "bc503dfa9b00b0c054f722146c600ff9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113469,
          "sha512": "e96f5fd30e24bcfe8cdb8f9da4be13ea45ab9fdbba07b88464feb7fdb289c3faf2202c399e1d6b733e337b65cec14ec11d3706bf4caa6db298ad22860b666f21",
          "sha256": "85d3f45208e6fddd22c978ba2b91808bf1a423251f7f2bb6034992ff9e0c11a1",
          "sha1": "8345882bb1196d6be58b4611dc186290862710e5",
          "md5": "bc503dfa9b00b0c054f722146c600ff9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.5.0-SNAPSHOT/fhir-helper-metadata-1.5.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
