{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir-helper/1.5.0-SNAPSHOT/fhir-helper-1.5.0-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-helper-sdk-kmp",
    "module": "fhir-helper",
    "version": "1.5.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rjcgjaz3yfe6td4rvxjvlkqrc4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "hc-fhir-sdk-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113469,
          "sha512": "e9ea3585c07c2b976127bb882a9c890794cdcde3fd6c3e74f14261c1ca0ee5ccedecfa86c50dec4ab7e07e44a47f862524fcef7791854a27ba351834edbab857",
          "sha256": "740ea65a7d59dcef8ea13bae644f7302c57183eab76aba935fa7dfee8a263dfe",
          "sha1": "a0805be4650ed6537c49781c76b63c13ad18832a",
          "md5": "ae148bb7b5bf9980eebe5a4695fe78f9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "hc-fhir-sdk-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "url": "fhir-helper-jvm-1.5.0-SNAPSHOT.jar",
          "size": 113469,
          "sha512": "e9ea3585c07c2b976127bb882a9c890794cdcde3fd6c3e74f14261c1ca0ee5ccedecfa86c50dec4ab7e07e44a47f862524fcef7791854a27ba351834edbab857",
          "sha256": "740ea65a7d59dcef8ea13bae644f7302c57183eab76aba935fa7dfee8a263dfe",
          "sha1": "a0805be4650ed6537c49781c76b63c13ad18832a",
          "md5": "ae148bb7b5bf9980eebe5a4695fe78f9"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-helper-metadata/1.5.0-SNAPSHOT/fhir-helper-metadata-1.5.0-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-helper-sdk-kmp",
        "module": "fhir-helper-metadata",
        "version": "1.5.0-SNAPSHOT"
      }
    }
  ]
}
