{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.1-change-recordservice-countrecords-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g73b6zjoifec5cyzqrtbdhgyta"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-countrecords-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-change-recordservice-countrecords-tests-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-change-recordservice-countrecords-tests-SNAPSHOT.aar",
          "size": 41927,
          "sha512": "f853d44588e637a2abdbdb6bd3eaed038f9cbe683add78fe78743aaf5c8f6f553246ec105b05215eeec7b90e8f04221a4ac46228d1bee98efc2519cecdb3a159",
          "sha256": "fba7f8e494ac98eb079925fd5d9f857710b7e245dd913a13ecdefad7868ddaf6",
          "sha1": "a6118f36bdee69518cb6beadb4ba90928bd0da3c",
          "md5": "6c0813bde5f7638a9f954cff51f24e3c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-countrecords-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-change-recordservice-countrecords-tests-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-change-recordservice-countrecords-tests-SNAPSHOT.aar",
          "size": 41927,
          "sha512": "f853d44588e637a2abdbdb6bd3eaed038f9cbe683add78fe78743aaf5c8f6f553246ec105b05215eeec7b90e8f04221a4ac46228d1bee98efc2519cecdb3a159",
          "sha256": "fba7f8e494ac98eb079925fd5d9f857710b7e245dd913a13ecdefad7868ddaf6",
          "sha1": "a6118f36bdee69518cb6beadb4ba90928bd0da3c",
          "md5": "6c0813bde5f7638a9f954cff51f24e3c"
        }
      ]
    }
  ]
}
