{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jg7tjokwergndhbbp4w6ryopxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d0e24ab25f0689f8ecd0f616127ae151b98607a283264a401ec8ec2d2e65d650155b84c396dc1cbb36ef48d5d216c4ddf78aedc5b35565383d3ac1876c9f80e7",
          "sha256": "0beb022ae567e47cea064f943b80944ec7f8986077fafa81cf834a51a9e9a621",
          "sha1": "67f40f38118e0b4f543b366f17352a6e97d744ca",
          "md5": "e4b31809f5fd850b88a6393ca4887a9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d0e24ab25f0689f8ecd0f616127ae151b98607a283264a401ec8ec2d2e65d650155b84c396dc1cbb36ef48d5d216c4ddf78aedc5b35565383d3ac1876c9f80e7",
          "sha256": "0beb022ae567e47cea064f943b80944ec7f8986077fafa81cf834a51a9e9a621",
          "sha1": "67f40f38118e0b4f543b366f17352a6e97d744ca",
          "md5": "e4b31809f5fd850b88a6393ca4887a9d"
        }
      ]
    }
  ]
}
