{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "d5y5vfqtl5gp5ecerwsgh5sphi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "54d2f271c640ebc6c8ba297a2a1e7d6593eed86476e97dbf963b12eb16339474590fca277c3c65c1d324d706e0bf2894a51ce89a81d37a863716a61c9c5c74f3",
          "sha256": "3935b68576d6f755233251e98ae8e4c16328ede18106c9a522e33ca42f733bc4",
          "sha1": "65bf1177802bc5b3214cc91f44b6bded5ceae4a9",
          "md5": "469e1a7308f55452606c2408df839903"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "54d2f271c640ebc6c8ba297a2a1e7d6593eed86476e97dbf963b12eb16339474590fca277c3c65c1d324d706e0bf2894a51ce89a81d37a863716a61c9c5c74f3",
          "sha256": "3935b68576d6f755233251e98ae8e4c16328ede18106c9a522e33ca42f733bc4",
          "sha1": "65bf1177802bc5b3214cc91f44b6bded5ceae4a9",
          "md5": "469e1a7308f55452606c2408df839903"
        }
      ]
    }
  ]
}
