{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "imzeqhalfzfrdk3qxsrewgyble"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8093792fdb99530260d0a8f0c8493c65accc358f63929247907fa6c5d3b647f4af38a86014eb7969921dc7ae52123849189a0423b973df16b3fcc39555f8b20d",
          "sha256": "68fbb55ba8b1ac21ddf29be1c6aa746f508d44a8dc62c8592540dd574e8f743a",
          "sha1": "92da6e13b68305a4eaba4a2c283752e7dfc2d562",
          "md5": "023f95c6ed9fbfe4406770ce2e2853b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8093792fdb99530260d0a8f0c8493c65accc358f63929247907fa6c5d3b647f4af38a86014eb7969921dc7ae52123849189a0423b973df16b3fcc39555f8b20d",
          "sha256": "68fbb55ba8b1ac21ddf29be1c6aa746f508d44a8dc62c8592540dd574e8f743a",
          "sha1": "92da6e13b68305a4eaba4a2c283752e7dfc2d562",
          "md5": "023f95c6ed9fbfe4406770ce2e2853b5"
        }
      ]
    }
  ]
}
