{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hpq2qaxruvaxflkm3famdi3qq4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "3ee8c14df5624c908eca7615612bf4e58f8ae84789f6c1eba0dff72f7c66cc852142ad3f21204a9d69a807fc11bf042a4cd1b099584518a42ee0ae949a284077",
          "sha256": "0ee45ec82bb2192f4b53f42714017b4a81380fb89e5da443eafa4fb18f07d16d",
          "sha1": "70965a2960bf27b266629b7ca3930aa23ec71de8",
          "md5": "c6d540b31fdcd707ffc8247ebceb7f51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "3ee8c14df5624c908eca7615612bf4e58f8ae84789f6c1eba0dff72f7c66cc852142ad3f21204a9d69a807fc11bf042a4cd1b099584518a42ee0ae949a284077",
          "sha256": "0ee45ec82bb2192f4b53f42714017b4a81380fb89e5da443eafa4fb18f07d16d",
          "sha1": "70965a2960bf27b266629b7ca3930aa23ec71de8",
          "md5": "c6d540b31fdcd707ffc8247ebceb7f51"
        }
      ]
    }
  ]
}
