{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sz3r3xffkfbm7h4fijct73k7fm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "8692a125119d7457ddef8510df9da2db73c99cc8283b380335267c0241f6d58a00bf461762874db2706041febedc6a2154c9503fb96998d6dbf9b7b8116870de",
          "sha256": "071bb08ac70a7e991249840f4a503b5b325153c0508285ea91f7920cee6b447c",
          "sha1": "b9f55f633a788ee93bd7dad4cc20004e92f96e69",
          "md5": "b6b50a4a7aa08b8a6a4c8fa149e703f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "8692a125119d7457ddef8510df9da2db73c99cc8283b380335267c0241f6d58a00bf461762874db2706041febedc6a2154c9503fb96998d6dbf9b7b8116870de",
          "sha256": "071bb08ac70a7e991249840f4a503b5b325153c0508285ea91f7920cee6b447c",
          "sha1": "b9f55f633a788ee93bd7dad4cc20004e92f96e69",
          "md5": "b6b50a4a7aa08b8a6a4c8fa149e703f0"
        }
      ]
    }
  ]
}
