{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-readme-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gq43aegte5fsjkx5s4p5dw7vzi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "cca5a816c5fd1d0253da6bca1f646046074ea476e87999dccd4aab78ff72ce0a205b918eaa5507d48b176b1f0a7c2b290360415cb9d1f8ced71ca283a3437c88",
          "sha256": "5353c75b9e4b05cccb2d2d15ed4e7e580c8d5063139b41f8b1a5fe8fd923210e",
          "sha1": "e1093fc0c7028604b2fbfa75f9919037ad69c667",
          "md5": "b1e363dcccd7baa411b95adbb2e3235d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-readme-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "cca5a816c5fd1d0253da6bca1f646046074ea476e87999dccd4aab78ff72ce0a205b918eaa5507d48b176b1f0a7c2b290360415cb9d1f8ced71ca283a3437c88",
          "sha256": "5353c75b9e4b05cccb2d2d15ed4e7e580c8d5063139b41f8b1a5fe8fd923210e",
          "sha1": "e1093fc0c7028604b2fbfa75f9919037ad69c667",
          "md5": "b1e363dcccd7baa411b95adbb2e3235d"
        }
      ]
    }
  ]
}
