{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-readme-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qhsmuqmh7rfdzfk3s4odl6a5ci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "a95ef77a581c975e6d7a74d0af5a4a425af74cfba1cf1c2045bc93aefa5a378ee3cdc8687529cf69d09b7cf2df70735880ea09b95149eada1efa43f703ab45ae",
          "sha256": "0d71e75a39b72b442a8934207976df11a575c6e1fe70ba3b55cd3ef425f9c002",
          "sha1": "e3ad606964fa36c706c261683f88fd3a855b26e5",
          "md5": "9714d60655518d3d78ce67937d42e262"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-readme-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-readme-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "a95ef77a581c975e6d7a74d0af5a4a425af74cfba1cf1c2045bc93aefa5a378ee3cdc8687529cf69d09b7cf2df70735880ea09b95149eada1efa43f703ab45ae",
          "sha256": "0d71e75a39b72b442a8934207976df11a575c6e1fe70ba3b55cd3ef425f9c002",
          "sha1": "e3ad606964fa36c706c261683f88fd3a855b26e5",
          "md5": "9714d60655518d3d78ce67937d42e262"
        }
      ]
    }
  ]
}
