{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pljt23c73fbfbcvqonbftgc4t4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "ac0d5e16033642e0ef892036615deecba09899a0119e890f2c1f8c3741ebf6e5cf59046bd7fa77ca2755fa5e337e5375d035ea48016637125665bebb34d67416",
          "sha256": "97d8cc82aee90f7c0f74b2b48dec2b1ffc928122b525d491f3e68aee1f576372",
          "sha1": "a36e20cd8b78249dda48db5707860cfea458e382",
          "md5": "0a4cd38a3dda99ecec51f4794e627562"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "ac0d5e16033642e0ef892036615deecba09899a0119e890f2c1f8c3741ebf6e5cf59046bd7fa77ca2755fa5e337e5375d035ea48016637125665bebb34d67416",
          "sha256": "97d8cc82aee90f7c0f74b2b48dec2b1ffc928122b525d491f3e68aee1f576372",
          "sha1": "a36e20cd8b78249dda48db5707860cfea458e382",
          "md5": "0a4cd38a3dda99ecec51f4794e627562"
        }
      ]
    }
  ]
}
