{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-tags-and-annotations-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wpmpnmkxcfhjdardqdbyexbrda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "0e61018b86fe0eddf83c85f1467e10c1c8c2561bf4b5fa7650072f119471b366ab1f60f6e9dfe03f5b1bc885900f3f9ee0a2f329b479b6d525383e71bd6ba7c8",
          "sha256": "ca920ebce198b2365c11f9a108f5f04b44d5d538de2083c626cf653c7fdc5a6b",
          "sha1": "61f5d1f99a23adcb929cbb3c45d495bc25f27d23",
          "md5": "94e374d1d4d9b71f3032feb3fdbd5520"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "0e61018b86fe0eddf83c85f1467e10c1c8c2561bf4b5fa7650072f119471b366ab1f60f6e9dfe03f5b1bc885900f3f9ee0a2f329b479b6d525383e71bd6ba7c8",
          "sha256": "ca920ebce198b2365c11f9a108f5f04b44d5d538de2083c626cf653c7fdc5a6b",
          "sha1": "61f5d1f99a23adcb929cbb3c45d495bc25f27d23",
          "md5": "94e374d1d4d9b71f3032feb3fdbd5520"
        }
      ]
    }
  ]
}
