{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sz3r3xffkfbm7h4fijct73k7fm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "url": "securestore-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "size": 41927,
          "sha512": "2a0fe403dcdd259c731f5f1c496c697dab0ab4018412b1e75ddfd98d9727f98cb1611dccd9eeea115615398cd4a6f2bf5321d82c2a1ecf4b5e56100652022c3a",
          "sha256": "ab3f18236f11a7c714c1f9d9a1332fbe60fba00365417d7a41669c94a039f7a2",
          "sha1": "34cd13427e66c0c32ae3ee34cb8f9d14a489382b",
          "md5": "c2fa0349e51055006a8d2b7380c255cf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "url": "securestore-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "size": 41927,
          "sha512": "2a0fe403dcdd259c731f5f1c496c697dab0ab4018412b1e75ddfd98d9727f98cb1611dccd9eeea115615398cd4a6f2bf5321d82c2a1ecf4b5e56100652022c3a",
          "sha256": "ab3f18236f11a7c714c1f9d9a1332fbe60fba00365417d7a41669c94a039f7a2",
          "sha1": "34cd13427e66c0c32ae3ee34cb8f9d14a489382b",
          "md5": "c2fa0349e51055006a8d2b7380c255cf"
        }
      ]
    }
  ]
}
