{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "n22v6nixsvaphf4sksikff2phq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d5adfa79ab4840e0eb1bacb05f09dbb0be76328d61150b3226a4027bf3cf18d84b25b2dd7408bf5e6ad603f5a42c9fefab2b38e0aa14405ed5ad9f20d40c8731",
          "sha256": "5152b489f5b1c74182c7b316a6534443efa8cb57652525f8409dc277107828ed",
          "sha1": "2d6c3bb5b15b01f279063b617af9e347aaa15ad6",
          "md5": "5bc2cf4c04233e30600dcf9688b3cead"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d5adfa79ab4840e0eb1bacb05f09dbb0be76328d61150b3226a4027bf3cf18d84b25b2dd7408bf5e6ad603f5a42c9fefab2b38e0aa14405ed5ad9f20d40c8731",
          "sha256": "5152b489f5b1c74182c7b316a6534443efa8cb57652525f8409dc277107828ed",
          "sha1": "2d6c3bb5b15b01f279063b617af9e347aaa15ad6",
          "md5": "5bc2cf4c04233e30600dcf9688b3cead"
        }
      ]
    }
  ]
}
