{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z7tc2apk45awvduwy5cthg6ch4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "9bcaa419baef76c53c7cc00865be97977a7aee9b31e7d8e5b2e188adb26f52d19b7994f1d7459c749b1fb202e2d5a3b57f1dffe5c5678792935e5831996aa34b",
          "sha256": "854569d5f7a503fabeabee4ec99c4e0e57bc2b22ae679506376d32de2f8f3cec",
          "sha1": "f7eaf42ea066712151f2cf9c892baffce02d1853",
          "md5": "0a101260d580e9f5af7b57697c8de3fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "9bcaa419baef76c53c7cc00865be97977a7aee9b31e7d8e5b2e188adb26f52d19b7994f1d7459c749b1fb202e2d5a3b57f1dffe5c5678792935e5831996aa34b",
          "sha256": "854569d5f7a503fabeabee4ec99c4e0e57bc2b22ae679506376d32de2f8f3cec",
          "sha1": "f7eaf42ea066712151f2cf9c892baffce02d1853",
          "md5": "0a101260d580e9f5af7b57697c8de3fb"
        }
      ]
    }
  ]
}
