{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "swlchhbfvrhc5hcb5szgxujo7u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "28e09d7b1f5991c155dffee77a543eca389c277c4b618fb32d6f1a272f9e1d9510deab2726c48cf313b9228d5cd918269e58ddf307cded7eafba5c875bf5d50c",
          "sha256": "7fab7fbc0eb8c213d54c0137e646882611231580b5f927554db1eefdc5c5f5fa",
          "sha1": "9ac17cc240b5d12b4bae0a5b448771d3910896e0",
          "md5": "a839442010855cd0591f9b9f5fb59eec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "28e09d7b1f5991c155dffee77a543eca389c277c4b618fb32d6f1a272f9e1d9510deab2726c48cf313b9228d5cd918269e58ddf307cded7eafba5c875bf5d50c",
          "sha256": "7fab7fbc0eb8c213d54c0137e646882611231580b5f927554db1eefdc5c5f5fa",
          "sha1": "9ac17cc240b5d12b4bae0a5b448771d3910896e0",
          "md5": "a839442010855cd0591f9b9f5fb59eec"
        }
      ]
    }
  ]
}
