{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dz6dzztqzrezxaxhvchzv33o3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4c9c105a6032bb1b924ffe8d97d5caa385ddf1c9b00e99f2f16aadf99f5c9cd8a931147b630584e954a45e54a117a16f01e8bcd7f2aff2c1ecf3d106f48f90e8",
          "sha256": "4acfd75e6d8e1a43d1d5b03f40ac3c9f75318cbd06245c60a5e821b55b196a6a",
          "sha1": "4715fdbf2b5bf275ade124e26080eeaa3c703548",
          "md5": "4140a60abbd8e20d53739ea6cc14a5bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "4c9c105a6032bb1b924ffe8d97d5caa385ddf1c9b00e99f2f16aadf99f5c9cd8a931147b630584e954a45e54a117a16f01e8bcd7f2aff2c1ecf3d106f48f90e8",
          "sha256": "4acfd75e6d8e1a43d1d5b03f40ac3c9f75318cbd06245c60a5e821b55b196a6a",
          "sha1": "4715fdbf2b5bf275ade124e26080eeaa3c703548",
          "md5": "4140a60abbd8e20d53739ea6cc14a5bc"
        }
      ]
    }
  ]
}
