{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xcsmmheb5ngdhem2yn6sciglju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "5fafb5cb74a8f0c39edda3b93cf9fed0b89cdef4ea8449555859a7a34549f280c512a2d377486c9d72de7cedf6261c8d86b2374524e01103f3b2bf5cc7021dcb",
          "sha256": "4f3737c15dff4e6ed005ab3afe7b1fda823812f04f04b8c243d264afa0ae1b85",
          "sha1": "8f02f2b3d21a946ccc550ad2ce67018fb16717d2",
          "md5": "1de1fb86fe9f87e5dad7be779f610ec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "5fafb5cb74a8f0c39edda3b93cf9fed0b89cdef4ea8449555859a7a34549f280c512a2d377486c9d72de7cedf6261c8d86b2374524e01103f3b2bf5cc7021dcb",
          "sha256": "4f3737c15dff4e6ed005ab3afe7b1fda823812f04f04b8c243d264afa0ae1b85",
          "sha1": "8f02f2b3d21a946ccc550ad2ce67018fb16717d2",
          "md5": "1de1fb86fe9f87e5dad7be779f610ec1"
        }
      ]
    }
  ]
}
