{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "32azslkqffd3znzgmhvi44kjza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "69d3d251852ee9cf683523d7cfe9c3ef5c645af53a610d865759ef07aa4946bf90851a06a7e75fe2ed55f6a1af968c3b2ff429f64358eab53e26a03b66b061fb",
          "sha256": "ac5b9ad3bffa6b23676c8422c347c087476fda97e54a7a82cc9a87c1303b3388",
          "sha1": "73246d804a9c06cdaa3f02ef07069e9b3c4758f0",
          "md5": "0a65b5f7cc35a3d44ccabfccaf8c449d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "69d3d251852ee9cf683523d7cfe9c3ef5c645af53a610d865759ef07aa4946bf90851a06a7e75fe2ed55f6a1af968c3b2ff429f64358eab53e26a03b66b061fb",
          "sha256": "ac5b9ad3bffa6b23676c8422c347c087476fda97e54a7a82cc9a87c1303b3388",
          "sha1": "73246d804a9c06cdaa3f02ef07069e9b3c4758f0",
          "md5": "0a65b5f7cc35a3d44ccabfccaf8c449d"
        }
      ]
    }
  ]
}
