{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m7nxczhs6vhnbej7f63yi3rily"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "85717be12a73139e84d02c18a5f6c4d754108e9b94e0a3f6a3d8ac649e0f175b9694696dc7bb676b55844ea386cf78282b9e84f70926a1e061cb9323da2127fd",
          "sha256": "b14389d320ddc87b70bc778e8b35c808723a93e8da657a77d978581700407299",
          "sha1": "e5c3ee370b9cc12f4a68f8872229ca8812903bb0",
          "md5": "714b075f9afdc695685207dd378f3eef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "85717be12a73139e84d02c18a5f6c4d754108e9b94e0a3f6a3d8ac649e0f175b9694696dc7bb676b55844ea386cf78282b9e84f70926a1e061cb9323da2127fd",
          "sha256": "b14389d320ddc87b70bc778e8b35c808723a93e8da657a77d978581700407299",
          "sha1": "e5c3ee370b9cc12f4a68f8872229ca8812903bb0",
          "md5": "714b075f9afdc695685207dd378f3eef"
        }
      ]
    }
  ]
}
