{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4vaohbfcnresdmlpcjoahtwuja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "28f8effc4f7fccc50a3da2f7a080da7fdb95baf165ee7e51aa357febd4ee4ebd99af293d76518377c5e11d75c24488f2c5aef1112a8d6fbe24d3a9a2c243821f",
          "sha256": "484a0210f661e43d337331ff457deb4a0ac22daa72ef5dd87c6c0d4030671ffc",
          "sha1": "7c17affaeaba7c18b05ca096dd7fc98b149e1ef4",
          "md5": "ce45fcbba01e594a70d511d975b286ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "28f8effc4f7fccc50a3da2f7a080da7fdb95baf165ee7e51aa357febd4ee4ebd99af293d76518377c5e11d75c24488f2c5aef1112a8d6fbe24d3a9a2c243821f",
          "sha256": "484a0210f661e43d337331ff457deb4a0ac22daa72ef5dd87c6c0d4030671ffc",
          "sha1": "7c17affaeaba7c18b05ca096dd7fc98b149e1ef4",
          "md5": "ce45fcbba01e594a70d511d975b286ec"
        }
      ]
    }
  ]
}
