{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ztcrv55rn5gjrdntn7yjwcrf3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "8e3ce3a56d82e20fd0cf3db83fc6e0e7e63b040f4afab6255f9bb68af577400449edd11fc1379653082ed526ea0016924836007ef9e323695fe418a9ea0c1692",
          "sha256": "7b6c3844f061e52a338230c2518c60df51dde399919a2e470ecc52efed281516",
          "sha1": "1d8bf7dd17db7d83df9971e980f75a7b059b4943",
          "md5": "80181ee313000ed129e91acdd88385e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "8e3ce3a56d82e20fd0cf3db83fc6e0e7e63b040f4afab6255f9bb68af577400449edd11fc1379653082ed526ea0016924836007ef9e323695fe418a9ea0c1692",
          "sha256": "7b6c3844f061e52a338230c2518c60df51dde399919a2e470ecc52efed281516",
          "sha1": "1d8bf7dd17db7d83df9971e980f75a7b059b4943",
          "md5": "80181ee313000ed129e91acdd88385e9"
        }
      ]
    }
  ]
}
