{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xq2kyv6e2rbszfz7wqsh2j3tri"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "url": "securestore-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "size": 41930,
          "sha512": "637a386239115f207e6b87fda5cd17800e573bddacb0c8584ed80b4be145611dfe9212ef01370771554fc58c4751c4e44e42fbef925b3558572cdb1a748b356c",
          "sha256": "358f762a4debc8e0036ba2e0aa3306ca8712b8957b7cba26b780b4d56b3c1448",
          "sha1": "fc9aab1bbf365abb02ecb91c3b9cb6f4798e90fb",
          "md5": "4c145fd6abc47153644763105c101221"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "url": "securestore-android-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.aar",
          "size": 41930,
          "sha512": "637a386239115f207e6b87fda5cd17800e573bddacb0c8584ed80b4be145611dfe9212ef01370771554fc58c4751c4e44e42fbef925b3558572cdb1a748b356c",
          "sha256": "358f762a4debc8e0036ba2e0aa3306ca8712b8957b7cba26b780b4d56b3c1448",
          "sha1": "fc9aab1bbf365abb02ecb91c3b9cb6f4798e90fb",
          "md5": "4c145fd6abc47153644763105c101221"
        }
      ]
    }
  ]
}
