{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-add-fhir-primitives-number-support-SNAPSHOT/fhir-0.0.1-add-fhir-primitives-number-support-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-add-fhir-primitives-number-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "lobn4juwjzagdogwbbrairyky4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir.klib",
          "url": "fhir-iosx64-0.0.1-add-fhir-primitives-number-support-SNAPSHOT.klib",
          "size": 1320202,
          "sha512": "57ebc41294eee55ac50d7f2be37d1293cc9b287a5455b14b2772c3204f459419088869899a306b48b86f7e0f9e8a7c14c3a069c4634a2b103375a3674779dce0",
          "sha256": "5ca6d82e7667ebe5593ee6a2996902a317ecc9eb95769f73864972db35189d2d",
          "sha1": "c3245da5945ffeb97eb6b97eec2b6baa4ec23509",
          "md5": "1577810ce00a87a80b6243483b5ba7cd"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-add-fhir-primitives-number-support-SNAPSHOT/fhir-metadata-0.0.1-add-fhir-primitives-number-support-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-add-fhir-primitives-number-support-SNAPSHOT"
      }
    }
  ]
}
