{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mhtegx5hr5bvlnzldnfls4vgzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "3db50a8025d7cad6fe03cc1621076da014d866cf461588312ca0abe41e6c5986edb2824da8943d837b723ac7882bb1f50c49b8b4baf4823de94cd73e1acfb2f7",
          "sha256": "4ead71f06fc2c1759c19bd8597a6c19f345a825ad019d586162ba995e0967bfb",
          "sha1": "3849411c133cc75aefe504c415274903032fe608",
          "md5": "b94b64349352d2d487581ff657a3fe20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "3db50a8025d7cad6fe03cc1621076da014d866cf461588312ca0abe41e6c5986edb2824da8943d837b723ac7882bb1f50c49b8b4baf4823de94cd73e1acfb2f7",
          "sha256": "4ead71f06fc2c1759c19bd8597a6c19f345a825ad019d586162ba995e0967bfb",
          "sha1": "3849411c133cc75aefe504c415274903032fe608",
          "md5": "b94b64349352d2d487581ff657a3fe20"
        }
      ]
    }
  ]
}
