{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5tshejskb5hqjgwhqusnarwxda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a9840109cd99a52b552ccbb8f3304eaf05c591e49af89230ad0d71e2126b2f9ca33e83ea6c61039e2ca06253a7c98c9f80b2f08aa22e596c752ca26fb8ec40d7",
          "sha256": "d3ebd91f591cc00705c6ebf82540a006e9acc18427853ef5dfc67278b393e7ef",
          "sha1": "ddada19b374c7c100965d2c1bd861122d4767182",
          "md5": "d9b5ee69aacec6802125d858767d6616"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a9840109cd99a52b552ccbb8f3304eaf05c591e49af89230ad0d71e2126b2f9ca33e83ea6c61039e2ca06253a7c98c9f80b2f08aa22e596c752ca26fb8ec40d7",
          "sha256": "d3ebd91f591cc00705c6ebf82540a006e9acc18427853ef5dfc67278b393e7ef",
          "sha1": "ddada19b374c7c100965d2c1bd861122d4767182",
          "md5": "d9b5ee69aacec6802125d858767d6616"
        }
      ]
    }
  ]
}
