{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.10.0-change-tags-and-annotations-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "c64kvleewfbv7gv3dfpz3wrevy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 487816,
          "sha512": "d3993a3756ea6e6b06f04f84215e5a40ae68c6f3f4541185fc7fe330ce27221721bc63c3efc2110d5b3f3b8736d31f1b0005b8208a02c9fe6740fc7a38007e12",
          "sha256": "414083c9c64e04b411cbf93d06f0897114b24a0874dd0a416da70eb35a8a560c",
          "sha1": "f919df4c08f636017240bc0c9c918e62fff58de8",
          "md5": "d3d63843465479023591641817dab3c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-tags-and-annotations-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-change-tags-and-annotations-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-change-tags-and-annotations-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 487816,
          "sha512": "d3993a3756ea6e6b06f04f84215e5a40ae68c6f3f4541185fc7fe330ce27221721bc63c3efc2110d5b3f3b8736d31f1b0005b8208a02c9fe6740fc7a38007e12",
          "sha256": "414083c9c64e04b411cbf93d06f0897114b24a0874dd0a416da70eb35a8a560c",
          "sha1": "f919df4c08f636017240bc0c9c918e62fff58de8",
          "md5": "d3d63843465479023591641817dab3c6"
        }
      ]
    }
  ]
}
