{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ebllkv5sr5c7bmsh4whon2uqa4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "b5af9ea03040718d1d6df56f9bfbbdc851a7b7c014d042d9c2634f144f51a194ea72209131a22ded50d868676ce13b2117520b9416cc1eacf5695ec424a20d87",
          "sha256": "29bca953a3d739ae79c43129d3dda58cf2658acdda519dc5770400b124799d55",
          "sha1": "ed86a4ee1db220f4f7d9df4ec78e165c89238e43",
          "md5": "c6356af14483803b256734198bd3f499"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "b5af9ea03040718d1d6df56f9bfbbdc851a7b7c014d042d9c2634f144f51a194ea72209131a22ded50d868676ce13b2117520b9416cc1eacf5695ec424a20d87",
          "sha256": "29bca953a3d739ae79c43129d3dda58cf2658acdda519dc5770400b124799d55",
          "sha1": "ed86a4ee1db220f4f7d9df4ec78e165c89238e43",
          "md5": "c6356af14483803b256734198bd3f499"
        }
      ]
    }
  ]
}
