{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-bump-fhir-lib-1-4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ctzmyecinjcjzlrgyyvbevqn5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "ae5fcef944bd92808d25d8dfea4c7cf46b38f0bfda9b63e8a34a53dc320f320030edf54cc01b7bc98465c14ca3ff72b43a82a3d54d1cb49cc030c3a32621a172",
          "sha256": "ecba38ba59c20139b039c314655b435bdd5672d163f2c53d73aa9c02011ed4b4",
          "sha1": "13a507fcf33e1be6c1fad2f8fedbc1d483d400ed",
          "md5": "f9aa8250ce32ad460126c8a2b1255aae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-fhir-lib-1-4-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-bump-fhir-lib-1-4-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "ae5fcef944bd92808d25d8dfea4c7cf46b38f0bfda9b63e8a34a53dc320f320030edf54cc01b7bc98465c14ca3ff72b43a82a3d54d1cb49cc030c3a32621a172",
          "sha256": "ecba38ba59c20139b039c314655b435bdd5672d163f2c53d73aa9c02011ed4b4",
          "sha1": "13a507fcf33e1be6c1fad2f8fedbc1d483d400ed",
          "md5": "f9aa8250ce32ad460126c8a2b1255aae"
        }
      ]
    }
  ]
}
