{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jgvme47vgjhftjihmpc4fmeom4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "b994dcc83e4209db464d0f0d6c86657909ab231dae4adfd53d8c6d58d28aee5eee1c9f65ca8b7ae2a93ac7af001d65039405f46a78a78384e1369d63964b9bea",
          "sha256": "cf49c7e967dcc48860c2b13749c7e0a901b7cfe53ca7ce0ccb309eb89ec97bc5",
          "sha1": "e56d21ed207ef0e72f0dbeaa520217bbd4ed188c",
          "md5": "33f747ee3924a3169e923db369944ac3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "b994dcc83e4209db464d0f0d6c86657909ab231dae4adfd53d8c6d58d28aee5eee1c9f65ca8b7ae2a93ac7af001d65039405f46a78a78384e1369d63964b9bea",
          "sha256": "cf49c7e967dcc48860c2b13749c7e0a901b7cfe53ca7ce0ccb309eb89ec97bc5",
          "sha1": "e56d21ed207ef0e72f0dbeaa520217bbd4ed188c",
          "md5": "33f747ee3924a3169e923db369944ac3"
        }
      ]
    }
  ]
}
