{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2xtkg4arcjduphpx2djj7egbhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d2c94a1b969cf9abced067e6c83c9a056a0c92a20f1c360ea52a7e4e942937db17779d57c57a716aedee829e86ff34648e1838552f5917b885b44a9c98786b70",
          "sha256": "5b82a0d7e4806fad38b33471a97f7141d9bf5c2dfd2c1788cb46d0ecf087c11a",
          "sha1": "50e0d505a4ebf5cee0a49d32d8a358708ebdd86a",
          "md5": "a58c85af0bc404892cd3124cd9d58e21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d2c94a1b969cf9abced067e6c83c9a056a0c92a20f1c360ea52a7e4e942937db17779d57c57a716aedee829e86ff34648e1838552f5917b885b44a9c98786b70",
          "sha256": "5b82a0d7e4806fad38b33471a97f7141d9bf5c2dfd2c1788cb46d0ecf087c11a",
          "sha1": "50e0d505a4ebf5cee0a49d32d8a358708ebdd86a",
          "md5": "a58c85af0bc404892cd3124cd9d58e21"
        }
      ]
    }
  ]
}
