{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zt2zqpbavncx3botu5tvhxr7cy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "b25a40bdc379c0ea3d14b30e7815845db24b024ee691bd57a369c0c49428756583703ab638333590b34b4474dd03ea8f50b2134f47ef726e513b854786a8a350",
          "sha256": "3d32de7ab9c47f955bd976726ba9415b727453f4a05365babfc677f7825c821f",
          "sha1": "84bbd0703f21b07a0d3040c930470f7ffa8d8d61",
          "md5": "db1bad460c2a608b6e0aeb1af58770a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "b25a40bdc379c0ea3d14b30e7815845db24b024ee691bd57a369c0c49428756583703ab638333590b34b4474dd03ea8f50b2134f47ef726e513b854786a8a350",
          "sha256": "3d32de7ab9c47f955bd976726ba9415b727453f4a05365babfc677f7825c821f",
          "sha1": "84bbd0703f21b07a0d3040c930470f7ffa8d8d61",
          "md5": "db1bad460c2a608b6e0aeb1af58770a4"
        }
      ]
    }
  ]
}
