{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "x65k6sjn7bes3c4xhpyjdld6bm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7c690c7890b2e73b37b38f1c3112df252ced3beb100f15f88f276ca69faa5b18ee392cfc2558769a689a9601381d9a10e1515cffa84308af96dc1521f43525cf",
          "sha256": "20789b36d634d6e0c3aac91c8f8167ddb45b9febe34860d5eb19e069be0c7f7b",
          "sha1": "969762bdf985ebc95bbb49abb442763881a414a7",
          "md5": "9712852b7330ff694a5fa2b2a138ac20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7c690c7890b2e73b37b38f1c3112df252ced3beb100f15f88f276ca69faa5b18ee392cfc2558769a689a9601381d9a10e1515cffa84308af96dc1521f43525cf",
          "sha256": "20789b36d634d6e0c3aac91c8f8167ddb45b9febe34860d5eb19e069be0c7f7b",
          "sha1": "969762bdf985ebc95bbb49abb442763881a414a7",
          "md5": "9712852b7330ff694a5fa2b2a138ac20"
        }
      ]
    }
  ]
}
