{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uyejqxajfnhqhnfhw42xkk64iq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b5ed6cf48449f17a569cabb792db1a4995d26bb15ad44f44dfa80c81c882f310976b431dc65ea8d55d5c624cb97a65a334639770cb6a921dce240b2b49108420",
          "sha256": "aa920b8304d2e8c58eb33a1910f74091cbb99c09d557f1c5ba71d4b92fb890f9",
          "sha1": "4b813241cf52eb46ed3b006b3a5da05269d76a82",
          "md5": "49bba536873cfd4b19adbdec3c319410"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b5ed6cf48449f17a569cabb792db1a4995d26bb15ad44f44dfa80c81c882f310976b431dc65ea8d55d5c624cb97a65a334639770cb6a921dce240b2b49108420",
          "sha256": "aa920b8304d2e8c58eb33a1910f74091cbb99c09d557f1c5ba71d4b92fb890f9",
          "sha1": "4b813241cf52eb46ed3b006b3a5da05269d76a82",
          "md5": "49bba536873cfd4b19adbdec3c319410"
        }
      ]
    }
  ]
}
