{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.0-prepare-release-1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qxnhzhcfdnf4xhl6xin2es7xv4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.0-prepare-release-1.9.1-SNAPSHOT.aar",
          "url": "securestore-android-1.9.0-prepare-release-1.9.1-SNAPSHOT.aar",
          "size": 41915,
          "sha512": "c275414d1bf1adc973e9e95f7a8847cfe9aa97e41599223cba4385825a21613d9156c6e4ff29b4072d124e86e4f921fec14086d09db0dd1ebec88c89f61efbba",
          "sha256": "b33421f58519a224e653ad5186369f557a6737d640138ecca091ebf3df750e61",
          "sha1": "37b43c929764bb6df9973556449a0dce4fbb6209",
          "md5": "9aaa39be8bc9b8782296f82449b24ec0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.0-prepare-release-1.9.1-SNAPSHOT.aar",
          "url": "securestore-android-1.9.0-prepare-release-1.9.1-SNAPSHOT.aar",
          "size": 41915,
          "sha512": "c275414d1bf1adc973e9e95f7a8847cfe9aa97e41599223cba4385825a21613d9156c6e4ff29b4072d124e86e4f921fec14086d09db0dd1ebec88c89f61efbba",
          "sha256": "b33421f58519a224e653ad5186369f557a6737d640138ecca091ebf3df750e61",
          "sha1": "37b43c929764bb6df9973556449a0dce4fbb6209",
          "md5": "9aaa39be8bc9b8782296f82449b24ec0"
        }
      ]
    }
  ]
}
