{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-add-api-service-unit-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "c7kv3sbzo5b5xakqhskkutrzzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-api-service-unit-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "f784ea03053e9684c69eb26a7359d4f4ea04bd17f391b789d1d09595de5be7af563d7e71245d0f4aac1e27ae3157cbdcbd8fb84ab0c5a827ee2d2b49c48af0a2",
          "sha256": "f84baef2bfdf6de33b238e067bf7364eb5d189084a8fcfbe94defd447933ee85",
          "sha1": "cd73dc46f20df45b4477f71d3283b6dbd3fa88a1",
          "md5": "e101eb44da972ac0a7c8288be101a465"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-add-api-service-unit-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-api-service-unit-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-add-api-service-unit-tests-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "f784ea03053e9684c69eb26a7359d4f4ea04bd17f391b789d1d09595de5be7af563d7e71245d0f4aac1e27ae3157cbdcbd8fb84ab0c5a827ee2d2b49c48af0a2",
          "sha256": "f84baef2bfdf6de33b238e067bf7364eb5d189084a8fcfbe94defd447933ee85",
          "sha1": "cd73dc46f20df45b4477f71d3283b6dbd3fa88a1",
          "md5": "e101eb44da972ac0a7c8288be101a465"
        }
      ]
    }
  ]
}
