{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.2-change-model-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ecdwxwthkvdxnkduu4tscfkrx4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "size": 44891,
          "sha512": "524467274dabf2908e763b3bfd85c8f5f041e2a10e8a496a123abdee45d27eb3c62128f403eaf59c629507dc2b23c2c076502e03af378cded7023e462a982115",
          "sha256": "2ad12c941ea96435af26902e97918814543c9379c0a8e8a5acb46d3979d20c87",
          "sha1": "e1b42b7bde5d2f88a58dc78217624167a40cca6d",
          "md5": "45617e932392520356b2bf87ee14b82f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "url": "auth-android-1.9.2-change-model-version-SNAPSHOT.aar",
          "size": 44891,
          "sha512": "524467274dabf2908e763b3bfd85c8f5f041e2a10e8a496a123abdee45d27eb3c62128f403eaf59c629507dc2b23c2c076502e03af378cded7023e462a982115",
          "sha256": "2ad12c941ea96435af26902e97918814543c9379c0a8e8a5acb46d3979d20c87",
          "sha1": "e1b42b7bde5d2f88a58dc78217624167a40cca6d",
          "md5": "45617e932392520356b2bf87ee14b82f"
        }
      ]
    }
  ]
}
