{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "zriivgusrng6bavxn7or772wey"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.aar",
          "size": 61909,
          "sha512": "cff3a0d9ead42ce19fb495ad47f73d978a1e8589167ec4d00b20185f3cea4f70d3460b3fb5ebe785a6f89957c737d98fd23798e6f527deb4a00506f2dacc4e15",
          "sha256": "32ed43074fc61fb02cbb0122a01e0b87c7df96fbc6e62691a190a9210c68ec43",
          "sha1": "fc78ed854a4b9e5cf720dabe52ae543df1befb4e",
          "md5": "b138be4f5bcc1e81ccd5b28f1615d5d9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.aar",
          "size": 61909,
          "sha512": "cff3a0d9ead42ce19fb495ad47f73d978a1e8589167ec4d00b20185f3cea4f70d3460b3fb5ebe785a6f89957c737d98fd23798e6f527deb4a00506f2dacc4e15",
          "sha256": "32ed43074fc61fb02cbb0122a01e0b87c7df96fbc6e62691a190a9210c68ec43",
          "sha1": "fc78ed854a4b9e5cf720dabe52ae543df1befb4e",
          "md5": "b138be4f5bcc1e81ccd5b28f1615d5d9"
        }
      ]
    }
  ]
}
