{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wgde7xnbkzhrjkwotraczy5wyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "4998fd9a957f23d069ca25d09b792f4a4c49f6e234f0e67efa3c7bd0edc88c950fc72ca1df9843f29f2084b01b8cc380ac905a5b58ea6281517d339e82122582",
          "sha256": "917948ad152401059d435adde7edeab087577b71730576155250adb218a242d9",
          "sha1": "dbaeb585a6e6d20f95bb53a5e03e08e74e5282b7",
          "md5": "aeae98dfd47878ee33ffed110c8c51c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "4998fd9a957f23d069ca25d09b792f4a4c49f6e234f0e67efa3c7bd0edc88c950fc72ca1df9843f29f2084b01b8cc380ac905a5b58ea6281517d339e82122582",
          "sha256": "917948ad152401059d435adde7edeab087577b71730576155250adb218a242d9",
          "sha1": "dbaeb585a6e6d20f95bb53a5e03e08e74e5282b7",
          "md5": "aeae98dfd47878ee33ffed110c8c51c7"
        }
      ]
    }
  ]
}
