{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sz3r3xffkfbm7h4fijct73k7fm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1a19359f12367c7b6afdf24e21afa2d40d4c711e51a43b39174c92e35fad5a64a9a9f5118e31f5befb0dacb802233d0615c418db4d7c1821162480f3856f6f24",
          "sha256": "c4f05795223dcc5f198b6f3d0292541f85ab014c0d388ef0e65313bff0360478",
          "sha1": "079be658273ddc6a39971369d13cee17eeef7d58",
          "md5": "f6a1f41cf32466b05ea3609856af7249"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1a19359f12367c7b6afdf24e21afa2d40d4c711e51a43b39174c92e35fad5a64a9a9f5118e31f5befb0dacb802233d0615c418db4d7c1821162480f3856f6f24",
          "sha256": "c4f05795223dcc5f198b6f3d0292541f85ab014c0d388ef0e65313bff0360478",
          "sha1": "079be658273ddc6a39971369d13cee17eeef7d58",
          "md5": "f6a1f41cf32466b05ea3609856af7249"
        }
      ]
    }
  ]
}
