{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jaop2jc4tfej7kxvvv6ulzacdu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "5044057743958ae08982bcbb775322f5ab113d80d14d879e7c556482d73fe8a9d117ea40cf23a264eb24a4831741331bb5e2d11cf46e7c83f040c5c5590d9586",
          "sha256": "433cc3429f442cea8c122948bc8d09c4728dced2f8f7f768e632b11717d332fc",
          "sha1": "b621a13cd04397d8bdaa67710af26e678f3c0fa8",
          "md5": "c165b50e7c228eae2cb4d249bde8fdf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "5044057743958ae08982bcbb775322f5ab113d80d14d879e7c556482d73fe8a9d117ea40cf23a264eb24a4831741331bb5e2d11cf46e7c83f040c5c5590d9586",
          "sha256": "433cc3429f442cea8c122948bc8d09c4728dced2f8f7f768e632b11717d332fc",
          "sha1": "b621a13cd04397d8bdaa67710af26e678f3c0fa8",
          "md5": "c165b50e7c228eae2cb4d249bde8fdf6"
        }
      ]
    }
  ]
}
