{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "h53qwca7d5huhgp6fb77cod7dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "aa3ad00f95f4fa4e1b9a4e1dfecdc561768533ef18c1ddc6e7c777ea70ac94b5be50d05072d0638ce39263c3f9d0554556b97d643b753ad7b5c7042ee7acc966",
          "sha256": "2e7beab29555b7b896604c8e3c3844e720f79090cd43dfe0be94efada77f4134",
          "sha1": "e96a88da8dd15e7cf879b864b933d04b81ea9894",
          "md5": "6f1d21eb8dd2e482b4c88fc3541950bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "aa3ad00f95f4fa4e1b9a4e1dfecdc561768533ef18c1ddc6e7c777ea70ac94b5be50d05072d0638ce39263c3f9d0554556b97d643b753ad7b5c7042ee7acc966",
          "sha256": "2e7beab29555b7b896604c8e3c3844e720f79090cd43dfe0be94efada77f4134",
          "sha1": "e96a88da8dd15e7cf879b864b933d04b81ea9894",
          "md5": "6f1d21eb8dd2e482b4c88fc3541950bb"
        }
      ]
    }
  ]
}
