{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jttq4ms2gndzjfd2tzcpjhxtou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "cb453c7f30eaceb07b39ef3555b2efe6171425195f6f3540fb8a8eeebb274fcfa917c712a6a03508accf6b60280de99129a883a424502e0cc601dc417e091144",
          "sha256": "8dc0ff34f031698dde2f9d6cd77a64132bc9acae3e0b5887acf8a45bf4746d4e",
          "sha1": "1b571b990a85cd6d533baa0367e6a2e2d6dfebc1",
          "md5": "737d10742594b52d1493ac051143eec0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "cb453c7f30eaceb07b39ef3555b2efe6171425195f6f3540fb8a8eeebb274fcfa917c712a6a03508accf6b60280de99129a883a424502e0cc601dc417e091144",
          "sha256": "8dc0ff34f031698dde2f9d6cd77a64132bc9acae3e0b5887acf8a45bf4746d4e",
          "sha1": "1b571b990a85cd6d533baa0367e6a2e2d6dfebc1",
          "md5": "737d10742594b52d1493ac051143eec0"
        }
      ]
    }
  ]
}
