{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-prepare-release-1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qn3mgeyd5feolnqmdv4hil2qnq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-prepare-release-1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-prepare-release-1.9.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-prepare-release-1.9.2-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "51aa60952a530f2daf2ab9e51a875d46fcee4ead7e7e824a2eb0d7adf30e2c1b47e30c230c0753d818f5855d074023c8dd8eb869e22f0afa847271035a9256e9",
          "sha256": "2d187ef193bc7fe839950f6e122690b33477582f6204cbd8eb8d51afc614b071",
          "sha1": "0897a266fc61c5e2e828e475761aaa2436825ed7",
          "md5": "540bb1682ac68e266878a67391368a26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-prepare-release-1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-prepare-release-1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-prepare-release-1.9.2-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-prepare-release-1.9.2-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "51aa60952a530f2daf2ab9e51a875d46fcee4ead7e7e824a2eb0d7adf30e2c1b47e30c230c0753d818f5855d074023c8dd8eb869e22f0afa847271035a9256e9",
          "sha256": "2d187ef193bc7fe839950f6e122690b33477582f6204cbd8eb8d51afc614b071",
          "sha1": "0897a266fc61c5e2e828e475761aaa2436825ed7",
          "md5": "540bb1682ac68e266878a67391368a26"
        }
      ]
    }
  ]
}
