{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-fhir-sdk-java",
    "module": "fhir-java",
    "version": "1.2.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cwopdnxx3zcbxoi5ki2gf254mu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fhir-java-1.2.0-SNAPSHOT.jar",
          "url": "fhir-java-1.2.0-SNAPSHOT.jar",
          "size": 982177,
          "sha512": "9b417940d9071d6c01afdedd3d1de7e9cf543370a181deb754a553b9d20441cc31127aca5c63bc883d10f6e422e30c8d27bd8020081e0d0aff6fc1d04a913ebd",
          "sha256": "d2d95e48bb02792d0ef1cb14693b6d24ab4294b0c2687d28fbfabeeecc1c1a06",
          "sha1": "5ab1b97d8acbac184e667d6594ae9829d50a89fa",
          "md5": "214e75fae197f0fcea7fea464dedb16a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-java-1.2.0-SNAPSHOT.jar",
          "url": "fhir-java-1.2.0-SNAPSHOT.jar",
          "size": 982177,
          "sha512": "9b417940d9071d6c01afdedd3d1de7e9cf543370a181deb754a553b9d20441cc31127aca5c63bc883d10f6e422e30c8d27bd8020081e0d0aff6fc1d04a913ebd",
          "sha256": "d2d95e48bb02792d0ef1cb14693b6d24ab4294b0c2687d28fbfabeeecc1c1a06",
          "sha1": "5ab1b97d8acbac184e667d6594ae9829d50a89fa",
          "md5": "214e75fae197f0fcea7fea464dedb16a"
        }
      ]
    }
  ]
}
