{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "t4jodykw2rbzdbdheazrnp2kwu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0970c26bad0b4c995a1fbd6ae2a389550911d1314c634e4c8ea31b061d78e3802fb1515e4c4e31738052c343c68274e4e94e9f6f253a4eb746f49c199f75c4c5",
          "sha256": "e6903d6be69f7a840d82b703bd4914a94166935eb5f7267ea67bd5f3acea96c5",
          "sha1": "f3eee66e28bee88151dfe7dd47d5bd36ba084753",
          "md5": "992e204ef5e598f64008ff90a192739d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0970c26bad0b4c995a1fbd6ae2a389550911d1314c634e4c8ea31b061d78e3802fb1515e4c4e31738052c343c68274e4e94e9f6f253a4eb746f49c199f75c4c5",
          "sha256": "e6903d6be69f7a840d82b703bd4914a94166935eb5f7267ea67bd5f3acea96c5",
          "sha1": "f3eee66e28bee88151dfe7dd47d5bd36ba084753",
          "md5": "992e204ef5e598f64008ff90a192739d"
        }
      ]
    }
  ]
}
