{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vlb4f3mjb5hq7ggttjdgjxr6vm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-code-style-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-code-style-SNAPSHOT.jar",
          "size": 27862,
          "sha512": "4ac1fb4058c0bbc394e41af6a50bd912f793c6abd06f1c9e2467c67250229af2b724b3ab023259acf6c2b5d24a2c301a8fb926c1f1f45c7ee6f4dc4e353ce98e",
          "sha256": "008174f8ad2e0e66c00b94661afb8c27f46db101517bfbb877fc19ef836a0825",
          "sha1": "bf1d2a884a8c4cbcbc874bfb127e68acf9d4698d",
          "md5": "1f601d5668477c734497f64468df4db3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-code-style-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-code-style-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-code-style-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-code-style-SNAPSHOT.jar",
          "size": 27862,
          "sha512": "4ac1fb4058c0bbc394e41af6a50bd912f793c6abd06f1c9e2467c67250229af2b724b3ab023259acf6c2b5d24a2c301a8fb926c1f1f45c7ee6f4dc4e353ce98e",
          "sha256": "008174f8ad2e0e66c00b94661afb8c27f46db101517bfbb877fc19ef836a0825",
          "sha1": "bf1d2a884a8c4cbcbc874bfb127e68acf9d4698d",
          "md5": "1f601d5668477c734497f64468df4db3"
        }
      ]
    }
  ]
}
