{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-naming-crypto-convention-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "i2h2nwcxybe6la4yy327lnmiva"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-naming-crypto-convention-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "da1d61441bbee876ed9df0769d2cbe48f1e34a03ab7efa8937498d2f2aa2e14e5a4bf6ffd6a80086366c6e50b5ebaa183c18e4ab272bfd682d9f2546074c81d8",
          "sha256": "0107aaee10e7f90844acc332e8e76a077340b83b4ba1417884511908eb199ff7",
          "sha1": "efa9f09bf13e12b37ea7e188cfd81ed0bdbda464",
          "md5": "c6a189802997e2d19b03d98c7862026c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-naming-crypto-convention-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-naming-crypto-convention-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "da1d61441bbee876ed9df0769d2cbe48f1e34a03ab7efa8937498d2f2aa2e14e5a4bf6ffd6a80086366c6e50b5ebaa183c18e4ab272bfd682d9f2546074c81d8",
          "sha256": "0107aaee10e7f90844acc332e8e76a077340b83b4ba1417884511908eb199ff7",
          "sha1": "efa9f09bf13e12b37ea7e188cfd81ed0bdbda464",
          "md5": "c6a189802997e2d19b03d98c7862026c"
        }
      ]
    }
  ]
}
