{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-test-utils-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kfkubimiv5htnlqvkjf4ozuutu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "04fd8df6d61b24ff6ce043d9ff04b27c4941b6fd2c6a9bacecbc76c10f95d9b7b419ffd49da5bbdb4da70d68c1de07afb25ca87ee7b643ca692a4297a40ec6d7",
          "sha256": "6ccc60e96c9b2c864284227a645642bf862520262c4cd851368e638a34a5a331",
          "sha1": "41c6f6db6dd3fb1d21b0a5d6d47c353c1d1cc49e",
          "md5": "f7fcd18bf09331210a7f6f65ae4ba2ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "04fd8df6d61b24ff6ce043d9ff04b27c4941b6fd2c6a9bacecbc76c10f95d9b7b419ffd49da5bbdb4da70d68c1de07afb25ca87ee7b643ca692a4297a40ec6d7",
          "sha256": "6ccc60e96c9b2c864284227a645642bf862520262c4cd851368e638a34a5a331",
          "sha1": "41c6f6db6dd3fb1d21b0a5d6d47c353c1d1cc49e",
          "md5": "f7fcd18bf09331210a7f6f65ae4ba2ad"
        }
      ]
    }
  ]
}
