{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-test-utils-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7rfhydy4b5eerh5ew26qydql7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ea60cfc8fb443683240889cc5648f6e6521029f71a492756150ffb76f34287057516eb4b6d78cfbe8a7e3bebc48410130c9e4f373dcfdac6d9af20d70365d940",
          "sha256": "dac312a1e4c3a3eb1f8d825cfa02c1fddceca58a98fb1c1393cfa040166e5ea3",
          "sha1": "f7a2b7b2be2a3ded4da82dc0cf13cab0cef54bcd",
          "md5": "549dcc269384cea8eab1ee33f880d7b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ea60cfc8fb443683240889cc5648f6e6521029f71a492756150ffb76f34287057516eb4b6d78cfbe8a7e3bebc48410130c9e4f373dcfdac6d9af20d70365d940",
          "sha256": "dac312a1e4c3a3eb1f8d825cfa02c1fddceca58a98fb1c1393cfa040166e5ea3",
          "sha1": "f7a2b7b2be2a3ded4da82dc0cf13cab0cef54bcd",
          "md5": "549dcc269384cea8eab1ee33f880d7b7"
        }
      ]
    }
  ]
}
