{
  "formatVersion": "1.1",
  "component": {
    "url": "../../securestore/0.0.1-add-securestore-implementation-SNAPSHOT/securestore-0.0.1-add-securestore-implementation-SNAPSHOT.module",
    "group": "care.data4life.hc-securestore-kmp",
    "module": "securestore",
    "version": "0.0.1-add-securestore-implementation-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uzcrtmthefgxdlsnppeqgk6vhq"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-release.aar",
          "url": "securestore-android-0.0.1-add-securestore-implementation-SNAPSHOT.aar",
          "size": 31753,
          "sha512": "e39b18ea1f35faa41ae0e634d43abe8552437ccb59416b8b04607b8f56152b5789bba2d680db41f1d412db7d274d5d36ae24dcf83938b54b8b3f6939060826d6",
          "sha256": "926d3b3948094f4e76f16642c2fdf7440488769deb1e95f2b8e57ead6c8f8955",
          "sha1": "b03040f21b0130e733ff1bd2d59a8089ced30d9f",
          "md5": "4bbe73d5b5c05c4a1e2755f5fa6f78a6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-release.aar",
          "url": "securestore-android-0.0.1-add-securestore-implementation-SNAPSHOT.aar",
          "size": 31753,
          "sha512": "e39b18ea1f35faa41ae0e634d43abe8552437ccb59416b8b04607b8f56152b5789bba2d680db41f1d412db7d274d5d36ae24dcf83938b54b8b3f6939060826d6",
          "sha256": "926d3b3948094f4e76f16642c2fdf7440488769deb1e95f2b8e57ead6c8f8955",
          "sha1": "b03040f21b0130e733ff1bd2d59a8089ced30d9f",
          "md5": "4bbe73d5b5c05c4a1e2755f5fa6f78a6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../securestore-metadata/0.0.1-add-securestore-implementation-SNAPSHOT/securestore-metadata-0.0.1-add-securestore-implementation-SNAPSHOT.module",
        "group": "care.data4life.hc-securestore-kmp",
        "module": "securestore-metadata",
        "version": "0.0.1-add-securestore-implementation-SNAPSHOT"
      }
    }
  ]
}
