{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kbq63nxerffnrfw7qmmxelluri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 487507,
          "sha512": "895f65c9cae1e07c06611a62b032f2868ead4c1d0a5eafe42264495d851b771e6ca1536edf7f12fd71c645f571389ff42a10f048264f31bd8615b73eeb07b488",
          "sha256": "c51098c14edce25fbf3c883c4715f3bea7c829826b0c748a2a4986f3bcb537d9",
          "sha1": "4d0c4a93a1d55c2ddddcf02732e45ccf37727873",
          "md5": "eea6b7cca81f52fcb2e95ba404ac7ed1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 487507,
          "sha512": "895f65c9cae1e07c06611a62b032f2868ead4c1d0a5eafe42264495d851b771e6ca1536edf7f12fd71c645f571389ff42a10f048264f31bd8615b73eeb07b488",
          "sha256": "c51098c14edce25fbf3c883c4715f3bea7c829826b0c748a2a4986f3bcb537d9",
          "sha1": "4d0c4a93a1d55c2ddddcf02732e45ccf37727873",
          "md5": "eea6b7cca81f52fcb2e95ba404ac7ed1"
        }
      ]
    }
  ]
}
