{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-update-ci-label-configuration-SNAPSHOT/fhir-0.0.1-update-ci-label-configuration-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-update-ci-label-configuration-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "u6fmybakpvbrpijiiwffvyabo4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir.klib",
          "url": "fhir-iosarm64-0.0.1-update-ci-label-configuration-SNAPSHOT.klib",
          "size": 1321441,
          "sha512": "2b888bdfb6f5f705da02e47838f4835469e7de4c5fd94d982da0ee272e1b673bc3503e6134aa2045406d818326f826e7746b31956033b3e66b77cbb38008f543",
          "sha256": "1564ebb66287d017e6d997d586deba81d3217bfef1d950e13b7b952052f54645",
          "sha1": "af05aadf731c3e8229026a2234c8ea462df0b4db",
          "md5": "c10adecda5d7edfaf3681bc0beebfe8d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-update-ci-label-configuration-SNAPSHOT/fhir-metadata-0.0.1-update-ci-label-configuration-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-update-ci-label-configuration-SNAPSHOT"
      }
    }
  ]
}
