{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-add-envrioment-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vzo25yfyefdzdnpylje6evaal4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b66e0a0442ada2562c90bcd170fe47809b5972fabaca8ff0834a6901253b0c6760869f995736c35e88fba360f489a8898756e2185f9c5389bc09a3ef7eeccd7b",
          "sha256": "78001efe5f9018da03cda4336cc33f02b5d49abebf3eb5ca8ff6ae1e1e13aeb8",
          "sha1": "d241462380d6176d86edeb0bf509eb3d18e239f4",
          "md5": "7bbbeaebcd027b5cf47e4cd94b9430db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-envrioment-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b66e0a0442ada2562c90bcd170fe47809b5972fabaca8ff0834a6901253b0c6760869f995736c35e88fba360f489a8898756e2185f9c5389bc09a3ef7eeccd7b",
          "sha256": "78001efe5f9018da03cda4336cc33f02b5d49abebf3eb5ca8ff6ae1e1e13aeb8",
          "sha1": "d241462380d6176d86edeb0bf509eb3d18e239f4",
          "md5": "7bbbeaebcd027b5cf47e4cd94b9430db"
        }
      ]
    }
  ]
}
