{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-change-attachment-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6733dv5kkbab5ld45f5uxzcgfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ff302d2bfb79b33fa645c72c9ba7b3378f426e8a847b1c67cd1c2c1c2399effc897410f08f8d6961dc2bc54c9465c417cc69de84a54d3dac5a15467aac099f1e",
          "sha256": "c923ded74bec7b6dd3c75336a6edc81d28c64de237e5f58dfb1f441b90aa40f3",
          "sha1": "555cb850d70edc7853fc97726d41c450ed05e63e",
          "md5": "104abd149e72a9d1c2cf3bcdfe1798d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ff302d2bfb79b33fa645c72c9ba7b3378f426e8a847b1c67cd1c2c1c2399effc897410f08f8d6961dc2bc54c9465c417cc69de84a54d3dac5a15467aac099f1e",
          "sha256": "c923ded74bec7b6dd3c75336a6edc81d28c64de237e5f58dfb1f441b90aa40f3",
          "sha1": "555cb850d70edc7853fc97726d41c450ed05e63e",
          "md5": "104abd149e72a9d1c2cf3bcdfe1798d6"
        }
      ]
    }
  ]
}
