{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-fix-document-upload-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5khqrztukbbz5mtsjprwk7j7wi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "342fd28f42577504c82eaa9c4209380740de1a503309982f343843245ab98c2ad867d29400ca7a68bab1f6cde4fbcba1d62317921831bc294b07dca9d8b95278",
          "sha256": "c878da8b3eb695134f8fdabc5b79954766146e96397e559b302ba3aea83ac9d7",
          "sha1": "2a7818162f4fa503ed1dc73180d63d622e2c8f2c",
          "md5": "dde7a65b2956ba1bc00ddd14890aaa48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "342fd28f42577504c82eaa9c4209380740de1a503309982f343843245ab98c2ad867d29400ca7a68bab1f6cde4fbcba1d62317921831bc294b07dca9d8b95278",
          "sha256": "c878da8b3eb695134f8fdabc5b79954766146e96397e559b302ba3aea83ac9d7",
          "sha1": "2a7818162f4fa503ed1dc73180d63d622e2c8f2c",
          "md5": "dde7a65b2956ba1bc00ddd14890aaa48"
        }
      ]
    }
  ]
}
