{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-fix-document-upload-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7fswvv4qirhtrj77wv2b5d6kiu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "0a264a0ba299b069e51205d466d1ed517ddc6fc4afc1a4e842f72aac37e729778616d44d2fe8a02ce05228a7ad602293a29709d3113c016cd813b5919b5f6e13",
          "sha256": "6e71fa0b1738a878503db99c0991fa8b9e00bd94d3cf12999b3553e685aecfae",
          "sha1": "1e30638dc1eb2d3cecacddb2fa179481b4f6ed37",
          "md5": "7f518e30d316df4c9d0db02c802c4851"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "0a264a0ba299b069e51205d466d1ed517ddc6fc4afc1a4e842f72aac37e729778616d44d2fe8a02ce05228a7ad602293a29709d3113c016cd813b5919b5f6e13",
          "sha256": "6e71fa0b1738a878503db99c0991fa8b9e00bd94d3cf12999b3553e685aecfae",
          "sha1": "1e30638dc1eb2d3cecacddb2fa179481b4f6ed37",
          "md5": "7f518e30d316df4c9d0db02c802c4851"
        }
      ]
    }
  ]
}
