{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-tag-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fgehbeg3onclrdcsgzga4v7z4a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a0b10f4c7adcff2cace26f4f02f1af67965238adbaab58350ca4e7b53559388357b2255888369152a13dfec3c2ce587533ceb620d32944d627808cd951eb210d",
          "sha256": "ec8121659802c8fe11e975ec65bd640c201a5605740bcefac3931342caabea95",
          "sha1": "86ddd3e9f1164886a8836e645778e72941ae663a",
          "md5": "575c1d32d1d2832e01e13f5df7212877"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a0b10f4c7adcff2cace26f4f02f1af67965238adbaab58350ca4e7b53559388357b2255888369152a13dfec3c2ce587533ceb620d32944d627808cd951eb210d",
          "sha256": "ec8121659802c8fe11e975ec65bd640c201a5605740bcefac3931342caabea95",
          "sha1": "86ddd3e9f1164886a8836e645778e72941ae663a",
          "md5": "575c1d32d1d2832e01e13f5df7212877"
        }
      ]
    }
  ]
}
