{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-bump-fhir-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4576llu3avb23d2tof26t2wwcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "eeb64ee5d2afd02a573593d2cae67f01c54736d3b5c912633c1700c22cf7189839368ff3b89f53b22531d1c76477ab2e74e4dfae4f8c6bd84b8557f02ccd0baf",
          "sha256": "057dfd4190a517d38511f35be8c0cfc97f987c7fa697f1fd11a6c6f8536c157f",
          "sha1": "9405f08e167792257db92f905088436b0a89e1dd",
          "md5": "edb92ca4f9c69c51e85e765c767d599f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "eeb64ee5d2afd02a573593d2cae67f01c54736d3b5c912633c1700c22cf7189839368ff3b89f53b22531d1c76477ab2e74e4dfae4f8c6bd84b8557f02ccd0baf",
          "sha256": "057dfd4190a517d38511f35be8c0cfc97f987c7fa697f1fd11a6c6f8536c157f",
          "sha1": "9405f08e167792257db92f905088436b0a89e1dd",
          "md5": "edb92ca4f9c69c51e85e765c767d599f"
        }
      ]
    }
  ]
}
