{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qaymwtgcxrasjp6nvlx4n2grxu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "6ff97f82198e9b0d0ae47b86e45f1d2dfd9e69fd48f0227fb81b8d155900e7390ef3f92061a1b621ac51c6eb6cd10fd51517df4efcbaa5bec9cf685b3fb1a980",
          "sha256": "ef575f2c44cb590f4290aab01ea65a08de8b97adceb7f7103272ce4ec0c977e6",
          "sha1": "108851a7086ac11d55a875bc7aaf4e5ff87171a5",
          "md5": "ca7a1458fa10eba3630dbb5e450c8ad8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "6ff97f82198e9b0d0ae47b86e45f1d2dfd9e69fd48f0227fb81b8d155900e7390ef3f92061a1b621ac51c6eb6cd10fd51517df4efcbaa5bec9cf685b3fb1a980",
          "sha256": "ef575f2c44cb590f4290aab01ea65a08de8b97adceb7f7103272ce4ec0c977e6",
          "sha1": "108851a7086ac11d55a875bc7aaf4e5ff87171a5",
          "md5": "ca7a1458fa10eba3630dbb5e450c8ad8"
        }
      ]
    }
  ]
}
