{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uwmpo4yfrvdfpg35w7w5jzniaq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.aar",
          "size": 44951,
          "sha512": "d375ac14b409e3c8276c34f76e2abbffbb197d9fca200d5f70c1ac657e4490ee39e87585c932447d981448d27d7c96bd3959c7d892088a34fa57ece898891839",
          "sha256": "92c71e7649c64fabd1116be3db9a61332c97a4d6c5a948e053102efb48760340",
          "sha1": "b78445450a82bc8efe1c70a7a4d19bd18a7e6c2f",
          "md5": "b4470970bc44e8fede00aaefa053ae87"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.aar",
          "size": 44951,
          "sha512": "d375ac14b409e3c8276c34f76e2abbffbb197d9fca200d5f70c1ac657e4490ee39e87585c932447d981448d27d7c96bd3959c7d892088a34fa57ece898891839",
          "sha256": "92c71e7649c64fabd1116be3db9a61332c97a4d6c5a948e053102efb48760340",
          "sha1": "b78445450a82bc8efe1c70a7a4d19bd18a7e6c2f",
          "md5": "b4470970bc44e8fede00aaefa053ae87"
        }
      ]
    }
  ]
}
