{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jaamjrhupffsli7sw5hz2qu3ka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "92ec1225d73efdf35cee1b44bf677174a27afbe6617433d59f9ed403eaca884fc5b95f33d436edccdfbd3a3dfb6127dd29628b5294287d846be329470df80557",
          "sha256": "304a45a11f1be25b7f66ef905b066fc3859e3510b9a6a77ed72037bdb2520087",
          "sha1": "de76f32f16aff1a0823357dc2707af672ba970f7",
          "md5": "f6d512021735856401aa487c8199935f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "92ec1225d73efdf35cee1b44bf677174a27afbe6617433d59f9ed403eaca884fc5b95f33d436edccdfbd3a3dfb6127dd29628b5294287d846be329470df80557",
          "sha256": "304a45a11f1be25b7f66ef905b066fc3859e3510b9a6a77ed72037bdb2520087",
          "sha1": "de76f32f16aff1a0823357dc2707af672ba970f7",
          "md5": "f6d512021735856401aa487c8199935f"
        }
      ]
    }
  ]
}
