{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-attachment-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wl4mwif3s5dmhgdrycqkf45cp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "5045cbf024d6dd54d8fd9972eb3ec4645a61b5950e6299d036dd41f8f59817883917db3c2c70d39463e28c7a55f2d82d4c4e6da1b22d1e989b9474d14d286f4e",
          "sha256": "7c9e2d22301eb815b10ebeb4e161975f4578d9f93a0eff3f832f5eaa82fdd70c",
          "sha1": "967baae4835e577e51a47d625eb999b45d582527",
          "md5": "39edebbf48f0844a83a56bae2a37f6ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "5045cbf024d6dd54d8fd9972eb3ec4645a61b5950e6299d036dd41f8f59817883917db3c2c70d39463e28c7a55f2d82d4c4e6da1b22d1e989b9474d14d286f4e",
          "sha256": "7c9e2d22301eb815b10ebeb4e161975f4578d9f93a0eff3f832f5eaa82fdd70c",
          "sha1": "967baae4835e577e51a47d625eb999b45d582527",
          "md5": "39edebbf48f0844a83a56bae2a37f6ad"
        }
      ]
    }
  ]
}
