{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kpfe7unvhbgytk5djvvovhhywe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8bfb5ce2457c39dbd8909304aa7c36b55a0c68a10b0690cc4a573dee94e66292bad468b6a08be9365b1e4e26b8be40d6f341fcbf177a486be440cbbafb326a5a",
          "sha256": "a5237b56771b59c50be74cf9a7354dabadc5a487a6e1c235aac25003bd5c5d54",
          "sha1": "e65d6470660f8347f8a8e4cb1aa67b530132c56f",
          "md5": "62fdf8174a9b38963fa205763961ca00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8bfb5ce2457c39dbd8909304aa7c36b55a0c68a10b0690cc4a573dee94e66292bad468b6a08be9365b1e4e26b8be40d6f341fcbf177a486be440cbbafb326a5a",
          "sha256": "a5237b56771b59c50be74cf9a7354dabadc5a487a6e1c235aac25003bd5c5d54",
          "sha1": "e65d6470660f8347f8a8e4cb1aa67b530132c56f",
          "md5": "62fdf8174a9b38963fa205763961ca00"
        }
      ]
    }
  ]
}
