{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-recordservice-test-attachments-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6l76aactebef5mirvdcoqqgr6i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "9427b0aa9e9bea1e1ee2b790cf292007ecca4e10aede36b545e7c4a88bdb883ab5a1f51c0ab9305f0d01c28b565fd9dc75417514fd684466a618716bd6a5a86d",
          "sha256": "f6247fe6ce1145b3d523eccc177dbc51bdcf8cad814ca6308819cec26af64289",
          "sha1": "3ac5ccddfe5338bcedd3df94ee3e0e1df8c78c27",
          "md5": "69942b37e7817cc694d47dddee99b383"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "9427b0aa9e9bea1e1ee2b790cf292007ecca4e10aede36b545e7c4a88bdb883ab5a1f51c0ab9305f0d01c28b565fd9dc75417514fd684466a618716bd6a5a86d",
          "sha256": "f6247fe6ce1145b3d523eccc177dbc51bdcf8cad814ca6308819cec26af64289",
          "sha1": "3ac5ccddfe5338bcedd3df94ee3e0e1df8c78c27",
          "md5": "69942b37e7817cc694d47dddee99b383"
        }
      ]
    }
  ]
}
