{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-recordservice-test-attachments-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4mk7sy5f65bt7de4cebkeqillu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5a0e72b98e204bdeb670d0d40789966f56eae9e7c4526ac25d63138a6035130a7ca00029bfe828a8015aeac4806cd52d205bb17d491519415cdc97705faebc58",
          "sha256": "e9f2850bd790d5559d6fe23773857ccf2621ab8ad91c4415b3c168232e693f47",
          "sha1": "3e02cf221c06db6379879ef2f0a35d711cf806d4",
          "md5": "75d1e7221b661c84ef9ec3f4c322d188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-recordservice-test-attachments-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5a0e72b98e204bdeb670d0d40789966f56eae9e7c4526ac25d63138a6035130a7ca00029bfe828a8015aeac4806cd52d205bb17d491519415cdc97705faebc58",
          "sha256": "e9f2850bd790d5559d6fe23773857ccf2621ab8ad91c4415b3c168232e693f47",
          "sha1": "3e02cf221c06db6379879ef2f0a35d711cf806d4",
          "md5": "75d1e7221b661c84ef9ec3f4c322d188"
        }
      ]
    }
  ]
}
