{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-fix-search-count-api-call-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3zsqnthe7rerjmbd6qiqaozyxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-fix-search-count-api-call-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "760d745acf1e71a3f73f0b4cf37fa62cdb43e633260ed5767b52ce60e471d9320d7de53a5317f90ebdafa6320bc12e81b6afcb969ab9c142eeb19368fa0372e1",
          "sha256": "5dc5e1226f406386a2ca464dc3b6386aecc73bae3f43cf2f313176fb0237cd2c",
          "sha1": "562da277a9b6ddd193e2acf4df70e45b4d87be52",
          "md5": "c357b11339cca96e8fcac94a5ce6a69a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-fix-search-count-api-call-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "760d745acf1e71a3f73f0b4cf37fa62cdb43e633260ed5767b52ce60e471d9320d7de53a5317f90ebdafa6320bc12e81b6afcb969ab9c142eeb19368fa0372e1",
          "sha256": "5dc5e1226f406386a2ca464dc3b6386aecc73bae3f43cf2f313176fb0237cd2c",
          "sha1": "562da277a9b6ddd193e2acf4df70e45b4d87be52",
          "md5": "c357b11339cca96e8fcac94a5ce6a69a"
        }
      ]
    }
  ]
}
