{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "suktouhx35hzda2onq4552twrm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "bed982dbd43bd69b7b166b5f08e606f85e4ffd9aab6a15df5881d13e3ffac8740d1fc531a785a9e6645bfb7964d429fa1ef71d5f9fbc6deaae447ef214fe033c",
          "sha256": "a2935767d313d817ce18425b44df85cf8f5901524cbda513ab158968c735339e",
          "sha1": "71b230b694bb542f02a3c46d6de9d0909e369a73",
          "md5": "2ecc119bdbb596c247cf1e50bd711475"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "bed982dbd43bd69b7b166b5f08e606f85e4ffd9aab6a15df5881d13e3ffac8740d1fc531a785a9e6645bfb7964d429fa1ef71d5f9fbc6deaae447ef214fe033c",
          "sha256": "a2935767d313d817ce18425b44df85cf8f5901524cbda513ab158968c735339e",
          "sha1": "71b230b694bb542f02a3c46d6de9d0909e369a73",
          "md5": "2ecc119bdbb596c247cf1e50bd711475"
        }
      ]
    }
  ]
}
