{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yxzgrzu6gjba5fovau6tmwuyq4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d8ad25523b224de166979636c214e008bbc6e6369896ca65c46ee640c7515f4d98cc99ac2ecec93455b6b046519b134ec72ff839a01e5fd58e6c310517bc0717",
          "sha256": "08bd0fd1baabe8fe3bb97ca166865f1ffc68c506c12e1d0576498d65323af4aa",
          "sha1": "318ce1163330347d89129949640d81670632e899",
          "md5": "b6066b4e11b86f604510d156907107f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d8ad25523b224de166979636c214e008bbc6e6369896ca65c46ee640c7515f4d98cc99ac2ecec93455b6b046519b134ec72ff839a01e5fd58e6c310517bc0717",
          "sha256": "08bd0fd1baabe8fe3bb97ca166865f1ffc68c506c12e1d0576498d65323af4aa",
          "sha1": "318ce1163330347d89129949640d81670632e899",
          "md5": "b6066b4e11b86f604510d156907107f9"
        }
      ]
    }
  ]
}
