{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ih5xjviyszesvhtokz2lpfo6m4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "7ee119be8cfb57329f3835054f2d21cd584c6f255771d1d2a5a8cf6efe597b84a5941a6bc780208109917af6e0eeac26e017718bcd73fabd58ab3d8300dbc170",
          "sha256": "ff9819bafaa7bdb21dda852cd1305ca4fbf19858f76a9d6613c96350fbdd0baa",
          "sha1": "c106a3de6d6b0c7a5103aa2004b82371cf953f31",
          "md5": "e09d3f038ed34a098f48ae1238075580"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "7ee119be8cfb57329f3835054f2d21cd584c6f255771d1d2a5a8cf6efe597b84a5941a6bc780208109917af6e0eeac26e017718bcd73fabd58ab3d8300dbc170",
          "sha256": "ff9819bafaa7bdb21dda852cd1305ca4fbf19858f76a9d6613c96350fbdd0baa",
          "sha1": "c106a3de6d6b0c7a5103aa2004b82371cf953f31",
          "md5": "e09d3f038ed34a098f48ae1238075580"
        }
      ]
    }
  ]
}
