{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.11.0-change-data-resource-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yd6cmoqvw5gtxadrkzzeeddmfe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "url": "securestore-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "size": 41955,
          "sha512": "8ad4606d9d70f295edae01dca5b145c490322ac344b8fff3e23eeb6e95134db4a0b0b597a083f24fc2c39f9b46c372f64d7b169d897ee341e8b71a87d6bfd0a5",
          "sha256": "0759bf3a67ee0072f176717fe7e0f22b7cd0f26e6765f0cda053fc10235960b3",
          "sha1": "a3639888ff7e2d0e8814ac2b1d399581bcc88864",
          "md5": "8e829548b4dac6655d72968436bfce82"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "url": "securestore-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "size": 41955,
          "sha512": "8ad4606d9d70f295edae01dca5b145c490322ac344b8fff3e23eeb6e95134db4a0b0b597a083f24fc2c39f9b46c372f64d7b169d897ee341e8b71a87d6bfd0a5",
          "sha256": "0759bf3a67ee0072f176717fe7e0f22b7cd0f26e6765f0cda053fc10235960b3",
          "sha1": "a3639888ff7e2d0e8814ac2b1d399581bcc88864",
          "md5": "8e829548b4dac6655d72968436bfce82"
        }
      ]
    }
  ]
}
