{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-wrapper-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wqbcb6m6vjak7i7yto6btu5lzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "06b6be9c63c58edcedf5409a17575362dd27fd7ef9f3944535363f6f41b6c034a94e6f1a5c18c8386babdb28a899d64227916f363e58f2374cf4d6ed14d4249c",
          "sha256": "22fa6fb039dad53b359026cc719f22d35d1ce59f3d09fcff1714a47ee4912183",
          "sha1": "5d084863f18d47b6d7144dffed3a1999661b7ac1",
          "md5": "41a218ac6fea2bb958a0786ebabe0f50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "06b6be9c63c58edcedf5409a17575362dd27fd7ef9f3944535363f6f41b6c034a94e6f1a5c18c8386babdb28a899d64227916f363e58f2374cf4d6ed14d4249c",
          "sha256": "22fa6fb039dad53b359026cc719f22d35d1ce59f3d09fcff1714a47ee4912183",
          "sha1": "5d084863f18d47b6d7144dffed3a1999661b7ac1",
          "md5": "41a218ac6fea2bb958a0786ebabe0f50"
        }
      ]
    }
  ]
}
