{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-model-version-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5rlxeo2qu5e45pfhpw5vjyg3dq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "aa9a5e5bca2bcd6d9d391a4858d5394d8043f85ad7143ff5dc9f265ded62ae03caa6d7f7871dfa6aa061e73c7988d5e359860427e48f3a91148e00160e59daca",
          "sha256": "39342d403334532b154a20ce1706a3ba6d9de07e8fb757ebaadeb8668478c8c6",
          "sha1": "f03d70be0ae002195cf5979ceac71ae8b0602da4",
          "md5": "4304c2465acfecf5ac21515cf9aa3757"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-model-version-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-model-version-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "aa9a5e5bca2bcd6d9d391a4858d5394d8043f85ad7143ff5dc9f265ded62ae03caa6d7f7871dfa6aa061e73c7988d5e359860427e48f3a91148e00160e59daca",
          "sha256": "39342d403334532b154a20ce1706a3ba6d9de07e8fb757ebaadeb8668478c8c6",
          "sha1": "f03d70be0ae002195cf5979ceac71ae8b0602da4",
          "md5": "4304c2465acfecf5ac21515cf9aa3757"
        }
      ]
    }
  ]
}
