{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-add-userservice-interface-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gq7rh7nl2ver7doxoqznlktzka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "735ef91fc1236be4b54c041920e24d17f5b572fa35fb3368dbb54dcd3fc928fcd7051a9681e244105cae65057cdebb1c8062684caeb37e9cdf26935d8d694455",
          "sha256": "24b6cdf7d7f8123d674717bddc4e122d28fece9537602a1b19c7cfa2d70710df",
          "sha1": "24cb06004ba51a4ce1ccd0d23c9ee93a76fd777e",
          "md5": "bd9acd7a73cf001380c6cf795883a63e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-userservice-interface-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-userservice-interface-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "735ef91fc1236be4b54c041920e24d17f5b572fa35fb3368dbb54dcd3fc928fcd7051a9681e244105cae65057cdebb1c8062684caeb37e9cdf26935d8d694455",
          "sha256": "24b6cdf7d7f8123d674717bddc4e122d28fece9537602a1b19c7cfa2d70710df",
          "sha1": "24cb06004ba51a4ce1ccd0d23c9ee93a76fd777e",
          "md5": "bd9acd7a73cf001380c6cf795883a63e"
        }
      ]
    }
  ]
}
