{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0-add-codeowner-file-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uv37b57dtndp5py35xyridc4du"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a67c4bc179e6ac8af025f31cc37e1cfd3e4563b8317ceba4663f277176ef42cc20657ac2966d024c944d301a2da50ea87c046a7a015384494af14ac25255d060",
          "sha256": "7719458ae547fd3ef52479cb340e7a5662e214bb0982df7ae1c1d0ef96cb906a",
          "sha1": "6712cf7b8c3ee8a99765a40ecb2a13d03d0f1d48",
          "md5": "372a3223199ed2fcc42d8a8484f3bec5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "url": "crypto-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a67c4bc179e6ac8af025f31cc37e1cfd3e4563b8317ceba4663f277176ef42cc20657ac2966d024c944d301a2da50ea87c046a7a015384494af14ac25255d060",
          "sha256": "7719458ae547fd3ef52479cb340e7a5662e214bb0982df7ae1c1d0ef96cb906a",
          "sha1": "6712cf7b8c3ee8a99765a40ecb2a13d03d0f1d48",
          "md5": "372a3223199ed2fcc42d8a8484f3bec5"
        }
      ]
    }
  ]
}
