{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-add-resource-encryption-service-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qh5gbqk3vze6jbl2o3umojltca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "5380d11eca5d9551f3e86ded1b1f41b6befa251f1f75081b6ce63fa939e7abed25857ba9891de46b26b288c66a4f6256b0607cc415e1133926ccb693b06b1818",
          "sha256": "5a5ee32c0b6a6ccd284b6319111ca07dcc9ca1410840337a121c6bd5115e5972",
          "sha1": "723cb7719f403d98ce0693cb510e417ab42aced4",
          "md5": "5ea2bfc200887500bda2833df4ea2771"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-add-resource-encryption-service-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "5380d11eca5d9551f3e86ded1b1f41b6befa251f1f75081b6ce63fa939e7abed25857ba9891de46b26b288c66a4f6256b0607cc415e1133926ccb693b06b1818",
          "sha256": "5a5ee32c0b6a6ccd284b6319111ca07dcc9ca1410840337a121c6bd5115e5972",
          "sha1": "723cb7719f403d98ce0693cb510e417ab42aced4",
          "md5": "5ea2bfc200887500bda2833df4ea2771"
        }
      ]
    }
  ]
}
