{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.7.0-add-gradle-dependency-locking-SNAPSHOT/util-jvm-1.7.0-add-gradle-dependency-locking-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.7.0-add-gradle-dependency-locking-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "brdebwtobbbjvokrun4okdmq2u"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.7.0-add-gradle-dependency-locking-SNAPSHOT.jar",
          "url": "util-metadata-1.7.0-add-gradle-dependency-locking-SNAPSHOT.jar",
          "size": 6584,
          "sha512": "82e6d923422d4ef61afca828a97ebc12515d673067b97f42b4853d23b2dc0dc8b29787145312116b0625447667a45eca9444812e5d7f13d0c3c2beb926b47449",
          "sha256": "81403207e98cb6c6732de4cb9f4c84a676ccafd7e1aa643440d73895ba56afe9",
          "sha1": "8ce08ad457459a9c17761d0699fc1c60dc518201",
          "md5": "be711961fb90e03671d934921e98a5bd"
        }
      ]
    }
  ]
}
