{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-add-networking-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ovqqtql4fvehpib6k64hztsk34"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-networking-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-add-networking-contract-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-add-networking-contract-SNAPSHOT.aar",
          "size": 44947,
          "sha512": "550dea5be62134fb472a45764f53117102118f23bc1160bcbb47e1dd39825b00feb9091736dc44adee79f95a6a9d5066ee135c14b86f4dd555e75e4784a10ddb",
          "sha256": "d66679399f7f49dab1e740bb362ffd28d3243e08740e183a446fc3882521d2f6",
          "sha1": "c02e3cf5d5a5b57124e07b67f0f7df769ed9399d",
          "md5": "ed92185187acd62a41618dc92abe02f2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-add-networking-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-add-networking-contract-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-add-networking-contract-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-add-networking-contract-SNAPSHOT.aar",
          "size": 44947,
          "sha512": "550dea5be62134fb472a45764f53117102118f23bc1160bcbb47e1dd39825b00feb9091736dc44adee79f95a6a9d5066ee135c14b86f4dd555e75e4784a10ddb",
          "sha256": "d66679399f7f49dab1e740bb362ffd28d3243e08740e183a446fc3882521d2f6",
          "sha1": "c02e3cf5d5a5b57124e07b67f0f7df769ed9399d",
          "md5": "ed92185187acd62a41618dc92abe02f2"
        }
      ]
    }
  ]
}
