{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qakweihz5jhp5cvemvsem6bqga"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "e26cf3aa7e829005324b698b6a75ac6f6cc371fdea3635ba07495d7568ce263a89982140b8d7a2ab77bffcb99df18486687707fa5d5c0004e5c4651dcfc21aa1",
          "sha256": "709d963c5ab3775189c9841c52df1ccc49ac2f5dcd3366e79704f157b332ea42",
          "sha1": "e3b547d5cef3553160d02a96f3418eb5ce83bd79",
          "md5": "c2162fb12ef4279f3cc2f7430ae2f768"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "e26cf3aa7e829005324b698b6a75ac6f6cc371fdea3635ba07495d7568ce263a89982140b8d7a2ab77bffcb99df18486687707fa5d5c0004e5c4651dcfc21aa1",
          "sha256": "709d963c5ab3775189c9841c52df1ccc49ac2f5dcd3366e79704f157b332ea42",
          "sha1": "e3b547d5cef3553160d02a96f3418eb5ce83bd79",
          "md5": "c2162fb12ef4279f3cc2f7430ae2f768"
        }
      ]
    }
  ]
}
