{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-change-tagging-encoding-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jg7tjokwergndhbbp4w6ryopxm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "69194ae70c10be0485c954cf5c7a3ebd400c7bcf2c88b8bd355c73cf7eb6efe06c69b1f44042424e278b899a72b02935a12f525369603d5d85c0db6be97b26e0",
          "sha256": "f62b69f0034ec1e1b5930f8d6a80f9dd45718d88e62ba5406cb6d59c347e0cbd",
          "sha1": "82601368b6d1be6acfc5d9700c3125bab15df227",
          "md5": "089c94ce689271a9220d33c19cd6d871"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-change-tagging-encoding-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-change-tagging-encoding-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "69194ae70c10be0485c954cf5c7a3ebd400c7bcf2c88b8bd355c73cf7eb6efe06c69b1f44042424e278b899a72b02935a12f525369603d5d85c0db6be97b26e0",
          "sha256": "f62b69f0034ec1e1b5930f8d6a80f9dd45718d88e62ba5406cb6d59c347e0cbd",
          "sha1": "82601368b6d1be6acfc5d9700c3125bab15df227",
          "md5": "089c94ce689271a9220d33c19cd6d871"
        }
      ]
    }
  ]
}
