{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-change-tag-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fgehbeg3onclrdcsgzga4v7z4a"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "size": 51954,
          "sha512": "70454e342acb4704adebe4ab18b3163aecbeef8e321124cf28e1ab82edaa09162eda74af99cd51018a2568f689d343e76cb14300fe33b2097e2e17b73fa9a1d2",
          "sha256": "6d4e78f3ad7a73e8baf2cd4307a9b0d41b31c53e3d8a13ec80cd6696534e3504",
          "sha1": "cfc6ffa68f97975537ece15dd5a104ae9e3e6189",
          "md5": "d29dc1799d0eef41332df8681a5d8d03"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-change-tag-tests-SNAPSHOT.aar",
          "size": 51954,
          "sha512": "70454e342acb4704adebe4ab18b3163aecbeef8e321124cf28e1ab82edaa09162eda74af99cd51018a2568f689d343e76cb14300fe33b2097e2e17b73fa9a1d2",
          "sha256": "6d4e78f3ad7a73e8baf2cd4307a9b0d41b31c53e3d8a13ec80cd6696534e3504",
          "sha1": "cfc6ffa68f97975537ece15dd5a104ae9e3e6189",
          "md5": "d29dc1799d0eef41332df8681a5d8d03"
        }
      ]
    }
  ]
}
