{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uqhiwpdgfnczzag5r5sfh4rche"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b288408289b04280fc3866de5ff1e464c7f6cfba7f4d4c6fbf690930516572f9fa08dd24c6437f973dc5d20fcdebee227abb60985a63a3b41ffa8860ca24097e",
          "sha256": "5393c4f5d8114db38497dcbae3df40283bff25dcef14df7b65a5dd3d44a9c947",
          "sha1": "a64078e6b1c7b4085f278f7b6af94cffc5e93081",
          "md5": "b049593311dc9ee21fe9cb77a636e3b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b288408289b04280fc3866de5ff1e464c7f6cfba7f4d4c6fbf690930516572f9fa08dd24c6437f973dc5d20fcdebee227abb60985a63a3b41ffa8860ca24097e",
          "sha256": "5393c4f5d8114db38497dcbae3df40283bff25dcef14df7b65a5dd3d44a9c947",
          "sha1": "a64078e6b1c7b4085f278f7b6af94cffc5e93081",
          "md5": "b049593311dc9ee21fe9cb77a636e3b0"
        }
      ]
    }
  ]
}
