{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xn4cqacczvasvh6dqh5ii2fshm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "99aaccb28e1a7905e683c01eea7e3d30f129989ffc0eada886d5d2362d0ceb5c4f26bb338e6580e0b5409248b213b1cf5f33d9bf629a63880cbf4429f53624a1",
          "sha256": "55a284a834af89d9e4671eacd8172d9b7b36b448455c9c92dfcaef2d1bb78ec4",
          "sha1": "e4e78c86d8356ab39c368c082227b19be6823517",
          "md5": "94154ed1577cb7bb54563d4bbcbf5391"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "99aaccb28e1a7905e683c01eea7e3d30f129989ffc0eada886d5d2362d0ceb5c4f26bb338e6580e0b5409248b213b1cf5f33d9bf629a63880cbf4429f53624a1",
          "sha256": "55a284a834af89d9e4671eacd8172d9b7b36b448455c9c92dfcaef2d1bb78ec4",
          "sha1": "e4e78c86d8356ab39c368c082227b19be6823517",
          "md5": "94154ed1577cb7bb54563d4bbcbf5391"
        }
      ]
    }
  ]
}
