{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rnjrov47ovh2tp7hzipxsm7tvu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "43658bee80b8ffd10af106cc6f003388a7cf61f35acef5a3a78821bd9472d7c5d50215e4f6b301f37c9824015875f5f747320396533662b0712778b8121c6ae8",
          "sha256": "64c3dc30d01cbadc7010195601f9e3b02e2d652b340cbb322389fc3a78e0daba",
          "sha1": "d2ccaf6beca73709c450e6715b167650ace03a2d",
          "md5": "6ba7f00b76a149ae5d6d46dc7fc09fc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "size": 10855,
          "sha512": "43658bee80b8ffd10af106cc6f003388a7cf61f35acef5a3a78821bd9472d7c5d50215e4f6b301f37c9824015875f5f747320396533662b0712778b8121c6ae8",
          "sha256": "64c3dc30d01cbadc7010195601f9e3b02e2d652b340cbb322389fc3a78e0daba",
          "sha1": "d2ccaf6beca73709c450e6715b167650ace03a2d",
          "md5": "6ba7f00b76a149ae5d6d46dc7fc09fc4"
        }
      ]
    }
  ]
}
