{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "enqqfhmb3vdvphf56irbbmcjp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8ea2b341ba64ed3939f16c14586fe28fd5e266a51f2d450d9a6f8121bbc177bbf722c000afcf9698b2849727d72e811cae633fe22a3d296b11d5254a2974e286",
          "sha256": "97d2d748a4603e9beca2b75c6f5c85b2b4b3c6459bdcafde7efe320ba16054a1",
          "sha1": "e65da0f4161015ff9d3aff9898627ed464922e55",
          "md5": "5c2f000fedcbb6889d1e970a7698d1cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8ea2b341ba64ed3939f16c14586fe28fd5e266a51f2d450d9a6f8121bbc177bbf722c000afcf9698b2849727d72e811cae633fe22a3d296b11d5254a2974e286",
          "sha256": "97d2d748a4603e9beca2b75c6f5c85b2b4b3c6459bdcafde7efe320ba16054a1",
          "sha1": "e65da0f4161015ff9d3aff9898627ed464922e55",
          "md5": "5c2f000fedcbb6889d1e970a7698d1cd"
        }
      ]
    }
  ]
}
