{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bwy24dubdva5djrrcuvxm56d5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "4f7e433951533c41630e8d64b3b9a3840ae4f3a29cf53ee06eebc805e5d37d966617fc049b2743f658514dc46a6295172f2c937b7bcfb7457faae41215761409",
          "sha256": "87e84308721fa0b5a41f399cf35c1b8dfcfb5975a7fca6751b10aa86a1a9e3be",
          "sha1": "62adde9513ef4382be5eb0c8d8989a158ae66450",
          "md5": "2edaaec98cfb64f560c4e9e02fa97e31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "4f7e433951533c41630e8d64b3b9a3840ae4f3a29cf53ee06eebc805e5d37d966617fc049b2743f658514dc46a6295172f2c937b7bcfb7457faae41215761409",
          "sha256": "87e84308721fa0b5a41f399cf35c1b8dfcfb5975a7fca6751b10aa86a1a9e3be",
          "sha1": "62adde9513ef4382be5eb0c8d8989a158ae66450",
          "md5": "2edaaec98cfb64f560c4e9e02fa97e31"
        }
      ]
    }
  ]
}
