{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bjlqrxtr6feqvdwnzzqsiaiir4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.aar",
          "size": 51844,
          "sha512": "82e92c0f3f346272ce37fc1cd34f9fde31c8de3d4fd63a9935cf5dd3beaffe7e8fbd46c0751b1f78054003a936686bc32740d58825bf0fff6480847abdc2d0a9",
          "sha256": "6929c878f41cc338bd272dba7d920857fab67973dee5665b7c7f3d0c2445fc78",
          "sha1": "1f141dc85eaf3eee0965d4412d9663ab704baf46",
          "md5": "17c877dbfdd6feb86d6d5ea901c0f5ff"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.aar",
          "url": "crypto-android-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.aar",
          "size": 51844,
          "sha512": "82e92c0f3f346272ce37fc1cd34f9fde31c8de3d4fd63a9935cf5dd3beaffe7e8fbd46c0751b1f78054003a936686bc32740d58825bf0fff6480847abdc2d0a9",
          "sha256": "6929c878f41cc338bd272dba7d920857fab67973dee5665b7c7f3d0c2445fc78",
          "sha1": "1f141dc85eaf3eee0965d4412d9663ab704baf46",
          "md5": "17c877dbfdd6feb86d6d5ea901c0f5ff"
        }
      ]
    }
  ]
}
