{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dfqbqnnpgng5deyx5nnh2urune"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "11322c7be00c89f5c5b08ab278ecf1615a93357efcbe4bfd4dc1f437a24112a84db81df4f7f52ac49ecbe09c3bcf0d46bc3cbcd98686897a52d312823f03a5ac",
          "sha256": "9ed3c2d4e39bc25c4ea60955b32055be301915f334194ef630a6098e33dd7920",
          "sha1": "2b4ef0b177a38b5fe7025425ec2a253425b0000e",
          "md5": "2de2173e32f7c710696fa7357ad99e82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "11322c7be00c89f5c5b08ab278ecf1615a93357efcbe4bfd4dc1f437a24112a84db81df4f7f52ac49ecbe09c3bcf0d46bc3cbcd98686897a52d312823f03a5ac",
          "sha256": "9ed3c2d4e39bc25c4ea60955b32055be301915f334194ef630a6098e33dd7920",
          "sha1": "2b4ef0b177a38b5fe7025425ec2a253425b0000e",
          "md5": "2de2173e32f7c710696fa7357ad99e82"
        }
      ]
    }
  ]
}
