{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fi7anlizdzh4ngxnaamktd6r7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0812897a85753246c5edd44beffb521db8d901ca03ab6f231d8e82974535bb33b9a4d60a2f04392e70672f8a848df2dd568da341173c5ff693e6d8cf3d6ea7c4",
          "sha256": "e4ee25141176f20c840ac8601801a9ded3592d2372f299900eded5c1b540041e",
          "sha1": "bfc116e6db7dfbcfbf0075ae9eb6523227edcecc",
          "md5": "ef2a822175daf32e4d73dce0b961076e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0812897a85753246c5edd44beffb521db8d901ca03ab6f231d8e82974535bb33b9a4d60a2f04392e70672f8a848df2dd568da341173c5ff693e6d8cf3d6ea7c4",
          "sha256": "e4ee25141176f20c840ac8601801a9ded3592d2372f299900eded5c1b540041e",
          "sha1": "bfc116e6db7dfbcfbf0075ae9eb6523227edcecc",
          "md5": "ef2a822175daf32e4d73dce0b961076e"
        }
      ]
    }
  ]
}
