{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-fix-search-count-api-call-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3zsqnthe7rerjmbd6qiqaozyxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "bdbb4d5f7b71de4352b88340ffd6f4255d1443308944a42c0002418649c04fae16af83251167c1302709cfdaa84dc232984bb999a4748c764e6c49d1049c7531",
          "sha256": "6b388e3e45a06cbcba8018ac430190c49e76b144013eca6679820e69d9d38519",
          "sha1": "9c33295558784d2dfbf9c21a6139152c897a8be2",
          "md5": "2970b3bcdfdd5c7e0945b4df2991dbfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-fix-search-count-api-call-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "bdbb4d5f7b71de4352b88340ffd6f4255d1443308944a42c0002418649c04fae16af83251167c1302709cfdaa84dc232984bb999a4748c764e6c49d1049c7531",
          "sha256": "6b388e3e45a06cbcba8018ac430190c49e76b144013eca6679820e69d9d38519",
          "sha1": "9c33295558784d2dfbf9c21a6139152c897a8be2",
          "md5": "2970b3bcdfdd5c7e0945b4df2991dbfc"
        }
      ]
    }
  ]
}
