{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-add-public-userid-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kp4u7z3745gyxhwrzcp3wzcwj4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-public-userid-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "6db7bbaba2cbaadd4b8f7ad9548a6ff99e40d1972aa3a4ab162cdd5b16978f82dd2937937b326ac4e2e880efbae4934324c7d62b277a10b18f630f6642bc5e44",
          "sha256": "c127f3623fdf6aac6d05ecda7f91b24a3c39d70540e08d273adbbd9daf50246c",
          "sha1": "a38dae9164a25962913014486ef764e4b6651d5c",
          "md5": "cec0bd4500fe2d8fecd1ea136ecd5358"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-public-userid-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "6db7bbaba2cbaadd4b8f7ad9548a6ff99e40d1972aa3a4ab162cdd5b16978f82dd2937937b326ac4e2e880efbae4934324c7d62b277a10b18f630f6642bc5e44",
          "sha256": "c127f3623fdf6aac6d05ecda7f91b24a3c39d70540e08d273adbbd9daf50246c",
          "sha1": "a38dae9164a25962913014486ef764e4b6651d5c",
          "md5": "cec0bd4500fe2d8fecd1ea136ecd5358"
        }
      ]
    }
  ]
}
