{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qpj2yhlstbbb7i7lrnp3i42ggy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "8004c49bd30a43d824f2a16e3691590cf6dbe0d0399e4a5c4163f961ca86a8a8c79d28d0cae635f1130df7d35a9957956c763264dae21a0d50f4de26e4f4e3c6",
          "sha256": "ffa318f5f9256d98e0f85136cff450d54797cc7adc4ed53db4ef1d2047f74edc",
          "sha1": "3f854f29eab01b1dad1e0d2bc7d3fb1196219e07",
          "md5": "8fab8df73927c8a788275408ebf2d6b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "8004c49bd30a43d824f2a16e3691590cf6dbe0d0399e4a5c4163f961ca86a8a8c79d28d0cae635f1130df7d35a9957956c763264dae21a0d50f4de26e4f4e3c6",
          "sha256": "ffa318f5f9256d98e0f85136cff450d54797cc7adc4ed53db4ef1d2047f74edc",
          "sha1": "3f854f29eab01b1dad1e0d2bc7d3fb1196219e07",
          "md5": "8fab8df73927c8a788275408ebf2d6b0"
        }
      ]
    }
  ]
}
