{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uqhiwpdgfnczzag5r5sfh4rche"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "96c2d5d1547bbcdbd11f287fa4c04f1acc605d9e6bb1af8d4ce5d22febb8fd23144bece35c50aa5b003a45e36b57029a5670278395de12c642ef10f43f019f09",
          "sha256": "0c84bc943d9630d6aa21ee48875b599057a282bb07d8ea22679bbdb72ec2cabd",
          "sha1": "f95cb8001eaccc88d870155802142fa57edda9ec",
          "md5": "41f1ae38cd4e5dc1dfa671e95c82bf41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "96c2d5d1547bbcdbd11f287fa4c04f1acc605d9e6bb1af8d4ce5d22febb8fd23144bece35c50aa5b003a45e36b57029a5670278395de12c642ef10f43f019f09",
          "sha256": "0c84bc943d9630d6aa21ee48875b599057a282bb07d8ea22679bbdb72ec2cabd",
          "sha1": "f95cb8001eaccc88d870155802142fa57edda9ec",
          "md5": "41f1ae38cd4e5dc1dfa671e95c82bf41"
        }
      ]
    }
  ]
}
