{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5ph2gi7uebgnrcbd2s4f6dhuxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "bff14a85ab734fa7b179bee17a4d770ce1663979544f037c254b7f7dfdb1666c75c9e5678ee9c628c54018e66f28cdb3d9e5ed9f10ec31e08f4bb1603161aed9",
          "sha256": "7edf1081125b0d1b7bfa100029e9aab318ed513c5d9294a57a551a9b36933da8",
          "sha1": "107c09c5db21af8adc9fa9f98745aa7d37550585",
          "md5": "faef242ed2eea3353be8752aa48cf415"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "bff14a85ab734fa7b179bee17a4d770ce1663979544f037c254b7f7dfdb1666c75c9e5678ee9c628c54018e66f28cdb3d9e5ed9f10ec31e08f4bb1603161aed9",
          "sha256": "7edf1081125b0d1b7bfa100029e9aab318ed513c5d9294a57a551a9b36933da8",
          "sha1": "107c09c5db21af8adc9fa9f98745aa7d37550585",
          "md5": "faef242ed2eea3353be8752aa48cf415"
        }
      ]
    }
  ]
}
