{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.11.0-change-decrypted-record-definitions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rhzzoimqbnhwpakrp2kvqterka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-decrypted-record-definitions-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "d03836c1df318e84e95df5e6e6c39b165ab426d694a9b665d4efd3d747a7151ae3766982585aefcc6088bb4a959578bb199d989838ed1fa2ffb265ebb087f63f",
          "sha256": "449c287f6855a4c88a827a098cf82c32e5aa3fce7c99b2176b7945fa1012600f",
          "sha1": "3ca82a2a792419ae1ebc9c9e8b45f36854d5b158",
          "md5": "630fb3d8874b87c04b677d103042b816"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-decrypted-record-definitions-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "url": "securestore-jvm-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "d03836c1df318e84e95df5e6e6c39b165ab426d694a9b665d4efd3d747a7151ae3766982585aefcc6088bb4a959578bb199d989838ed1fa2ffb265ebb087f63f",
          "sha256": "449c287f6855a4c88a827a098cf82c32e5aa3fce7c99b2176b7945fa1012600f",
          "sha1": "3ca82a2a792419ae1ebc9c9e8b45f36854d5b158",
          "md5": "630fb3d8874b87c04b677d103042b816"
        }
      ]
    }
  ]
}
