{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ec4ea6r24vevhm4cwchkbgeolm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 465144,
          "sha512": "f4dacd77ee0e182ba4effd9b07e8e00d67d85877de769683bc1a94410fe4933aafd974ba118597fbc5a2ab078bec47eb0968517bd84193d6d68d312c94c90d20",
          "sha256": "c9a265096cc195afb695b4750c30af55819e96c37c34a18503fdcabdfc460fc3",
          "sha1": "1ea3d2f0ffe90861c70d28368dbd08b670388122",
          "md5": "ef7509e0342e7c4cb3fc1d332da617c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 465144,
          "sha512": "f4dacd77ee0e182ba4effd9b07e8e00d67d85877de769683bc1a94410fe4933aafd974ba118597fbc5a2ab078bec47eb0968517bd84193d6d68d312c94c90d20",
          "sha256": "c9a265096cc195afb695b4750c30af55819e96c37c34a18503fdcabdfc460fc3",
          "sha1": "1ea3d2f0ffe90861c70d28368dbd08b670388122",
          "md5": "ef7509e0342e7c4cb3fc1d332da617c8"
        }
      ]
    }
  ]
}
