{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.2-change-recordservice-crypto-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bjmffnrewvfpjimoavhgpltn74"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.2-change-recordservice-crypto-test-SNAPSHOT.aar",
          "url": "crypto-android-1.9.2-change-recordservice-crypto-test-SNAPSHOT.aar",
          "size": 51838,
          "sha512": "ee751ad5149de59de6a08b855ed67a0d28398e36fedd950bc8af50f01e842024f4325996c7a3568c2ab8cbec4c82d6a0572e5df9a7accdb4f5281f0cbeb7aa4a",
          "sha256": "b6d41ba09b442d840de7eaf094830778285e5379ca1e8171d0ef400cc67fede4",
          "sha1": "5112e53c42161f3dbd5b6a8fd9be4a83ef120146",
          "md5": "bbe99466412324abb2a21502cb3e1abc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.2-change-recordservice-crypto-test-SNAPSHOT.aar",
          "url": "crypto-android-1.9.2-change-recordservice-crypto-test-SNAPSHOT.aar",
          "size": 51838,
          "sha512": "ee751ad5149de59de6a08b855ed67a0d28398e36fedd950bc8af50f01e842024f4325996c7a3568c2ab8cbec4c82d6a0572e5df9a7accdb4f5281f0cbeb7aa4a",
          "sha256": "b6d41ba09b442d840de7eaf094830778285e5379ca1e8171d0ef400cc67fede4",
          "sha1": "5112e53c42161f3dbd5b6a8fd9be4a83ef120146",
          "md5": "bbe99466412324abb2a21502cb3e1abc"
        }
      ]
    }
  ]
}
