{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-bump-update-fhir-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nd6oie6ysjboxkcwyybcj7bbzm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-bump-update-fhir-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "dce90252f47c58c3c4cca3a3cfedceed476f8544986cc1fb5c09196561d31bde0985c82a4b8fb7f11255dc22c70a267614f549b39a521e14e09814893c8636f8",
          "sha256": "af0afe66757fd844ff680d58b80ab6a11db600768c3c4bf4a49a5c193bfcab9b",
          "sha1": "63cb0c6b17c21a010e4c9e15dce95e53a90bf286",
          "md5": "5aefc7b77bb0d82ac78bf1fc0e34c05b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-bump-update-fhir-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "dce90252f47c58c3c4cca3a3cfedceed476f8544986cc1fb5c09196561d31bde0985c82a4b8fb7f11255dc22c70a267614f549b39a521e14e09814893c8636f8",
          "sha256": "af0afe66757fd844ff680d58b80ab6a11db600768c3c4bf4a49a5c193bfcab9b",
          "sha1": "63cb0c6b17c21a010e4c9e15dce95e53a90bf286",
          "md5": "5aefc7b77bb0d82ac78bf1fc0e34c05b"
        }
      ]
    }
  ]
}
