{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4l73c3bqrza5dgzs5aamnxtud4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "fa1ece353807bd968b4c558f0782d3c639f12e970a59af3790fefd7f4f5b6ab064f532cb9a1515ed5109fa95e928d50838cfe4270e5cf8781d94b4300744ac99",
          "sha256": "a334e92071311d91be30c4fb6a421c18050790e59629ca98f3accb24713ad814",
          "sha1": "1b186fb38800f6ea66fb137dce584afa67f7d62e",
          "md5": "83dcac79819cf2836a4fec51737e8023"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "fa1ece353807bd968b4c558f0782d3c639f12e970a59af3790fefd7f4f5b6ab064f532cb9a1515ed5109fa95e928d50838cfe4270e5cf8781d94b4300744ac99",
          "sha256": "a334e92071311d91be30c4fb6a421c18050790e59629ca98f3accb24713ad814",
          "sha1": "1b186fb38800f6ea66fb137dce584afa67f7d62e",
          "md5": "83dcac79819cf2836a4fec51737e8023"
        }
      ]
    }
  ]
}
