{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "or57dccynrfj7i3n64cav5czii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "b35f2ab1a6491f965fd65b4c4eea3a2c4cace3b1f2b5afbd7c6c2a8aa3bb918c7ee18f07d91bbeeffadd6b6071c09c93acc139f19ecf421567cd59b6a84b7578",
          "sha256": "3e8ceab49b379a78cb4bb88d8af129d5544aefe8cd57cd57fe76d64684547f9b",
          "sha1": "02455d380b100a3f401b764c9714a90e64de39ac",
          "md5": "a16cb5fd716238040d45c401ea1cea8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "b35f2ab1a6491f965fd65b4c4eea3a2c4cace3b1f2b5afbd7c6c2a8aa3bb918c7ee18f07d91bbeeffadd6b6071c09c93acc139f19ecf421567cd59b6a84b7578",
          "sha256": "3e8ceab49b379a78cb4bb88d8af129d5544aefe8cd57cd57fe76d64684547f9b",
          "sha1": "02455d380b100a3f401b764c9714a90e64de39ac",
          "md5": "a16cb5fd716238040d45c401ea1cea8e"
        }
      ]
    }
  ]
}
