{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-user-info-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3at7kjh3mbahxhqzgufly3v7aq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "88bb83b08d493aff9ed07030018897dcb9be39d43be5d0c21e6dc972e49c964b00998517fdca97fded2ce91c3d427212bceefdff56b38843c583a14c57c44412",
          "sha256": "d41bf7b87d7ba5e3aaa59aa257ba14e544138c94b2e55ca730491f2dab28ca64",
          "sha1": "376f5054b3e886ca9bb22e1acffa2a15399427e0",
          "md5": "8ac3cab983f4142735800c7c5f75ba1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "88bb83b08d493aff9ed07030018897dcb9be39d43be5d0c21e6dc972e49c964b00998517fdca97fded2ce91c3d427212bceefdff56b38843c583a14c57c44412",
          "sha256": "d41bf7b87d7ba5e3aaa59aa257ba14e544138c94b2e55ca730491f2dab28ca64",
          "sha1": "376f5054b3e886ca9bb22e1acffa2a15399427e0",
          "md5": "8ac3cab983f4142735800c7c5f75ba1e"
        }
      ]
    }
  ]
}
