{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-user-info-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "o22vsrhwmzhizi7zpknq5ftu7y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "894c0cef19e854b773abdaf4d4e014d38058a81eacbb7787e369729aed6f58966bd966773dbe85a0ab7340cf516d953b26ad7e039f2b4d09f073a7fcdf631007",
          "sha256": "82e5c44890fd857b8fa06829762d3df7dee7f36f613e470775940f83aa21f059",
          "sha1": "8649e9fe011ad82e458f5703406d8f8d19a0faac",
          "md5": "596a52ea6c19296b53bf2805f2081fd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "894c0cef19e854b773abdaf4d4e014d38058a81eacbb7787e369729aed6f58966bd966773dbe85a0ab7340cf516d953b26ad7e039f2b4d09f073a7fcdf631007",
          "sha256": "82e5c44890fd857b8fa06829762d3df7dee7f36f613e470775940f83aa21f059",
          "sha1": "8649e9fe011ad82e458f5703406d8f8d19a0faac",
          "md5": "596a52ea6c19296b53bf2805f2081fd5"
        }
      ]
    }
  ]
}
