{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-bump-update-fhir-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nd6oie6ysjboxkcwyybcj7bbzm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "6fcb18ba47a57da37317d51875001fc349b09890f03aa6b217eb25c741efcce1e75a46d15b69ac284a00cd9dbd80fe204a447895d8778e4b0010aaf4b3422b4b",
          "sha256": "4dbc3d320f09d65930b666ce7fd354d8883733e37a6226e379130c789e079650",
          "sha1": "01473f46a66db873e8f3fc70b57bb0e5bb8b46c6",
          "md5": "1d9158f5ba9ba2848a57fe3c24a6f6bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-bump-update-fhir-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "6fcb18ba47a57da37317d51875001fc349b09890f03aa6b217eb25c741efcce1e75a46d15b69ac284a00cd9dbd80fe204a447895d8778e4b0010aaf4b3422b4b",
          "sha256": "4dbc3d320f09d65930b666ce7fd354d8883733e37a6226e379130c789e079650",
          "sha1": "01473f46a66db873e8f3fc70b57bb0e5bb8b46c6",
          "md5": "1d9158f5ba9ba2848a57fe3c24a6f6bf"
        }
      ]
    }
  ]
}
