{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.0-add-codeowner-file-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uv37b57dtndp5py35xyridc4du"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-add-codeowner-file-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.0-add-codeowner-file-SNAPSHOT.aar",
          "url": "crypto-android-1.9.0-add-codeowner-file-SNAPSHOT.aar",
          "size": 51830,
          "sha512": "8dd80d5c9be510dfcf7fa98e7165125059f5fc44891cd2a8dd0a8843a64eabfd04634c1a2230f55f434f9908d83677be4adb3a7391d40395262e77cf33ee58a4",
          "sha256": "21d3adcdd742cf0988534210c9679aad64f34d676ab23136224381c3190da196",
          "sha1": "c14f5ec811f7e50e5caa47f50995ffb2ed966c43",
          "md5": "2753ab62a78f9d18d37ecbdb9d1053ef"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-add-codeowner-file-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.0-add-codeowner-file-SNAPSHOT.aar",
          "url": "crypto-android-1.9.0-add-codeowner-file-SNAPSHOT.aar",
          "size": 51830,
          "sha512": "8dd80d5c9be510dfcf7fa98e7165125059f5fc44891cd2a8dd0a8843a64eabfd04634c1a2230f55f434f9908d83677be4adb3a7391d40395262e77cf33ee58a4",
          "sha256": "21d3adcdd742cf0988534210c9679aad64f34d676ab23136224381c3190da196",
          "sha1": "c14f5ec811f7e50e5caa47f50995ffb2ed966c43",
          "md5": "2753ab62a78f9d18d37ecbdb9d1053ef"
        }
      ]
    }
  ]
}
