{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mqcpuq73arb4ppmqu2hzevedli"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "ffa9cd91a9331fbd0ef0c3198ef20050bc78799019c549745ca87fa3640da162464bcdbffbb0dd1a29f707192838315572a4c2901041d0ffd457c4e31147191a",
          "sha256": "e0b8e1a8ec7669ecd18a5b59f392eb2aab8b7173fd492edafe455f1e8a99df93",
          "sha1": "9cb9c531e202b036ae9ea5323df836e4938ee007",
          "md5": "5f339927d1207b5ec4aa175f1e8074b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "ffa9cd91a9331fbd0ef0c3198ef20050bc78799019c549745ca87fa3640da162464bcdbffbb0dd1a29f707192838315572a4c2901041d0ffd457c4e31147191a",
          "sha256": "e0b8e1a8ec7669ecd18a5b59f392eb2aab8b7173fd492edafe455f1e8a99df93",
          "sha1": "9cb9c531e202b036ae9ea5323df836e4938ee007",
          "md5": "5f339927d1207b5ec4aa175f1e8074b2"
        }
      ]
    }
  ]
}
