{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ed42tcj7wvazldtj4ajihfe3uu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "a668afa07c619ac1259d438ede7de7cd166955fda5497216bb90ec80b02433387db18b53abc4811c18f85f0a919ce0b9ef243c3bf83960c965b4ea44418cf783",
          "sha256": "5a53b13ec48ea25be8adcc272b1a00105bd1b6585aaf991f01c3aba6c227a02c",
          "sha1": "86aabbbdeffe46bd206eeb979eeedf8365967c74",
          "md5": "5c5924202281d3aa0d9c6887f3e39158"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "a668afa07c619ac1259d438ede7de7cd166955fda5497216bb90ec80b02433387db18b53abc4811c18f85f0a919ce0b9ef243c3bf83960c965b4ea44418cf783",
          "sha256": "5a53b13ec48ea25be8adcc272b1a00105bd1b6585aaf991f01c3aba6c227a02c",
          "sha1": "86aabbbdeffe46bd206eeb979eeedf8365967c74",
          "md5": "5c5924202281d3aa0d9c6887f3e39158"
        }
      ]
    }
  ]
}
