{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nz6yfyustbadrjljfp7uu6fuje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d2fbc99cf955a2f47724d50ec80a0f2a3f5f9366bbaa892b4525592bea8c4f9c8c4279bb6be2d842ba782d8883f2a35d11bc6d37b580274065b0630459dc00b8",
          "sha256": "0a296af86b9c8e360d69683d993d22af6ec2eca8b168047470885f8f24302846",
          "sha1": "d9a3b2a0c67c72acaa0cf9e227246413ea97169e",
          "md5": "36c35dea25d60a8a3b2eebf6d952371f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-test-recordservice-leftovers-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d2fbc99cf955a2f47724d50ec80a0f2a3f5f9366bbaa892b4525592bea8c4f9c8c4279bb6be2d842ba782d8883f2a35d11bc6d37b580274065b0630459dc00b8",
          "sha256": "0a296af86b9c8e360d69683d993d22af6ec2eca8b168047470885f8f24302846",
          "sha1": "d9a3b2a0c67c72acaa0cf9e227246413ea97169e",
          "md5": "36c35dea25d60a8a3b2eebf6d952371f"
        }
      ]
    }
  ]
}
