{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zt2zqpbavncx3botu5tvhxr7cy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5f8ad0c3fa199e03d13aea63fd111b1237f317c8ef7f86cf804a6735d46e250db37dabd6b849279cc70ac55d65048d5b07346f6f397ecee85b3f8f5e740fed65",
          "sha256": "0951f2d7429b9348c53bdff7fc72b22373d6118ddbc59f184471753729d3173f",
          "sha1": "2f18ad79a46393fdbde13658cec2f7074e38a013",
          "md5": "f45b487aa61ca42671adb7dc70834656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "5f8ad0c3fa199e03d13aea63fd111b1237f317c8ef7f86cf804a6735d46e250db37dabd6b849279cc70ac55d65048d5b07346f6f397ecee85b3f8f5e740fed65",
          "sha256": "0951f2d7429b9348c53bdff7fc72b22373d6118ddbc59f184471753729d3173f",
          "sha1": "2f18ad79a46393fdbde13658cec2f7074e38a013",
          "md5": "f45b487aa61ca42671adb7dc70834656"
        }
      ]
    }
  ]
}
