{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2xtkg4arcjduphpx2djj7egbhm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "e07041333cb0c0987a6bd6a9f0ad289e9ec06ecc3b42b8a1ef1d30324778e050cc8fae35a13c2f8ea31de28c1ea22aa208abdd48b1e11011c8362556f48bba9e",
          "sha256": "63382979b4e6d11501bf745608b8f1c487cb478c3107cc492f3abaee2f81384d",
          "sha1": "128298972e3ec7d8a71e94ff043ed852cc88ba84",
          "md5": "c9688762738c2aa1c29d944bcd0b8a4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "e07041333cb0c0987a6bd6a9f0ad289e9ec06ecc3b42b8a1ef1d30324778e050cc8fae35a13c2f8ea31de28c1ea22aa208abdd48b1e11011c8362556f48bba9e",
          "sha256": "63382979b4e6d11501bf745608b8f1c487cb478c3107cc492f3abaee2f81384d",
          "sha1": "128298972e3ec7d8a71e94ff043ed852cc88ba84",
          "md5": "c9688762738c2aa1c29d944bcd0b8a4b"
        }
      ]
    }
  ]
}
