{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-data-resource-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vtq5ykq5jndbngibx2fzqtishy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "e789f2f377e8c176b1db53ff48e967cb7e7d218ea2af9f33c644dc954715eeaf2b704a651e87ed4230bb6780d5e17bd24cf65645ba642fd932f9b804ec748e7c",
          "sha256": "467e086f830dcd75c277e017ae86e526d66c9d1156e28fa122ba5da460fbe828",
          "sha1": "1c38b4d84eccf7aec4d340c38c1e3eadfbce0bb3",
          "md5": "9454b398eba594a0a064c940d97787d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "e789f2f377e8c176b1db53ff48e967cb7e7d218ea2af9f33c644dc954715eeaf2b704a651e87ed4230bb6780d5e17bd24cf65645ba642fd932f9b804ec748e7c",
          "sha256": "467e086f830dcd75c277e017ae86e526d66c9d1156e28fa122ba5da460fbe828",
          "sha1": "1c38b4d84eccf7aec4d340c38c1e3eadfbce0bb3",
          "md5": "9454b398eba594a0a064c940d97787d2"
        }
      ]
    }
  ]
}
