{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.11.0-change-data-resource-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yd6cmoqvw5gtxadrkzzeeddmfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "040b54242b93928e726747283a448e4be0786dd521d99004edc65a067a4503e828219fcd4b95fee7b3d380004c1067b915104503dc902e0bec6aad4e741e4d10",
          "sha256": "79116c615c22a6eb606a85e18a4a90670487cdd020b7e95195a1512ec7aadfa2",
          "sha1": "b37090a23225bb33258ae068a283b57768abfbb0",
          "md5": "e776da5a0b0097c0a12d422f092ce837"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "url": "crypto-jvm-1.11.0-change-data-resource-SNAPSHOT.jar",
          "size": 57138,
          "sha512": "040b54242b93928e726747283a448e4be0786dd521d99004edc65a067a4503e828219fcd4b95fee7b3d380004c1067b915104503dc902e0bec6aad4e741e4d10",
          "sha256": "79116c615c22a6eb606a85e18a4a90670487cdd020b7e95195a1512ec7aadfa2",
          "sha1": "b37090a23225bb33258ae068a283b57768abfbb0",
          "md5": "e776da5a0b0097c0a12d422f092ce837"
        }
      ]
    }
  ]
}
