{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zt2zqpbavncx3botu5tvhxr7cy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 456230,
          "sha512": "8b0f9693686622bbaf92cfd0aded39dd4a301bcb5dea17584eab3db1983236136797a65d2bfb8f5ed01de1005db1aec7ce32c77438098c56b9e38f4d860cd645",
          "sha256": "e92557b87aafdc4b03ec2e5a8527e47bba6a60ba61c6aea01dbe95db8f2cc8fb",
          "sha1": "38befe0956ca605f1e47a874dc8e1dd198392a72",
          "md5": "f8a6f36308307ce66694180b6ede0639"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 456230,
          "sha512": "8b0f9693686622bbaf92cfd0aded39dd4a301bcb5dea17584eab3db1983236136797a65d2bfb8f5ed01de1005db1aec7ce32c77438098c56b9e38f4d860cd645",
          "sha256": "e92557b87aafdc4b03ec2e5a8527e47bba6a60ba61c6aea01dbe95db8f2cc8fb",
          "sha1": "38befe0956ca605f1e47a874dc8e1dd198392a72",
          "md5": "f8a6f36308307ce66694180b6ede0639"
        }
      ]
    }
  ]
}
