{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zfqw324xfbgbtimlicwgf4hbcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "6b13c124594853c2a95f80b05892af8b387c9e5230ef1f16e66a5c84e45dcc22ab41e59146a42f4466aab9f73ed73b572684a752dfb887c30957d93b4b9beb80",
          "sha256": "50f1c91c52374a1f644197dbb1042c54b52fd7fd1cf7cf57a8546cda5ac72bc3",
          "sha1": "9a967413c0907ca2d45d87b1dec1409cbd86e6cf",
          "md5": "0a3ffc050fa2fa94f316b7cc3f3e036e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "6b13c124594853c2a95f80b05892af8b387c9e5230ef1f16e66a5c84e45dcc22ab41e59146a42f4466aab9f73ed73b572684a752dfb887c30957d93b4b9beb80",
          "sha256": "50f1c91c52374a1f644197dbb1042c54b52fd7fd1cf7cf57a8546cda5ac72bc3",
          "sha1": "9a967413c0907ca2d45d87b1dec1409cbd86e6cf",
          "md5": "0a3ffc050fa2fa94f316b7cc3f3e036e"
        }
      ]
    }
  ]
}
