{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.11.0-change-data-resource-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yd6cmoqvw5gtxadrkzzeeddmfe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "size": 61904,
          "sha512": "ed250d7c8a882f3830f9ab9980fdfd9d770d74fcf20ccaa3532c97c1b24083390aae7a7a5acd1a0143f79c20064336c625200449b0d10ff4b5b897d4ef266d66",
          "sha256": "949e0e23ea830c920241c4056b49f047c4fce4de77211f1ad9b53e42189bc505",
          "sha1": "ef7f5499d216b25c7b633702a870abb6ff1181fb",
          "md5": "89fcda5836fd65e8f5c13f1f3bfefccd"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "url": "crypto-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "size": 61904,
          "sha512": "ed250d7c8a882f3830f9ab9980fdfd9d770d74fcf20ccaa3532c97c1b24083390aae7a7a5acd1a0143f79c20064336c625200449b0d10ff4b5b897d4ef266d66",
          "sha256": "949e0e23ea830c920241c4056b49f047c4fce4de77211f1ad9b53e42189bc505",
          "sha1": "ef7f5499d216b25c7b633702a870abb6ff1181fb",
          "md5": "89fcda5836fd65e8f5c13f1f3bfefccd"
        }
      ]
    }
  ]
}
