{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sz3r3xffkfbm7h4fijct73k7fm"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "size": 44906,
          "sha512": "6f59e78e288b5e4f72e609c188b810a928c218124131524f100bf7553beeab31d0f24cf2359b2debd6d6c2cfdcb92d625401fa8012ce2b84cf4504917eac6512",
          "sha256": "50b2cbe15fd03b78136d42ddc9dff09266ca7a0dfb8dc2c11d8eebc5f1b154d5",
          "sha1": "1190e5d02a82221239b7fb4ad8bb1dc4ab57252b",
          "md5": "6f18882aa95eccc904c24324cc46a9ab"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.aar",
          "size": 44906,
          "sha512": "6f59e78e288b5e4f72e609c188b810a928c218124131524f100bf7553beeab31d0f24cf2359b2debd6d6c2cfdcb92d625401fa8012ce2b84cf4504917eac6512",
          "sha256": "50b2cbe15fd03b78136d42ddc9dff09266ca7a0dfb8dc2c11d8eebc5f1b154d5",
          "sha1": "1190e5d02a82221239b7fb4ad8bb1dc4ab57252b",
          "md5": "6f18882aa95eccc904c24324cc46a9ab"
        }
      ]
    }
  ]
}
