{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kbq63nxerffnrfw7qmmxelluri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "0c0c331edcb39a97c924fb8ed216cb6a5ab98fddec857645d274618059b6ca9af9066faf84468e3bb74f79c59293b1cdd2f51aa796c355374982f58660f8f5c7",
          "sha256": "f14a6acb142ae51caeaaa2b5f6e7e3caff56822f0b551e6424bc33000473690b",
          "sha1": "69dbc1f56a6cd0f518f2ed19e5537b181bebc2b2",
          "md5": "03e667a6cc35887be4532fe3376ef236"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "0c0c331edcb39a97c924fb8ed216cb6a5ab98fddec857645d274618059b6ca9af9066faf84468e3bb74f79c59293b1cdd2f51aa796c355374982f58660f8f5c7",
          "sha256": "f14a6acb142ae51caeaaa2b5f6e7e3caff56822f0b551e6424bc33000473690b",
          "sha1": "69dbc1f56a6cd0f518f2ed19e5537b181bebc2b2",
          "md5": "03e667a6cc35887be4532fe3376ef236"
        }
      ]
    }
  ]
}
