{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-network-model-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "qiqytyzdpzgi7kdggmyetgjnlu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "bf30fbda37aa8dc95e5461f1c9a945b52a2bac1995a733a2660ecc76fe60ee61028ff1de00bab7724ea407d67aaec91d7344feb14a1620fb33bd97a757d952e8",
          "sha256": "ff63760b424a548bc5a1d2490473c006dfffa5b8e431270edbf561676591ecde",
          "sha1": "366a3b5bcf2ef1d05b455679cd557b2d6a1b38ff",
          "md5": "3b7b23334897e0789924b2fd01dbfcbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "bf30fbda37aa8dc95e5461f1c9a945b52a2bac1995a733a2660ecc76fe60ee61028ff1de00bab7724ea407d67aaec91d7344feb14a1620fb33bd97a757d952e8",
          "sha256": "ff63760b424a548bc5a1d2490473c006dfffa5b8e431270edbf561676591ecde",
          "sha1": "366a3b5bcf2ef1d05b455679cd557b2d6a1b38ff",
          "md5": "3b7b23334897e0789924b2fd01dbfcbb"
        }
      ]
    }
  ]
}
