{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "h2sp3o6kxjeltkj72ecygshhxi"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "size": 51968,
          "sha512": "b65a38dfbc611cae3af90c32ce6b08083c76dcc036cfcf89a3d86cbe113826436e94b482691e2c9b2f011d1c7aceb045b8d204ebc932a6dcf71e141d37dbea63",
          "sha256": "7a8d2736e2e1549ed63eb191b630478b4587d965faba22ad90b42590d8be04b2",
          "sha1": "02672d6d7587b8989473d8e26a88a2f9ac3a1783",
          "md5": "41fb0d94a57ec69ae24f75444f46454b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "size": 51968,
          "sha512": "b65a38dfbc611cae3af90c32ce6b08083c76dcc036cfcf89a3d86cbe113826436e94b482691e2c9b2f011d1c7aceb045b8d204ebc932a6dcf71e141d37dbea63",
          "sha256": "7a8d2736e2e1549ed63eb191b630478b4587d965faba22ad90b42590d8be04b2",
          "sha1": "02672d6d7587b8989473d8e26a88a2f9ac3a1783",
          "md5": "41fb0d94a57ec69ae24f75444f46454b"
        }
      ]
    }
  ]
}
