{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rnjrov47ovh2tp7hzipxsm7tvu"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "size": 51875,
          "sha512": "14092291787173ed28d1b0ce7a70521e64be8af9375c82b42f64e4aef0404370226af562910252256c65ef30bedfc8606cc8000fa6e9169d08a360e9089f020b",
          "sha256": "36cd93bf9a6664731cb6a3bcd6a9477aac8f69c6f5e335160cbcb754c7597d79",
          "sha1": "4be2acc14f177074522d87c4170a8a925300ac7b",
          "md5": "e019a3725d81692465ca8df8117eaf22"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "size": 51875,
          "sha512": "14092291787173ed28d1b0ce7a70521e64be8af9375c82b42f64e4aef0404370226af562910252256c65ef30bedfc8606cc8000fa6e9169d08a360e9089f020b",
          "sha256": "36cd93bf9a6664731cb6a3bcd6a9477aac8f69c6f5e335160cbcb754c7597d79",
          "sha1": "4be2acc14f177074522d87c4170a8a925300ac7b",
          "md5": "e019a3725d81692465ca8df8117eaf22"
        }
      ]
    }
  ]
}
