{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.2-add-crypto-service-interface-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7vdoo7el4nhrhlao4geitoadoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 11324,
          "sha512": "4e3ec00b746a5a4989c80fa725b4d242d184cc26e14cf1fec60672bcf14505632f496ba3a2fa96e0ab3c68a6fe6a78d39236aa6bbf6b1df9480bf884086652de",
          "sha256": "918f745ed7a541a1a6c57a5f99d4d8e215628433a13cbce767fdfdd574a824c7",
          "sha1": "7972cc2d65b960899d519d752221e4e8883863e8",
          "md5": "0193f16aa92c47f52d575dc7f1a297a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 11324,
          "sha512": "4e3ec00b746a5a4989c80fa725b4d242d184cc26e14cf1fec60672bcf14505632f496ba3a2fa96e0ab3c68a6fe6a78d39236aa6bbf6b1df9480bf884086652de",
          "sha256": "918f745ed7a541a1a6c57a5f99d4d8e215628433a13cbce767fdfdd574a824c7",
          "sha1": "7972cc2d65b960899d519d752221e4e8883863e8",
          "md5": "0193f16aa92c47f52d575dc7f1a297a8"
        }
      ]
    }
  ]
}
