{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-crypto-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uf537qzlr5a6jigmhnxstsv4ge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "c7a10be449d25bcb9038bd8cf813bea012680d2926ac054834a6df63a2a9683706cfb20c8e8d8a8aad24ce36428efc9bcac012ab0671bda1173d08a9bec87afe",
          "sha256": "863a58304c2074d960ac86969ecc0a6390afa65a1ae21a583b7bcd3f76250529",
          "sha1": "7415f363081755f3bcba591f97bf62bf306d770a",
          "md5": "fd3b479320c1e27bddd47f94c5f2af6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "c7a10be449d25bcb9038bd8cf813bea012680d2926ac054834a6df63a2a9683706cfb20c8e8d8a8aad24ce36428efc9bcac012ab0671bda1173d08a9bec87afe",
          "sha256": "863a58304c2074d960ac86969ecc0a6390afa65a1ae21a583b7bcd3f76250529",
          "sha1": "7415f363081755f3bcba591f97bf62bf306d770a",
          "md5": "fd3b479320c1e27bddd47f94c5f2af6c"
        }
      ]
    }
  ]
}
