{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-crypto-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bjmffnrewvfpjimoavhgpltn74"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "fbacf74ac1bb2cefc8cf38cea889cad977be40096bf50abe3f22c2cb990c2b15a7aecc220f777d613cbfec82d50c869cb681a60a664803e0e728569590185aff",
          "sha256": "e733c52d088c0fc015affe9beacb7f0f45d65b3cd1e8db8ed64d82d352e2d7af",
          "sha1": "bc017db29c6e7951c8e3dae5b99452ce41be4696",
          "md5": "db6a30753ea063d22536b6f4be33eb60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "fbacf74ac1bb2cefc8cf38cea889cad977be40096bf50abe3f22c2cb990c2b15a7aecc220f777d613cbfec82d50c869cb681a60a664803e0e728569590185aff",
          "sha256": "e733c52d088c0fc015affe9beacb7f0f45d65b3cd1e8db8ed64d82d352e2d7af",
          "sha1": "bc017db29c6e7951c8e3dae5b99452ce41be4696",
          "md5": "db6a30753ea063d22536b6f4be33eb60"
        }
      ]
    }
  ]
}
