{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-crypto-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wbrwgj5hnfap3l6ykkhhzzxwge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "055a4a7ba404cd96714ef951c30b75ceedf25d2fb9fd0c032f396afc6296288994665b62f633f10648af42938d6f79b2e2fcb2863294f8918e124c51f822e24d",
          "sha256": "e6cbcc8705654a383ef9e58ced09ad34d80fcb2e2b796dceb925f8995254b768",
          "sha1": "1384fa8b3cc770fd650545964147bd49d04380c0",
          "md5": "2ee2a8eddc7db6609ebe5bfe922d7ff3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-crypto-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-crypto-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "055a4a7ba404cd96714ef951c30b75ceedf25d2fb9fd0c032f396afc6296288994665b62f633f10648af42938d6f79b2e2fcb2863294f8918e124c51f822e24d",
          "sha256": "e6cbcc8705654a383ef9e58ced09ad34d80fcb2e2b796dceb925f8995254b768",
          "sha1": "1384fa8b3cc770fd650545964147bd49d04380c0",
          "md5": "2ee2a8eddc7db6609ebe5bfe922d7ff3"
        }
      ]
    }
  ]
}
