{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uqyy5glaw5gpvjfyvnsd4h3a7m"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.0-fix-logger-SNAPSHOT.aar",
          "url": "crypto-android-1.9.0-fix-logger-SNAPSHOT.aar",
          "size": 51825,
          "sha512": "429becfaea1d42b30ae047a136d41defddd9ecdc549c97cd451db0350ff961be6927e76ce53d7fb4e930fd7eb97f0a9f9373bc908e337dfc421b0b51c9ac1970",
          "sha256": "16403e9fa01595cc0c901f75ac9616946683076b136c54cdfad797158d1aad63",
          "sha1": "9fb5857f235c6b1b79ec73b5bc2f2c19ec274be9",
          "md5": "2a97d3803e6221503cd781695bcf0d99"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.0-fix-logger-SNAPSHOT.aar",
          "url": "crypto-android-1.9.0-fix-logger-SNAPSHOT.aar",
          "size": 51825,
          "sha512": "429becfaea1d42b30ae047a136d41defddd9ecdc549c97cd451db0350ff961be6927e76ce53d7fb4e930fd7eb97f0a9f9373bc908e337dfc421b0b51c9ac1970",
          "sha256": "16403e9fa01595cc0c901f75ac9616946683076b136c54cdfad797158d1aad63",
          "sha1": "9fb5857f235c6b1b79ec73b5bc2f2c19ec274be9",
          "md5": "2a97d3803e6221503cd781695bcf0d99"
        }
      ]
    }
  ]
}
