{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "or57dccynrfj7i3n64cav5czii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "2d2ef05b8ff87c78d6cbf1260a920459b0ffe73d2e799970d04a74fb2c4535fdcd3f63e2c369a7842dc8896b1235c46a62e311f970ff02cc0bcfb83e71512266",
          "sha256": "ea9a9088d3f79b1b989190a9a74df4b6fd8f26d8db159d6fffcd8ed8d7a8beaf",
          "sha1": "b48a8108b040bee8e78544f08ce0dfb4852eb7b5",
          "md5": "8acedf0d9a112989a2df115f8f8ff8a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-fix-nullpointer-of-FhirElementFactory-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "2d2ef05b8ff87c78d6cbf1260a920459b0ffe73d2e799970d04a74fb2c4535fdcd3f63e2c369a7842dc8896b1235c46a62e311f970ff02cc0bcfb83e71512266",
          "sha256": "ea9a9088d3f79b1b989190a9a74df4b6fd8f26d8db159d6fffcd8ed8d7a8beaf",
          "sha1": "b48a8108b040bee8e78544f08ce0dfb4852eb7b5",
          "md5": "8acedf0d9a112989a2df115f8f8ff8a4"
        }
      ]
    }
  ]
}
