{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ih5xjviyszesvhtokz2lpfo6m4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "dc7ed336ed5dd298b13f4788298993778299e79145e09f54ab7f4c408662a3496eb8233612130d4c585bc0d04c9cf871a3d0e3dc06798dbd1daa49bbc0eec95d",
          "sha256": "e9676429af5438ad4204bb83818135884ba93ff9103a073a04514d6b18321e00",
          "sha1": "89ee1434105b884708e012b79f411e9563528ee6",
          "md5": "d5e5ec6b65c6994835136ef4a30ad1f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "dc7ed336ed5dd298b13f4788298993778299e79145e09f54ab7f4c408662a3496eb8233612130d4c585bc0d04c9cf871a3d0e3dc06798dbd1daa49bbc0eec95d",
          "sha256": "e9676429af5438ad4204bb83818135884ba93ff9103a073a04514d6b18321e00",
          "sha1": "89ee1434105b884708e012b79f411e9563528ee6",
          "md5": "d5e5ec6b65c6994835136ef4a30ad1f1"
        }
      ]
    }
  ]
}
