{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tmdbyggbhbaopkxsrpsr5y5ikm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "5c166eaffb5e9a8b4209bed45fb061778b8e9498938dce75579a73c1006adfb86ed6a93e4e277e249876a2aa0ffe689079762f3b2ad45a6f7f585f2468277688",
          "sha256": "3004626776965f9bcc32a14ad6192d65aad8048b4456063d9fb6c472e9629fda",
          "sha1": "d87144adfcaceec238317d2796445b26ce1b34d7",
          "md5": "a152e166e18c46a2c0d4f94cc63ce930"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "5c166eaffb5e9a8b4209bed45fb061778b8e9498938dce75579a73c1006adfb86ed6a93e4e277e249876a2aa0ffe689079762f3b2ad45a6f7f585f2468277688",
          "sha256": "3004626776965f9bcc32a14ad6192d65aad8048b4456063d9fb6c472e9629fda",
          "sha1": "d87144adfcaceec238317d2796445b26ce1b34d7",
          "md5": "a152e166e18c46a2c0d4f94cc63ce930"
        }
      ]
    }
  ]
}
