{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6oau6ptl7va6rdgaejx6j2j2um"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d8e18a8bda6308f25909a05da51c344ffc4ace70cc3e451822509d3b24f2e22694a656514bf0022fb99d47181c218bb6c421134cc6b5f65b6706ec7314d2b38f",
          "sha256": "363d92e1711f5d5f196289d2519784d779f0cf536619985d9bf9abaf18ad50d5",
          "sha1": "a806e166258db47158455656ff11062bb78c9fe4",
          "md5": "676e7b8bf908693db2f3936b7d1f3072"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-fix-versioning-for-ticket-branches-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "d8e18a8bda6308f25909a05da51c344ffc4ace70cc3e451822509d3b24f2e22694a656514bf0022fb99d47181c218bb6c421134cc6b5f65b6706ec7314d2b38f",
          "sha256": "363d92e1711f5d5f196289d2519784d779f0cf536619985d9bf9abaf18ad50d5",
          "sha1": "a806e166258db47158455656ff11062bb78c9fe4",
          "md5": "676e7b8bf908693db2f3936b7d1f3072"
        }
      ]
    }
  ]
}
