{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qqu3uu4u6zhhrijjnyvvajkysm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "9800d3037cadcc3b55888576574880bdd2e1826c898aa7db1e011d35f8109da8c8722b95f576f7c4f3c8d64451d5ef4321c5920520496083ee5913613393bf6c",
          "sha256": "8c7bd98f991184cd2dce23fe7525a3069db2e191ae76387520d76e95bab0f9ff",
          "sha1": "a18225bfd8f74f0191cbbec1075d314d541a10b2",
          "md5": "bec763a8371aadb6631c1c59e70c602a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "9800d3037cadcc3b55888576574880bdd2e1826c898aa7db1e011d35f8109da8c8722b95f576f7c4f3c8d64451d5ef4321c5920520496083ee5913613393bf6c",
          "sha256": "8c7bd98f991184cd2dce23fe7525a3069db2e191ae76387520d76e95bab0f9ff",
          "sha1": "a18225bfd8f74f0191cbbec1075d314d541a10b2",
          "md5": "bec763a8371aadb6631c1c59e70c602a"
        }
      ]
    }
  ]
}
