{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dws5bmwndjfjtlacyyxejjgowm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ac44c8ee2f33e5050210beb5de56470fd781dd878791232abc40e713ccb937f78347b1784e52f466f1ff45fedd248f2c00bafb634c754bd4c67b2c13540fe6b8",
          "sha256": "da41547cafcfe0520416b2cc907e12df9a5bc9cedcaabaabc94aa948486fe51e",
          "sha1": "bf8b7da686e900d92eefdf2a1f92d815e88ea312",
          "md5": "1f0fa33705933c2b07c8450b210e0a78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.1-SNAPSHOT.jar",
          "url": "securestore-common-1.9.1-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "ac44c8ee2f33e5050210beb5de56470fd781dd878791232abc40e713ccb937f78347b1784e52f466f1ff45fedd248f2c00bafb634c754bd4c67b2c13540fe6b8",
          "sha256": "da41547cafcfe0520416b2cc907e12df9a5bc9cedcaabaabc94aa948486fe51e",
          "sha1": "bf8b7da686e900d92eefdf2a1f92d815e88ea312",
          "md5": "1f0fa33705933c2b07c8450b210e0a78"
        }
      ]
    }
  ]
}
