{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z3hehjzzprcmbdgrr3n6axcn6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "5052414c6f5e28a0afb84237389b2f9ec6c2e01f41ea7366050f810c389e70943d16ed3e3fb481ef5bfecb30064184c4bd3dc09cafff7ae6aa0422877b6d298b",
          "sha256": "06bb4d5d03baee98beb571422b66f799151ecf7cf6b1af47aca74d5135a9d576",
          "sha1": "b28524d640d738f34a8cd282cd2d7df510369a44",
          "md5": "a0f516d39d3bdd5cf143291c51507cf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "5052414c6f5e28a0afb84237389b2f9ec6c2e01f41ea7366050f810c389e70943d16ed3e3fb481ef5bfecb30064184c4bd3dc09cafff7ae6aa0422877b6d298b",
          "sha256": "06bb4d5d03baee98beb571422b66f799151ecf7cf6b1af47aca74d5135a9d576",
          "sha1": "b28524d640d738f34a8cd282cd2d7df510369a44",
          "md5": "a0f516d39d3bdd5cf143291c51507cf3"
        }
      ]
    }
  ]
}
