{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nebkbmyrxvev5gieafqvvw5zye"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "9ddbc40cad63f701cd924514b3e8d59812b42f4a902b0dd22d68922ac9a1a0465f405bb2f2a56199f2300707b85c90a3b1eb6d3e8c8828daccfb3f8b1b84aabf",
          "sha256": "9549f6ae76a0002389b0ed60401d32421978f1ef41b0c0cd5f5eb327911eebf9",
          "sha1": "3218ebc9f0fca0759b40ca139cef706b1b1d0799",
          "md5": "2d749e9020bb73a0926df579ba34a678"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "9ddbc40cad63f701cd924514b3e8d59812b42f4a902b0dd22d68922ac9a1a0465f405bb2f2a56199f2300707b85c90a3b1eb6d3e8c8828daccfb3f8b1b84aabf",
          "sha256": "9549f6ae76a0002389b0ed60401d32421978f1ef41b0c0cd5f5eb327911eebf9",
          "sha1": "3218ebc9f0fca0759b40ca139cef706b1b1d0799",
          "md5": "2d749e9020bb73a0926df579ba34a678"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
