{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ll6wivaevffabnouiknzbvq5cy"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "0ee52c272df3cd90718e370152ea414dbd857f822a0a053029abd6ce6b315a0c41e5da9069eb736327ab9cc52fde6e93e779e5cea0eaf454e314840a64931365",
          "sha256": "7453e03fc342d2d5f773646f29827996a24261ab56437f77f351af7fff94069b",
          "sha1": "a9464c22b6d5e4d4f2eb364cc75ed6c89296155b",
          "md5": "2642395b542335635237b8e7d8201798"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "0ee52c272df3cd90718e370152ea414dbd857f822a0a053029abd6ce6b315a0c41e5da9069eb736327ab9cc52fde6e93e779e5cea0eaf454e314840a64931365",
          "sha256": "7453e03fc342d2d5f773646f29827996a24261ab56437f77f351af7fff94069b",
          "sha1": "a9464c22b6d5e4d4f2eb364cc75ed6c89296155b",
          "md5": "2642395b542335635237b8e7d8201798"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
