{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library/0.0.1-SNAPSHOT/example-kmp-library-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "syq5ddzwxvcshc44sbjmn7u7xq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "c565b3eb3a8fbb5cd83f266a2e5163748e2c52accfe725869687ff1e0658dfbc458ef481c619d7e9be98a319d4175c3d37fedc5752cc5d1f51f060a493a46d07",
          "sha256": "66f996ac3e8a94be1c170c52b3ab6249b977e82e12a385c92f2153b8b5359490",
          "sha1": "e43898e65cbcd322c530aa39c6d7ca81b595c95d",
          "md5": "9fb995124567fe55906402849cf7f025"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-jvm-0.0.1-SNAPSHOT.jar",
          "size": 14357,
          "sha512": "c565b3eb3a8fbb5cd83f266a2e5163748e2c52accfe725869687ff1e0658dfbc458ef481c619d7e9be98a319d4175c3d37fedc5752cc5d1f51f060a493a46d07",
          "sha256": "66f996ac3e8a94be1c170c52b3ab6249b977e82e12a385c92f2153b8b5359490",
          "sha1": "e43898e65cbcd322c530aa39c6d7ca81b595c95d",
          "md5": "9fb995124567fe55906402849cf7f025"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../example-kmp-library-metadata/0.0.1-SNAPSHOT/example-kmp-library-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-gradle-scripts",
        "module": "example-kmp-library-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
