{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-add-cryptoservice-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mbjfbzhpvbfxpnbkilce3pxfzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a2010e67a443785d72d4baead822ada881b93e5ec0a6e4771c849520af5fd9327d9fe89d1ead76a6b81899e4d93082010b01d96d57579f8cec43a6389308bb67",
          "sha256": "8dadea28fc4e05e3997404b665aad0bebe9e7bd6429bfd815252a9fbc80fbe4c",
          "sha1": "54e5169e81ca68879f0d894610af5555dff8d6f8",
          "md5": "1b0d2cec4116b002028cb381c38fa251"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a2010e67a443785d72d4baead822ada881b93e5ec0a6e4771c849520af5fd9327d9fe89d1ead76a6b81899e4d93082010b01d96d57579f8cec43a6389308bb67",
          "sha256": "8dadea28fc4e05e3997404b665aad0bebe9e7bd6429bfd815252a9fbc80fbe4c",
          "sha1": "54e5169e81ca68879f0d894610af5555dff8d6f8",
          "md5": "1b0d2cec4116b002028cb381c38fa251"
        }
      ]
    }
  ]
}
