{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-add-cryptoservice-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "eetpy5443zhxbbdp3vczcue5be"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "b8b766f691c5fdaec48b3c71271e3f83391b303c4fe2be2677388d3dc98b73431651cf4e8b24d09f78e03198cad6b58017da34afc7426aebb304314adfc85904",
          "sha256": "75cd7f4d002514c1542986882eada35c215adc516fcf6edbb57600fdbb0b40cf",
          "sha1": "a593ebb45db3d0502b2b59f42a3de202e33233e0",
          "md5": "7434adf7271ce286e7d29d60a2917d0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-add-cryptoservice-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "b8b766f691c5fdaec48b3c71271e3f83391b303c4fe2be2677388d3dc98b73431651cf4e8b24d09f78e03198cad6b58017da34afc7426aebb304314adfc85904",
          "sha256": "75cd7f4d002514c1542986882eada35c215adc516fcf6edbb57600fdbb0b40cf",
          "sha1": "a593ebb45db3d0502b2b59f42a3de202e33233e0",
          "md5": "7434adf7271ce286e7d29d60a2917d0b"
        }
      ]
    }
  ]
}
