{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-wrapper-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wqbcb6m6vjak7i7yto6btu5lzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "de5fa7ebce003e57e4f730f8f720d9648504c09ed09adc6b2fc48b77c2c8ac457648ee6baf4e1ed3de185039d23a1977d3a40d8064444abbe7fce2a95d2efc1c",
          "sha256": "3c20b1a9b697a98d7b5ca29ed3b0693c21ef3ba6c8e0b3dfb8ad843a7fe481c0",
          "sha1": "d01a0cc48d66f6ecdad223ddc156a37fd4466c8e",
          "md5": "f8ef917166757a35e25b2a0ff93c2e23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "de5fa7ebce003e57e4f730f8f720d9648504c09ed09adc6b2fc48b77c2c8ac457648ee6baf4e1ed3de185039d23a1977d3a40d8064444abbe7fce2a95d2efc1c",
          "sha256": "3c20b1a9b697a98d7b5ca29ed3b0693c21ef3ba6c8e0b3dfb8ad843a7fe481c0",
          "sha1": "d01a0cc48d66f6ecdad223ddc156a37fd4466c8e",
          "md5": "f8ef917166757a35e25b2a0ff93c2e23"
        }
      ]
    }
  ]
}
