{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-wrapper-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "llvbuumicfclxl6bekytqeiury"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "fdd1aa97e212e4d0f66f12a8a4c0e6f185fdff2843f8dcf8bb97c3aba8c68afa23ae74e237d46c685b5df753e24f1b410a7e626a67eff0dcb29cbb1c4359bcc1",
          "sha256": "7c7289921ff3e06429040b1d2f76a81b676c4ac902e10081fd7e12df9727a79b",
          "sha1": "54239afc213ab5944220cd4ba47b747d14870fbf",
          "md5": "c864d6e5ecfed50dd81224d1d5d12773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "fdd1aa97e212e4d0f66f12a8a4c0e6f185fdff2843f8dcf8bb97c3aba8c68afa23ae74e237d46c685b5df753e24f1b410a7e626a67eff0dcb29cbb1c4359bcc1",
          "sha256": "7c7289921ff3e06429040b1d2f76a81b676c4ac902e10081fd7e12df9727a79b",
          "sha1": "54239afc213ab5944220cd4ba47b747d14870fbf",
          "md5": "c864d6e5ecfed50dd81224d1d5d12773"
        }
      ]
    }
  ]
}
