{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jy4ndyx24fhzvigbhmmt2ndrty"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.aar",
          "size": 44900,
          "sha512": "97a37efd2c1adeede1a4a67374afe1fcf8d39d3efe810b0db8c992bf6ae62627d335bd7b2653f18d3d1d73f4b6baa025f555e022d1fee6980d5ed5d0cce57ab2",
          "sha256": "1e126b37dcffe5f0b53fe63f53504b6075095431afec5eb9a6990f1582e49f0d",
          "sha1": "79ea13f25d39c86cc6662fe6d15c6ab65d6fbb53",
          "md5": "679d424648f620369ed790865403052d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.aar",
          "size": 44900,
          "sha512": "97a37efd2c1adeede1a4a67374afe1fcf8d39d3efe810b0db8c992bf6ae62627d335bd7b2653f18d3d1d73f4b6baa025f555e022d1fee6980d5ed5d0cce57ab2",
          "sha256": "1e126b37dcffe5f0b53fe63f53504b6075095431afec5eb9a6990f1582e49f0d",
          "sha1": "79ea13f25d39c86cc6662fe6d15c6ab65d6fbb53",
          "md5": "679d424648f620369ed790865403052d"
        }
      ]
    }
  ]
}
