{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-add-public-userid-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6rownicaifc75pidpscs3pwvki"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-public-userid-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "59323d7868a570332639cd292353b38348583d2b53d2ad76c11a58ba129514eeeade80e5df18dc2dac301577298d67eaa2e18ddf016f7e98e073971f73412091",
          "sha256": "141b8ad60e06622f26a2e11af4f0f7cd02d47fbbeb7d18fb74ae4f7efb6f2001",
          "sha1": "f603fcb9be574afbb0351649fe90f40d4090bb98",
          "md5": "7a0dea253ea93b88f562a422900d0953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-public-userid-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "59323d7868a570332639cd292353b38348583d2b53d2ad76c11a58ba129514eeeade80e5df18dc2dac301577298d67eaa2e18ddf016f7e98e073971f73412091",
          "sha256": "141b8ad60e06622f26a2e11af4f0f7cd02d47fbbeb7d18fb74ae4f7efb6f2001",
          "sha1": "f603fcb9be574afbb0351649fe90f40d4090bb98",
          "md5": "7a0dea253ea93b88f562a422900d0953"
        }
      ]
    }
  ]
}
