{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-add-public-userid-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "l6ztkekqtzc27fitvroekqzi2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-public-userid-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "690aa2ebe405e3391c89c5a3dcefbe9e205a8799fc25ddf572665b3109e458b1cc1cf32bea78f234fe2840ebfda54d409b81658b78c06b78d5cc3d8600f63c21",
          "sha256": "283c3c4c1af79105c99a8fe5c6aa73821fa6f39d8717ba856cc3f50bbe7b1257",
          "sha1": "99d00fb741a92d098900516f842c9f23d6a96832",
          "md5": "9932eac2e0cd05bbe120f00e97092bd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-public-userid-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-add-public-userid-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "690aa2ebe405e3391c89c5a3dcefbe9e205a8799fc25ddf572665b3109e458b1cc1cf32bea78f234fe2840ebfda54d409b81658b78c06b78d5cc3d8600f63c21",
          "sha256": "283c3c4c1af79105c99a8fe5c6aa73821fa6f39d8717ba856cc3f50bbe7b1257",
          "sha1": "99d00fb741a92d098900516f842c9f23d6a96832",
          "md5": "9932eac2e0cd05bbe120f00e97092bd8"
        }
      ]
    }
  ]
}
