{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "h2sp3o6kxjeltkj72ecygshhxi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "size": 487507,
          "sha512": "4d8f1f3f98c645bfec259656f45ecd71992f28fa13748fa06c3803babb90b4384ea4ab1fdd2cb0751374982d8f03718c7bc767ed0aa5da678b1fa682fddeacf5",
          "sha256": "f819d55b9b7754bb7d870d9b3069f393af7cda4fd53fcf07c8f7e9067dca3d9d",
          "sha1": "e82f539ea0b288b1a7b609ad6a6cee8f040ee271",
          "md5": "1fd3b5eab30003fff3f34b62cfee6834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "url": "sdk-core-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.jar",
          "size": 487507,
          "sha512": "4d8f1f3f98c645bfec259656f45ecd71992f28fa13748fa06c3803babb90b4384ea4ab1fdd2cb0751374982d8f03718c7bc767ed0aa5da678b1fa682fddeacf5",
          "sha256": "f819d55b9b7754bb7d870d9b3069f393af7cda4fd53fcf07c8f7e9067dca3d9d",
          "sha1": "e82f539ea0b288b1a7b609ad6a6cee8f040ee271",
          "md5": "1fd3b5eab30003fff3f34b62cfee6834"
        }
      ]
    }
  ]
}
