{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-remove-bintray-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hau4h3odnfdqrd3kcmmfixmrqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "d6964f9009d14dfec28f3ed5eb760ff29b3069770e5b517f533743d4ab87d5eb727e29e3f7cc432b5282115be240d77d2fa3ac6d3e1b95f57b945ddc80638a56",
          "sha256": "168cf69b31503911e0befe66e8358e4d0571a903004ad66494a6192ffb01f9b7",
          "sha1": "4cb19f7d3c88677736dd2327009707555d8ffa4d",
          "md5": "b3d9c05c9989f5e7c388b796491c6055"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-remove-bintray-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-remove-bintray-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "d6964f9009d14dfec28f3ed5eb760ff29b3069770e5b517f533743d4ab87d5eb727e29e3f7cc432b5282115be240d77d2fa3ac6d3e1b95f57b945ddc80638a56",
          "sha256": "168cf69b31503911e0befe66e8358e4d0571a903004ad66494a6192ffb01f9b7",
          "sha1": "4cb19f7d3c88677736dd2327009707555d8ffa4d",
          "md5": "b3d9c05c9989f5e7c388b796491c6055"
        }
      ]
    }
  ]
}
