{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qpj2yhlstbbb7i7lrnp3i42ggy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 464676,
          "sha512": "943564708b5319ffba13b2deaa1e732fac1781460cadeb48ca9b62fabe29ab059dc56cd3b08012909abd712e8741ed61d7989b242256d60719e74fe82591960c",
          "sha256": "1f89e552d58c82a3d888fecd2e857089b87580b2a2f99bdc33933da246db7440",
          "sha1": "d85c643df21b6f4bf5e9972466a148a4c7be6190",
          "md5": "450276b681ae15aaf875eb2bfd23b1f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 464676,
          "sha512": "943564708b5319ffba13b2deaa1e732fac1781460cadeb48ca9b62fabe29ab059dc56cd3b08012909abd712e8741ed61d7989b242256d60719e74fe82591960c",
          "sha256": "1f89e552d58c82a3d888fecd2e857089b87580b2a2f99bdc33933da246db7440",
          "sha1": "d85c643df21b6f4bf5e9972466a148a4c7be6190",
          "md5": "450276b681ae15aaf875eb2bfd23b1f3"
        }
      ]
    }
  ]
}
