{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-change-wrapper-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wqbcb6m6vjak7i7yto6btu5lzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f5b07d778bf34b20ee1cdb13427077db1f04fc1df36ef84835b99e2023a95f847b3419d89bbb74896d7bf715cfae09b56aa55aa4f780a957c569e600bfed6c72",
          "sha256": "6837130047580fac81ead8db576a469ca47b2407d16fc496584a146c4b6c08d9",
          "sha1": "bf03a3460c6dd8914bd8c2c931961ab233ca6bfe",
          "md5": "0b7ff5e1c4d4826dea579b98f5a6f851"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f5b07d778bf34b20ee1cdb13427077db1f04fc1df36ef84835b99e2023a95f847b3419d89bbb74896d7bf715cfae09b56aa55aa4f780a957c569e600bfed6c72",
          "sha256": "6837130047580fac81ead8db576a469ca47b2407d16fc496584a146c4b6c08d9",
          "sha1": "bf03a3460c6dd8914bd8c2c931961ab233ca6bfe",
          "md5": "0b7ff5e1c4d4826dea579b98f5a6f851"
        }
      ]
    }
  ]
}
