{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-fix-code-style-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6u2uiei5vnd45k5lwuwzjxc3ay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "00d65cf2f4c807bc0e6a4981efe227ffaf37a01145022a28b94f58d63cb383dea296edcb311c22114e4c48ae6add15c445861fc05b37a8f73b49ce630c121c9e",
          "sha256": "df26b1b34e1dc776290239d879d47ac365eb40fad328d2a440857e13908b93e1",
          "sha1": "4a8157c40d15b9d99348fc4a8fa066b009d4c7a1",
          "md5": "d9529f353d6bd4eb091ae4b3590f68ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-fix-code-style-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "00d65cf2f4c807bc0e6a4981efe227ffaf37a01145022a28b94f58d63cb383dea296edcb311c22114e4c48ae6add15c445861fc05b37a8f73b49ce630c121c9e",
          "sha256": "df26b1b34e1dc776290239d879d47ac365eb40fad328d2a440857e13908b93e1",
          "sha1": "4a8157c40d15b9d99348fc4a8fa066b009d4c7a1",
          "md5": "d9529f353d6bd4eb091ae4b3590f68ca"
        }
      ]
    }
  ]
}
