{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.1-fix-date-formatting-on-search-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6xcmg72gknbmln5zn4duvnj2b4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-fix-date-formatting-on-search-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-fix-date-formatting-on-search-SNAPSHOT.aar",
          "size": 44900,
          "sha512": "42fe720bda5e63a595ab1a763d2c7e8d5deeecce7bf464170cf1a52626d3154a658b2e242924e9b46687d398b700b2bb991060c19320397c3d84de9f75e268ef",
          "sha256": "097de7dbf18d4ea1ec1ee5a555f8972d51b77ce4141985756e3805b7369a9fa0",
          "sha1": "600ed28f1710edaa87a42f18c04136315029081e",
          "md5": "eefa69a475295c93394150dab6e27fad"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-fix-date-formatting-on-search-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-fix-date-formatting-on-search-SNAPSHOT.aar",
          "size": 44900,
          "sha512": "42fe720bda5e63a595ab1a763d2c7e8d5deeecce7bf464170cf1a52626d3154a658b2e242924e9b46687d398b700b2bb991060c19320397c3d84de9f75e268ef",
          "sha256": "097de7dbf18d4ea1ec1ee5a555f8972d51b77ce4141985756e3805b7369a9fa0",
          "sha1": "600ed28f1710edaa87a42f18c04136315029081e",
          "md5": "eefa69a475295c93394150dab6e27fad"
        }
      ]
    }
  ]
}
