{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yl7niwsknrfxzkt2l6kfb3fq6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "384c62df7f7b59a45d59e62f6de36315a621cd16a7c62f7c12ceb33acfae646e3ebcb7f8f3d473c092fd0e0f703229ad0e903a4aa9c9a651fad8bfdbad57dd06",
          "sha256": "dad8ddff2df65bbdc274381686266fb121e025f36bb5260ad96be258179c9b8e",
          "sha1": "1d6fa25e09c0e65b68f750bbe4985d4397f28f2e",
          "md5": "97e1c0b150303adf740e33ec8b47ba12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-ImageResizer-visibility-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-fix-ImageResizer-visibility-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "384c62df7f7b59a45d59e62f6de36315a621cd16a7c62f7c12ceb33acfae646e3ebcb7f8f3d473c092fd0e0f703229ad0e903a4aa9c9a651fad8bfdbad57dd06",
          "sha256": "dad8ddff2df65bbdc274381686266fb121e025f36bb5260ad96be258179c9b8e",
          "sha1": "1d6fa25e09c0e65b68f750bbe4985d4397f28f2e",
          "md5": "97e1c0b150303adf740e33ec8b47ba12"
        }
      ]
    }
  ]
}
