{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5ra3tyqeafcl5cwiigzp2kmum4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "a3e261f958af4c3f3733dc8bee2da09803f77c0c3908dfe6cac2db52b22d6ea65294b2b8c564803456c64a6a1a2998b793217e46f992250fb0670b7e11b4813c",
          "sha256": "ce657a48aba2ba3e8d24dcca534fdd1bde92150a13e30ea6144ab311434996b2",
          "sha1": "6685a566456d37d05b522f5e28ffca52f29e7a3f",
          "md5": "038c3084c81b6a591503a17666c89af9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "a3e261f958af4c3f3733dc8bee2da09803f77c0c3908dfe6cac2db52b22d6ea65294b2b8c564803456c64a6a1a2998b793217e46f992250fb0670b7e11b4813c",
          "sha256": "ce657a48aba2ba3e8d24dcca534fdd1bde92150a13e30ea6144ab311434996b2",
          "sha1": "6685a566456d37d05b522f5e28ffca52f29e7a3f",
          "md5": "038c3084c81b6a591503a17666c89af9"
        }
      ]
    }
  ]
}
