{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xn4cqacczvasvh6dqh5ii2fshm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1c899ab27a096822ebc2898248b59793e86a9f0449f028098868f42be416175910edcba82ac1056d5a78f476ca644b87b6be552d6ff60a5141d9581540141ebe",
          "sha256": "71e62f1fc9e4b5aee21ca767cac76617be111d7bd40ddad3c203377675c5fe5a",
          "sha1": "0a07b24cd8b7b75bcf7e270df48a5c880cb7c688",
          "md5": "9ba407844ec77060186a158f6f550ca8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "1c899ab27a096822ebc2898248b59793e86a9f0449f028098868f42be416175910edcba82ac1056d5a78f476ca644b87b6be552d6ff60a5141d9581540141ebe",
          "sha256": "71e62f1fc9e4b5aee21ca767cac76617be111d7bd40ddad3c203377675c5fe5a",
          "sha1": "0a07b24cd8b7b75bcf7e270df48a5c880cb7c688",
          "md5": "9ba407844ec77060186a158f6f550ca8"
        }
      ]
    }
  ]
}
