{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rwszed26yrcmfggg4ln3iezvbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c7e6421834646c067f48ba9dadb5e43f4a2a61203fe98ffbd43557b075280982763ac5870903f06aab15411e5a90d3ff09f47f0991dc990d996fe4eda2380f1d",
          "sha256": "7dec4438dcf0dc51df89f7839278ee8028fb89077bb8f95f1b701fcdc15359b9",
          "sha1": "b8672456b59f91ee156cf8b1709f4a99a7459ce5",
          "md5": "c423963f2a5da20dcc825012398cc421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c7e6421834646c067f48ba9dadb5e43f4a2a61203fe98ffbd43557b075280982763ac5870903f06aab15411e5a90d3ff09f47f0991dc990d996fe4eda2380f1d",
          "sha256": "7dec4438dcf0dc51df89f7839278ee8028fb89077bb8f95f1b701fcdc15359b9",
          "sha1": "b8672456b59f91ee156cf8b1709f4a99a7459ce5",
          "md5": "c423963f2a5da20dcc825012398cc421"
        }
      ]
    }
  ]
}
