{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "n22v6nixsvaphf4sksikff2phq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7c856ac6c6d3bad2503d5c9392f570049a3e81ca291cc206160fe6666daede6b34b8733241fa48da65cca3f1d8201960259deb7c068e8b359f8357c4f0dfc45b",
          "sha256": "016475ef67ac7894ba86bf161fe04a1b222fdf261ebe3f57bc88fb685a77e71a",
          "sha1": "e0052dcdc8703fb48adf42d98baa8c1768d782ef",
          "md5": "cdd7646f35f2aadab5cb741eee8ddb79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "7c856ac6c6d3bad2503d5c9392f570049a3e81ca291cc206160fe6666daede6b34b8733241fa48da65cca3f1d8201960259deb7c068e8b359f8357c4f0dfc45b",
          "sha256": "016475ef67ac7894ba86bf161fe04a1b222fdf261ebe3f57bc88fb685a77e71a",
          "sha1": "e0052dcdc8703fb48adf42d98baa8c1768d782ef",
          "md5": "cdd7646f35f2aadab5cb741eee8ddb79"
        }
      ]
    }
  ]
}
