{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ulge73bdcfgbtbu2hivwowptdm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "1c7824f8f950cf88560e9f375e6a5ffacb289fe3f8c11026851e59192a4156dd3a705c0184cb72b90f5364aed1ca4da259ca31df5580d001c90772e5f9225ac7",
          "sha256": "1e8532ef420c67cd9c65a3777f7b7d3059ef52fafed06fd7637cb33bbbc3a977",
          "sha1": "b6836db71615e9b57b909af9ad0cae5d0306bf8e",
          "md5": "3515a695afc73f669e223b2f8fa4c3f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "1c7824f8f950cf88560e9f375e6a5ffacb289fe3f8c11026851e59192a4156dd3a705c0184cb72b90f5364aed1ca4da259ca31df5580d001c90772e5f9225ac7",
          "sha256": "1e8532ef420c67cd9c65a3777f7b7d3059ef52fafed06fd7637cb33bbbc3a977",
          "sha1": "b6836db71615e9b57b909af9ad0cae5d0306bf8e",
          "md5": "3515a695afc73f669e223b2f8fa4c3f5"
        }
      ]
    }
  ]
}
