{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lscg57k2unewtjzqzddmcyqdje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0b1e7a0cced6d546b76569c09fc82028da771785f152f591cc2a36cacb3bdcd66d2f40e5ddb322d08b5175b1d8ffa59417a92f2d3ba3a10139f39cdf9d1715de",
          "sha256": "6b9f66af55c3a167ef17ca5f9487a960fa50c58c86d2828f23bed5d667d3a339",
          "sha1": "5d9bc24d68351b1399faf0ba9302da66cbe613cb",
          "md5": "e2c8130d1ac84f6e9b9d2b69660cc787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0b1e7a0cced6d546b76569c09fc82028da771785f152f591cc2a36cacb3bdcd66d2f40e5ddb322d08b5175b1d8ffa59417a92f2d3ba3a10139f39cdf9d1715de",
          "sha256": "6b9f66af55c3a167ef17ca5f9487a960fa50c58c86d2828f23bed5d667d3a339",
          "sha1": "5d9bc24d68351b1399faf0ba9302da66cbe613cb",
          "md5": "e2c8130d1ac84f6e9b9d2b69660cc787"
        }
      ]
    }
  ]
}
