{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z7tc2apk45awvduwy5cthg6ch4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0446033a9a7eca344d54c8e71b156dba05f1c566fb418a1fcd876e6538f61f1e43bb7bfe13f9eb3440b2ffd2482111f3bbf1cd66ade325ed64a4656229f6ea4c",
          "sha256": "70ac04680290711fbfdfdb23e818309677d1ee391b14d48e6ab2dd25e007462b",
          "sha1": "3f42bfc66b6d21ba33a285aa8a059a6f3141577f",
          "md5": "830009b635fa3b27db2b08aa26e7fb62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "0446033a9a7eca344d54c8e71b156dba05f1c566fb418a1fcd876e6538f61f1e43bb7bfe13f9eb3440b2ffd2482111f3bbf1cd66ade325ed64a4656229f6ea4c",
          "sha256": "70ac04680290711fbfdfdb23e818309677d1ee391b14d48e6ab2dd25e007462b",
          "sha1": "3f42bfc66b6d21ba33a285aa8a059a6f3141577f",
          "md5": "830009b635fa3b27db2b08aa26e7fb62"
        }
      ]
    }
  ]
}
