{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dzv35tvuw5g75orrm34hqptk2y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b0c5d6b308ace4e6b7d1073cf5e51b4184a08ddc2a0c23784f86c7d65f1a08c390cd5df9c2d2d887c02fef5caa0218375ceaf62364906f5a473a82c939bb0df8",
          "sha256": "f13df29d897601a3ab4d3ff5af64bbfc603913a19702e6a8552d2e47a424c10e",
          "sha1": "8e80036a4bb089fb40e7648c08154630612be8ff",
          "md5": "d01bb8d10186237b2afe59ef5db66a1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "b0c5d6b308ace4e6b7d1073cf5e51b4184a08ddc2a0c23784f86c7d65f1a08c390cd5df9c2d2d887c02fef5caa0218375ceaf62364906f5a473a82c939bb0df8",
          "sha256": "f13df29d897601a3ab4d3ff5af64bbfc603913a19702e6a8552d2e47a424c10e",
          "sha1": "8e80036a4bb089fb40e7648c08154630612be8ff",
          "md5": "d01bb8d10186237b2afe59ef5db66a1e"
        }
      ]
    }
  ]
}
