{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gmpnppj4rnbtdojeyzzgxk62u4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "88dd3b3e0046b100f1a33dae6f4cee2a74776db7a351e88db5ecb4b96828fbd9bcfae827d8eecba70a21c9f4dabe400d68807d5fce3354d6917b2f2c15d491a6",
          "sha256": "904f91fd2faa5fd5f222f1f08ccf3b7390b19296ddc16a880333d251e582372c",
          "sha1": "3ac79f1184c986ab4969bbeb212d807b1edcc187",
          "md5": "095126a90af9a2e939eb639f954fc8b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "88dd3b3e0046b100f1a33dae6f4cee2a74776db7a351e88db5ecb4b96828fbd9bcfae827d8eecba70a21c9f4dabe400d68807d5fce3354d6917b2f2c15d491a6",
          "sha256": "904f91fd2faa5fd5f222f1f08ccf3b7390b19296ddc16a880333d251e582372c",
          "sha1": "3ac79f1184c986ab4969bbeb212d807b1edcc187",
          "md5": "095126a90af9a2e939eb639f954fc8b8"
        }
      ]
    }
  ]
}
