{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4vaohbfcnresdmlpcjoahtwuja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "22dcec40e4a43f1c6a0f99bb7fb667a0b595a7bfd944d05b108f1f7af00d1f18d01c4ac7c090686c58d8404688d43c7dd572ed87a7e8e7f317b5712a4b7e0881",
          "sha256": "a0963e7a3220c8d0bdb8bd77224731b9af40a11f89667fd436078e901be922ed",
          "sha1": "5e6aba9ac49d6a7db6834d9790fce16043a83fb3",
          "md5": "c32c4b9c4bcf1cb9859fd06d52fcf602"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "22dcec40e4a43f1c6a0f99bb7fb667a0b595a7bfd944d05b108f1f7af00d1f18d01c4ac7c090686c58d8404688d43c7dd572ed87a7e8e7f317b5712a4b7e0881",
          "sha256": "a0963e7a3220c8d0bdb8bd77224731b9af40a11f89667fd436078e901be922ed",
          "sha1": "5e6aba9ac49d6a7db6834d9790fce16043a83fb3",
          "md5": "c32c4b9c4bcf1cb9859fd06d52fcf602"
        }
      ]
    }
  ]
}
