{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dpegcwlaknhglexe5z7dicohte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1f7da23e09b1834d66002d5f02243edf362c7c63c409c892ba762a89cb79df20d674c2a79b9e0cd7c37c769c088b5811ff4c39c5004f47ffe6e243aa0a84ab26",
          "sha256": "bbc4acb0a3704f87dd5f294e5b5b6b22d9bd9c212be175173750a8622ed06b95",
          "sha1": "5a86d5d1556fb20b800dd8722d681f98c315d6a4",
          "md5": "21a99f65f7dee1287c68737fe2e551bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1f7da23e09b1834d66002d5f02243edf362c7c63c409c892ba762a89cb79df20d674c2a79b9e0cd7c37c769c088b5811ff4c39c5004f47ffe6e243aa0a84ab26",
          "sha256": "bbc4acb0a3704f87dd5f294e5b5b6b22d9bd9c212be175173750a8622ed06b95",
          "sha1": "5a86d5d1556fb20b800dd8722d681f98c315d6a4",
          "md5": "21a99f65f7dee1287c68737fe2e551bc"
        }
      ]
    }
  ]
}
