{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3pyb4puf7bhmlkvuvebv6cilhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "0c4ad5010bf7d249a04fd600678fc1778889489d5d747181e9d80755f7526ed896fcb1c96e4f7130f13a40a7bfe89d477634a5cddc8f3dce78d1ad0698ef6481",
          "sha256": "e7babecc25e27a862d8785d627326d15e86b530d84c9cd0793781c7a4be183f6",
          "sha1": "07ec983b139dae3fc25e999a20a20420b1c13ed4",
          "md5": "c730856427a94907da0ed586e249979f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "0c4ad5010bf7d249a04fd600678fc1778889489d5d747181e9d80755f7526ed896fcb1c96e4f7130f13a40a7bfe89d477634a5cddc8f3dce78d1ad0698ef6481",
          "sha256": "e7babecc25e27a862d8785d627326d15e86b530d84c9cd0793781c7a4be183f6",
          "sha1": "07ec983b139dae3fc25e999a20a20420b1c13ed4",
          "md5": "c730856427a94907da0ed586e249979f"
        }
      ]
    }
  ]
}
