{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vnzvke5bmvc3vjgyohvw7e73li"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "1795d84b7b9c78678e0e4b737fd92aafcd7e476d29ec54f077408a5fb3d10c223651b707d277edfdd333d8a1bf285ae1ce112152c091fb1936753eb9efd4e898",
          "sha256": "4270bbf2cd8413b8992abaf29dfc16a966b9991a88c4b6ba9e914534dd1b829e",
          "sha1": "e9eb0a3fe63ae8134aafe98f9278f3be735591a0",
          "md5": "4e954e64603277d28da6b9de9cb3d70c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "1795d84b7b9c78678e0e4b737fd92aafcd7e476d29ec54f077408a5fb3d10c223651b707d277edfdd333d8a1bf285ae1ce112152c091fb1936753eb9efd4e898",
          "sha256": "4270bbf2cd8413b8992abaf29dfc16a966b9991a88c4b6ba9e914534dd1b829e",
          "sha1": "e9eb0a3fe63ae8134aafe98f9278f3be735591a0",
          "md5": "4e954e64603277d28da6b9de9cb3d70c"
        }
      ]
    }
  ]
}
