{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qn2temi5sbc7nbiuu63cd3yfmq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8eb7b8b8e0fc06cf3c8be977c48c9bea03769a29a4755878a85f67060d4d42f7c59802bf065992d1bc151963fe08626d55649e36acd0b81ba5fef663654098b9",
          "sha256": "b02d8dc7275e3f1b905aad8a7bbc4a502dcdea80131e5ec5f063621ddb8252ac",
          "sha1": "6d7fb6e57a8b03d0693247ea69b17727fd0b0552",
          "md5": "9f129ef3a774963c7188ad00ac82df17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "8eb7b8b8e0fc06cf3c8be977c48c9bea03769a29a4755878a85f67060d4d42f7c59802bf065992d1bc151963fe08626d55649e36acd0b81ba5fef663654098b9",
          "sha256": "b02d8dc7275e3f1b905aad8a7bbc4a502dcdea80131e5ec5f063621ddb8252ac",
          "sha1": "6d7fb6e57a8b03d0693247ea69b17727fd0b0552",
          "md5": "9f129ef3a774963c7188ad00ac82df17"
        }
      ]
    }
  ]
}
