{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-wrapper-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wqbcb6m6vjak7i7yto6btu5lzu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "bdb6bf5e5da4d91dffa83f799a4b51064df158b8de4f5fbcb547f07104ce2914efba03a7b7f8efaea6431563543ad14df86e9d7f7ba9a90c7c8970f09df298b5",
          "sha256": "2ce3f794f082d65883fe39cfb5e386667ff2f92e0b6961a77b26166681c72c68",
          "sha1": "b9a793934f671d54f01a1015356660a7d733c026",
          "md5": "3d7d34c2029fbb83270d5d0c66313341"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "bdb6bf5e5da4d91dffa83f799a4b51064df158b8de4f5fbcb547f07104ce2914efba03a7b7f8efaea6431563543ad14df86e9d7f7ba9a90c7c8970f09df298b5",
          "sha256": "2ce3f794f082d65883fe39cfb5e386667ff2f92e0b6961a77b26166681c72c68",
          "sha1": "b9a793934f671d54f01a1015356660a7d733c026",
          "md5": "3d7d34c2029fbb83270d5d0c66313341"
        }
      ]
    }
  ]
}
