{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-wrapper-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "llvbuumicfclxl6bekytqeiury"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "37d47ac6c94ab3c84c549bf075af26d11060ddee2edf2ffbd312d552532aa5bdb41ffeac15acdab4e61e7770f3783ea0ce8da36fcb4864862e713c128bd5dc5b",
          "sha256": "c90e24f77fb0365377cd0a55d16430843d31cd219c8686ac7d7c1674aa90ead4",
          "sha1": "9571d1c40687d6dc7c8cecbae3053f4dc647e288",
          "md5": "5173d4c1b5c0626f3dc1982968456831"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-wrapper-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-wrapper-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "37d47ac6c94ab3c84c549bf075af26d11060ddee2edf2ffbd312d552532aa5bdb41ffeac15acdab4e61e7770f3783ea0ce8da36fcb4864862e713c128bd5dc5b",
          "sha256": "c90e24f77fb0365377cd0a55d16430843d31cd219c8686ac7d7c1674aa90ead4",
          "sha1": "9571d1c40687d6dc7c8cecbae3053f4dc647e288",
          "md5": "5173d4c1b5c0626f3dc1982968456831"
        }
      ]
    }
  ]
}
