{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "b2jdpwlhsbdaderp7fakrbig5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "45122f2a1173ecf1ced84f504970afe3184d0d8530e5008f878ee0f385096020b46953df094c572512932d982bec5673abead1dcbf68603091a72e873b1e1bb7",
          "sha256": "26627d888cb61f9d3ea988e5b26fbbff207308631a3d6fa503079c152e0cc962",
          "sha1": "c9c9a21ec4fd5ef71371a8c5a33eb0271e0d8a90",
          "md5": "65ad1fed8d606990af3342a1fcd9415a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "45122f2a1173ecf1ced84f504970afe3184d0d8530e5008f878ee0f385096020b46953df094c572512932d982bec5673abead1dcbf68603091a72e873b1e1bb7",
          "sha256": "26627d888cb61f9d3ea988e5b26fbbff207308631a3d6fa503079c152e0cc962",
          "sha1": "c9c9a21ec4fd5ef71371a8c5a33eb0271e0d8a90",
          "md5": "65ad1fed8d606990af3342a1fcd9415a"
        }
      ]
    }
  ]
}
