{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z7tc2apk45awvduwy5cthg6ch4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.0-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.0-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "62dcfc16d933edb8ba1de879287c20e38e432dbb4f312779fd651491e8da69be3824720dc72892ec14489e1b9744a9f3b74a25ef62c329d2150a68ec9ff3ce7e",
          "sha256": "cbf701682eaa66321f98cd37132afa423d5181b0025e83f5750f49ba9261a12a",
          "sha1": "ff7cfbdee84faae5d40aa1994688429e15fb076c",
          "md5": "f2dc9a08464bdeb174261e19adb8363d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "hc-fhir-sdk-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.0-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.0-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "62dcfc16d933edb8ba1de879287c20e38e432dbb4f312779fd651491e8da69be3824720dc72892ec14489e1b9744a9f3b74a25ef62c329d2150a68ec9ff3ce7e",
          "sha256": "cbf701682eaa66321f98cd37132afa423d5181b0025e83f5750f49ba9261a12a",
          "sha1": "ff7cfbdee84faae5d40aa1994688429e15fb076c",
          "md5": "f2dc9a08464bdeb174261e19adb8363d"
        }
      ]
    }
  ]
}
