{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.11.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "h53qwca7d5huhgp6fb77cod7dy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "ad0ab3472fe438e3c1a9cf31cd4b0784703660cf8f8f6e327497d1176e00bde725904ebd6137b97840b5ab85e65e97d40f65f82c42287e2707d1a1694584a15a",
          "sha256": "86632152665bb8306ec570ddde149ba28aca0b657fb59edda6217355f2160e0c",
          "sha1": "579688446087166589a65ce3688977ed684a09c6",
          "md5": "2a23f69e3abccf6552902e8e2c3a420e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.11.0-SNAPSHOT.jar",
          "size": 34283,
          "sha512": "ad0ab3472fe438e3c1a9cf31cd4b0784703660cf8f8f6e327497d1176e00bde725904ebd6137b97840b5ab85e65e97d40f65f82c42287e2707d1a1694584a15a",
          "sha256": "86632152665bb8306ec570ddde149ba28aca0b657fb59edda6217355f2160e0c",
          "sha1": "579688446087166589a65ce3688977ed684a09c6",
          "md5": "2a23f69e3abccf6552902e8e2c3a420e"
        }
      ]
    }
  ]
}
