{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "s65lxdex2faa5he6eyhs347mvi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "size": 447580,
          "sha512": "2d1d1f82abee2b0be4e4047617af63f60eb5891ff747cc5ce37d74432bf4818228b1fab5e769b9992a1162ad02089b4ac5add590971f1dbe6661a1cd0f646410",
          "sha256": "b57194aa26b0e0a3c096a1d2ec046eff7a13aad65f293594ac80f4791c3e2519",
          "sha1": "b71e41ca54e5ec1a96532fec2034a2897c9cf6eb",
          "md5": "352c61fdfddaf185884aeb653c735063"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "url": "sdk-core-1.9.1-fix-RecordService-deleteRecords-parameter-mixup-SNAPSHOT.jar",
          "size": 447580,
          "sha512": "2d1d1f82abee2b0be4e4047617af63f60eb5891ff747cc5ce37d74432bf4818228b1fab5e769b9992a1162ad02089b4ac5add590971f1dbe6661a1cd0f646410",
          "sha256": "b57194aa26b0e0a3c096a1d2ec046eff7a13aad65f293594ac80f4791c3e2519",
          "sha1": "b71e41ca54e5ec1a96532fec2034a2897c9cf6eb",
          "md5": "352c61fdfddaf185884aeb653c735063"
        }
      ]
    }
  ]
}
