{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.10.0-fix-document-upload-response-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lgtadhf4xjgj5jbmmvgfljowii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "1d88ff5dd4625f38c1bd293cc65d15efc1b6f614aef7261acd3e65c000e928c3a715bf7df029db8a11c438cbe8eb6eb04d5c6a9b77357983afad417616503e76",
          "sha256": "3480815932e40cd392d2acf2b80897bccd0225868579732d79cd8149bbe2e154",
          "sha1": "b0fef8d8e5814c054a23081643e10b49fb7fd4e8",
          "md5": "5a865821ac8d462aea0aced5f58cddb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-fix-document-upload-response-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "url": "sdk-jvm-1.10.0-fix-document-upload-response-SNAPSHOT.jar",
          "size": 11463,
          "sha512": "1d88ff5dd4625f38c1bd293cc65d15efc1b6f614aef7261acd3e65c000e928c3a715bf7df029db8a11c438cbe8eb6eb04d5c6a9b77357983afad417616503e76",
          "sha256": "3480815932e40cd392d2acf2b80897bccd0225868579732d79cd8149bbe2e154",
          "sha1": "b0fef8d8e5814c054a23081643e10b49fb7fd4e8",
          "md5": "5a865821ac8d462aea0aced5f58cddb8"
        }
      ]
    }
  ]
}
