{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "h3krjl4ru5fflidpkuassdnfgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0c8c06337a8359304a629122e33211ec5059bf9df155c2050d3c109bbf61bedf2bb4ee64c28de558efae9f9b6ddbfb83cf408a3c736b4a79ef464faf04a40aa7",
          "sha256": "3c254887ee4130b15dbd4fa7b07801a9b5d508df24b5abb6b8ffa961a4208dec",
          "sha1": "2f394c3c571a307c9a21dd1a238d2ec96bf99fdc",
          "md5": "4c3e9a3e4bddd6774cd74c6d2ac4bbd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0c8c06337a8359304a629122e33211ec5059bf9df155c2050d3c109bbf61bedf2bb4ee64c28de558efae9f9b6ddbfb83cf408a3c736b4a79ef464faf04a40aa7",
          "sha256": "3c254887ee4130b15dbd4fa7b07801a9b5d508df24b5abb6b8ffa961a4208dec",
          "sha1": "2f394c3c571a307c9a21dd1a238d2ec96bf99fdc",
          "md5": "4c3e9a3e4bddd6774cd74c6d2ac4bbd2"
        }
      ]
    }
  ]
}
