{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hnv2ozbnlbhspbndxpgesli6yy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "3370137d112c6d66966a2a0ceec2a36659a235b6d9b38de5f50f91712615a51033ccc2b94e5790393cff343b3f719bc69906a2dc1ff6d02c40bfb52117722ba9",
          "sha256": "d4a79fdd30e3d65b416b4b845ffb35db41a063ddac7abb9fe33e4ce31493b714",
          "sha1": "4d3fa23619231f5f27f7176ce8e74c13046ee70c",
          "md5": "d75d8f897aeff81e658bb99b09b856f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "3370137d112c6d66966a2a0ceec2a36659a235b6d9b38de5f50f91712615a51033ccc2b94e5790393cff343b3f719bc69906a2dc1ff6d02c40bfb52117722ba9",
          "sha256": "d4a79fdd30e3d65b416b4b845ffb35db41a063ddac7abb9fe33e4ce31493b714",
          "sha1": "4d3fa23619231f5f27f7176ce8e74c13046ee70c",
          "md5": "d75d8f897aeff81e658bb99b09b856f5"
        }
      ]
    }
  ]
}
