{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rasgwsgqijf7bhg2obw3tli3x4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "756cf6415f2aa1c0ce9d78447a22e2c91cc87ba9d9ec009aaf1774df91f1ac7004c2d89919d7c86103ad8b7494d01c99bfb8089381020c84d56849c133a79888",
          "sha256": "c294e436b9e4e7bee6419e4a3abb8e3cf682363b65215a0dd237781e9a7cda94",
          "sha1": "0ed9cf0832b50953c0a4ed4c46fe84c5403720d6",
          "md5": "6edc27843405bcfb02977360d6606a01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "756cf6415f2aa1c0ce9d78447a22e2c91cc87ba9d9ec009aaf1774df91f1ac7004c2d89919d7c86103ad8b7494d01c99bfb8089381020c84d56849c133a79888",
          "sha256": "c294e436b9e4e7bee6419e4a3abb8e3cf682363b65215a0dd237781e9a7cda94",
          "sha1": "0ed9cf0832b50953c0a4ed4c46fe84c5403720d6",
          "md5": "6edc27843405bcfb02977360d6606a01"
        }
      ]
    }
  ]
}
