{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hpq2qaxruvaxflkm3famdi3qq4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "17892af3add7cb7c19cd0e24e1e5c46053405aa6d7c0ef3d8c575112506378ba32d401691b348f1a9791e9f884e8a884f81ca383132e5daa6b7ba1bcb6c1b48d",
          "sha256": "a4f388497fad90088f4545b4c2457d81a57583f5097699af768cc1a2f53eaf8e",
          "sha1": "255244989c740525eed0ec341e619b1cc9d02e5f",
          "md5": "9926eace4be55f7b3c5c3ff0c983ab9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "17892af3add7cb7c19cd0e24e1e5c46053405aa6d7c0ef3d8c575112506378ba32d401691b348f1a9791e9f884e8a884f81ca383132e5daa6b7ba1bcb6c1b48d",
          "sha256": "a4f388497fad90088f4545b4c2457d81a57583f5097699af768cc1a2f53eaf8e",
          "sha1": "255244989c740525eed0ec341e619b1cc9d02e5f",
          "md5": "9926eace4be55f7b3c5c3ff0c983ab9c"
        }
      ]
    }
  ]
}
