{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "a2gxlr67vjd6pgvnmsqrgucg3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0e46f6e063c8396a8aee29e4d8d214d4187a13d6751abca6094f7eefcb546707b4f096b3e5c701064cf78e945a0688374516b028c642ab4ff1e7b3c67d9c2500",
          "sha256": "21b824cfc8d6c569e1a2997dd65c90281ef09817bad511bdd34c7517d845934a",
          "sha1": "e7c5e7fb5322ea4c44a87dac3772072490e60714",
          "md5": "ba0b31c7562057b4deac7fe9aeebf7c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0e46f6e063c8396a8aee29e4d8d214d4187a13d6751abca6094f7eefcb546707b4f096b3e5c701064cf78e945a0688374516b028c642ab4ff1e7b3c67d9c2500",
          "sha256": "21b824cfc8d6c569e1a2997dd65c90281ef09817bad511bdd34c7517d845934a",
          "sha1": "e7c5e7fb5322ea4c44a87dac3772072490e60714",
          "md5": "ba0b31c7562057b4deac7fe9aeebf7c2"
        }
      ]
    }
  ]
}
