{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "dws5bmwndjfjtlacyyxejjgowm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "25324edb3d4641cad65c52d10a45d9ac92af90f6238dc051639a1726f1056643c669851834eb896e89b2054150bda512283a201fbda8f3b9bc5d817f4410b884",
          "sha256": "926014407b8331e702519d334f4969ff7afe72924fb2024d810f0b40e2e3f3ac",
          "sha1": "5cd78b606c3faa3e80b577a067d47d16b51fec86",
          "md5": "25aa2147965370281f567dfee477fcf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "25324edb3d4641cad65c52d10a45d9ac92af90f6238dc051639a1726f1056643c669851834eb896e89b2054150bda512283a201fbda8f3b9bc5d817f4410b884",
          "sha256": "926014407b8331e702519d334f4969ff7afe72924fb2024d810f0b40e2e3f3ac",
          "sha1": "5cd78b606c3faa3e80b577a067d47d16b51fec86",
          "md5": "25aa2147965370281f567dfee477fcf1"
        }
      ]
    }
  ]
}
