{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4vaohbfcnresdmlpcjoahtwuja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "29ce18c3978e7da9c5f1e77397d4d440d9968e6d064453da97d30a49d0f5540384a04e4e7f2c1f702181dc7f37fe5bc5e19889d548c80dd0e046e9a00bf6402b",
          "sha256": "96b1dce7790add0febdcc396137ad6b7250223b4d89a08d2772b48512fb9b879",
          "sha1": "7a471bfe435eee0938e8b5cd89daa79a904a9d27",
          "md5": "af7806fe94c99eaafb7554c6fae12df6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "29ce18c3978e7da9c5f1e77397d4d440d9968e6d064453da97d30a49d0f5540384a04e4e7f2c1f702181dc7f37fe5bc5e19889d548c80dd0e046e9a00bf6402b",
          "sha256": "96b1dce7790add0febdcc396137ad6b7250223b4d89a08d2772b48512fb9b879",
          "sha1": "7a471bfe435eee0938e8b5cd89daa79a904a9d27",
          "md5": "af7806fe94c99eaafb7554c6fae12df6"
        }
      ]
    }
  ]
}
