{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fy2h4icwofb2tnozqrmgmnqqce"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "064d1d723eeaf4e4f9e8eeb9ea4fe540cec56826c9a0f78e8ad3c0871780306fedafb263719916378ecfba9650c6868426ccaa39a86c58f97a110611eae49c75",
          "sha256": "fc9e0323d0726320b4e36d7b5917dbe810e36fd931101dbbad4f89ce97b2576c",
          "sha1": "a07094fcd5bed81f4bee910fb281b2d47ad88a77",
          "md5": "13b0d254f75333e3675d0b1c676df527"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "064d1d723eeaf4e4f9e8eeb9ea4fe540cec56826c9a0f78e8ad3c0871780306fedafb263719916378ecfba9650c6868426ccaa39a86c58f97a110611eae49c75",
          "sha256": "fc9e0323d0726320b4e36d7b5917dbe810e36fd931101dbbad4f89ce97b2576c",
          "sha1": "a07094fcd5bed81f4bee910fb281b2d47ad88a77",
          "md5": "13b0d254f75333e3675d0b1c676df527"
        }
      ]
    }
  ]
}
