{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3pyb4puf7bhmlkvuvebv6cilhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "cf97947cbe120a01e837d2cbfd998cce4e51a0720236d0bb382861e83f4a6df8842ff0314c0704846bbbc24f1b6d13aafe59e44f8e8feae063fb4d24442d9f4c",
          "sha256": "ceb70c99b7259cd0f9cd3d5e265af3c4a7783c87cbbf1bf5a84ffca28124224b",
          "sha1": "e0d707ed0eb7fc359709dad1c1d6654f74ea259f",
          "md5": "f2949af81aa56effb5828166ef04a653"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "cf97947cbe120a01e837d2cbfd998cce4e51a0720236d0bb382861e83f4a6df8842ff0314c0704846bbbc24f1b6d13aafe59e44f8e8feae063fb4d24442d9f4c",
          "sha256": "ceb70c99b7259cd0f9cd3d5e265af3c4a7783c87cbbf1bf5a84ffca28124224b",
          "sha1": "e0d707ed0eb7fc359709dad1c1d6654f74ea259f",
          "md5": "f2949af81aa56effb5828166ef04a653"
        }
      ]
    }
  ]
}
