{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xnh4hokt75ckzjw5iiy2uuictm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "753d6ce43ec6b14f043331a26dc9d1d8884350cc1238fc7b8119299d1235b214064ab647320241c5c654dd624535d1070ed6ead587c8726c691ef86db0dc1c1c",
          "sha256": "1b35db31e5e5b518fef4965239825655c13dd8b0c48a6cdebe34dea4a2616aa3",
          "sha1": "053a4627b0d55b74eb3fa7b84534dd4fd5c7fb8b",
          "md5": "fdb0bc1262b584df82dc832fbdb48c19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "753d6ce43ec6b14f043331a26dc9d1d8884350cc1238fc7b8119299d1235b214064ab647320241c5c654dd624535d1070ed6ead587c8726c691ef86db0dc1c1c",
          "sha256": "1b35db31e5e5b518fef4965239825655c13dd8b0c48a6cdebe34dea4a2616aa3",
          "sha1": "053a4627b0d55b74eb3fa7b84534dd4fd5c7fb8b",
          "md5": "fdb0bc1262b584df82dc832fbdb48c19"
        }
      ]
    }
  ]
}
