{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uhzw3paygrhubm5wa7imgubjsu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "4896af11507870e38081138511a7cede6642d9e2c43710868aa831d07b7cc560811cfe1eeba2a5a836fc9767b501f9acb4f87344e6b6d935b7f92e4fdfd5a4da",
          "sha256": "4410da979a7e9a07f4e585d619275c7237a49d9be5143e10f31ade9fac3c0225",
          "sha1": "c7edd24fc45b18f9afc6ba53f658349f904f2c5b",
          "md5": "946018cce77e1462f47fe5bda6285eb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "4896af11507870e38081138511a7cede6642d9e2c43710868aa831d07b7cc560811cfe1eeba2a5a836fc9767b501f9acb4f87344e6b6d935b7f92e4fdfd5a4da",
          "sha256": "4410da979a7e9a07f4e585d619275c7237a49d9be5143e10f31ade9fac3c0225",
          "sha1": "c7edd24fc45b18f9afc6ba53f658349f904f2c5b",
          "md5": "946018cce77e1462f47fe5bda6285eb0"
        }
      ]
    }
  ]
}
