{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "m7nxczhs6vhnbej7f63yi3rily"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "fc8e4f3a1248f730edf1a4ef9c763b2c615ad416c2f777626310f62c25459410f55d8f215d33aef4294fcf1522e2416dc3bcb147b9c041eacee25f7fdb654d64",
          "sha256": "b863a037698ba9f489e1f7b4e71a2ff0e40d4ef29f0536545d57bd32a1c0e765",
          "sha1": "942a948b822f81392f71e1073fb16c3f96e27d37",
          "md5": "d53ad34002569c95dc1a4c5745f6e493"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "fc8e4f3a1248f730edf1a4ef9c763b2c615ad416c2f777626310f62c25459410f55d8f215d33aef4294fcf1522e2416dc3bcb147b9c041eacee25f7fdb654d64",
          "sha256": "b863a037698ba9f489e1f7b4e71a2ff0e40d4ef29f0536545d57bd32a1c0e765",
          "sha1": "942a948b822f81392f71e1073fb16c3f96e27d37",
          "md5": "d53ad34002569c95dc1a4c5745f6e493"
        }
      ]
    }
  ]
}
