{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "j2mylc3nv5hh7f75sbxnz4o2lu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a42f9094c61cd61fde4b85d89869f5678bb2c81b77fed2fcdafa6b14c04a7285786efcb6d60f57744665fa3ed49a328ae9f580a17769ffef3f4273d38ca8fb91",
          "sha256": "f6c0f6008d1efb404052bfb6047afe4ec63eb734c848081a32d329c5d33aed4e",
          "sha1": "a0a6a769a0b6076340cf439d139bbd6f1830f71a",
          "md5": "d7941f7369eb77eea445ca8e18b7990e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "a42f9094c61cd61fde4b85d89869f5678bb2c81b77fed2fcdafa6b14c04a7285786efcb6d60f57744665fa3ed49a328ae9f580a17769ffef3f4273d38ca8fb91",
          "sha256": "f6c0f6008d1efb404052bfb6047afe4ec63eb734c848081a32d329c5d33aed4e",
          "sha1": "a0a6a769a0b6076340cf439d139bbd6f1830f71a",
          "md5": "d7941f7369eb77eea445ca8e18b7990e"
        }
      ]
    }
  ]
}
