{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "m7aaxujckjf7zf6fwpkjzmpblm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f87e3e90343f0e7ae188da9b24fc016ab5340d1cf1f59d150331caa3246fbeff7f68250efdb3032f2b1cc984d3e8b1c2983a2a09bc51a562a9b433013eccda7a",
          "sha256": "c8eeef8576492aa0389d81166cadbba7528c3d2c939ea24150a6cac4bdef13e2",
          "sha1": "933316e3dcf03a89bee60e8811c5680ab3626646",
          "md5": "040dc41c68cb277f82ca9e1d18680d37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f87e3e90343f0e7ae188da9b24fc016ab5340d1cf1f59d150331caa3246fbeff7f68250efdb3032f2b1cc984d3e8b1c2983a2a09bc51a562a9b433013eccda7a",
          "sha256": "c8eeef8576492aa0389d81166cadbba7528c3d2c939ea24150a6cac4bdef13e2",
          "sha1": "933316e3dcf03a89bee60e8811c5680ab3626646",
          "md5": "040dc41c68cb277f82ca9e1d18680d37"
        }
      ]
    }
  ]
}
