{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "32azslkqffd3znzgmhvi44kjza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "bd47d08ba3d6f9bbf6522a3a183e402aa2b6392073024a709644e9940661a0818e01f03f3fe57c7e76a5a4b2cc3d8f11f5de12deab1edd608edc5ce10c8a7670",
          "sha256": "8326a85deab38317c5eee3c9ef6a17b6ec18fe70c9058f5fe742279e13b64bdd",
          "sha1": "958a6fa9749a916457d5598997d6f6a4536d1e96",
          "md5": "5d6cfa67c20d3de06832584db1d8f8bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "bd47d08ba3d6f9bbf6522a3a183e402aa2b6392073024a709644e9940661a0818e01f03f3fe57c7e76a5a4b2cc3d8f11f5de12deab1edd608edc5ce10c8a7670",
          "sha256": "8326a85deab38317c5eee3c9ef6a17b6ec18fe70c9058f5fe742279e13b64bdd",
          "sha1": "958a6fa9749a916457d5598997d6f6a4536d1e96",
          "md5": "5d6cfa67c20d3de06832584db1d8f8bd"
        }
      ]
    }
  ]
}
