{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-fix-checkRestrictions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "diiijoabxbckzozrfz4hjevnv4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0e2dc9018764684cb1c4224b36baf171d73dd8d80a4942336c03107c6a9c4dcbbc23db0c5f468249664e964d4569ec00b34b4ee1cfd15ed6052364e19d95d87d",
          "sha256": "b91eb96f0fccd894b4b143a34c27aa0258557d93a8b1b9e867c56b0ddd475978",
          "sha1": "abd37e84d024aabfcfb5893f92cfa9c9cbfdc5fa",
          "md5": "7511e36a9ef176459de5c884887e64ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-checkRestrictions-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-checkRestrictions-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "0e2dc9018764684cb1c4224b36baf171d73dd8d80a4942336c03107c6a9c4dcbbc23db0c5f468249664e964d4569ec00b34b4ee1cfd15ed6052364e19d95d87d",
          "sha256": "b91eb96f0fccd894b4b143a34c27aa0258557d93a8b1b9e867c56b0ddd475978",
          "sha1": "abd37e84d024aabfcfb5893f92cfa9c9cbfdc5fa",
          "md5": "7511e36a9ef176459de5c884887e64ae"
        }
      ]
    }
  ]
}
