{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uhc6akxktvhrvmzhgrg4srjpwq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "7e53db8ddddd3589502f13b376aae7ff403e7d35e8b5c15b1aedd6c02feca45cafb4ccdaf41abb4705cc5444e33d5d46dbf17afd0f2611f5ebb9996fee281f54",
          "sha256": "1487aafafe492a5cee306ba4f3303da361a0b38bec3e622a8d1a9c516a304bf0",
          "sha1": "8c3692ce762958d1352daafbd8ae10be33f04863",
          "md5": "ed518f19391d7ca1ec3a741170cf620d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "7e53db8ddddd3589502f13b376aae7ff403e7d35e8b5c15b1aedd6c02feca45cafb4ccdaf41abb4705cc5444e33d5d46dbf17afd0f2611f5ebb9996fee281f54",
          "sha256": "1487aafafe492a5cee306ba4f3303da361a0b38bec3e622a8d1a9c516a304bf0",
          "sha1": "8c3692ce762958d1352daafbd8ae10be33f04863",
          "md5": "ed518f19391d7ca1ec3a741170cf620d"
        }
      ]
    }
  ]
}
