{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "k54ks5kykfawxetn3sqiancbbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "927f6be6071381e2b4f5d1b8117e184924681dc61ff94d9789d0cdc16d14c147e71e845bc0518a9f99882e2cb8cace90fc6890d6515a1adc57ad3ce85516eecc",
          "sha256": "c4bf5082058b98f78d1b65a5f92ebdd3f04a70251c5d903f3d99b12d8ab1eaf0",
          "sha1": "b30a09eeee9e112106554b50f84987ae281730ad",
          "md5": "8bf623e0263edf5b92c2b5b287775eed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "927f6be6071381e2b4f5d1b8117e184924681dc61ff94d9789d0cdc16d14c147e71e845bc0518a9f99882e2cb8cace90fc6890d6515a1adc57ad3ce85516eecc",
          "sha256": "c4bf5082058b98f78d1b65a5f92ebdd3f04a70251c5d903f3d99b12d8ab1eaf0",
          "sha1": "b30a09eeee9e112106554b50f84987ae281730ad",
          "md5": "8bf623e0263edf5b92c2b5b287775eed"
        }
      ]
    }
  ]
}
