{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.6.1-add-spotless-gradle-plugin-SNAPSHOT/util-jvm-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.6.1-add-spotless-gradle-plugin-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "y5px6cxa5jc3fi6srkqhuchaua"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "url": "util-metadata-1.6.1-add-spotless-gradle-plugin-SNAPSHOT.jar",
          "size": 6584,
          "sha512": "290bf87fb7d55d30f06892080fe6d9eefad116de246cb1d625031d6f8efe63e492bbabf8536d058a1d75ee91b1ba7ed3503661b70972b36009b9e2654961dbf0",
          "sha256": "ef345dc0b24189923f6dd8bfcea9ddea422d94b6555f2bf2e425cef37032f336",
          "sha1": "51ff24b9c44a7d29aba8f23a44c1446e1c3dc2dd",
          "md5": "fbcedc203fc09c52d7203812d6ebe9e4"
        }
      ]
    }
  ]
}
