{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-fix-date-formatting-on-search-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6xcmg72gknbmln5zn4duvnj2b4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "c874cdca252cbe75799b383e21b3352082620db93d14553c61dd8735811e774aa3522b19f55f3412698f40b4acb140daec6c844da3662c8e3c7804cc4063cb6a",
          "sha256": "2a9d56e6556b90d1aff6c8c36b17c51c91b3a40d81f666c7c1363001ad83d243",
          "sha1": "b4b1fc1736f88ebf7d5cbb749c6a08375db7be4f",
          "md5": "55e681fd0212c3fef266087ed34af086"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "c874cdca252cbe75799b383e21b3352082620db93d14553c61dd8735811e774aa3522b19f55f3412698f40b4acb140daec6c844da3662c8e3c7804cc4063cb6a",
          "sha256": "2a9d56e6556b90d1aff6c8c36b17c51c91b3a40d81f666c7c1363001ad83d243",
          "sha1": "b4b1fc1736f88ebf7d5cbb749c6a08375db7be4f",
          "md5": "55e681fd0212c3fef266087ed34af086"
        }
      ]
    }
  ]
}
