{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "mfprk45s25axdkmq3qj2tphg7i"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "size": 44957,
          "sha512": "db540d7f47aa3c3b79dda6cb499f0876535291402cdec76e26e4f8a076886229bfc78a95da4b6a54c435ebd153ada513c85419256995fa8297f682d7a01e3a18",
          "sha256": "08951458dc92ea06a1fd60ad369d106fa51b6953ab29fa73dc31cc8b010031eb",
          "sha1": "477dce53cc52ebfcfae711af9ab96ce0c4c550cb",
          "md5": "798e92c28ece8fe5fac71bd6875c683b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-module-tests-ignore-tag-order-SNAPSHOT.aar",
          "size": 44957,
          "sha512": "db540d7f47aa3c3b79dda6cb499f0876535291402cdec76e26e4f8a076886229bfc78a95da4b6a54c435ebd153ada513c85419256995fa8297f682d7a01e3a18",
          "sha256": "08951458dc92ea06a1fd60ad369d106fa51b6953ab29fa73dc31cc8b010031eb",
          "sha1": "477dce53cc52ebfcfae711af9ab96ce0c4c550cb",
          "md5": "798e92c28ece8fe5fac71bd6875c683b"
        }
      ]
    }
  ]
}
