{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.0-fix-release-ci-job-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xur4nmttufginmopoalmcfnbeu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "93e2f5ecbae343d0f4f74d0d576cf260593a1b9c9ce1d4894bbd74fc4b890c57e482fc0664241a6bf03494fcd6afd7804d6095c4bb836ab326ccc7970658a548",
          "sha256": "f93b6a017e17c3a9a9df6970911e89671bd8c15e8251461f649ba23205cad27e",
          "sha1": "224e3a54e60996d3f5337bcf7478e359c2871caa",
          "md5": "a7df3fe8183d20f70708a9260f882158"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.0-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.0-fix-release-ci-job-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "93e2f5ecbae343d0f4f74d0d576cf260593a1b9c9ce1d4894bbd74fc4b890c57e482fc0664241a6bf03494fcd6afd7804d6095c4bb836ab326ccc7970658a548",
          "sha256": "f93b6a017e17c3a9a9df6970911e89671bd8c15e8251461f649ba23205cad27e",
          "sha1": "224e3a54e60996d3f5337bcf7478e359c2871caa",
          "md5": "a7df3fe8183d20f70708a9260f882158"
        }
      ]
    }
  ]
}
