{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "goqahyz2p5catlz3u62nt6qc3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "9c75476f8f655704309746ec3d3eec2b5aa2ba0904fd65800ff6a51e83d790694650d0a76f8b782654175aceac9332f86ab64ee1c1344d86a78be9a03a18960a",
          "sha256": "f2a2ac049731d695dd5802a5907d121cbd97f405d599c2c64aca4c388c7684d8",
          "sha1": "b446c91543919d426886bae6515e6659c241e935",
          "md5": "084d9b713cc09bba1479e18faaa9c395"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "9c75476f8f655704309746ec3d3eec2b5aa2ba0904fd65800ff6a51e83d790694650d0a76f8b782654175aceac9332f86ab64ee1c1344d86a78be9a03a18960a",
          "sha256": "f2a2ac049731d695dd5802a5907d121cbd97f405d599c2c64aca4c388c7684d8",
          "sha1": "b446c91543919d426886bae6515e6659c241e935",
          "md5": "084d9b713cc09bba1479e18faaa9c395"
        }
      ]
    }
  ]
}
