{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "q2d73emoy5ddnd7y7p43cgs3za"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d1eaaf41809c95f4150d8cbdd91672c2888c7d6832db5a26fed599993e4494e61c76d47d976f0fd1b0c0f0e7cb4d11bcad5be074ce6927487600afeacb3c9042",
          "sha256": "351ed34d73375d4182c5e304a602c5004a355953ab4e70c9688ed5b9a7c99c3d",
          "sha1": "e62c8df1cfda8dc75ddf1ea220a23b465ea3d811",
          "md5": "cd47b4f6f771977f6bca1c9b47b91c22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "d1eaaf41809c95f4150d8cbdd91672c2888c7d6832db5a26fed599993e4494e61c76d47d976f0fd1b0c0f0e7cb4d11bcad5be074ce6927487600afeacb3c9042",
          "sha256": "351ed34d73375d4182c5e304a602c5004a355953ab4e70c9688ed5b9a7c99c3d",
          "sha1": "e62c8df1cfda8dc75ddf1ea220a23b465ea3d811",
          "md5": "cd47b4f6f771977f6bca1c9b47b91c22"
        }
      ]
    }
  ]
}
