{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-bump-update-fhir-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "nd6oie6ysjboxkcwyybcj7bbzm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-bump-update-fhir-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "a8fdfdf262abb789e686e33989b966efbf9ea0da82a90a4cfd7e2661530e6cfafcc8679e556ce281ea141cf9db39905f570ab3111251f20efd1bf82ada1680ca",
          "sha256": "7f56fcf3f469bf10f90450aed1d5da25ce801db191b94aca797c56edceae24ea",
          "sha1": "5de8b19b5016567c68bd4793cac73a70f87d14cc",
          "md5": "822bc1352930f6123652e85af41e518e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-bump-update-fhir-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-bump-update-fhir-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "a8fdfdf262abb789e686e33989b966efbf9ea0da82a90a4cfd7e2661530e6cfafcc8679e556ce281ea141cf9db39905f570ab3111251f20efd1bf82ada1680ca",
          "sha256": "7f56fcf3f469bf10f90450aed1d5da25ce801db191b94aca797c56edceae24ea",
          "sha1": "5de8b19b5016567c68bd4793cac73a70f87d14cc",
          "md5": "822bc1352930f6123652e85af41e518e"
        }
      ]
    }
  ]
}
