{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6d4fohjin5bthckban4ygjphc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "98912ae57c5950c6cf02babdaa8666c591e4b0bcceba78349d36272846513edfcc0832c862aa109988293e4e8a74ea42694c4720eac0d89f767b1a893eb41107",
          "sha256": "a29f18f03bf153c65cccaa678fb9cfcf24368a7840149f9ce1c5f3d6d5afa4d9",
          "sha1": "a25babac3719f77884682115d4104ebe3b5e9330",
          "md5": "548a92eb7dd64d165e9f06c49ae9dd05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-RecordServiceAdditionals-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-RecordServiceAdditionals-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "98912ae57c5950c6cf02babdaa8666c591e4b0bcceba78349d36272846513edfcc0832c862aa109988293e4e8a74ea42694c4720eac0d89f767b1a893eb41107",
          "sha256": "a29f18f03bf153c65cccaa678fb9cfcf24368a7840149f9ce1c5f3d6d5afa4d9",
          "sha1": "a25babac3719f77884682115d4104ebe3b5e9330",
          "md5": "548a92eb7dd64d165e9f06c49ae9dd05"
        }
      ]
    }
  ]
}
