{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.1-change-readme-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qhsmuqmh7rfdzfk3s4odl6a5ci"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.1-change-readme-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-readme-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "33dc66390238e576e59dd10d3627cf773503677d7f87f67675f41c9428e648e124e0d42de18b26960f22456597893abeeeb8c4b2f2ab7cbac09a956e1c2fcd6b",
          "sha256": "143c1835332ee769edc4e0d74d10193573ce16a0e67a16ded9716480ccf40705",
          "sha1": "68001ff48cbe8079ca7c3a1dd324a78566ef1e08",
          "md5": "5489c2ba0093cae697f20cac54bf5743"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.1-change-readme-SNAPSHOT.jar",
          "url": "crypto-common-1.9.1-change-readme-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "33dc66390238e576e59dd10d3627cf773503677d7f87f67675f41c9428e648e124e0d42de18b26960f22456597893abeeeb8c4b2f2ab7cbac09a956e1c2fcd6b",
          "sha256": "143c1835332ee769edc4e0d74d10193573ce16a0e67a16ded9716480ccf40705",
          "sha1": "68001ff48cbe8079ca7c3a1dd324a78566ef1e08",
          "md5": "5489c2ba0093cae697f20cac54bf5743"
        }
      ]
    }
  ]
}
