{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-change-tags-and-annotations-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "c64kvleewfbv7gv3dfpz3wrevy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "881768d9af7e3ba25e5485b648b10f658da7073e6844d2ca1aa026041f1377b211054382dee2628018603561f14a2fad0b1bba750089bab1ce28f73a2253eab4",
          "sha256": "70e73150849d8fb140113524ce638f7c8c1f79df2ebff70ddc6ec49550150096",
          "sha1": "ba76fac1a78f53bc654884f5d01b2c3bbbabaf9e",
          "md5": "20b9997a256f9ddb4f98c1715b24d0e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-tags-and-annotations-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-tags-and-annotations-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "881768d9af7e3ba25e5485b648b10f658da7073e6844d2ca1aa026041f1377b211054382dee2628018603561f14a2fad0b1bba750089bab1ce28f73a2253eab4",
          "sha256": "70e73150849d8fb140113524ce638f7c8c1f79df2ebff70ddc6ec49550150096",
          "sha1": "ba76fac1a78f53bc654884f5d01b2c3bbbabaf9e",
          "md5": "20b9997a256f9ddb4f98c1715b24d0e0"
        }
      ]
    }
  ]
}
