{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-recordservice-download-upload-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "onleued4znal7nvsg6sz4jmpme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-upload-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "90b3a4ac6ef4c4c3a33ed1a2bcdf36bd5b555c147d0a683d3d11d556a2ef1407ba29ecadc21898e0bdea6a218a7b96f2d64637480924da5ede6361099e0389e8",
          "sha256": "3655d33a0af30a177f80d9691e8ef801bf5cad147b571d6a11dace5d8412d51e",
          "sha1": "39e96e09d58ccf3d1399b936ae03faf8082ffc75",
          "md5": "4e77bdbd68fbc1ba7e2ee4e9566ca78e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-recordservice-download-upload-test-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-upload-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "90b3a4ac6ef4c4c3a33ed1a2bcdf36bd5b555c147d0a683d3d11d556a2ef1407ba29ecadc21898e0bdea6a218a7b96f2d64637480924da5ede6361099e0389e8",
          "sha256": "3655d33a0af30a177f80d9691e8ef801bf5cad147b571d6a11dace5d8412d51e",
          "sha1": "39e96e09d58ccf3d1399b936ae03faf8082ffc75",
          "md5": "4e77bdbd68fbc1ba7e2ee4e9566ca78e"
        }
      ]
    }
  ]
}
