{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4ji23phdcnhzpa3kqzxrm27uia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "dbfa3bcb983057d701b4f8510ef613cfb23f7679c261f3b31d1e4de6e49593d7e347e06b0e1320eb82c50f2f57a48bbeb8525372d09b250dac65a44b03993c04",
          "sha256": "7f60bda67f0b8b429c61fe403f278b6988e6f7448b928d849398e484dd7be5c6",
          "sha1": "d22df004c9c125c40a0729f69d42fe911bfb22fc",
          "md5": "7e51c17e78f422a1d8d8d69ea1dfeff6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "dbfa3bcb983057d701b4f8510ef613cfb23f7679c261f3b31d1e4de6e49593d7e347e06b0e1320eb82c50f2f57a48bbeb8525372d09b250dac65a44b03993c04",
          "sha256": "7f60bda67f0b8b429c61fe403f278b6988e6f7448b928d849398e484dd7be5c6",
          "sha1": "d22df004c9c125c40a0729f69d42fe911bfb22fc",
          "md5": "7e51c17e78f422a1d8d8d69ea1dfeff6"
        }
      ]
    }
  ]
}
