{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-record-creation-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zt2zqpbavncx3botu5tvhxr7cy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "ed52a5172c8d6e53a7e6180acc3514a0b39a05febf8f9079a8a43d9a65a1dedba72c65b0b2babb1e69ba05960349b88422046d61c2aa0f3f56a6f2289a7effd6",
          "sha256": "18b90f4257235a9f7acb271a86950c69a1a72408e77c3cbabcb2031677ab0ad3",
          "sha1": "2ff3ca994da3b3705f6dd73efeefba3018388f85",
          "md5": "736d212c3618c386572df1864c84b1d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-record-creation-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-record-creation-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "ed52a5172c8d6e53a7e6180acc3514a0b39a05febf8f9079a8a43d9a65a1dedba72c65b0b2babb1e69ba05960349b88422046d61c2aa0f3f56a6f2289a7effd6",
          "sha256": "18b90f4257235a9f7acb271a86950c69a1a72408e77c3cbabcb2031677ab0ad3",
          "sha1": "2ff3ca994da3b3705f6dd73efeefba3018388f85",
          "md5": "736d212c3618c386572df1864c84b1d8"
        }
      ]
    }
  ]
}
