{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "b2jdpwlhsbdaderp7fakrbig5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "620fe3339bf2af73ec5d55d9cf95f495d2fcb563fc45e346be79f53f16721a60cf1c5a1df606bf9a5dc0babff6e1ad9e53011d4b51d64f5ac8a4e15a467bde73",
          "sha256": "0f6d5b2764ad30829ede03ce2f27c56af337f31f9a8501dee899ccf514662647",
          "sha1": "d2e290ff776410e337fa8399f1002b51d8625551",
          "md5": "2889d7cc4af3ba0db7ec6c252ba77f87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-module-test-recordservice-count-fake-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "620fe3339bf2af73ec5d55d9cf95f495d2fcb563fc45e346be79f53f16721a60cf1c5a1df606bf9a5dc0babff6e1ad9e53011d4b51d64f5ac8a4e15a467bde73",
          "sha256": "0f6d5b2764ad30829ede03ce2f27c56af337f31f9a8501dee899ccf514662647",
          "sha1": "d2e290ff776410e337fa8399f1002b51d8625551",
          "md5": "2889d7cc4af3ba0db7ec6c252ba77f87"
        }
      ]
    }
  ]
}
