{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.11.0-change-network-model-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rytikfyslvfxbcghpiw35okugy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7f9cbe18da41c5c99c4baa2b6e2022f0b76b76a38d1c9acca1f808df375807b97b21218729c95508c7515f4bf7803877776fbe0901479dc324e9df7a55b5f1c9",
          "sha256": "4af35bbc692f2f4edcb0a7721cce2e059b272365caf9bd474f841edfd5ff40ea",
          "sha1": "83c6c26d3d90f4a7ee5ab9d41f69a38e78529c76",
          "md5": "3a3cb363f142ab9dbe1392c0d43565b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "url": "securestore-common-1.11.0-change-network-model-tests-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "7f9cbe18da41c5c99c4baa2b6e2022f0b76b76a38d1c9acca1f808df375807b97b21218729c95508c7515f4bf7803877776fbe0901479dc324e9df7a55b5f1c9",
          "sha256": "4af35bbc692f2f4edcb0a7721cce2e059b272365caf9bd474f841edfd5ff40ea",
          "sha1": "83c6c26d3d90f4a7ee5ab9d41f69a38e78529c76",
          "md5": "3a3cb363f142ab9dbe1392c0d43565b1"
        }
      ]
    }
  ]
}
