{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mo3uhzmzcvey3eimx3rsgwb3aa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "06e72ce9a59c6eb592f06817a7d6f027cb6f622a24c1294334db5a708756d0b2fe5005f050bbe854f16a2b29c10135a60828e131a4780d902c803bd01b8d63e3",
          "sha256": "a8bee7235b65287282b53db5cf7ee8d80d1a29550a3bdf51fee12c39971dae7a",
          "sha1": "b241041c7831ef87d5ea6c3003f06f94e03204b1",
          "md5": "84812f8743ba3e68cdf7af6c962591cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "06e72ce9a59c6eb592f06817a7d6f027cb6f622a24c1294334db5a708756d0b2fe5005f050bbe854f16a2b29c10135a60828e131a4780d902c803bd01b8d63e3",
          "sha256": "a8bee7235b65287282b53db5cf7ee8d80d1a29550a3bdf51fee12c39971dae7a",
          "sha1": "b241041c7831ef87d5ea6c3003f06f94e03204b1",
          "md5": "84812f8743ba3e68cdf7af6c962591cd"
        }
      ]
    }
  ]
}
