{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.2-change-crypte-secured-store-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bwy24dubdva5djrrcuvxm56d5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0a65108938cacbf2e708532eed00e7220226196f9af827f1c16957e1e9945546000a532e3e420ec7d5356f42cf6164770be913ecc06f369c9311ffcdd30bde3a",
          "sha256": "792f2703b5a705b731f7d27a8f42bab06b9a7b3cc1139e4c4696df729619277e",
          "sha1": "8eee3ae81905079cd6686bdffb8bd5f97f61acc0",
          "md5": "17f9cad520428cf833d3622a76eb9676"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.2-change-crypte-secured-store-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.2-change-crypte-secured-store-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0a65108938cacbf2e708532eed00e7220226196f9af827f1c16957e1e9945546000a532e3e420ec7d5356f42cf6164770be913ecc06f369c9311ffcdd30bde3a",
          "sha256": "792f2703b5a705b731f7d27a8f42bab06b9a7b3cc1139e4c4696df729619277e",
          "sha1": "8eee3ae81905079cd6686bdffb8bd5f97f61acc0",
          "md5": "17f9cad520428cf833d3622a76eb9676"
        }
      ]
    }
  ]
}
