{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-add-crypto-service-interface-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sgn7fwldjff4hmqfhhewyascbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "16b513378179e0f75df2d731f361a66fbe0af76f7b02a91d5e6fd19b766c96fc072220fd8a0e53fc4525f8432f2bb17ed4b683b76adaf87502aa705b68831247",
          "sha256": "3e3844f13b7295018c8d5c8fbce0ea8254cec388b1120b2318812a690bedeb6e",
          "sha1": "adde462bb3aa2a70962191a6a285d354eee2eef1",
          "md5": "9927a13c1a568e8d92d79930efccc7c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "16b513378179e0f75df2d731f361a66fbe0af76f7b02a91d5e6fd19b766c96fc072220fd8a0e53fc4525f8432f2bb17ed4b683b76adaf87502aa705b68831247",
          "sha256": "3e3844f13b7295018c8d5c8fbce0ea8254cec388b1120b2318812a690bedeb6e",
          "sha1": "adde462bb3aa2a70962191a6a285d354eee2eef1",
          "md5": "9927a13c1a568e8d92d79930efccc7c7"
        }
      ]
    }
  ]
}
