{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-add-crypto-service-interface-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zibhshthxfcwbmwhejrsgvmla4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "018c4208d3cca8dbc366e973c4672250cd704d403693bc2adb9c83375d7beb16c46a8e79c10194115f5daab252752256857aadf37bc10e2443cdc71d9823dac8",
          "sha256": "6e5a2efc8c2098dd7538eefdc988478660ff4e0a566888560686ff513ede7c91",
          "sha1": "41d5fb6395ecd90d57f3c2c2feb635e9d6db78b9",
          "md5": "3a3c66b82ecb747949ba9e3364715884"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-add-crypto-service-interface-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "018c4208d3cca8dbc366e973c4672250cd704d403693bc2adb9c83375d7beb16c46a8e79c10194115f5daab252752256857aadf37bc10e2443cdc71d9823dac8",
          "sha256": "6e5a2efc8c2098dd7538eefdc988478660ff4e0a566888560686ff513ede7c91",
          "sha1": "41d5fb6395ecd90d57f3c2c2feb635e9d6db78b9",
          "md5": "3a3c66b82ecb747949ba9e3364715884"
        }
      ]
    }
  ]
}
