{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-change-contribution-guide-SNAPSHOT/fhir-0.0.1-change-contribution-guide-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-change-contribution-guide-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "qgxwql3c5baj7evosdgiukx44m"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fhir-jvm-0.0.1-change-contribution-guide-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-change-contribution-guide-SNAPSHOT.jar",
          "size": 2431017,
          "sha512": "b24b7d3d5bbd4db5cb38b164138212ef413a0288b216a085546159369a78e0daea91a42e1d85c56c838fa987da36c1d6eff5e8fd525788c578071e4c6bd652d0",
          "sha256": "4c1fb3c64878a6a77427bb07343e8dbdc81ad19876e1a75bf25ef275269920be",
          "sha1": "2c73d1e3e5997d1a33de729b155fa5f6f4932212",
          "md5": "b46792f2bc181a98301e0112683da5b0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-jvm-0.0.1-change-contribution-guide-SNAPSHOT.jar",
          "url": "fhir-jvm-0.0.1-change-contribution-guide-SNAPSHOT.jar",
          "size": 2431017,
          "sha512": "b24b7d3d5bbd4db5cb38b164138212ef413a0288b216a085546159369a78e0daea91a42e1d85c56c838fa987da36c1d6eff5e8fd525788c578071e4c6bd652d0",
          "sha256": "4c1fb3c64878a6a77427bb07343e8dbdc81ad19876e1a75bf25ef275269920be",
          "sha1": "2c73d1e3e5997d1a33de729b155fa5f6f4932212",
          "md5": "b46792f2bc181a98301e0112683da5b0"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-change-contribution-guide-SNAPSHOT/fhir-metadata-0.0.1-change-contribution-guide-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-change-contribution-guide-SNAPSHOT"
      }
    }
  ]
}
