{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.10.0-change-attachment-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "exelpoy45nfzfo62fxa23bssyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "cc77569893f9e85ba2e0fcf1565bae3f1ecf35c62401c8aabe7e5053b39bae392e084dbc117ce7d0b3d42aebd0239a62033cdbc440fc8f7c6d69bcc9d0b29abb",
          "sha256": "36be826e2375e1c0a67d5939771a9cc4bee2865292ed0408f00651493b89e76a",
          "sha1": "38019d8174defbf69bd43f9e3e833f056cffc9fd",
          "md5": "d66ab777329677e573ddd2fe3e02cf2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "auth-common-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "cc77569893f9e85ba2e0fcf1565bae3f1ecf35c62401c8aabe7e5053b39bae392e084dbc117ce7d0b3d42aebd0239a62033cdbc440fc8f7c6d69bcc9d0b29abb",
          "sha256": "36be826e2375e1c0a67d5939771a9cc4bee2865292ed0408f00651493b89e76a",
          "sha1": "38019d8174defbf69bd43f9e3e833f056cffc9fd",
          "md5": "d66ab777329677e573ddd2fe3e02cf2d"
        }
      ]
    }
  ]
}
