{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "sgpkt5oz6rdojn6ojfll3aqlii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "4a4115d4982a391bb5cda24e83dc54bb669569db565718c566527bb0985b6f28f82ff8fdc24759931c190f36086883b607ae178080d5a07efec29a077b95ea05",
          "sha256": "1e1cedf080c10d2813d84eefa8978d0057efaf54a6bd8c2adcb3e4e410c3c280",
          "sha1": "8b12e8ae796c220c907e7bb035c026b1a7f8da45",
          "md5": "21b14ecadc25534a40d1c9859a0fff4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "4a4115d4982a391bb5cda24e83dc54bb669569db565718c566527bb0985b6f28f82ff8fdc24759931c190f36086883b607ae178080d5a07efec29a077b95ea05",
          "sha256": "1e1cedf080c10d2813d84eefa8978d0057efaf54a6bd8c2adcb3e4e410c3c280",
          "sha1": "8b12e8ae796c220c907e7bb035c026b1a7f8da45",
          "md5": "21b14ecadc25534a40d1c9859a0fff4f"
        }
      ]
    }
  ]
}
