{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "wpqrh6jrvbfnjab2fiv4or4h7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "9ce20d1eb20caad40740bca87793c124cf2f2a87272e15fc0c041e589e6ba18a85a10316d8bc55e320280713daabbce42365f1a3ad0458d5ae7e4f4f98bb70ac",
          "sha256": "fe35330dbd68f652446401667e66274dfde14edf40c0b5d2146bfa75b4196a20",
          "sha1": "8f53619f1b92460559d3d5f158e9de95e603aa09",
          "md5": "9eca48dd596be7eb14fc56b7e761ca63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "9ce20d1eb20caad40740bca87793c124cf2f2a87272e15fc0c041e589e6ba18a85a10316d8bc55e320280713daabbce42365f1a3ad0458d5ae7e4f4f98bb70ac",
          "sha256": "fe35330dbd68f652446401667e66274dfde14edf40c0b5d2146bfa75b4196a20",
          "sha1": "8f53619f1b92460559d3d5f158e9de95e603aa09",
          "md5": "9eca48dd596be7eb14fc56b7e761ca63"
        }
      ]
    }
  ]
}
