{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uqhiwpdgfnczzag5r5sfh4rche"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c804a4c2796ab83516af993a75367e95eb3ead9fb07f002a7e55effbf1851fed25dd49bee7725f12138bc1375257027c26f11073fd673ff00f0d2fbf420c82ab",
          "sha256": "02fa8f51de21546517f0792f86ea44586bc6751698640e52b32ffd66ac9ff618",
          "sha1": "ff0e05fa1af814272b3e050c1ab54fba3a25f6e2",
          "md5": "9ac6f8ed112ac908acde69fff74b522e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c804a4c2796ab83516af993a75367e95eb3ead9fb07f002a7e55effbf1851fed25dd49bee7725f12138bc1375257027c26f11073fd673ff00f0d2fbf420c82ab",
          "sha256": "02fa8f51de21546517f0792f86ea44586bc6751698640e52b32ffd66ac9ff618",
          "sha1": "ff0e05fa1af814272b3e050c1ab54fba3a25f6e2",
          "md5": "9ac6f8ed112ac908acde69fff74b522e"
        }
      ]
    }
  ]
}
