{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3a4sy6sxgfhl5k2fv2ec5p3wbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "56c9261697d89b9759f0f79e5624b139674f3042e91e6a5f023afc3bd6582c1d077f19b1dd14c0b0b06c924af44850eb1227998b26b9ae6a9f0518414bc7fb62",
          "sha256": "82f178c1a85110968d71dcead4bb285e6a06621afe97ae2506e77924b73d3b72",
          "sha1": "d969568302a946a829ad274b89019619e1817e35",
          "md5": "d7564e5d2b56b056b75becb49936329e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-module-test-recordservice-update-fake-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "56c9261697d89b9759f0f79e5624b139674f3042e91e6a5f023afc3bd6582c1d077f19b1dd14c0b0b06c924af44850eb1227998b26b9ae6a9f0518414bc7fb62",
          "sha256": "82f178c1a85110968d71dcead4bb285e6a06621afe97ae2506e77924b73d3b72",
          "sha1": "d969568302a946a829ad274b89019619e1817e35",
          "md5": "d7564e5d2b56b056b75becb49936329e"
        }
      ]
    }
  ]
}
