{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z7tc2apk45awvduwy5cthg6ch4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "9cd0e71f1d2d9bcb634fe2d4fbcf760f34d87975a54b50670f6594ac49eb9c04ec6372162ab7708fea73515c14cddffe085e032bb7135c03d5c28c2f76669d24",
          "sha256": "2abb03370a069812c02c728d67ef09c20a067e3cdf94bcff7ba6cf33a1cd83ee",
          "sha1": "03864017adf9e07c0b351fd495900917565c84e9",
          "md5": "005753b2039f09a2cacf9037f2be1946"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "9cd0e71f1d2d9bcb634fe2d4fbcf760f34d87975a54b50670f6594ac49eb9c04ec6372162ab7708fea73515c14cddffe085e032bb7135c03d5c28c2f76669d24",
          "sha256": "2abb03370a069812c02c728d67ef09c20a067e3cdf94bcff7ba6cf33a1cd83ee",
          "sha1": "03864017adf9e07c0b351fd495900917565c84e9",
          "md5": "005753b2039f09a2cacf9037f2be1946"
        }
      ]
    }
  ]
}
