{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "p65g65pmqvgftbdv7u2yhda3wy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0f2eb13644b38cc7aa3dd803380a22966831e20990fc9eea69b39a866f344b2c982ec80230e657145666a53e937f425b9bbf0d2cdc9e66286df8f9825eda4917",
          "sha256": "1c46c8c48f1028ffe521f0e2558f69740b21af85345f4a72153bfc6b2b5c2b07",
          "sha1": "4d598a428d5789028f7f1062ec2395e9f10e3029",
          "md5": "0ed8dd4879e5f772cbb7fdffafae4ecc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "0f2eb13644b38cc7aa3dd803380a22966831e20990fc9eea69b39a866f344b2c982ec80230e657145666a53e937f425b9bbf0d2cdc9e66286df8f9825eda4917",
          "sha256": "1c46c8c48f1028ffe521f0e2558f69740b21af85345f4a72153bfc6b2b5c2b07",
          "sha1": "4d598a428d5789028f7f1062ec2395e9f10e3029",
          "md5": "0ed8dd4879e5f772cbb7fdffafae4ecc"
        }
      ]
    }
  ]
}
