{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "plcsdnlf5vh4rmvujg7677fcbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "b4aa754b11d260b6fcfae21b3e0a40617cb42d0a6a9baba127d42ec325cc8ac92acec11bef1ed95c69cff6998e996f8ce63a71c6f0a1036288aefa604def59ac",
          "sha256": "5b421a9c356381bc0f59b641d394eeb039bb47935e48ed8347c5164b722e127f",
          "sha1": "6423dc64e60212cf84101111e4830e81293b0249",
          "md5": "7438c0e4804f24840bfdd4bdfb158f65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "b4aa754b11d260b6fcfae21b3e0a40617cb42d0a6a9baba127d42ec325cc8ac92acec11bef1ed95c69cff6998e996f8ce63a71c6f0a1036288aefa604def59ac",
          "sha256": "5b421a9c356381bc0f59b641d394eeb039bb47935e48ed8347c5164b722e127f",
          "sha1": "6423dc64e60212cf84101111e4830e81293b0249",
          "md5": "7438c0e4804f24840bfdd4bdfb158f65"
        }
      ]
    }
  ]
}
