{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-tag-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "62ahl5xfzzdthdw2z5pft6qnim"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "065b76737d06e98b34f533a8170eb105321db3032c91388fd59a4b077a1d40c20462090b677ecc00cc54b7e68e1d66bffbadbe37419fcb860fcab39dd46f5e8e",
          "sha256": "d2c7b3bdb8d419df4aec9f99cda2efa0a5dffc769d6eab3ae3d7492265540df9",
          "sha1": "2c7fb7dd4c6081f10c4111cd55d1a59bb397fd4d",
          "md5": "09b4d134a28874b9325b1a435bed4b63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-tag-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-tag-tests-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "065b76737d06e98b34f533a8170eb105321db3032c91388fd59a4b077a1d40c20462090b677ecc00cc54b7e68e1d66bffbadbe37419fcb860fcab39dd46f5e8e",
          "sha256": "d2c7b3bdb8d419df4aec9f99cda2efa0a5dffc769d6eab3ae3d7492265540df9",
          "sha1": "2c7fb7dd4c6081f10c4111cd55d1a59bb397fd4d",
          "md5": "09b4d134a28874b9325b1a435bed4b63"
        }
      ]
    }
  ]
}
