{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-SNAPSHOT/fhir-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "mby6ogm6dbgwzffwavymltlaee"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.0.1-SNAPSHOT.aar",
          "size": 2103286,
          "sha512": "4e4a21cf1cadfd7efefecae47077e8b36a7eb96b5d9efb10f2145d606275ec7b49e98950d92fdeaef754eb9229c8632cc3ea7d5445ebe31a0cee0e555f0eab6c",
          "sha256": "d211bc2babde77e08a126a3501c31a32393654025905470e0b712e63f9aeb81a",
          "sha1": "3a42afb616a3206e08075c7acc7dc57f9b3a6f92",
          "md5": "0b193e3df7e767dfded425acce00d4c8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.0.1-SNAPSHOT.aar",
          "size": 2103286,
          "sha512": "4e4a21cf1cadfd7efefecae47077e8b36a7eb96b5d9efb10f2145d606275ec7b49e98950d92fdeaef754eb9229c8632cc3ea7d5445ebe31a0cee0e555f0eab6c",
          "sha256": "d211bc2babde77e08a126a3501c31a32393654025905470e0b712e63f9aeb81a",
          "sha1": "3a42afb616a3206e08075c7acc7dc57f9b3a6f92",
          "md5": "0b193e3df7e767dfded425acce00d4c8"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-SNAPSHOT/fhir-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
