{
  "formatVersion": "1.1",
  "component": {
    "url": "../../fhir/0.0.1-SNAPSHOT/fhir-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-fhir-sdk-kmp",
    "module": "fhir",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.2",
      "buildId": "kov5wb6umrbs3gm2kpvmocqo74"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.0.1-SNAPSHOT.aar",
          "size": 2178669,
          "sha512": "6f8137000c5326cf756eff086e4ebf9fd01951e91be38b8820f70da95b957f64b357528a27e4e818d7952a51be69d77e5dbee7ffe4a815734c46e8b1b1123ab3",
          "sha256": "10aabe5fd956469a8536181502c6f08e0a631bc56204719aa434ba46ba437317",
          "sha1": "d4dd2ba7a4b8fc9e09c335c0ec0d0930b356de47",
          "md5": "165da74d658d05ee67d60f2043a54427"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "fhir-release.aar",
          "url": "fhir-android-0.0.1-SNAPSHOT.aar",
          "size": 2178669,
          "sha512": "6f8137000c5326cf756eff086e4ebf9fd01951e91be38b8820f70da95b957f64b357528a27e4e818d7952a51be69d77e5dbee7ffe4a815734c46e8b1b1123ab3",
          "sha256": "10aabe5fd956469a8536181502c6f08e0a631bc56204719aa434ba46ba437317",
          "sha1": "d4dd2ba7a4b8fc9e09c335c0ec0d0930b356de47",
          "md5": "165da74d658d05ee67d60f2043a54427"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../fhir-metadata/0.0.1-SNAPSHOT/fhir-metadata-0.0.1-SNAPSHOT.module",
        "group": "care.data4life.hc-fhir-sdk-kmp",
        "module": "fhir-metadata",
        "version": "0.0.1-SNAPSHOT"
      }
    }
  ]
}
