{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-bump-fhir-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "4576llu3avb23d2tof26t2wwcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-bump-fhir-sdk-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "e7e54b203f5d3294fe7c742a6168a3751028819952ee8932d53b17873d9e3fc85b3c34269752c5b9b5426b28884980fc53a430e04710b77fc8d2349a563deb0d",
          "sha256": "5ac7de6e410b42da569eebeb3c20008d58f787988ca2d8787fcda5f5ee025ec2",
          "sha1": "a23b1a6deaf6b5c8e447692e6041060a7004a755",
          "md5": "5a060cd41bc2a79cd37ae51c0e53e5c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-bump-fhir-sdk-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-bump-fhir-sdk-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "e7e54b203f5d3294fe7c742a6168a3751028819952ee8932d53b17873d9e3fc85b3c34269752c5b9b5426b28884980fc53a430e04710b77fc8d2349a563deb0d",
          "sha256": "5ac7de6e410b42da569eebeb3c20008d58f787988ca2d8787fcda5f5ee025ec2",
          "sha1": "a23b1a6deaf6b5c8e447692e6041060a7004a755",
          "md5": "5a060cd41bc2a79cd37ae51c0e53e5c5"
        }
      ]
    }
  ]
}
