{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "h3krjl4ru5fflidpkuassdnfgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "1a8804ffd4c9ae9a69db8434e42ba5d3067b6ce8cbb82401d7c8ba2a64ad90225648622ca1d74f71c57252829babcddde2efa0382558c10e51b04cdf0be268fa",
          "sha256": "5e72ec99a18fea0ae51839036180f2021c0d0b2f7f7899f0b1720b45c03c919b",
          "sha1": "0a6d687c84c2aa728f886c44b6caadee3b94b521",
          "md5": "fc79ef408855c53aaccee3a11f5da26b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "1a8804ffd4c9ae9a69db8434e42ba5d3067b6ce8cbb82401d7c8ba2a64ad90225648622ca1d74f71c57252829babcddde2efa0382558c10e51b04cdf0be268fa",
          "sha256": "5e72ec99a18fea0ae51839036180f2021c0d0b2f7f7899f0b1720b45c03c919b",
          "sha1": "0a6d687c84c2aa728f886c44b6caadee3b94b521",
          "md5": "fc79ef408855c53aaccee3a11f5da26b"
        }
      ]
    }
  ]
}
