{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-add-crypto-service-interface-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7vdoo7el4nhrhlao4geitoadoy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "6a69fce33d10a6b6c692323ba09d2893bab8a8b49bbfbb35d993c4c2621c91e4672b4063a00c0a92dc017e797761f54c24427557d0133d91373be9c73e7e52e9",
          "sha256": "afb65fb6934fe8185e289721cedfcddf50c791ed8d6579d3c6daa93becc8ef80",
          "sha1": "e938b7bdf835bae46bf708fbb9c83ee4f8f098a2",
          "md5": "a218c0468e46c6346cdfd7d47f810a98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-add-crypto-service-interface-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "6a69fce33d10a6b6c692323ba09d2893bab8a8b49bbfbb35d993c4c2621c91e4672b4063a00c0a92dc017e797761f54c24427557d0133d91373be9c73e7e52e9",
          "sha256": "afb65fb6934fe8185e289721cedfcddf50c791ed8d6579d3c6daa93becc8ef80",
          "sha1": "e938b7bdf835bae46bf708fbb9c83ee4f8f098a2",
          "md5": "a218c0468e46c6346cdfd7d47f810a98"
        }
      ]
    }
  ]
}
