{
  "formatVersion": "1.1",
  "component": {
    "url": "../../util-jvm/1.7.0-SNAPSHOT/util-jvm-1.7.0-SNAPSHOT.module",
    "group": "care.data4life.hc-util-sdk-kmp",
    "module": "util-jvm",
    "version": "1.7.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "hpf5e3lkhvblrar6ldtv3ei7cy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "util-metadata-1.7.0-SNAPSHOT.jar",
          "url": "util-metadata-1.7.0-SNAPSHOT.jar",
          "size": 6584,
          "sha512": "a686cc7f14fa63ccc1b4d4f08be7a941216dc95ce37b0afc7762a73e84949590a62209a1e7e45b09cd3fec00c80ccc116090ed18d3d54e21f78418d83754684d",
          "sha256": "e2aa0320be0149f3ac7f5704f5b2b168e994668ae3233704e3737c501efa8e50",
          "sha1": "8182b95b49b13c81b8660652bd677d83a63be9ec",
          "md5": "3f12bdc14b306a6b0703eef2b643a9ea"
        }
      ]
    }
  ]
}
