{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-userid-on-client-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kupdmgur6bbnzmbzxuws6kjkhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "dfa257dd02fd03e0c1b1266a83ec6264ac2290623e14a56ce2b25a1e34e67844c9173fd396f1ca642d953bf611d0d0924f4c2147d22c4bbb8f78dd130ff217df",
          "sha256": "aeecd7e320ffa810e587e828dec9e080c1f4fec0677e33e1b6570f5945d39656",
          "sha1": "4aa926773860ac1337a0f8c6fce58b69ef845770",
          "md5": "70b8f180b8bf4e690df44a676211b841"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "dfa257dd02fd03e0c1b1266a83ec6264ac2290623e14a56ce2b25a1e34e67844c9173fd396f1ca642d953bf611d0d0924f4c2147d22c4bbb8f78dd130ff217df",
          "sha256": "aeecd7e320ffa810e587e828dec9e080c1f4fec0677e33e1b6570f5945d39656",
          "sha1": "4aa926773860ac1337a0f8c6fce58b69ef845770",
          "md5": "70b8f180b8bf4e690df44a676211b841"
        }
      ]
    }
  ]
}
