{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-change-userid-on-client-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "67pv5qmtinegdfj5xdsl5wvkru"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "26bb2bf30a66b32bf233c069fc45f6bbff9ab29196267daad2ad42305bfbbfe537b1f7b25a02a5e53f18f8575016a9eea3782925f18408c7aea466f53aed06e5",
          "sha256": "500f9daef08b48637cc72cf5fc0daa21a3e70ec87dc3c50280b81ba0bd230b96",
          "sha1": "a106b2346b2a0df392ff3b5ca411e0eac766173c",
          "md5": "3e997929cdfef7f23901e0a0a463415b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "26bb2bf30a66b32bf233c069fc45f6bbff9ab29196267daad2ad42305bfbbfe537b1f7b25a02a5e53f18f8575016a9eea3782925f18408c7aea466f53aed06e5",
          "sha256": "500f9daef08b48637cc72cf5fc0daa21a3e70ec87dc3c50280b81ba0bd230b96",
          "sha1": "a106b2346b2a0df392ff3b5ca411e0eac766173c",
          "md5": "3e997929cdfef7f23901e0a0a463415b"
        }
      ]
    }
  ]
}
