{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.11.0-change-data-resource-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yd6cmoqvw5gtxadrkzzeeddmfe"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "size": 44945,
          "sha512": "9ec333fad338b1f347577e0bd0b6f59a60ee26a980cfaeb69fd62e03dee30330653cfa85d505877d1f87943e2e3f03d67db319f5f2d11d73e6db97138d37b6fc",
          "sha256": "d9ea3c32802995abf17a59d42184520f2d138c7a148d0df65529df4ccf6de7d2",
          "sha1": "f81bb575eb1d9568b96fb8587c9c380e4d7d59b2",
          "md5": "c70cfb864ac3c2736954833067b67231"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.11.0-change-data-resource-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "url": "auth-android-1.11.0-change-data-resource-SNAPSHOT.aar",
          "size": 44945,
          "sha512": "9ec333fad338b1f347577e0bd0b6f59a60ee26a980cfaeb69fd62e03dee30330653cfa85d505877d1f87943e2e3f03d67db319f5f2d11d73e6db97138d37b6fc",
          "sha256": "d9ea3c32802995abf17a59d42184520f2d138c7a148d0df65529df4ccf6de7d2",
          "sha1": "f81bb575eb1d9568b96fb8587c9c380e4d7d59b2",
          "md5": "c70cfb864ac3c2736954833067b67231"
        }
      ]
    }
  ]
}
