{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-fix-date-formatting-on-search-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6xcmg72gknbmln5zn4duvnj2b4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "c79d33cce16f2cdf1aca9e72df3532fb22177af9c35460d8b7fcbe698d3df290b8beccb08efd3d6503b421fa9693df78c43782e2ef489e679d71163249b2fdf3",
          "sha256": "9e19d459603c797dc8e4df9bd60b5c91257c0eb61160041e7066894ecdf3c67f",
          "sha1": "8d167cc307b44247aaaaac2421561795d7e0899e",
          "md5": "1fbb0216e89e792b4e6c013fa3c9753a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-date-formatting-on-search-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-fix-date-formatting-on-search-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "c79d33cce16f2cdf1aca9e72df3532fb22177af9c35460d8b7fcbe698d3df290b8beccb08efd3d6503b421fa9693df78c43782e2ef489e679d71163249b2fdf3",
          "sha256": "9e19d459603c797dc8e4df9bd60b5c91257c0eb61160041e7066894ecdf3c67f",
          "sha1": "8d167cc307b44247aaaaac2421561795d7e0899e",
          "md5": "1fbb0216e89e792b4e6c013fa3c9753a"
        }
      ]
    }
  ]
}
