{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vjsmew4pmfah3h2anggjyebl2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "bfb64b8930037f69442bb0f4a7a9e53e09c004340ebf65bc1f51e31be470157d860486cb7acf32cef948bebbfc0d9382e33c2a8aa6e54151d5a395ee56beac7d",
          "sha256": "c23776f5cc2b97e149ecc2f167c2709638e05e97cea97e58c65f46810c85ce10",
          "sha1": "e7189a86a0835260c2d66069d090d251cf65c2a0",
          "md5": "b22cf2b7d7867199409a4b0c2776b0fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "bfb64b8930037f69442bb0f4a7a9e53e09c004340ebf65bc1f51e31be470157d860486cb7acf32cef948bebbfc0d9382e33c2a8aa6e54151d5a395ee56beac7d",
          "sha256": "c23776f5cc2b97e149ecc2f167c2709638e05e97cea97e58c65f46810c85ce10",
          "sha1": "e7189a86a0835260c2d66069d090d251cf65c2a0",
          "md5": "b22cf2b7d7867199409a4b0c2776b0fe"
        }
      ]
    }
  ]
}
