{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "n62ezrvpj5bgfjhf5k5hxsucre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "1d70f3e176dab5e5e3f23a0a573f79aa677b0968f4bfa7834a0900effe69accb80b0f80c7bcf57c30df114ceb760a374aafa6e6f1598329ea5bdf7e4138c29f2",
          "sha256": "e065993c78d68c10cf5be996bb22d86c987121717102c7fe21cd9d703a4a31ae",
          "sha1": "2640ff41f91792c769eafd59e0093a983edbf608",
          "md5": "f710978b08a5cc37a06a01d1938c78c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "1d70f3e176dab5e5e3f23a0a573f79aa677b0968f4bfa7834a0900effe69accb80b0f80c7bcf57c30df114ceb760a374aafa6e6f1598329ea5bdf7e4138c29f2",
          "sha256": "e065993c78d68c10cf5be996bb22d86c987121717102c7fe21cd9d703a4a31ae",
          "sha1": "2640ff41f91792c769eafd59e0093a983edbf608",
          "md5": "f710978b08a5cc37a06a01d1938c78c5"
        }
      ]
    }
  ]
}
