{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ckkllfjak5devl6px3rkuw52yy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "10d587555961aeef3df78d5541ffb3e5ac26c88e64d6e4c414e8e93a3fc64790c80f15a8fe1a21fec72393dd07aedc2e7915d89f609dfef56df1d4580f3cf948",
          "sha256": "d1e2f894d1e103f2e32f15ded5efcac4f0bec842b37c7f95e1ac8812290bfd6c",
          "sha1": "30c072e9d6b0a71910d36f1be1be300591c23504",
          "md5": "5de9ff114ef4ebfa349bd9221ab171f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "10d587555961aeef3df78d5541ffb3e5ac26c88e64d6e4c414e8e93a3fc64790c80f15a8fe1a21fec72393dd07aedc2e7915d89f609dfef56df1d4580f3cf948",
          "sha256": "d1e2f894d1e103f2e32f15ded5efcac4f0bec842b37c7f95e1ac8812290bfd6c",
          "sha1": "30c072e9d6b0a71910d36f1be1be300591c23504",
          "md5": "5de9ff114ef4ebfa349bd9221ab171f7"
        }
      ]
    }
  ]
}
