{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xhjn3mq3z5fb3ch22v4a32lkse"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "bdb8d40c7694db7c474affb5c5616af5b378976880eb5d3bf3719fe4b02eab43fe90a4b66d36e3d2a20174ef7ee9669aacfb3eea6851b40c5d6ee6ac23c02469",
          "sha256": "e8e5ed25f18b3580083f730d2a317369677d2c4d83b547464c6af7c93dd5060f",
          "sha1": "81e4a26305129cbdac9e10e92971f2f2306f81bf",
          "md5": "73b62ea9144b72a60b2c9e7c2253f0fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-add-datetimeformatter-wrapper-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-add-datetimeformatter-wrapper-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "bdb8d40c7694db7c474affb5c5616af5b378976880eb5d3bf3719fe4b02eab43fe90a4b66d36e3d2a20174ef7ee9669aacfb3eea6851b40c5d6ee6ac23c02469",
          "sha256": "e8e5ed25f18b3580083f730d2a317369677d2c4d83b547464c6af7c93dd5060f",
          "sha1": "81e4a26305129cbdac9e10e92971f2f2306f81bf",
          "md5": "73b62ea9144b72a60b2c9e7c2253f0fe"
        }
      ]
    }
  ]
}
