{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.0-rc1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rjsjddkq7jedtpp5e4mwmjlrii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-rc1-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-rc1-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d8b5cb6a5d13be11a12ae83a0822e9947247f65c2e9d6b5997b3cb65d1cf09ce23cc7825a618944ffb95b2ccf5250b460aca34eeb6c5e95ad2c016661fa0e7ed",
          "sha256": "74b71f679ac5196a165c2b7f1756e1a26a95fbbc8b2f9f9237966038b55acd3e",
          "sha1": "9a38ed93830e4ce5588d8fa4ef8ad0da360f4aa1",
          "md5": "80c612d8d2dc015dc299960bacf78c1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-rc1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-rc1-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-rc1-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d8b5cb6a5d13be11a12ae83a0822e9947247f65c2e9d6b5997b3cb65d1cf09ce23cc7825a618944ffb95b2ccf5250b460aca34eeb6c5e95ad2c016661fa0e7ed",
          "sha256": "74b71f679ac5196a165c2b7f1756e1a26a95fbbc8b2f9f9237966038b55acd3e",
          "sha1": "9a38ed93830e4ce5588d8fa4ef8ad0da360f4aa1",
          "md5": "80c612d8d2dc015dc299960bacf78c1b"
        }
      ]
    }
  ]
}
