{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-prepare-release-1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qxnhzhcfdnf4xhl6xin2es7xv4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "ae2c4c82a26489bb5ac181d243bfcdd63960c174ec21a39e8f0883fa502d5ce2c3a928c0320fafbbee21caea48e83bd86e95bdc8679b781b54baecb84defd020",
          "sha256": "1d43ace701c613097ae66e77afe35a38ef2666abf7446ed9875f6a36d01b7b71",
          "sha1": "9ffd09c93ffa0239c9e51beea648932f48244101",
          "md5": "a8611f1dd2444f1a4da58847bf2744e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "ae2c4c82a26489bb5ac181d243bfcdd63960c174ec21a39e8f0883fa502d5ce2c3a928c0320fafbbee21caea48e83bd86e95bdc8679b781b54baecb84defd020",
          "sha256": "1d43ace701c613097ae66e77afe35a38ef2666abf7446ed9875f6a36d01b7b71",
          "sha1": "9ffd09c93ffa0239c9e51beea648932f48244101",
          "md5": "a8611f1dd2444f1a4da58847bf2744e1"
        }
      ]
    }
  ]
}
