{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "vfimpztftbhm5prj6mfe64n5hu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b298eccd2280340a4185dc5548f05db32b977df7cf5872c8e34bda198450fe21c88c74475a7913267f1749fb036884c9730a285e1e014aa71b0b9ed1c7517e6a",
          "sha256": "e94183d4810ed3c75140a57e8f99c50674142e2eec2c0ffd66f793d3ccd1dd17",
          "sha1": "8566a493acac5e687d4ed2b9fc4fd003b6ff9620",
          "md5": "5d200ea186a6a281f5280cfd263c53d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-bump-moshi-1-9-3-kapt-SNAPSHOT.jar",
          "size": 6926,
          "sha512": "b298eccd2280340a4185dc5548f05db32b977df7cf5872c8e34bda198450fe21c88c74475a7913267f1749fb036884c9730a285e1e014aa71b0b9ed1c7517e6a",
          "sha256": "e94183d4810ed3c75140a57e8f99c50674142e2eec2c0ffd66f793d3ccd1dd17",
          "sha1": "8566a493acac5e687d4ed2b9fc4fd003b6ff9620",
          "md5": "5d200ea186a6a281f5280cfd263c53d3"
        }
      ]
    }
  ]
}
