{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.1-fix-release-ci-job-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pr6loosk2fa5jlcqcqncxhbwra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "76d45a9b321a95a19030dba2ada85af1da99bf8ba6f24c9463ce10d3d393f4077533e4ba5e97b35764bbbb817f664603b965d0d8ecc98493f0759f60b9c476fb",
          "sha256": "1cbfb11f910672a10cfaf5c324f25a317da2f7b36cebb759a017e5eb90e973c3",
          "sha1": "b85ea15b05dec8e771fd8379fdc14fd545bd2224",
          "md5": "34e7f4014e84433a6cb5abbd5a641ece"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-fix-release-ci-job-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.1-fix-release-ci-job-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "76d45a9b321a95a19030dba2ada85af1da99bf8ba6f24c9463ce10d3d393f4077533e4ba5e97b35764bbbb817f664603b965d0d8ecc98493f0759f60b9c476fb",
          "sha256": "1cbfb11f910672a10cfaf5c324f25a317da2f7b36cebb759a017e5eb90e973c3",
          "sha1": "b85ea15b05dec8e771fd8379fdc14fd545bd2224",
          "md5": "34e7f4014e84433a6cb5abbd5a641ece"
        }
      ]
    }
  ]
}
