{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xu2s7z2m5bdm7ppyb76ul6vrg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "52c93a27971ea717762621c0af2646c41397ba71ca41a51cddcaa9d94a3ec03dacc2f36bd71fde61d3957999a0cf45d89441867202ac9562d736b0e43e6f8fe1",
          "sha256": "4094edf4f2988a560e1b841b2594d15c32a9ff8ec7df83c1cf80690c2c4f9723",
          "sha1": "d1c9919121c3fab9791423a1e1a788723f0c01dd",
          "md5": "d427e4309fd351c07e012750de0e708c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "52c93a27971ea717762621c0af2646c41397ba71ca41a51cddcaa9d94a3ec03dacc2f36bd71fde61d3957999a0cf45d89441867202ac9562d736b0e43e6f8fe1",
          "sha256": "4094edf4f2988a560e1b841b2594d15c32a9ff8ec7df83c1cf80690c2c4f9723",
          "sha1": "d1c9919121c3fab9791423a1e1a788723f0c01dd",
          "md5": "d427e4309fd351c07e012750de0e708c"
        }
      ]
    }
  ]
}
