{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mezr5ujomngztn6rcvg5o23z5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "98a43be6edae747ec90544e40b72bfb5dcf70d71d38c566803a2c55ccec981e8fdbd445f055adfd46466fbc9736e4e757b5e729dbd67fddf2da6774addb259ac",
          "sha256": "e3f140ab771baeaeea129932d863df4c402b4009d76b1767b39a7460bdb9f37c",
          "sha1": "bd8aa3654a5bbcc0478ce78e86d97c616bb26ce1",
          "md5": "0ff4a3223fb3e7080fbbe55103d99bb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "98a43be6edae747ec90544e40b72bfb5dcf70d71d38c566803a2c55ccec981e8fdbd445f055adfd46466fbc9736e4e757b5e729dbd67fddf2da6774addb259ac",
          "sha256": "e3f140ab771baeaeea129932d863df4c402b4009d76b1767b39a7460bdb9f37c",
          "sha1": "bd8aa3654a5bbcc0478ce78e86d97c616bb26ce1",
          "md5": "0ff4a3223fb3e7080fbbe55103d99bb7"
        }
      ]
    }
  ]
}
