{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wakwsun7erdyhdcvwter7j4g3q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0.jar",
          "url": "crypto-common-1.11.0.jar",
          "size": 11519,
          "sha512": "b016a2eee36d714183877c8f47d2777a04b7b7fb03555a9a9f607a17c40598b9e14b7df6d7562e41320e05cf6f17e157f014ba1cf0af34687dd14f6773f2034c",
          "sha256": "776253c23abbbe9eaf806f8f4a293b1c01c1905b92615d9ffed2fae41a9555ba",
          "sha1": "f52e53d3a2fc2d93b36afc53abdd7841d3759848",
          "md5": "d8f6d2f47c22a22a618527edc212b6e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0.jar",
          "url": "crypto-common-1.11.0.jar",
          "size": 11519,
          "sha512": "b016a2eee36d714183877c8f47d2777a04b7b7fb03555a9a9f607a17c40598b9e14b7df6d7562e41320e05cf6f17e157f014ba1cf0af34687dd14f6773f2034c",
          "sha256": "776253c23abbbe9eaf806f8f4a293b1c01c1905b92615d9ffed2fae41a9555ba",
          "sha1": "f52e53d3a2fc2d93b36afc53abdd7841d3759848",
          "md5": "d8f6d2f47c22a22a618527edc212b6e1"
        }
      ]
    }
  ]
}
