{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5ioeabvh65edhkyshovmfqfz5u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "ab7dbfba7f921657dfc1ce410a3181907157b9c64b75585d734841eb519e6992fe500129a331d9aebd476f4ac6d2d7244568c3fbab8468d588baaba9d3646112",
          "sha256": "7c61477fb4989d4ffbe0d67fa91bf228fe267a9175b56820043a24523c8d3106",
          "sha1": "3552a5a99a8f868ebdd5157b77c823ac0417e28e",
          "md5": "67bd5e92782af2ede8d0449bacef6443"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 11235,
          "sha512": "ab7dbfba7f921657dfc1ce410a3181907157b9c64b75585d734841eb519e6992fe500129a331d9aebd476f4ac6d2d7244568c3fbab8468d588baaba9d3646112",
          "sha256": "7c61477fb4989d4ffbe0d67fa91bf228fe267a9175b56820043a24523c8d3106",
          "sha1": "3552a5a99a8f868ebdd5157b77c823ac0417e28e",
          "md5": "67bd5e92782af2ede8d0449bacef6443"
        }
      ]
    }
  ]
}
