{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pljt23c73fbfbcvqonbftgc4t4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1c349cbb05f2dad84745ad5e641826e767d44f872253b0e6cb0b5fb8fa919ad33301ed2629c0cf2ad8e79093f941cb369b44cf2b35ef400d70d8f889bda403e9",
          "sha256": "7088da4e5f12082654b815b1438bec4b85e01828cc705a133afccf533807ebd9",
          "sha1": "5f65f9b1aa17e77296945b0513cab811b454dc3b",
          "md5": "bf5a90826d776b8c1c09aafe745d9bdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-change-recordservice-test-identifiers-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-change-recordservice-test-identifiers-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "1c349cbb05f2dad84745ad5e641826e767d44f872253b0e6cb0b5fb8fa919ad33301ed2629c0cf2ad8e79093f941cb369b44cf2b35ef400d70d8f889bda403e9",
          "sha256": "7088da4e5f12082654b815b1438bec4b85e01828cc705a133afccf533807ebd9",
          "sha1": "5f65f9b1aa17e77296945b0513cab811b454dc3b",
          "md5": "bf5a90826d776b8c1c09aafe745d9bdf"
        }
      ]
    }
  ]
}
