{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.2-fix-search-count-api-call-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3zsqnthe7rerjmbd6qiqaozyxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "2ac6bb0ddc3248636786c25f385ad6a42610084357fc78d64c8b78e0a1600ea1456b9cd70440811caf124c6b7574c7d7206346b1f46d5c369caeb58dae24307b",
          "sha256": "d06c5da41a809c4e30cff16cff559edc4d9caf5c758794adb9023579a79b5c4e",
          "sha1": "ea70239d0b230fe39ece47d4f17cc02d571de7ad",
          "md5": "69e9b984db0b87a165020ea46697505a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "url": "securestore-common-1.9.2-fix-search-count-api-call-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "2ac6bb0ddc3248636786c25f385ad6a42610084357fc78d64c8b78e0a1600ea1456b9cd70440811caf124c6b7574c7d7206346b1f46d5c369caeb58dae24307b",
          "sha256": "d06c5da41a809c4e30cff16cff559edc4d9caf5c758794adb9023579a79b5c4e",
          "sha1": "ea70239d0b230fe39ece47d4f17cc02d571de7ad",
          "md5": "69e9b984db0b87a165020ea46697505a"
        }
      ]
    }
  ]
}
