{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zs5bqhfjbzdkljd5h6p63dloh4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "9a9edd09ac258acae3397790f82d574ac015259c8d586a223fb8b344802654f2b5a0766d925b64cd9d8555992045d729ed3211c7b5595c1366d3954d20005380",
          "sha256": "118564b5e122ab7c187b31de8e3ce833a320f127043e0f13b1f0f0e9116daa63",
          "sha1": "9fb07dedc3110b857d3ae02c8bfdb01ebdbb2d90",
          "md5": "05dea1e541eda510b8b3a089b7526631"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "9a9edd09ac258acae3397790f82d574ac015259c8d586a223fb8b344802654f2b5a0766d925b64cd9d8555992045d729ed3211c7b5595c1366d3954d20005380",
          "sha256": "118564b5e122ab7c187b31de8e3ce833a320f127043e0f13b1f0f0e9116daa63",
          "sha1": "9fb07dedc3110b857d3ae02c8bfdb01ebdbb2d90",
          "md5": "05dea1e541eda510b8b3a089b7526631"
        }
      ]
    }
  ]
}
