{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5szpxyiewvhale5jpuegcbu7ou"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "4d062c054f4006685d4866cb2ed3d1afe4fa9169ac021c86a232c7255c7af8fa9443a735ac4285223e4e890fd05d47fd2a5da5e83781e2f4602fea0c94a6faa5",
          "sha256": "5c78c8e3ffc66c56811b738ca6c06db9c5a8e53cf695194c058757be5735b8f4",
          "sha1": "5646d58c8c03b48cc98719d4d7202ebd916f8d7a",
          "md5": "de462550d601037bce75c0da6bd50af1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "4d062c054f4006685d4866cb2ed3d1afe4fa9169ac021c86a232c7255c7af8fa9443a735ac4285223e4e890fd05d47fd2a5da5e83781e2f4602fea0c94a6faa5",
          "sha256": "5c78c8e3ffc66c56811b738ca6c06db9c5a8e53cf695194c058757be5735b8f4",
          "sha1": "5646d58c8c03b48cc98719d4d7202ebd916f8d7a",
          "md5": "de462550d601037bce75c0da6bd50af1"
        }
      ]
    }
  ]
}
