{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "oqz5tjc6h5c7zgbdltlbsrxmdu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.0.jar",
          "url": "crypto-common-1.9.0.jar",
          "size": 10850,
          "sha512": "7e8426a40c7382bbcc2b75ab81e3e4196a53b71101a55e2771c081937b540a7d20aa5caa8b9cb9b801618d9a8485470a7bac3f21daf633cd69faacaf7b55ce7b",
          "sha256": "6b06c50ac217cf72507b3176651d132ee0ee3438364de909eb74670f1db8c086",
          "sha1": "95cba5c9dcf127516a92faaca76c403a40288021",
          "md5": "6651c722bf34c8b1815bd1dafe42de4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.0.jar",
          "url": "crypto-common-1.9.0.jar",
          "size": 10850,
          "sha512": "7e8426a40c7382bbcc2b75ab81e3e4196a53b71101a55e2771c081937b540a7d20aa5caa8b9cb9b801618d9a8485470a7bac3f21daf633cd69faacaf7b55ce7b",
          "sha256": "6b06c50ac217cf72507b3176651d132ee0ee3438364de909eb74670f1db8c086",
          "sha1": "95cba5c9dcf127516a92faaca76c403a40288021",
          "md5": "6651c722bf34c8b1815bd1dafe42de4b"
        }
      ]
    }
  ]
}
