{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5qc2seelwnhfhfiley3tculkta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "452e6ab986215632f4f9f52fca3ee54ce9f9213e079fde0cad8c6f5c0935c0f0c85748f6de3d3932e5781d6b4ab0a7b46898d2d641f79959dbae85ce7c1fc153",
          "sha256": "53582dc6895467163ef502278adf144f0e4a513aab7d0d6b7000298bdd0136e4",
          "sha1": "a67f03332dc16f9639c6cd2f52edbeb8de430eb1",
          "md5": "7881a5161d3484e5d505f9eab15ed7d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-fhir4-support-countRecords-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-add-fhir4-support-countRecords-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "452e6ab986215632f4f9f52fca3ee54ce9f9213e079fde0cad8c6f5c0935c0f0c85748f6de3d3932e5781d6b4ab0a7b46898d2d641f79959dbae85ce7c1fc153",
          "sha256": "53582dc6895467163ef502278adf144f0e4a513aab7d0d6b7000298bdd0136e4",
          "sha1": "a67f03332dc16f9639c6cd2f52edbeb8de430eb1",
          "md5": "7881a5161d3484e5d505f9eab15ed7d0"
        }
      ]
    }
  ]
}
