{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.1-change-update-record-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gms5ane4vfaijmuqxchmkqqlsq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-update-record-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "fd0f0d1355fbafd0a949c304927ea3de2853593471cc8c516807008a5c4124340d811fbf151c4dc49171930bcbf6dae133b2f063715ac70a5262f03445189956",
          "sha256": "16d33b018a960d2dd33ab3fc078aa27377b6a4da9b310aec028b22da5fdd7ae2",
          "sha1": "23ceb6b3a0842a7f1a89850b1491da17f4525d6f",
          "md5": "847ea9d3cec370606fd4bed7360a2669"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-update-record-tests-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-update-record-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.1-change-update-record-tests-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "fd0f0d1355fbafd0a949c304927ea3de2853593471cc8c516807008a5c4124340d811fbf151c4dc49171930bcbf6dae133b2f063715ac70a5262f03445189956",
          "sha256": "16d33b018a960d2dd33ab3fc078aa27377b6a4da9b310aec028b22da5fdd7ae2",
          "sha1": "23ceb6b3a0842a7f1a89850b1491da17f4525d6f",
          "md5": "847ea9d3cec370606fd4bed7360a2669"
        }
      ]
    }
  ]
}
