{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-add-danger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "f2ujxy6ikjbezh2mz67jn6phle"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-danger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-add-danger-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-add-danger-SNAPSHOT.aar",
          "size": 51825,
          "sha512": "c403d2755c4e9891c400a2feff1005790e6aeba7b4b573ea18d3abba2380f1f33d51fa1b9093242c307ebc15af83f1783fe4874a4d87e4989f3823c2fe05c89b",
          "sha256": "cd9f48f7378a47ce1598c9d50318a39d9dd8afd07d27db514498fd2f11dd7102",
          "sha1": "29a37c79be2367e768661795710fd925fc73dafb",
          "md5": "5338efa729ef1c0a5cee06853b231c25"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-danger-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-add-danger-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-add-danger-SNAPSHOT.aar",
          "size": 51825,
          "sha512": "c403d2755c4e9891c400a2feff1005790e6aeba7b4b573ea18d3abba2380f1f33d51fa1b9093242c307ebc15af83f1783fe4874a4d87e4989f3823c2fe05c89b",
          "sha256": "cd9f48f7378a47ce1598c9d50318a39d9dd8afd07d27db514498fd2f11dd7102",
          "sha1": "29a37c79be2367e768661795710fd925fc73dafb",
          "md5": "5338efa729ef1c0a5cee06853b231c25"
        }
      ]
    }
  ]
}
