{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.0-add-label-ci-workflow-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "npror4vrubhehb2jhf4kh7fm7q"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-label-ci-workflow-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.0-add-label-ci-workflow-SNAPSHOT.aar",
          "url": "securestore-android-1.9.0-add-label-ci-workflow-SNAPSHOT.aar",
          "size": 41917,
          "sha512": "0ac1798c336287d6fe78be354b29ad7f1142d7c26f75f002a988740ecc6ee965baf212857acd25db76fffb73931068ed26b89f182ef0ce3ae3960e3826b88a73",
          "sha256": "ca2b660d9561d92f721564505e69fa2c0fc760b5e51f8808031e2f9656685bc2",
          "sha1": "aa13667d9ce7038725edee2d6cda9d8824cfbde6",
          "md5": "9ee7ad4fdac3c9c105d14e087b3e832b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-label-ci-workflow-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.0-add-label-ci-workflow-SNAPSHOT.aar",
          "url": "securestore-android-1.9.0-add-label-ci-workflow-SNAPSHOT.aar",
          "size": 41917,
          "sha512": "0ac1798c336287d6fe78be354b29ad7f1142d7c26f75f002a988740ecc6ee965baf212857acd25db76fffb73931068ed26b89f182ef0ce3ae3960e3826b88a73",
          "sha256": "ca2b660d9561d92f721564505e69fa2c0fc760b5e51f8808031e2f9656685bc2",
          "sha1": "aa13667d9ce7038725edee2d6cda9d8824cfbde6",
          "md5": "9ee7ad4fdac3c9c105d14e087b3e832b"
        }
      ]
    }
  ]
}
