{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.10.0-add-fhir4-download-attachment-support-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rwszed26yrcmfggg4ln3iezvbu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "b180d2cfffa8c80101e9338ed9768fea3bfa1e10a1893dba8077cd9b9e5be0b621c879947b58431fe93836803f3420150eb84dc739aca8fa935b4b1649210d84",
          "sha256": "5d999f8668d7913c2e9221c498e06f76f79a042d3ad32c8b9499971a6c10476b",
          "sha1": "d5d9cfa7a9be9b8c1a90c350f9860904d0b19950",
          "md5": "db3bc0a4ea21b57d234977a174369ced"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "url": "crypto-common-1.10.0-add-fhir4-download-attachment-support-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "b180d2cfffa8c80101e9338ed9768fea3bfa1e10a1893dba8077cd9b9e5be0b621c879947b58431fe93836803f3420150eb84dc739aca8fa935b4b1649210d84",
          "sha256": "5d999f8668d7913c2e9221c498e06f76f79a042d3ad32c8b9499971a6c10476b",
          "sha1": "d5d9cfa7a9be9b8c1a90c350f9860904d0b19950",
          "md5": "db3bc0a4ea21b57d234977a174369ced"
        }
      ]
    }
  ]
}
