{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.11.0-change-decrypted-record-definitions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rhzzoimqbnhwpakrp2kvqterka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "170161ff4898154e5b45e2eec6eca0bb439c02e2645293732b76977aa2dc2f3165fc5f4058e4eac51d0d6739f2bef70f8ad5b759fdf573511de9a8e64a591cb7",
          "sha256": "bca7d0af5e13ca4335a7b405421f16007fdeb3ff56748d56de795f2fd1fe1276",
          "sha1": "6e5076324526bc68ba91f4d2b127e0940958c17f",
          "md5": "49bfdc2dcf9ffa68df1caf5567c1966e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-decrypted-record-definitions-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "url": "auth-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "size": 3404,
          "sha512": "170161ff4898154e5b45e2eec6eca0bb439c02e2645293732b76977aa2dc2f3165fc5f4058e4eac51d0d6739f2bef70f8ad5b759fdf573511de9a8e64a591cb7",
          "sha256": "bca7d0af5e13ca4335a7b405421f16007fdeb3ff56748d56de795f2fd1fe1276",
          "sha1": "6e5076324526bc68ba91f4d2b127e0940958c17f",
          "md5": "49bfdc2dcf9ffa68df1caf5567c1966e"
        }
      ]
    }
  ]
}
