{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-test-utils-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7rfhydy4b5eerh5ew26qydql7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c6d0cb4f9b3717c1963e6a151807959868c962613da6b78b9b03b5eb2397253a26762bcb2f16a0dd7638174a5a021ab82e494e6f520f13c6a996be370fd1823d",
          "sha256": "5ce9af1f7b72e564ce008c83d2f6a7a7bf5962cf70611911e1962fa0dea33722",
          "sha1": "37a95c962bbd4fd991d8a9ee1e2e072dea0e16b8",
          "md5": "9312f0ce3b0b967e6a060b7012002ba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-test-utils-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-test-utils-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "c6d0cb4f9b3717c1963e6a151807959868c962613da6b78b9b03b5eb2397253a26762bcb2f16a0dd7638174a5a021ab82e494e6f520f13c6a996be370fd1823d",
          "sha256": "5ce9af1f7b72e564ce008c83d2f6a7a7bf5962cf70611911e1962fa0dea33722",
          "sha1": "37a95c962bbd4fd991d8a9ee1e2e072dea0e16b8",
          "md5": "9312f0ce3b0b967e6a060b7012002ba9"
        }
      ]
    }
  ]
}
