{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-userid-on-client-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kupdmgur6bbnzmbzxuws6kjkhu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 46020,
          "sha512": "c17c16b92347c0af603f30b87c43c4cf06d1b833ed364f561cf2185cf6d3b28f52e212ffbf18bf875df60eb9bff27ee19fe21bff911a30eef4385f037e5b6bc1",
          "sha256": "eba5ae91a12b8d0a3f9020c8f1e58f638d703c4dae9c5bd4d264f0f7814572d0",
          "sha1": "c8205858ffaad1ebdeb699568c7d1d621760e7b5",
          "md5": "d0c5c8fa246871829f1bde99c6177d42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 46020,
          "sha512": "c17c16b92347c0af603f30b87c43c4cf06d1b833ed364f561cf2185cf6d3b28f52e212ffbf18bf875df60eb9bff27ee19fe21bff911a30eef4385f037e5b6bc1",
          "sha256": "eba5ae91a12b8d0a3f9020c8f1e58f638d703c4dae9c5bd4d264f0f7814572d0",
          "sha1": "c8205858ffaad1ebdeb699568c7d1d621760e7b5",
          "md5": "d0c5c8fa246871829f1bde99c6177d42"
        }
      ]
    }
  ]
}
