{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-userid-on-client-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "wd43gdahbje6jkpbzmqxe6tv2i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 46020,
          "sha512": "c3f25852cddf3d983ef49353c79214b627ec5e4bf53a30946ca11b43207cb2482e7e4d030fe62b967338b90cfcc1a5a19b89849f08dc7fe9f672bcf80a8b433b",
          "sha256": "c739a851c50881e60410e1e800c5c50c40fac7624079a641b424f0fcf9f44662",
          "sha1": "e33b267d4e69dfe1882e28c18b2d783db4a23e67",
          "md5": "575f256cf3bd01cdb4f29cb9ea07852b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-userid-on-client-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-userid-on-client-SNAPSHOT.jar",
          "size": 46020,
          "sha512": "c3f25852cddf3d983ef49353c79214b627ec5e4bf53a30946ca11b43207cb2482e7e4d030fe62b967338b90cfcc1a5a19b89849f08dc7fe9f672bcf80a8b433b",
          "sha256": "c739a851c50881e60410e1e800c5c50c40fac7624079a641b424f0fcf9f44662",
          "sha1": "e33b267d4e69dfe1882e28c18b2d783db4a23e67",
          "md5": "575f256cf3bd01cdb4f29cb9ea07852b"
        }
      ]
    }
  ]
}
