{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6hpk6mu2nfdmlbxaoeepdqzkku"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "38ad429be800edb52348b80ee5fb1f9bf37d09f3b12200268b91cfcfdf823c92e406f94a8e6eebfedcf12c2ac8417c683d7faaf2b68ae3d6f478061850b6f509",
          "sha256": "708bbda24ed30fd0f7796fb802ab29a3947ddb18aefc02e709425e58a76b0461",
          "sha1": "5fc05dd226e2c983a5de601dfc698ef8310e0fc1",
          "md5": "3dc5af4193658dab51cbbbcfd101194c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "38ad429be800edb52348b80ee5fb1f9bf37d09f3b12200268b91cfcfdf823c92e406f94a8e6eebfedcf12c2ac8417c683d7faaf2b68ae3d6f478061850b6f509",
          "sha256": "708bbda24ed30fd0f7796fb802ab29a3947ddb18aefc02e709425e58a76b0461",
          "sha1": "5fc05dd226e2c983a5de601dfc698ef8310e0fc1",
          "md5": "3dc5af4193658dab51cbbbcfd101194c"
        }
      ]
    }
  ]
}
