{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jl2qil3tzff25k2hct3m6p7nya"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "da53f4bcba1b3fc16e3df45b803fcceda661f087d75316452cf3c2c35a89b11f7fcafd14c0ed3d3946d826a05e7d279b92149322957ab7f8a67b856ddda68833",
          "sha256": "7a13d839f7ed352925ed0dd238c46fa0bfe3dcf6e00a287c53c42d90692d119b",
          "sha1": "13e177d7bd2c504635803a964965669f97fbd5cc",
          "md5": "8e3727f6df6263d15a2aa90025500fea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "da53f4bcba1b3fc16e3df45b803fcceda661f087d75316452cf3c2c35a89b11f7fcafd14c0ed3d3946d826a05e7d279b92149322957ab7f8a67b856ddda68833",
          "sha256": "7a13d839f7ed352925ed0dd238c46fa0bfe3dcf6e00a287c53c42d90692d119b",
          "sha1": "13e177d7bd2c504635803a964965669f97fbd5cc",
          "md5": "8e3727f6df6263d15a2aa90025500fea"
        }
      ]
    }
  ]
}
