{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uh3ziqrwgbe6tp4p7bcp6y3w2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "size": 27862,
          "sha512": "8d960ca901d0a7a7345b01cfa8ecc7a5b19f3a96cf33e72de029779c2764411274d272201b2cda7722c979f4dea4563c960246d97b030d94bef2bd0e8a4f65e5",
          "sha256": "ef9d9245b0e0813d37fc86efbfcde88de39ad840d7aeb33d78e3868fd2b4a6a3",
          "sha1": "ed727a7f5414b0869651fb49f0a023d26e531db8",
          "md5": "789a1aed5e2490df46aff89277551f3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-SNAPSHOT.jar",
          "size": 27862,
          "sha512": "8d960ca901d0a7a7345b01cfa8ecc7a5b19f3a96cf33e72de029779c2764411274d272201b2cda7722c979f4dea4563c960246d97b030d94bef2bd0e8a4f65e5",
          "sha256": "ef9d9245b0e0813d37fc86efbfcde88de39ad840d7aeb33d78e3868fd2b4a6a3",
          "sha1": "ed727a7f5414b0869651fb49f0a023d26e531db8",
          "md5": "789a1aed5e2490df46aff89277551f3f"
        }
      ]
    }
  ]
}
