{
  "formatVersion": "1.1",
  "component": {
    "url": "../../example-kmp-library-jvm/0.0.1-SNAPSHOT/example-kmp-library-jvm-0.0.1-SNAPSHOT.module",
    "group": "care.data4life.hc-gradle-scripts",
    "module": "example-kmp-library-jvm",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nebkbmyrxvev5gieafqvvw5zye"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "url": "example-kmp-library-metadata-0.0.1-SNAPSHOT.jar",
          "size": 5643,
          "sha512": "7707da1369aaa6aa428143f511a8b2245d19fc46d5feabcf92b453ace37b09f65c98793245cea9ce98d7c9127a8deb6ab3594e12eac827e05cbe167c3f16c8af",
          "sha256": "b0df57d046095b65220b938d2df5ac61d3b09b2811bf0d314b5f869ca77577e9",
          "sha1": "365951bc48f9969cb065cc7c2193e93bff572073",
          "md5": "f5cbb553886969601dd77bbf95c62419"
        }
      ]
    }
  ]
}
