{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kbq63nxerffnrfw7qmmxelluri"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "size": 51970,
          "sha512": "c80f8c44b4b8a406328b2b6f0fd7c2fa0b78d37fb5fe521dfa0421b33dbba954a7ba116b87363e4a8f12367d5b6ea59e3f2e256adee61f797c3d5e79ff799355",
          "sha256": "46ca91e7576b457cc0c3decc3a565326b626bce10a1015a3ea01e3de1cb9740f",
          "sha1": "d0f25a050ba59877303be5467f5ab8407a9284b0",
          "md5": "21dd4ccf60e5c0946b34d6923ff16d8e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "url": "crypto-android-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.aar",
          "size": 51970,
          "sha512": "c80f8c44b4b8a406328b2b6f0fd7c2fa0b78d37fb5fe521dfa0421b33dbba954a7ba116b87363e4a8f12367d5b6ea59e3f2e256adee61f797c3d5e79ff799355",
          "sha256": "46ca91e7576b457cc0c3decc3a565326b626bce10a1015a3ea01e3de1cb9740f",
          "sha1": "d0f25a050ba59877303be5467f5ab8407a9284b0",
          "md5": "21dd4ccf60e5c0946b34d6923ff16d8e"
        }
      ]
    }
  ]
}
