{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-user-info-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3at7kjh3mbahxhqzgufly3v7aq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "4368ba462a960f853392d41e2e47eea551a929f02cb070ce74419fafcbc898ab7c0aa3b9c3b9dc6e672798fb846083462d8b17ee014a306f16b6b8cc68c47504",
          "sha256": "9210184352b486aea7779d4490799a3e8a8055b8634a3a9f20cd17d1405fc4d6",
          "sha1": "22d0ebcdcbde6e8d28e1ea9dac4acb5c983ad214",
          "md5": "7882689f5dbc28ad8990ffd52303bb32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-user-info-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-user-info-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "4368ba462a960f853392d41e2e47eea551a929f02cb070ce74419fafcbc898ab7c0aa3b9c3b9dc6e672798fb846083462d8b17ee014a306f16b6b8cc68c47504",
          "sha256": "9210184352b486aea7779d4490799a3e8a8055b8634a3a9f20cd17d1405fc4d6",
          "sha1": "22d0ebcdcbde6e8d28e1ea9dac4acb5c983ad214",
          "md5": "7882689f5dbc28ad8990ffd52303bb32"
        }
      ]
    }
  ]
}
