{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-jvm",
    "version": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gkmhx7mo2bebtctx6q3hzt6ypq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "e0440cf9a8d0de869090da97adb6b3bb93dac2986fec31110299eff480fb1c3e9c034dfef8842a20ebcc682c75a4dd78342857d8cfeada30402db7dda4409d50",
          "sha256": "c2e244c7de1cf4850b5948d6f9ab3fa24d7c416845baa49ec3e16bff3a9f91a5",
          "sha1": "fea90856a5fce32a63ab3d281137022056c51d42",
          "md5": "3c78a312c722725d0e252293d2faac70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "sdk-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 11300,
          "sha512": "e0440cf9a8d0de869090da97adb6b3bb93dac2986fec31110299eff480fb1c3e9c034dfef8842a20ebcc682c75a4dd78342857d8cfeada30402db7dda4409d50",
          "sha256": "c2e244c7de1cf4850b5948d6f9ab3fa24d7c416845baa49ec3e16bff3a9f91a5",
          "sha1": "fea90856a5fce32a63ab3d281137022056c51d42",
          "md5": "3c78a312c722725d0e252293d2faac70"
        }
      ]
    }
  ]
}
