{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.0-add-codeowner-file-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uv37b57dtndp5py35xyridc4du"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "a479a803c1311f8e6b11777092404ea5e216edda6aa89642a61ecf02f9e3b6769555a6bf1ef1ecb34397dc0c25ddfc8b8e06f5e50c2eacd5c16e1dc6c358acb0",
          "sha256": "15f2ec06aca4cf31daf59cca7c050e8586444c31fa4146367806d0c9cd68c1c6",
          "sha1": "4b30c96b5b1b879c0e0cbe7b34b231f3c5e3317b",
          "md5": "ee0ff6f5ec89392c26c02a2802d81251"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-codeowner-file-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "url": "auth-common-1.9.0-add-codeowner-file-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "a479a803c1311f8e6b11777092404ea5e216edda6aa89642a61ecf02f9e3b6769555a6bf1ef1ecb34397dc0c25ddfc8b8e06f5e50c2eacd5c16e1dc6c358acb0",
          "sha256": "15f2ec06aca4cf31daf59cca7c050e8586444c31fa4146367806d0c9cd68c1c6",
          "sha1": "4b30c96b5b1b879c0e0cbe7b34b231f3c5e3317b",
          "md5": "ee0ff6f5ec89392c26c02a2802d81251"
        }
      ]
    }
  ]
}
