{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-ingestion",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xn4cqacczvasvh6dqh5ii2fshm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 13633,
          "sha512": "223823fb0de70075cb1eff2f96245110ae166ca9879c6b5983fd3f9be492613b3e8b7371c7efb81f3963b600e8e313120a64b22dfbff4074da1c2a7134b4df18",
          "sha256": "285ff78f797879a19a5f61f9297355f24c4d002f45db15d0623c8ace3674e56c",
          "sha1": "83de5cfc6b6f7a0d41cecdb9227b4ee6d70b0219",
          "md5": "7eb1dc4daa8ab016f57cf3863f7d1fc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-fhir-helper-sdk-kmp",
          "module": "fhir-helper-jvm",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            }
          ]
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "sdk-core",
          "version": {
            "requires": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life",
              "module": "auth-android"
            },
            {
              "group": "care.data4life",
              "module": "securestore-android"
            },
            {
              "group": "care.data4life",
              "module": "crypto-android"
            },
            {
              "group": "care.data4life.hc-fhir-sdk-java",
              "module": "hc-fhir-sdk-java"
            },
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-android"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sdk-ingestion-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "sdk-ingestion-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 13633,
          "sha512": "223823fb0de70075cb1eff2f96245110ae166ca9879c6b5983fd3f9be492613b3e8b7371c7efb81f3963b600e8e313120a64b22dfbff4074da1c2a7134b4df18",
          "sha256": "285ff78f797879a19a5f61f9297355f24c4d002f45db15d0623c8ace3674e56c",
          "sha1": "83de5cfc6b6f7a0d41cecdb9227b4ee6d70b0219",
          "md5": "7eb1dc4daa8ab016f57cf3863f7d1fc9"
        }
      ]
    }
  ]
}
