{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.11.0-change-decrypted-record-definitions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rhzzoimqbnhwpakrp2kvqterka"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-decrypted-record-definitions-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.11.0-change-decrypted-record-definitions-SNAPSHOT.aar",
          "url": "securestore-android-1.11.0-change-decrypted-record-definitions-SNAPSHOT.aar",
          "size": 41964,
          "sha512": "702e036a7acbbda0f190686934f54d000cacff5a390d5fdafb467eee4216e60a188eac4f0b13365bda75adb672c6d1daa65bca7a2b51bdbd88e739631db01f9d",
          "sha256": "b524cc8313e29eb989b138461d8854c636ffe9977d375128598ea046a2b56af1",
          "sha1": "0571a5195702c5e6e2bb2550d220e4cf5f89e00d",
          "md5": "dff5d6168ac06a0bdb91fcd8445c8298"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.11.0-change-decrypted-record-definitions-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.11.0-change-decrypted-record-definitions-SNAPSHOT.aar",
          "url": "securestore-android-1.11.0-change-decrypted-record-definitions-SNAPSHOT.aar",
          "size": 41964,
          "sha512": "702e036a7acbbda0f190686934f54d000cacff5a390d5fdafb467eee4216e60a188eac4f0b13365bda75adb672c6d1daa65bca7a2b51bdbd88e739631db01f9d",
          "sha256": "b524cc8313e29eb989b138461d8854c636ffe9977d375128598ea046a2b56af1",
          "sha1": "0571a5195702c5e6e2bb2550d220e4cf5f89e00d",
          "md5": "dff5d6168ac06a0bdb91fcd8445c8298"
        }
      ]
    }
  ]
}
