{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.11.0-change-decrypted-record-definitions-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rhzzoimqbnhwpakrp2kvqterka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "e35b498f506e378bb31f90fc395ed6fac7a244099d3b835da87e3aa59847124cd6ac6e0f4580404c7169cc0d1188763603ed8b80891b8f2c388d6f5cfb830a71",
          "sha256": "bfa58408b312a17f4643c44eb95b16a3018824c43afde9771fc0ad68493c099c",
          "sha1": "e737e0eb09c030c0ecda4158cdaedc6ead301aba",
          "md5": "4dcdbf105f581b4effb309e7fb5799ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "url": "crypto-common-1.11.0-change-decrypted-record-definitions-SNAPSHOT.jar",
          "size": 11519,
          "sha512": "e35b498f506e378bb31f90fc395ed6fac7a244099d3b835da87e3aa59847124cd6ac6e0f4580404c7169cc0d1188763603ed8b80891b8f2c388d6f5cfb830a71",
          "sha256": "bfa58408b312a17f4643c44eb95b16a3018824c43afde9771fc0ad68493c099c",
          "sha1": "e737e0eb09c030c0ecda4158cdaedc6ead301aba",
          "md5": "4dcdbf105f581b4effb309e7fb5799ee"
        }
      ]
    }
  ]
}
