{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "lgjrpgozkzfc3cl7ifz2lxithi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0.jar",
          "url": "auth-jvm-1.9.0.jar",
          "size": 27832,
          "sha512": "a305daa3796faf1c524c3282d7c738eee6ccece631bbc5b61fd83f1a0d4a953786a9fd5f0d1a3b69d4274290ed56ef5606fd3a002460300157646b1c645b001b",
          "sha256": "379db8c5fb4a251cae321f3f398d66d560c807dc4c6dec780e51d14aa72f67dd",
          "sha1": "cd412503c793dc0be01ffbed2061e2b2b40fd405",
          "md5": "9ec90a9338a4b48e8bdce9903b2b92ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0.jar",
          "url": "auth-jvm-1.9.0.jar",
          "size": 27832,
          "sha512": "a305daa3796faf1c524c3282d7c738eee6ccece631bbc5b61fd83f1a0d4a953786a9fd5f0d1a3b69d4274290ed56ef5606fd3a002460300157646b1c645b001b",
          "sha256": "379db8c5fb4a251cae321f3f398d66d560c807dc4c6dec780e51d14aa72f67dd",
          "sha1": "cd412503c793dc0be01ffbed2061e2b2b40fd405",
          "md5": "9ec90a9338a4b48e8bdce9903b2b92ad"
        }
      ]
    }
  ]
}
