{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7wdmwkfllzfojdxiudlen4c3my"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d62acb861197dbd0f82e363ca7f685c621352a3023cb89d2e9ba4eb5e04d496723c09f4fc88d1c96cbf1b7856011c761cbb26e2fe269a2bd72b79c1ead495fa9",
          "sha256": "c04309d4d58e37c2c04636311deb420b6d2abbaa7c5904798f7823932190edd1",
          "sha1": "0a0cbc08a44f7b5ec8179df4d585656672eb9198",
          "md5": "32ee5be7c0384114a553821d7d5d436f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-change-module-test-recordservice-fetch-fake-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "d62acb861197dbd0f82e363ca7f685c621352a3023cb89d2e9ba4eb5e04d496723c09f4fc88d1c96cbf1b7856011c761cbb26e2fe269a2bd72b79c1ead495fa9",
          "sha256": "c04309d4d58e37c2c04636311deb420b6d2abbaa7c5904798f7823932190edd1",
          "sha1": "0a0cbc08a44f7b5ec8179df4d585656672eb9198",
          "md5": "32ee5be7c0384114a553821d7d5d436f"
        }
      ]
    }
  ]
}
