{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uqyy5glaw5gpvjfyvnsd4h3a7m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "ffa247dd1ae297c34e4106352454b6d9337dc3e7b9aa3aef3aefbb7f4778255be3e8cecff8bcc6ef0f520a06b87ca8177d82d4ac28b33b4ac780d331b3ef8cea",
          "sha256": "10471611663b8ce490179c12222d8dd52fe5dcb862dd1acab214a2bc9fab70ac",
          "sha1": "bea592fb762563b77fc0eb3049b1db61c5a4fb81",
          "md5": "1aad84f8c5fda90036ec8867adda0528"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "ffa247dd1ae297c34e4106352454b6d9337dc3e7b9aa3aef3aefbb7f4778255be3e8cecff8bcc6ef0f520a06b87ca8177d82d4ac28b33b4ac780d331b3ef8cea",
          "sha256": "10471611663b8ce490179c12222d8dd52fe5dcb862dd1acab214a2bc9fab70ac",
          "sha1": "bea592fb762563b77fc0eb3049b1db61c5a4fb81",
          "md5": "1aad84f8c5fda90036ec8867adda0528"
        }
      ]
    }
  ]
}
