{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.9.0-fix-logger-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ppijtr35czhnrfpayokisrwiji"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a9fc5375a5da94176ff53e144c2dfa534dba47ec9cf1ae5ed6228055d934df1051310cefa63fb104b48b4e9622dea1405e4da48c804071e3e6aa35609cfe773b",
          "sha256": "902410f11047cda072064dbdbd8d7d296ec33c929a495c7316a594d8249078a1",
          "sha1": "94f1d7fca52dffedcbb3560a1816400744e1250a",
          "md5": "06121965594817e5982d517766ccc251"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.0-fix-logger-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "url": "auth-jvm-1.9.0-fix-logger-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a9fc5375a5da94176ff53e144c2dfa534dba47ec9cf1ae5ed6228055d934df1051310cefa63fb104b48b4e9622dea1405e4da48c804071e3e6aa35609cfe773b",
          "sha256": "902410f11047cda072064dbdbd8d7d296ec33c929a495c7316a594d8249078a1",
          "sha1": "94f1d7fca52dffedcbb3560a1816400744e1250a",
          "md5": "06121965594817e5982d517766ccc251"
        }
      ]
    }
  ]
}
