{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-jvm",
    "version": "1.10.0-change-attachment-contract-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6733dv5kkbab5ld45f5uxzcgfq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a07422d260db48774018eb37d1de38fd4e4ffca9c472089466e2e3054cca2182bd0768a0e38141acbb660479840f00acf1627f2a39fe4c3f24abf811fc8e1b4d",
          "sha256": "658327a8195940cdc1efddf98d493774ab4706f2d511eafd2c28ce61f2d24ebf",
          "sha1": "366a3634519c3365e8312cdd6b6d54a21ebf19a2",
          "md5": "c23dcb9e806259c54d17c6ccdb9ab608"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.github.scribejava",
          "module": "scribejava-core",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-attachment-contract-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "auth-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "url": "auth-jvm-1.10.0-change-attachment-contract-SNAPSHOT.jar",
          "size": 27832,
          "sha512": "a07422d260db48774018eb37d1de38fd4e4ffca9c472089466e2e3054cca2182bd0768a0e38141acbb660479840f00acf1627f2a39fe4c3f24abf811fc8e1b4d",
          "sha256": "658327a8195940cdc1efddf98d493774ab4706f2d511eafd2c28ce61f2d24ebf",
          "sha1": "366a3634519c3365e8312cdd6b6d54a21ebf19a2",
          "md5": "c23dcb9e806259c54d17c6ccdb9ab608"
        }
      ]
    }
  ]
}
