{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "uwmpo4yfrvdfpg35w7w5jzniaq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "01df68308a64bc5788d34815a2abe81de06a8511d898bc49f6d7024b37a48641db6117be80171d43b5e21bdf0f8d69aa51beb0c37eecae1c2c3e736f76eba2d3",
          "sha256": "dbf1e09b4486737341ccb77f0c9ccdd6829c43c6ff16344bf84c4713ddfb0d59",
          "sha1": "24f3c8fb9d2946c0e4b3a8b7cdeb74266341314e",
          "md5": "be2f8bfa7bd1d705a8836f6fb2a76404"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "01df68308a64bc5788d34815a2abe81de06a8511d898bc49f6d7024b37a48641db6117be80171d43b5e21bdf0f8d69aa51beb0c37eecae1c2c3e736f76eba2d3",
          "sha256": "dbf1e09b4486737341ccb77f0c9ccdd6829c43c6ff16344bf84c4713ddfb0d59",
          "sha1": "24f3c8fb9d2946c0e4b3a8b7cdeb74266341314e",
          "md5": "be2f8bfa7bd1d705a8836f6fb2a76404"
        }
      ]
    }
  ]
}
