{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "jaop2jc4tfej7kxvvv6ulzacdu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "a18b3f981e746ca15dbd31569950f71e30681df84c12b3ebaa17347c45357bfbc8da23b7bfef790e60cdaa4af4d30c231cc1092c7ab886ff4faa2d0d1be1e7c4",
          "sha256": "bd1e9b1231d83c3e8725bfed41ac46e2f7fa248e36da17283e7f170174aa9e59",
          "sha1": "b3f3e0e2583050d2d88755c17cceea3a4d6cf796",
          "md5": "ce087f669ae76d1f5f76eafbb4f56030"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.10.0-bump-update-kotlin-gradle-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "url": "securestore-jvm-1.10.0-bump-update-kotlin-gradle-SNAPSHOT.jar",
          "size": 16453,
          "sha512": "a18b3f981e746ca15dbd31569950f71e30681df84c12b3ebaa17347c45357bfbc8da23b7bfef790e60cdaa4af4d30c231cc1092c7ab886ff4faa2d0d1be1e7c4",
          "sha256": "bd1e9b1231d83c3e8725bfed41ac46e2f7fa248e36da17283e7f170174aa9e59",
          "sha1": "b3f3e0e2583050d2d88755c17cceea3a4d6cf796",
          "md5": "ce087f669ae76d1f5f76eafbb4f56030"
        }
      ]
    }
  ]
}
