{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-add-label-ci-workflow-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "npror4vrubhehb2jhf4kh7fm7q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-label-ci-workflow-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-add-label-ci-workflow-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-add-label-ci-workflow-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "c2160c931f6b5df534469313959d7e6124a9a75b212cdd149efd02a080ab156cf59c72a9ad3d9ed694e89ee5c761fbd24dddbfc4689bde576f435ed86424c135",
          "sha256": "d94632b75cf05a5f2b920d994af5a0624aadf8ba807115f4534ff0edb771cc41",
          "sha1": "57024562afffe9ade16db5da5f8d7514129bc5c5",
          "md5": "a6619c59c4db72a99b2257b7263f70b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-add-label-ci-workflow-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-add-label-ci-workflow-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-add-label-ci-workflow-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "c2160c931f6b5df534469313959d7e6124a9a75b212cdd149efd02a080ab156cf59c72a9ad3d9ed694e89ee5c761fbd24dddbfc4689bde576f435ed86424c135",
          "sha256": "d94632b75cf05a5f2b920d994af5a0624aadf8ba807115f4534ff0edb771cc41",
          "sha1": "57024562afffe9ade16db5da5f8d7514129bc5c5",
          "md5": "a6619c59c4db72a99b2257b7263f70b1"
        }
      ]
    }
  ]
}
