{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.9.1-change-readme-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qhsmuqmh7rfdzfk3s4odl6a5ci"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-readme-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-change-readme-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-change-readme-SNAPSHOT.aar",
          "size": 44888,
          "sha512": "0681c21bb25c258fe635b5c51a8e494868ecd160b827e0311d0dc9c84b6b431c61fbb022a5fb20b6a3e94287604a656f91a592dd99e0c74160938c429a61aa99",
          "sha256": "69c0ae6735081f76da28807854f917a82c9ec6b2346c566043828219f6c46b5a",
          "sha1": "243d149f3d76c68c8d97769c3dd91e1750c921a3",
          "md5": "8f72b75691f117ead0c9bb57a3020957"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.9.1-change-readme-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.9.1-change-readme-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.9.1-change-readme-SNAPSHOT.aar",
          "url": "auth-android-1.9.1-change-readme-SNAPSHOT.aar",
          "size": 44888,
          "sha512": "0681c21bb25c258fe635b5c51a8e494868ecd160b827e0311d0dc9c84b6b431c61fbb022a5fb20b6a3e94287604a656f91a592dd99e0c74160938c429a61aa99",
          "sha256": "69c0ae6735081f76da28807854f917a82c9ec6b2346c566043828219f6c46b5a",
          "sha1": "243d149f3d76c68c8d97769c3dd91e1750c921a3",
          "md5": "8f72b75691f117ead0c9bb57a3020957"
        }
      ]
    }
  ]
}
