{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-android",
    "version": "1.10.0-change-versioning-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "nlqi4dpq5baftgemygj3kxgg5e"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-versioning-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-versioning-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-versioning-SNAPSHOT.aar",
          "size": 44941,
          "sha512": "2cf32630fb9c185cb9c3f5d19710ce549eae44fb63364be44539d1d8155644dce814453a0c0090c034f79f67c1e8e452daa73ec7445b2585d3c6df265051841f",
          "sha256": "9c02bdc17cc13046f45b5076fd666a580c0f4900370e38e888a6f3e46f2c48bc",
          "sha1": "561efe39dcb2bb2c2d922d6dafa81dba45d8a63d",
          "md5": "056778926bdffe7cbe3e0bf96083c334"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-common",
          "version": {
            "requires": "1.10.0-change-versioning-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-android",
          "version": {
            "requires": "1.10.0-change-versioning-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "care.data4life.hc-util-sdk-kmp",
              "module": "util-jvm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.gesundheitscloud",
          "module": "AppAuth-Android",
          "version": {
            "requires": "9e3cc033ff"
          }
        }
      ],
      "files": [
        {
          "name": "auth-android-1.10.0-change-versioning-SNAPSHOT.aar",
          "url": "auth-android-1.10.0-change-versioning-SNAPSHOT.aar",
          "size": 44941,
          "sha512": "2cf32630fb9c185cb9c3f5d19710ce549eae44fb63364be44539d1d8155644dce814453a0c0090c034f79f67c1e8e452daa73ec7445b2585d3c6df265051841f",
          "sha256": "9c02bdc17cc13046f45b5076fd666a580c0f4900370e38e888a6f3e46f2c48bc",
          "sha1": "561efe39dcb2bb2c2d922d6dafa81dba45d8a63d",
          "md5": "056778926bdffe7cbe3e0bf96083c334"
        }
      ]
    }
  ]
}
