{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-android",
    "version": "1.9.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "3eif4yillff6njydnkmeiklnmq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.2-SNAPSHOT.aar",
          "url": "crypto-android-1.9.2-SNAPSHOT.aar",
          "size": 51817,
          "sha512": "3a0593cc11f8d58679af01c1723882fdd1594a21f66db1106fc9c86a523e243b19f49aabe1555d22ad4379a4bd3ea7130c7f53887e329b10e3d8c0561e8044f7",
          "sha256": "a41f6344e492a78aefc881e67d958d3fdbea8d2a654c0c65210ec964abe68c69",
          "sha1": "360a29c667b05234262a0511c35d8c507a3f81dc",
          "md5": "10ecf0e829cfc2a383f3f5af5ba87217"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-android-1.9.2-SNAPSHOT.aar",
          "url": "crypto-android-1.9.2-SNAPSHOT.aar",
          "size": 51817,
          "sha512": "3a0593cc11f8d58679af01c1723882fdd1594a21f66db1106fc9c86a523e243b19f49aabe1555d22ad4379a4bd3ea7130c7f53887e329b10e3d8c0561e8044f7",
          "sha256": "a41f6344e492a78aefc881e67d958d3fdbea8d2a654c0c65210ec964abe68c69",
          "sha1": "360a29c667b05234262a0511c35d8c507a3f81dc",
          "md5": "10ecf0e829cfc2a383f3f5af5ba87217"
        }
      ]
    }
  ]
}
