{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zfqw324xfbgbtimlicwgf4hbcq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "df8901ab2ebf7c4e1ff6a3596eb0a5364aa06ad0dc6718922a31d75e49bddd1bb14b89e7682744aef9ea94aedb21632d07ea9a2eafff0543c6bf0458a7d608e2",
          "sha256": "b22cac28e276d545a6efcc7cfaaf787edf619ef47f14bcbfe67b1a68a6a351b2",
          "sha1": "b5cb3dc0d3b7d4622e9a6fda060fd6b3877062ac",
          "md5": "f861c6645d72845b832d6f758f130494"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.1-change-TaggingService-getTagFromType-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.1-change-TaggingService-getTagFromType-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "df8901ab2ebf7c4e1ff6a3596eb0a5364aa06ad0dc6718922a31d75e49bddd1bb14b89e7682744aef9ea94aedb21632d07ea9a2eafff0543c6bf0458a7d608e2",
          "sha256": "b22cac28e276d545a6efcc7cfaaf787edf619ef47f14bcbfe67b1a68a6a351b2",
          "sha1": "b5cb3dc0d3b7d4622e9a6fda060fd6b3877062ac",
          "md5": "f861c6645d72845b832d6f758f130494"
        }
      ]
    }
  ]
}
