{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-jvm",
    "version": "1.9.0-prepare-release-1.9.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qxnhzhcfdnf4xhl6xin2es7xv4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "2cba73a9639ebf720799b897b484a12ca262f24660a54710afba894f42166f3f31ca4cf64e8fd57d2ca554882a23bcdf393af5943fa75e9d67e5eb6da688df0a",
          "sha256": "5bd9ce55d9738fb9110e09315605fdf2bce1dc87ce4ce33b8e580118324a3f2f",
          "sha1": "67c841cb3207a4b6abada09b633c4f76557a220d",
          "md5": "8686268ab481ef329ac120fd0dd503bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.0-prepare-release-1.9.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "url": "securestore-jvm-1.9.0-prepare-release-1.9.1-SNAPSHOT.jar",
          "size": 16423,
          "sha512": "2cba73a9639ebf720799b897b484a12ca262f24660a54710afba894f42166f3f31ca4cf64e8fd57d2ca554882a23bcdf393af5943fa75e9d67e5eb6da688df0a",
          "sha256": "5bd9ce55d9738fb9110e09315605fdf2bce1dc87ce4ce33b8e580118324a3f2f",
          "sha1": "67c841cb3207a4b6abada09b633c4f76557a220d",
          "md5": "8686268ab481ef329ac120fd0dd503bb"
        }
      ]
    }
  ]
}
