{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "h3krjl4ru5fflidpkuassdnfgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 459440,
          "sha512": "eea004421209999f02b83c6870a73f0eaf78ef75186d12ef7b3a3454ab4269e66c8d67263745e38d3dcfe16d7035c2173c50c5f4fbb7c077065aff1e5b221fbf",
          "sha256": "6e00cfaf8627469578ae19fe47e848361d2d2b43543f31667990371ec5cc9ddb",
          "sha1": "3f529ed5e45336b85af4cbdd681a3532635ad51c",
          "md5": "e774259e1dd2b0d22f402fa3ee890d9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 459440,
          "sha512": "eea004421209999f02b83c6870a73f0eaf78ef75186d12ef7b3a3454ab4269e66c8d67263745e38d3dcfe16d7035c2173c50c5f4fbb7c077065aff1e5b221fbf",
          "sha256": "6e00cfaf8627469578ae19fe47e848361d2d2b43543f31667990371ec5cc9ddb",
          "sha1": "3f529ed5e45336b85af4cbdd681a3532635ad51c",
          "md5": "e774259e1dd2b0d22f402fa3ee890d9c"
        }
      ]
    }
  ]
}
