{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "sdk-core",
    "version": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "hnv2ozbnlbhspbndxpgesli6yy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 464676,
          "sha512": "4a97f890aae817e2e01e2bf42ded3acafc08fe2e6a2882ebd05ac1db581bf6a17dc8842f62ef8eeeea685d5dcd68b69d603fac2d24d4e0eb07c72d6f1e272da3",
          "sha256": "b79cbdd0a83cb8bae89ece0d41de4617f06d904074870ba1e142a13fe0b3a4bc",
          "sha1": "128e21964a23dc66024085886de2a5269c3d02b8",
          "md5": "410d57b9557b5b6ac39ba843154db9ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "auth-jvm",
          "version": {
            "requires": "1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-fhir-sdk-java",
          "module": "fhir-java",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.threeten",
          "module": "threetenbp",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.19"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "url": "sdk-core-1.9.2-change-module-test-recordservice-create-fake-SNAPSHOT.jar",
          "size": 464676,
          "sha512": "4a97f890aae817e2e01e2bf42ded3acafc08fe2e6a2882ebd05ac1db581bf6a17dc8842f62ef8eeeea685d5dcd68b69d603fac2d24d4e0eb07c72d6f1e272da3",
          "sha256": "b79cbdd0a83cb8bae89ece0d41de4617f06d904074870ba1e142a13fe0b3a4bc",
          "sha1": "128e21964a23dc66024085886de2a5269c3d02b8",
          "md5": "410d57b9557b5b6ac39ba843154db9ca"
        }
      ]
    }
  ]
}
