{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-recordservice-download-upload-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "onleued4znal7nvsg6sz4jmpme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f2697caf0c3c5a6ff16f6cbace0c153f277bcb9b064aed7200e6ee7d299b60957471336abb9c72545b285cf4d171df49fafd382e3b492defeadd7738e3eb4e42",
          "sha256": "62bd8ef18bbf32ca992e877f30b312748fa0ec7ed2af2ad296a12a0e3f3c4024",
          "sha1": "1dcb9b8678edd068f5fae3dfad5d52af94abcbb2",
          "md5": "f87674f812074bec510bf20d5f9fb7cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "f2697caf0c3c5a6ff16f6cbace0c153f277bcb9b064aed7200e6ee7d299b60957471336abb9c72545b285cf4d171df49fafd382e3b492defeadd7738e3eb4e42",
          "sha256": "62bd8ef18bbf32ca992e877f30b312748fa0ec7ed2af2ad296a12a0e3f3c4024",
          "sha1": "1dcb9b8678edd068f5fae3dfad5d52af94abcbb2",
          "md5": "f87674f812074bec510bf20d5f9fb7cc"
        }
      ]
    }
  ]
}
