{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-recordservice-download-upload-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "7aq5rzebv5c7jk5zwepcig6izy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "fb881160f87ee3bafd629dc16c7f49a35b7470f79d54fa9cd34fe14abfaa27282052b4a01c1c0f790454b17ce2de04a6a4102008eac5269d2c4bc7e5244d2bb6",
          "sha256": "ef7bcddba66c48a45bad9d9a6068079815aa13c54015e6e8d7ddf108d6dc8287",
          "sha1": "95b97d310e1e23affb43c22589c8c0610ce982a1",
          "md5": "9963686bf91d0aa51b1ce66abab36c51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-download-upload-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "fb881160f87ee3bafd629dc16c7f49a35b7470f79d54fa9cd34fe14abfaa27282052b4a01c1c0f790454b17ce2de04a6a4102008eac5269d2c4bc7e5244d2bb6",
          "sha256": "ef7bcddba66c48a45bad9d9a6068079815aa13c54015e6e8d7ddf108d6dc8287",
          "sha1": "95b97d310e1e23affb43c22589c8c0610ce982a1",
          "md5": "9963686bf91d0aa51b1ce66abab36c51"
        }
      ]
    }
  ]
}
