{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.10.0-change-module-tests-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z3evh7etebeahksfjm3wm4uh3q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "74ea94c2e3a072b80b663d71268974606459f3e0816db03cd58770476811d74055f0e9677a08a554dfd45893bfb9500a360a72c22a2ccb0cd5c61edd54df69dd",
          "sha256": "9df14b7f9eaa4239aa9bf01e05b3b8727cf6d2b0e4c19f0eda7a18d65935a19e",
          "sha1": "6cf386e19af04d32855677b4b3d969f4b66c6d2e",
          "md5": "9b9735b287a343eafa156303ca09f9ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.10.0-change-module-tests-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "url": "crypto-jvm-1.10.0-change-module-tests-SNAPSHOT.jar",
          "size": 46060,
          "sha512": "74ea94c2e3a072b80b663d71268974606459f3e0816db03cd58770476811d74055f0e9677a08a554dfd45893bfb9500a360a72c22a2ccb0cd5c61edd54df69dd",
          "sha256": "9df14b7f9eaa4239aa9bf01e05b3b8727cf6d2b0e4c19f0eda7a18d65935a19e",
          "sha1": "6cf386e19af04d32855677b4b3d969f4b66c6d2e",
          "md5": "9b9735b287a343eafa156303ca09f9ff"
        }
      ]
    }
  ]
}
