{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-android",
    "version": "1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "rcxffq6mmvecnovyph2o3337tq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.aar",
          "size": 41962,
          "sha512": "79e568e1aeb283037853bb34e00bc9b9b47bc0db00999df8986de1f3fd971d3688eb7db20cf3cbd46da6d30152b18516d40490f02f968a2794702d561c6207ba",
          "sha256": "2116875d99b6114bd88deb426a8e9ce2e84e1128e089f467dd96ff53b8bc638d",
          "sha1": "d420342b7932fe3b9afdf4c49f589060f59dded1",
          "md5": "f87888a2879b2aed0ab96f46864c2541"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-android-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.aar",
          "url": "securestore-android-1.9.1-RecordService-uses-the-UserId-instead-of-RecordId-in-the-legacy-batch-methods-deleteRecords-and-fetchRecords-SNAPSHOT.aar",
          "size": 41962,
          "sha512": "79e568e1aeb283037853bb34e00bc9b9b47bc0db00999df8986de1f3fd971d3688eb7db20cf3cbd46da6d30152b18516d40490f02f968a2794702d561c6207ba",
          "sha256": "2116875d99b6114bd88deb426a8e9ce2e84e1128e089f467dd96ff53b8bc638d",
          "sha1": "d420342b7932fe3b9afdf4c49f589060f59dded1",
          "md5": "f87888a2879b2aed0ab96f46864c2541"
        }
      ]
    }
  ]
}
