{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "goqahyz2p5catlz3u62nt6qc3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "de602e124c98e841d29f867fda2b3a88f088f41428ca6a0a8713da0d91f9ca87d6c5772d31c8135cde36d6f7b973c3f902a78b27d45d327b4d7cf79ce630ce2d",
          "sha256": "429550abb6be7cd605db088a7d7dee7ae508cdacea4fa3e3ed2dd9a992feebb5",
          "sha1": "2ff6117388e0df80506e36fe4ee7f67e9cfd4e1b",
          "md5": "c44857fde3ad3d6945ace98d347cc265"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-fetch-record-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-fetch-record-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "de602e124c98e841d29f867fda2b3a88f088f41428ca6a0a8713da0d91f9ca87d6c5772d31c8135cde36d6f7b973c3f902a78b27d45d327b4d7cf79ce630ce2d",
          "sha256": "429550abb6be7cd605db088a7d7dee7ae508cdacea4fa3e3ed2dd9a992feebb5",
          "sha1": "2ff6117388e0df80506e36fe4ee7f67e9cfd4e1b",
          "md5": "c44857fde3ad3d6945ace98d347cc265"
        }
      ]
    }
  ]
}
