{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "zto3y2boobfnzldsf7fiphv3ge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "fafbf6a6511b4605f616a02d7691af477403db381b7df9c34ce55f50fe043631850aab06527133bb13b86e40707b7c6aa5c4ae506872021ab44b5fa91019c46f",
          "sha256": "a905d582ffa85091396c1fe9e81fa29d5b7542071c9f20dd02961d4b9a2e182d",
          "sha1": "ad706532763ccd86d6d637d845e9cb8c474c8925",
          "md5": "871fb2d4f6ef15f78ca663698c118d54"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "fafbf6a6511b4605f616a02d7691af477403db381b7df9c34ce55f50fe043631850aab06527133bb13b86e40707b7c6aa5c4ae506872021ab44b5fa91019c46f",
          "sha256": "a905d582ffa85091396c1fe9e81fa29d5b7542071c9f20dd02961d4b9a2e182d",
          "sha1": "ad706532763ccd86d6d637d845e9cb8c474c8925",
          "md5": "871fb2d4f6ef15f78ca663698c118d54"
        }
      ]
    }
  ]
}
