{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-common",
    "version": "1.9.2-change-recordservice-update-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "2r7dgy54wvejhp6hlf6y46kg5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "66eb8054ebce3a6db582220da2c09a1415a56830316f0c032d1701e04165b69b1a2c3ad43c9ce946d687c96d5a5ad52744fba3d76cfb77e608d29e7675074714",
          "sha256": "d44ac19d2771ef54928207d6e9c8b20c4992834581f74dca99b86881af44ddba",
          "sha1": "3354f7ff400ccebd7ddfe9189063818ba5181c08",
          "md5": "66c198033452754d8ff8b8a2deb70537"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "url": "crypto-common-1.9.2-change-recordservice-update-attachment-test-SNAPSHOT.jar",
          "size": 10850,
          "sha512": "66eb8054ebce3a6db582220da2c09a1415a56830316f0c032d1701e04165b69b1a2c3ad43c9ce946d687c96d5a5ad52744fba3d76cfb77e608d29e7675074714",
          "sha256": "d44ac19d2771ef54928207d6e9c8b20c4992834581f74dca99b86881af44ddba",
          "sha1": "3354f7ff400ccebd7ddfe9189063818ba5181c08",
          "md5": "66c198033452754d8ff8b8a2deb70537"
        }
      ]
    }
  ]
}
