{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "z3hehjzzprcmbdgrr3n6axcn6e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "44b825cea491e6ba068fe50657a3ea5dea1322d83cb2a7539ebaa4f16e757eab8b2c1f7b2309ce4d091fcd4c5be70c256982e19e65ec50bf3890a2370112dc17",
          "sha256": "28a08d95348935db16dd5db27eeb2704a4e62f39ee9b601cdaab446463fcb444",
          "sha1": "0f21cb8b8d8161bb3de54ed2899e02ced65b3b9f",
          "md5": "1bf7e84e7d35088a4a8c8277bfc651ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "44b825cea491e6ba068fe50657a3ea5dea1322d83cb2a7539ebaa4f16e757eab8b2c1f7b2309ce4d091fcd4c5be70c256982e19e65ec50bf3890a2370112dc17",
          "sha256": "28a08d95348935db16dd5db27eeb2704a4e62f39ee9b601cdaab446463fcb444",
          "sha1": "0f21cb8b8d8161bb3de54ed2899e02ced65b3b9f",
          "md5": "1bf7e84e7d35088a4a8c8277bfc651ed"
        }
      ]
    }
  ]
}
