{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bpr7akrthngtnkpzwwsllvyjdi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "1a21b5e548258902eca3f36646437c042be9cf3ba55f64a614ef4e77a75f39900618897f034b5f8a43ea403c6f707861d87a9a134b79d1a4bd4505e27489afc4",
          "sha256": "fab3471e534e840de4dce0a5b00970c114f88aa2cdfee87d5aaeaa2b29e95732",
          "sha1": "51fb98fe49d2d6ef786e89ac6f042cab54c9e652",
          "md5": "9660a5bbe97e8e11ae330a40425ae62e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "1a21b5e548258902eca3f36646437c042be9cf3ba55f64a614ef4e77a75f39900618897f034b5f8a43ea403c6f707861d87a9a134b79d1a4bd4505e27489afc4",
          "sha256": "fab3471e534e840de4dce0a5b00970c114f88aa2cdfee87d5aaeaa2b29e95732",
          "sha1": "51fb98fe49d2d6ef786e89ac6f042cab54c9e652",
          "md5": "9660a5bbe97e8e11ae330a40425ae62e"
        }
      ]
    }
  ]
}
