{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "q4os6rn5dndqjnkodtw27f724m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "c02c6b76e9ec24a844c60d7c4ed0c924e27ba295cb290abb3b1941e6d3c05f4e01e8e448287e00634db658100f8595d6a29a3bd0a09f586ad725bb3d6e28e91c",
          "sha256": "c610f2748f81a80bcccf8f50ab64a3e7cc452b3ea2e74d38255adfba814e592e",
          "sha1": "35bc03109a7b61c0db660a7750b356ddafceccde",
          "md5": "31c968daff6f187eb4c036c4a9428c7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "url": "securestore-common-1.9.0-NAT-496-align-tagging-with-js-sdk-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "c02c6b76e9ec24a844c60d7c4ed0c924e27ba295cb290abb3b1941e6d3c05f4e01e8e448287e00634db658100f8595d6a29a3bd0a09f586ad725bb3d6e28e91c",
          "sha256": "c610f2748f81a80bcccf8f50ab64a3e7cc452b3ea2e74d38255adfba814e592e",
          "sha1": "35bc03109a7b61c0db660a7750b356ddafceccde",
          "md5": "31c968daff6f187eb4c036c4a9428c7e"
        }
      ]
    }
  ]
}
