{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "chojjztcwngxvnyz6vvkqrwrzq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "04302059f91b0ffb4dffefcac1755bbbeccf1fedc858a20949507cbdf9ef141c955176b62c67ffd977cae905560af857d32c67c5bb8865580f022bbc9c58ffec",
          "sha256": "f81cf88b51c8518d0cca4c68b6c16029260d0410fd25d811178aa03896b6ce89",
          "sha1": "5e34ace4ec5e0c00e0edbae198c2d0976c076379",
          "md5": "51c38d55d5ec5307b803594fcfcd1600"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.1-add-compatibility-layer-for-encording-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "url": "auth-common-1.9.1-add-compatibility-layer-for-encording-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "04302059f91b0ffb4dffefcac1755bbbeccf1fedc858a20949507cbdf9ef141c955176b62c67ffd977cae905560af857d32c67c5bb8865580f022bbc9c58ffec",
          "sha256": "f81cf88b51c8518d0cca4c68b6c16029260d0410fd25d811178aa03896b6ce89",
          "sha1": "5e34ace4ec5e0c00e0edbae198c2d0976c076379",
          "md5": "51c38d55d5ec5307b803594fcfcd1600"
        }
      ]
    }
  ]
}
