{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xu2s7z2m5bdm7ppyb76ul6vrg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "89f0b81f2902c55ac19a2b74c5f320f63a22d9bfe31294731f57ed5e914612c715469a8488c91d214f4b6fab66aca78768b890683208dd00ac9a6b96fb8917f7",
          "sha256": "3cf1927604641baea22e653b3708fa12c60457dd676f1da3b57d8c6b1164f4bd",
          "sha1": "0ff5dbb5c030edd1f88572c6c39ac9849323b938",
          "md5": "a7748065c2ea72d6e6c9814b6a8b2867"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "89f0b81f2902c55ac19a2b74c5f320f63a22d9bfe31294731f57ed5e914612c715469a8488c91d214f4b6fab66aca78768b890683208dd00ac9a6b96fb8917f7",
          "sha256": "3cf1927604641baea22e653b3708fa12c60457dd676f1da3b57d8c6b1164f4bd",
          "sha1": "0ff5dbb5c030edd1f88572c6c39ac9849323b938",
          "md5": "a7748065c2ea72d6e6c9814b6a8b2867"
        }
      ]
    }
  ]
}
