{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "mezr5ujomngztn6rcvg5o23z5y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "5571f6ff74f77abfcbd8281363d27fcffbe45787f3b817d693e5ce8080f91213b4aa5e748d03e142013b264baf748609122fee1ebbbebea618ea392ed6f167f3",
          "sha256": "899a81815c2d5ca64abe3760880d0ef0f92d876ef20e0b81907436bd32a26d6a",
          "sha1": "57fb7c82c079ec996ad58d5d9b77a3fe471dab7a",
          "md5": "65267e6a764fe70fb220af068f327e83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "5571f6ff74f77abfcbd8281363d27fcffbe45787f3b817d693e5ce8080f91213b4aa5e748d03e142013b264baf748609122fee1ebbbebea618ea392ed6f167f3",
          "sha256": "899a81815c2d5ca64abe3760880d0ef0f92d876ef20e0b81907436bd32a26d6a",
          "sha1": "57fb7c82c079ec996ad58d5d9b77a3fe471dab7a",
          "md5": "65267e6a764fe70fb220af068f327e83"
        }
      ]
    }
  ]
}
