{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "crypto-jvm",
    "version": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fi7anlizdzh4ngxnaamktd6r7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "e3c174726ed5222e4b88293c0713679e07b595bb01bb7816ef9241c2d55f90e67eb9254a66965642a070c936e91b5312101e31f187e5065bf79f8a7ba85c42ac",
          "sha256": "7d15c66e38355af580a324bef2b2ac120e20b0b1d6c99f1bf5b603207c3055a4",
          "sha1": "50a853d3abad1ee010bc7984cb753976b202bc70",
          "md5": "b5c1a27722f93ec5a3563d34df1a8039"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.64"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "crypto-common",
          "version": {
            "requires": "1.9.2-change-recordservice-download-attachment-test-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "url": "crypto-jvm-1.9.2-change-recordservice-download-attachment-test-SNAPSHOT.jar",
          "size": 46078,
          "sha512": "e3c174726ed5222e4b88293c0713679e07b595bb01bb7816ef9241c2d55f90e67eb9254a66965642a070c936e91b5312101e31f187e5065bf79f8a7ba85c42ac",
          "sha256": "7d15c66e38355af580a324bef2b2ac120e20b0b1d6c99f1bf5b603207c3055a4",
          "sha1": "50a853d3abad1ee010bc7984cb753976b202bc70",
          "md5": "b5c1a27722f93ec5a3563d34df1a8039"
        }
      ]
    }
  ]
}
