{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xn4cqacczvasvh6dqh5ii2fshm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "9b4e67ef4b8a09c9e6d530b930c0432f19948a893ccd7f725fd506a721e23ebe833d68a40c30a40b1f4015a7e1688423f7d7ad908d701bbc0f30bb26f7e421bf",
          "sha256": "bd838544acca8a6b3d772dbf2ee2c2e5a875c50081a27470536cd0666032b099",
          "sha1": "8c1faab4d9973c7561dfc9d222a7a21b176d5375",
          "md5": "98ce069ea9505e3ffca4b63173a67c62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "9b4e67ef4b8a09c9e6d530b930c0432f19948a893ccd7f725fd506a721e23ebe833d68a40c30a40b1f4015a7e1688423f7d7ad908d701bbc0f30bb26f7e421bf",
          "sha256": "bd838544acca8a6b3d772dbf2ee2c2e5a875c50081a27470536cd0666032b099",
          "sha1": "8c1faab4d9973c7561dfc9d222a7a21b176d5375",
          "md5": "98ce069ea9505e3ffca4b63173a67c62"
        }
      ]
    }
  ]
}
