{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "securestore-common",
    "version": "1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kbq63nxerffnrfw7qmmxelluri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8cf0c9b788c9a7df754cd497f0edade5e3ed3b13b6e7fc3531d35a68e8da140b1d56ed92099009d8e93723d47a8b8bfaca01f6e237835035b4ca281361590021",
          "sha256": "51348b9cd4dbe978b25e081131c9841fbc634b3ee40826c8b3c2915eb9471baf",
          "sha1": "c3015a52ba39e1b15728b43d8319c0945c8f6a48",
          "md5": "49dbab88dd8951d81ab38a6c5473ca0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "url": "securestore-common-1.10.0-add-fhir4-download-support-in-clients-SNAPSHOT.jar",
          "size": 6921,
          "sha512": "8cf0c9b788c9a7df754cd497f0edade5e3ed3b13b6e7fc3531d35a68e8da140b1d56ed92099009d8e93723d47a8b8bfaca01f6e237835035b4ca281361590021",
          "sha256": "51348b9cd4dbe978b25e081131c9841fbc634b3ee40826c8b3c2915eb9471baf",
          "sha1": "c3015a52ba39e1b15728b43d8319c0945c8f6a48",
          "md5": "49dbab88dd8951d81ab38a6c5473ca0a"
        }
      ]
    }
  ]
}
