{
  "formatVersion": "1.1",
  "component": {
    "group": "care.data4life.hc-sdk-kmp",
    "module": "auth-common",
    "version": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tmdbyggbhbaopkxsrpsr5y5ikm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d17ea56538f070cce8d9a399945e06b6b74cbcc924ed8940ff09fadf3378d3a7a5f71de96d17cc3fd020b7e285575c97848838e0852029ca776cdceb0b5a7963",
          "sha256": "79b3d4c706225e224431586e6ff3b28c1a9d3ed7ef59947dcb864cbbe67fe497",
          "sha1": "3161db3bb9a2e4ca8c5e9fd71aad8907e73f9ebc",
          "md5": "62ed4f718a3a3d97aae4c5120a423f61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "care.data4life.hc-sdk-kmp",
          "module": "securestore-common",
          "version": {
            "requires": "1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "care.data4life.hc-util-sdk-kmp",
          "module": "util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "auth-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "url": "auth-common-1.9.2-change-recordservice-upload-attachment-test-SNAPSHOT.jar",
          "size": 3399,
          "sha512": "d17ea56538f070cce8d9a399945e06b6b74cbcc924ed8940ff09fadf3378d3a7a5f71de96d17cc3fd020b7e285575c97848838e0852029ca776cdceb0b5a7963",
          "sha256": "79b3d4c706225e224431586e6ff3b28c1a9d3ed7ef59947dcb864cbbe67fe497",
          "sha1": "3161db3bb9a2e4ca8c5e9fd71aad8907e73f9ebc",
          "md5": "62ed4f718a3a3d97aae4c5120a423f61"
        }
      ]
    }
  ]
}
